### ISSUE TITLE
Dataplane wizard in web gui doesn't include the correct cp-address

### ISSUE THREAD

**Issue by KongSteve** [kumahq/kuma#1000]
For example, the gui displays:

kuma-dp run \
  --name=backend-1 \
  --mesh=default \
  --cp-address=localhost \
  --dataplane-token-file=

**Comment by nickolaev** [comment]
@bloqhead we'd like this to include a better `--cp-address` line. It would be something like `--cp-address=http://127.0.0.1:5681`, where the address is the address of the API server, which the GUI already knows.

**Comment by tharun208** [comment]
closed by https://github.com/kumahq/kuma-gui/pull/90

**Comment by jakubdyszkiewicz** [comment]
done
