### ISSUE TITLE
Missing `name` on MeshGatewayListener

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#10011]
### Description

This exists in GatewayAPI: https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.Listener

**Comment by lahabana** [comment]
This would also mean that listener matching for policies could be done by name no?

**Comment by michaelbeaumont** [comment]
@lahabana we already convert the name to a tag on the MeshGateway listener

**Comment by michaelbeaumont** [comment]
https://github.com/kumahq/kuma/blob/ab855530b3cc87dff937c93432f528f24fc95cbf/api/mesh/v1alpha1/dataplane_helpers.go#L41

**Comment by michaelbeaumont** [comment]
But yes we can add this as a real field to the MeshGateway listener

**Comment by jakubdyszkiewicz** [comment]
> Triage: We don't need this for now. We can add this if we need it xref https://github.com/kumahq/kuma/issues/10014
