### ISSUE TITLE
MeshService status conditions

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#10057]
### Description

Update MADR and add conditions for:
- [x] have a VIP
- [ ] [TLS readiness](https://github.com/Kong/kong-mesh/issues/6185)
- [ ] [has non-meshed (UDP) ports](https://github.com/kumahq/kuma/issues/10614)

**Comment by lahabana** [comment]
Maybe a `hasSomeOfflineProxies` and `hasSomeOnlineProxies`

**Comment by michaelbeaumont** [comment]
See linked issues
