### ISSUE TITLE
Add control plane identifier in DiscoveryResponse

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#1011]
### Summary

1) We should generate more recognizable Control Plane InstanceID (like `hostname-${4 random chars}` not random `UUID`)
2) `DiscoveryResponse` contains Control Plane Identifier that we should fill this info in the control plane.
3) We can then build a pane in `Kuma Dataplane` dashboard to which CP Instance the DP is connected which will help with debugging.

**Comment by jewertow** [comment]
Hi, I would like to work on this issue.

**Comment by jakubdyszkiewicz** [comment]
Great, let me know if you have any questions @jewertow

**Comment by jewertow** [comment]
@jakubdyszkiewicz
I implemented subtasks 1 and 2 (https://github.com/kumahq/kuma/pull/1037) and now I want to expose this control plane identifier for Kuma GUI, but as I am new contributor I need a hint where should I add this information?

**Comment by jewertow** [comment]
@jakubdyszkiewicz
There are already several implementations of Callbacks interface, but in my opinion none of them fit well for this case.
Can I add another implementation dedicated for this case or should I add this feature to one of existing implementations?
What do you think?

**Comment by jakubdyszkiewicz** [comment]
Hey @jewertow 
agreed, that's a job for separate Callback.

**Comment by jakubdyszkiewicz** [comment]
1) and 2) is done. 3) is still to do

**Comment by jewertow** [comment]
I will do the last part of this task.

**Comment by jewertow** [comment]
For now we cannot display control plane identifier, because envoy does not export this value to prometheus.
I created an issue, described the problem and suggested a solution [here](https://github.com/envoyproxy/envoy/issues/14823). I will implement it soon and then I will come back to this task.

**Comment by jewertow** [comment]
It took a while, but I implemented missing metrics in Envoy and exporting text stats should be available in the next release. However this feature has some weaknesses that are explained in the [documentation](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--stats?format=prometheus&text_readouts).
What's more, I can't continue to work on this task.

**Comment by jakubdyszkiewicz** [comment]
Lets investigate if we can use GET /stats?format=prometheus&text_readouts[¶](https://www.envoyproxy.io/docs/envoy/latest/operations/admin#get--stats?format=prometheus&text_readouts) with shortcomings. If now, we can close this issue. This information is visible in DataplaneInsights, but It would be nice to also see this in Grafana.
