### ISSUE TITLE
Can't install Kuma .71 on MacOS Mojave

### ISSUE THREAD

**Issue by ManojGoel2020** [kumahq/kuma#1013]
### Summary

I have been trying to install Kuma 0.71 on Mac OS Mojave but the image does not get pulled

kubectl get pod -n kuma-system
NAME                                  READY   STATUS             RESTARTS   AGE
kuma-control-plane-78b89c455f-tg6md   0/1     ImagePullBackOff   0          131m

This is prohibiting me from installing other Service Mesh systems as it is stuck with Kuma system issues related to io.

Why I do i get this
kubectl -n kuma-system describe pods | grep Failed
  Warning  Failed   21m (x496 over 135m)  kubelet, minikube  Error: ImagePullBackOff

Please advice. I was trying to demo this

**Comment by jakubdyszkiewicz** [comment]
Hey @ManojGoel2020 thanks for trying Kuma.

Do you run this in Minikube or on some cloud? It seems like you cannot pull the image. The image is up in the repo
```
❯❯❯ docker pull kong-docker-kuma-docker.bintray.io/kuma-cp:0.7.1
0.7.1: Pulling from kuma-cp
Digest: sha256:8104d7577f87a1e8c86d92371a0f0724667085a77879892595e1a37da2f18720
Status: Image is up to date for kong-docker-kuma-docker.bintray.io/kuma-cp:0.7.1
kong-docker-kuma-docker.bintray.io/kuma-cp:0.7.1
```

**Comment by subnetmarco** [comment]
@ManojGoel2020 in certain instances you may be running in restricted environment where docker repository have to be explicitly allowed. Just make sure you can pull from `kong-docker-kuma-docker.bintray.io` like @jakubdyszkiewicz explained.

**Comment by ManojGoel2020** [comment]
First I tried pulling from docker source - kong-docker-kuma-docker.bintray.io , but could not. It is a restricted environment as you guessed. But then I was using curl command to get Kuma, which it did install , when run kumactl it does not get image. So same affect. Is there a proxy or something we have to set to pull image? I installed easily on my own personal laptop but I have less memory only 8gb, so could not run all services and things needed to Demo it with all its bells and whistles.

Also is there a good demo which we can use to see Traffic, Routing,Splitting and any other benefits it has?

Thanks

**Comment by subnetmarco** [comment]
> First I tried pulling from docker source - kong-docker-kuma-docker.bintray.io , but could not. It is a restricted environment as you guessed. But then I was using curl command to get Kuma, which it did install , when run kumactl it does not get image. So same affect. Is there a proxy or something we have to set to pull image?

To determine if you need - or not - a proxy is being determined by your networking environment. The distribution is available on the open internet at `kong-docker-kuma-docker.bintray.io`.

> Also is there a good demo which we can use to see Traffic, Routing,Splitting and any other benefits it has?

You can take a look at the [kuma-demo](https://github.com/kumahq/kuma-demo) repository which demonstrates many features.

> Consul has somewhat better console where we can do all this using a UI, do you have something similar?

Not sure I understand what you are looking to do via the UI. In Kuma the UI is read-only because your infrastructure should be changed with `kubectl` on Kubernetes or `kumactl` (or the REST API) on other environments in order to promote reproducibility of your mesh. We wouldn't want to potentially disrupt a service mesh by clicking a button from the browser.
