### ISSUE TITLE
When modifying the headers, split the value may cause unexpected bug

### ISSUE THREAD

**Issue by spacewander** [kumahq/kuma#10156]
### What happened?

In https://github.com/kumahq/kuma/blob/5c1f62de50047e0c082ec6d8f92337a12c27ce47/pkg/plugins/policies/meshhttproute/xds/filters/requestheadermodifier.go#L36

the header value is split by `,`, and then added one by one.

In case like `Set-Cookie: id=a3fWa; Expires=Wed, 21 Oct 2015 07:28:00 GMT`, it will be added as:
`Set-Cookie: id=a3fWa; Expires=Wed` and
`Set-Cookie: 21 Oct 2015 07:28:00 GMT`

I wonder why not set the header directly without any splitting?

**Comment by michaelbeaumont** [comment]
This may be an oversight, [particularly important for Set-Cookie](https://datatracker.ietf.org/doc/html/rfc7230#autoid-21), regarding directives from [the gateway API docs at the time](https://github.com/kubernetes-sigs/gateway-api/blob/9a5e4462b572610c5a7de968d1165c050164f11e/apis/v1beta1/httproute_types.go#L731). I think Envoy will do the right thing here.

**Comment by spacewander** [comment]
@michaelbeaumont 
Would you assign this to me? I would submit a PR to change it a few days later.
