### ISSUE TITLE
kumactl support for logs 

### ISSUE THREAD

**Issue by nikita15p** [kumahq/kuma#1016]
### Summary

SUMMARY_GOES_HERE
kumactl does not have logs feature. It should add support for log stdout and filesystem to start with.

### Steps To Reproduce
NA

### Additional Details & Logs

- Version NA
- Error logs NA
- Configuration NA
- Platform and Operating System NA

**Comment by jakubdyszkiewicz** [comment]
Hey @nikita15p what exactly logs do you have in mind? Are you talking about TrafficLog? Or logs of kumactl binary?

**Comment by nikita15p** [comment]
@jakubdyszkiewicz kumactl binary

**Comment by jakubdyszkiewicz** [comment]
kumactl produce all the output to the stdout. This is how you interact with CLI tool. There are no logs aside from this.

Can you describe a little bit more your use case? Thanks!

**Comment by nikita15p** [comment]
Yes, so we can direct the output to any number of different locations by adding some flags --log_target for eg. Also other features like level of logs ie warning, error /info can be added via --log_level. ALso we can provide log rotation feature as well.

**Comment by jakubdyszkiewicz** [comment]
`kumactl` does not produce any logs at all. We just push the data on the stdout and if there is an error on stderr. So when you do `kumactl get meshes` we build a response and push on stdout. It's not a log. If you want to push this response to a file you could do `kumactl get meshes >> /tmp/kumactl-output`.
Those responses do not have levels.

I don't believe that for example `kubectl` offers such functionality.

If you would like to have a response on stdout and file you could use tee
```
kumactl get meshes 2>&1 | tee /tmp/kumactl-output
```

would this solve your needs for `kumactl`?

With that in mind, I agree that we could introduce `--log-target=file` to `kuma-cp` and `kuma-dp` (we already have `--log-level` there)
