### ISSUE TITLE
support for --log-target=<target> to kuma-cp and kuma-dp

### ISSUE THREAD

**Issue by sudeeptoroy** [kumahq/kuma#1019]
Need support for re-directing output of kuma components to number of different location like filesystem or network port.
This would help to integrate with several log processor like fluentbit, vector with sidecar pattern. 
For example: https://vector.dev/docs/setup/deployment/strategies/#sidecar

**Comment by jakubdyszkiewicz** [comment]
We now have `--log-output-path` to change target to a file, also with rotation!
