### ISSUE TITLE
Merge `kumactl install ingress` in the main `kumactl install control-plane`

### ISSUE THREAD

**Issue by nickolaev** [kumahq/kuma#1020]
### Summary

#989 merged the generic `kumactl install control-plane` and the Helm Charts, replacing the old templates and relying on the Helm to render the charts at `kumactl` execution time. The Helm Charts also do support the `ingress` deployment, which allows merging this functionality to `kumactl install control-plane` I would suggest a new flag `--ingress` and them migrate the relevant options from the existing command.

**Comment by austince** [comment]
Looks good to me, and can start work on this Monday 9/21.
