### ISSUE TITLE
use self-hosted runners for core branches

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#10235]
### Description

We have 2 problems with CI still:

- arm free runners don't exist on github
- the max parallel runners is limited in github free and causes queueing

To alleviate this using self-hosted runners sponsored by Kong would be ideal (it's a setup we use for our enterprise builds).
This ticket tracks:

- [x] Bringing up self-hosted runners on hetzner
- [x] Register the self-hosted runners with the kumahq org
- [x] #10583
- [x] https://github.com/kumahq/kuma/issues/10904
- [x] #10585
- [x] #10584

**Comment by jijiechen** [comment]
As of 15 Aug, self hosted runners are enabled for running E2E tasks on:

|  ARCH   | Branch | Enabled | 
|---------|---------|---------|
|  AMD64   | `master` | Y |
|  AMD64   | `release-*` >= 2.6 | N (planned) |
|  ARM64 | `master` | Y |
|  ARM64   | `release-*` >= 2.6 | Y |

CircleCI code is cleaned up on master and `release-*` >= 2.6.

**Comment by lahabana** [comment]
I think we should not bother with AMD64 for `release-* >= 2.6` . Let's just focus on having self-hosted runners reliably pass on master.
