### ISSUE TITLE
Support specifying custom SAN for generated general tls certificates in Helm Chart

### ISSUE THREAD

**Issue by jijiechen** [kumahq/kuma#10365]
### Description

We need a way to specify custom hostnames to support the global CP servers to be accessed using hostnames other than the *incluster* names (listed below).

When verifying certificate of a global KDS server and the tls certificate is issued by the generated CA from the Helm Chart based installation, I could not make it work because of:

In additional to the CN, the generated certificate right now has two SANs. So all valid hostnames are:

* kuma-control-plane
* kuma-control-plane.kuma-system
* kuma-control-plane.kuma-system.svc

These are not sufficient for being accessed with a custom hostname (like, `kuma-global-cp.my-own-domain.net`) when the global CP is in a k8s cluster different with the Zone CP, which is a very common case.

When we setup the verification now, it will fail with the following error:
```
2024-05-31T06:21:48.720Z	ERROR	kds-zone.kds-mux-client	component terminated with an error	{"generationID": 4, "error": "rpc error: code = Unavailable desc = connection error: desc = \"transport: authentication handshake failed: tls: failed to verify certificate: x509: cannot validate certificate for 172.18.52.0 because it doesn't contain any IP SANs\""}
```

**Comment by lahabana** [comment]
Should we just recommend users to set their own CA and certificates in this case?

**Comment by jijiechen** [comment]
Well, without this feature, we just can't make the Zone CP verify the KDS server certificate. So the bulitin self-sign mechanism is buggy when we think it in this way.
On the other hand, it's useful for users who only wants to verify the KDS server CA but keep the simplicity of installing by using the self-signed certificates. It's easy for us to support this capability by introducing a parameter in the Helm Chart.

**Comment by jakubdyszkiewicz** [comment]
> Triage: We can just rely on certs provided by the user. What could help is maybe providing link to the doc in prod values?

https://kuma.io/docs/2.7.x/production/secure-deployment/certificates/

**Comment by jijiechen** [comment]
While I don't agree with the triage conclusion, I'll not open it again. 
Let me remind, this basically means people can't use the builtin values to setup a environment that verifies the global KDS certificate. And we gave up the opportunity to improve it by a small effort.
