### ISSUE TITLE
Consistent way of getting name of a resource

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#10435]
### Description

from @lukidzi:

There are multiple ways of getting a name:
- meta.GetName() # name from the resource
- meta.GetNameExtensions()[model.K8sNameComponent] # "k8s.kuma.io/name"
- GetDisplayName(meta) # "kuma.io/display-name"
- es.Spec.GetService() # "kuma.io/service"

We should have a single way of getting the correct name so we don't mess up. E.g. when we generate resources in different places (e.g. listener in one place and cluster in another name) and we need to match them up.

**Comment by lobkovilya** [comment]
> Triage: we should remove `meta.GetNameExtensions()[model.K8sNameComponent]` and use labels instead. `es.Spec.GetService()` shouldn't be the case anymore as we introduced MeshExternalService, no? Let's also add docs to these methods.

**Comment by slonka** [comment]
@lobkovilya was this solved by https://github.com/kumahq/kuma/pull/10886 ?

**Comment by lobkovilya** [comment]
Yes
