### ISSUE TITLE
Explicitly require `proxyType: sidecar` in MeshPassthrough validator

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#10468]
### Description

decision from https://github.com/kumahq/kuma-website/pull/1809#discussion_r1635898786

**Comment by lobkovilya** [comment]
> Triage: at this moment there is no MeshGateway support. We want to require `proxyType: sidecar` to avoid backwards compatibility issue when it's implemented. 

xref: https://github.com/kumahq/kuma/issues/10513
