### ISSUE TITLE
KDS updates stuck after webhook rejects the changes with NACK

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#10463]
### What happened?

Visible as an e2e test failure:

```
• [FAILED] [148.788 seconds]
Upgrade Multizone with Helm upgrade helm multizone [It] from version: 2.6.7 [job-2]
github.com/kumahq/kuma/test/framework/ginkgo.go:105

  [FAILED] Timed out after 30.000s.
  meshtimeouts are not synced to zone
  Expected
      <int>: 1
  to equal
      <int>: 3
Error: It 06/12/24 20:09:49.466
```

It's possible to reproduce locally after running the test in the loop for a few minutes.

  
[zone.txt](https://github.com/user-attachments/files/15822695/zone.txt)
[global.txt](https://github.com/user-attachments/files/15822696/global.txt)

**Comment by lukidzi** [comment]
Action items:
* Don’t set owner ref on remote resources
* Distinguish validation errors and other errors and only return NACK on validation error
* In other cases restart KDS sync (crash the component)
