### ISSUE TITLE
MeshPassthrough policy support for Delegated MeshGateway

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#10513]
### Description

We need to support MeshGateways

**Comment by lukidzi** [comment]
Is it possible? MeshPassthrough works only thanks to a transparent proxy. Based on the original destination, we can match traffic and route it through the sidecar if there is no matching route. The Gateway defines routes and listeners and does not use a transparent proxy, making it impossible to match on the packet level. If the request comes from the outside, the Gateway needs to have a defined route to handle the request. In this case, it is more the role of MeshHTTPRoute/MeshTCPRoute to handle it. Additionally, if communication with an external endpoint is needed, the user can create a MeshExternalService.

**Comment by lukidzi** [comment]
After the discussion, it only makes sense for a delegated gateway so we decided to implement it.
