### ISSUE TITLE
Warning in the GUI that Dataplane/Control Plane rejected configs

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#1056]
### Summary

In Kuma, we follow the number of updates, ACK and NACKs on ADS stream in the object called DataplaneInsights.
Right now in the GUI we show `Total Updates`. When there are any updates that were rejected by Envoy, we should show this to user. In total updates cell this can be either
1) a warning sign so: 3 ⚠️
2) 3 (1 rejected)
When user hoover mouse over this we should see "Some configuration changes were rejected by Envoy. The most common reason is that the configuration generated by the control plane may be invalid. Check Kuma DP sidecar logs for more details"

(also similar pattern for ZoneInsights)

@subnetmarco what do you think?

**Comment by subnetmarco** [comment]
I like the idra

**Comment by subnetmarco** [comment]
I like the idea

**Comment by tharun208** [comment]
I like this idea and implemented it with showing the `totalRejections` along with the warning text we show on during mouse hover.

**Comment by tharun208** [comment]
> I like this idea and implemented it by showing the `totalRejections` along with the warning text that we show on during mouse hover.

@jakubdyszkiewicz @bloqhead
