### ISSUE TITLE
add dnsConfig to egress/ingress deployments in kuma helm chart

### ISSUE THREAD

**Issue by jijiechen** [kumahq/kuma#10588]
### Description

It's asked by some kuma users that they want kuma helm chart to support configuring `dnsConfig` for egress and ingress deployments.

They are currently manually adding the configuration to their deployments after kuma installation, and they need to redo this each time they upgrade kuma.

**Comment by slonka** [comment]
> Triage: this is passed through to the Kube DNS, it's just plumming through the DNS config
