### ISSUE TITLE
Run all arm jobs from master on self-hosted runners

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#10583]

**Comment by jijiechen** [comment]
Here is a test run: https://github.com/kumahq/kuma/actions/runs/9607883135/job/26500839299
The code changes are tracked on [branch "chore/self-hosted-runners-arm64"](https://github.com/kumahq/kuma/compare/master...chore/self-hosted-runners-arm64)

We'll officially enable them as soon as we finished seting them up on the org level.

**Comment by lahabana** [comment]
Reopening issue as it requires backport to 2.8,2.7 and 2.6

**Comment by lahabana** [comment]
This is done and everything was backported to 2.8, 2.7 and 2.6.
