### ISSUE TITLE
Add support for MeshService to `to[].targetRef.kind` for all policies

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#10608]
### Description

https://github.com/kumahq/kuma/issues/10607 provides an example, all other policies should follow it

**Comment by Automaat** [comment]
closing as more specific issues were created: 
- [ ] https://github.com/kumahq/kuma/issues/10607
- [ ] https://github.com/kumahq/kuma/issues/10994
- [ ] https://github.com/kumahq/kuma/issues/10995
- [ ] https://github.com/kumahq/kuma/issues/10996
- [ ] https://github.com/kumahq/kuma/issues/10997
