### ISSUE TITLE
Option to disable Available Services in ZoneIngress

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#10611]
### Description

I think we can just rely on `KUMA_EXPERIMENTAL_SKIP_PERSISTED_VIPS: true`. VIPs are the only way to go through ZoneIngress so if someone disables them, it means that they don't need the old way of accessing services.

**Comment by slonka** [comment]
> Triage: `KUMA_EXPERIMENTAL_SKIP_PERSISTED_VIPS` flag wipes out available services.
