### ISSUE TITLE
Gateway API issue with v 2.8.0

### ISSUE THREAD

**Issue by manju-rn** [kumahq/kuma#10677]
### What happened?

By using the Gateway API - https://kuma.io/docs/2.8.x/using-mesh/managing-ingress-traffic/gateway-api/#kubernetes-gateway-api  
while the Gateway Class and Gateway resource is created, the corresponding POD and LoadBalancer service is not getting created. There are no error logged also.  In v 2.7.3 this works perfectly

**Comment by Automaat** [comment]
I've tested it today with docs example linked in issue on Kuma 2.8.0 and everything worked fine

**Comment by manju-rn** [comment]
I stand corrected. I was not able to reproduce this issue. Most likely with other 2 clusters i had problems with, I might have had mesh deleted in the global control plane in which case the cp nodes were not able to sync and hence was the issue.
Now I created 3 times with no modifications either on global or cp nodes and it works perfectly.  Thanks and sorry for inconvenience, will close the ticket in github
manju@k11:~/kuma$ ku version
Client: Kuma 2.8.0
Server: Kuma 2.8.0
manju@k11:~/kuma$ k get pods -n kuma-system
NAME                                  READY   STATUS    RESTARTS   AGE
kuma-control-plane-5bcb46cd7b-f65mx   1/1     Running   0          5m44s
kuma-gateway-8457985687-qkjb6         1/1     Running   0          4m36s
kuma-ingress-564c8f5954-5xc42         1/1     Running   0          5m44s
manju@k11:~/kuma$ k get svc -n kuma-system
NAME                 TYPE           CLUSTER-IP       EXTERNAL-IP      PORT(S)                                                                                    AGE
kuma-control-plane   LoadBalancer   10.152.183.144   10.173.253.196   5680:30090/TCP,5681:32047/TCP,5682:30293/TCP,443:32461/TCP,5676:31917/TCP,5678:32402/TCP   5m47s
kuma-gateway         LoadBalancer   10.152.183.106   10.173.253.196   80:30230/TCP                                                                               4m39s
kuma-ingress         LoadBalancer   10.152.183.243   <pending>        10001:32730/TCP                                                                            5m47s
