### ISSUE TITLE
DB connection metric

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#1068]
### Summary

Expose metrics with Postgres stats
https://golang.org/src/database/sql/sql.go?s=29131:29944#L1053

```
store_postgres_connections{} // labels: "in_use", "idle"
store_postgres_connections_max{}

store_postgres_connection_wait_count{}
store_postgres_connection_wait_duration{} // technically should be histogram but I would keep it simple as gauge
store_postgres_connection_closed{} // labels: "max_idle_conns", "conn_max_idle_time", "conn_max_life_time"
```

I'm a bit hesitant to put a Pane with a builtin Kuma CP dashboard because most of the deployments are Kubernetes so this chart will be empty and unnecessary. I think just exposing these stats and having it in Prometheus is enough.

**Comment by tharun208** [comment]
I can pick this up.
