### ISSUE TITLE
Add GOMEMLIMIT environment variable in kuma control plane deployment based on helm chart resource limits

### ISSUE THREAD

**Issue by jijiechen** [kumahq/kuma#10714]
### Description

When there is a large number of data planes in the cluster and it exceeds the capacity that Kuma control plane instances can handle, the control plane can be OOM-killed on a Kubernetes.To reduce the chance of being OOM-killed, we can introduce the `GOMEMLIMIT` environment variable on the control plane to make the GC more frequently. 

We can calculate the value and set it automatically based on the resource limit set when installing the control plane using helm chart or kumactl.

**Comment by lahabana** [comment]
@lukidzi this was do no?

**Comment by lukidzi** [comment]
I think it should be solved by https://github.com/kumahq/kuma/pull/10879
