### ISSUE TITLE
In Global Control Plane, the AdvertisedAddress and the AdvertisedPort is wiped off when Workload is created in corresponding Zone

### ISSUE THREAD

**Issue by manju-rn** [kumahq/kuma#10738]
### What happened?

Setup:
1. Cluster with Zone Control plane, Gateway and a HttpRoute resource
2. Cluster with Global Control Plane to which Zone is connected. The ZoneIngress in the GUI is visible and AdvertisedAddress & AdvertisedPort of the zone cluster is manually updated
3. If in the cluster of the zone control, if I delete Workload and corresponding HttpRoute and recreate it, the AdvertisedAddress & AdvertisedPort in Global Control plane vanishes!

Step 1:   Workload and HttpRoute is available in the zone control plane and the AdvertisedAddress & AdvertisedPort is available
![image](https://github.com/kumahq/kuma/assets/26291847/593e854c-2c92-4263-bf60-5f3734a8e63b)
Step 2:  Remove the workload recreate the workload in the zone control plane,
```
manju@k1:~/adminer$ ls
adminer_all.yaml  adminer_http_route.yaml
manju@k1:~/adminer$ k apply -f adminer_all.yaml
service/adminer-svc created
deployment.apps/adminer-app created
```
Step 3: Check the GUI in the Global Control plane, the AdvertisedAddress & AdvertisedPort is missing in the ZoneIngress
![image](https://github.com/kumahq/kuma/assets/26291847/4e7470e3-2c19-4f91-b0c2-1bc5cd031093)

**Comment by michaelbeaumont** [comment]
Hi, can you post the resources you applied? Can you also check the control plane logs for any errors or warnings?

**Comment by manju-rn** [comment]
Okay i found the solution. I think we need to update the docs based on this.
Legend: gk=cluster with Global Control Plane  k1/k2=clusters with Zone Control plane and hosts workloads

Interestingly, if I change the `advertisedAddress` and `advertisedPort` of ZoneIngress via gk, and if in k1 / k2, the workloads are refreshed / workloads  added /deleted, then the `advertisedAddress` and `advertisedPort`  vanish (as my original post).

However, if I update the `advertisedAddress` and `advertisedPort` of ZoneIngress in the respective cluster (k1 / k2), than these values stay put regardless of any workloads change.

I think it might have to do how Global Control Plane uses the zone ingress instances from Zone Control Plane. like:
in gk, the ZoneIngress are like below
```
manju@gk:~$ k -n kuma-system get zoneingress
NAME                                             ZONE
kuma-ingress-564c8f5954-4n22c-z859dvcx86v9zxcc   k1
```
in k1, the ZoneIngress is like:
```
manju@k1:~$ k -n kuma-system get zoneingress
NAME                                             ZONE
kuma-ingress-564c8f5954-4n22c
```
So when changing the ZoneIngress in gk, I was probably changing only the instance value `kuma-ingress-564c8f5954-4n22c-z859dvcx86v9zxcc` and not actual resource itself which is in k1 `kuma-ingress-564c8f5954-4n22c`. **Am i correct in my analysis?**
Hence the ZoneIngress values must not be changed via gk (Global CP), but directly on k1 /k2 (Zone CP)

**Comment by jakubdyszkiewicz** [comment]
Yes, you are correct. You should change the object only in the source of truth which is Zone CP.

Let's double-check our validation. We should prevent users from doing this to avoid such issues.

**Comment by manju-rn** [comment]
Thanks. Yes, i think a validation webhook would be good at global CP to prevent tinkering zone-ingress there
