### ISSUE TITLE
Add possibility to easily identify for which owner (MS, MES, Route) of Envoy resource in ResourceSet

### ISSUE THREAD

**Issue by Automaat** [kumahq/kuma#10820]
### Description

 It would be nice is to find a way to easily identify Envoy resources that was generated for given MeshService, MeshExternalService or Mesh*Route.

Now we have this helpers like [GatherListeners](https://github.com/kumahq/kuma/blob/a1515c18c656f4d68b7460aeb469e75162566eef/pkg/plugins/policies/core/xds/listeners.go#L26) that simply aggregates listeners, clusters etc. But then in policy we need to do some weird translations, extract names from random strings, do some tricky reverse engineering. In my opinion, this brings a lot of complexity to policy code that is hard to understand, and you need to spend quite some time to figure it out every time you revisit policy implementation.

It would be nice to identify these resources by the real resource for which it was generated, for example using UniqueResourceKey introduced in [this MADR](https://github.com/kumahq/kuma/pull/10726). With this, applying policy could be as simple as:

```go
// pseudocode
outboundListeners := GatherListeners(resourceSet)
for _, outbound := range outboundListeners {
  ownerResourceKey := outbound.GetOwnerResourceUniqueKey()
  conf :=  toRules.ResourceRules[ownerResourceKey]
  configureListener(outbound, conf)
}
```

**Comment by lukidzi** [comment]
@Automaat We have something like this now for real resources, dp you think it's enough ?https://github.com/kumahq/kuma/blob/master/pkg/plugins/policies/meshretry/plugin/v1alpha1/plugin.go#L143

**Comment by Automaat** [comment]
@lukidzi this is exactly what I wanted. I forgot closing the issue after implementing it
