### ISSUE TITLE
MeshHTTPRoute with MeshServiceSubset in backendRef probably doesn't work cross zone when created on zone

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#10865]
### What happened?

When building a filterChain for ZoneIngress we [take into account routes](https://github.com/kumahq/kuma/blob/1f9c8337fdff07606b0544af0576d4037370fb1b/pkg/xds/generator/zoneproxy/destinations.go#L55-L70) to know all possible destinations. But when building ZoneIngress config in `zone-1` we take into account only routes synced to `zone-1`. With zone-originated policies it's possible to create MeshHTTPRoute in `zone-2` and it won't be synced to `zone-1` and so that the destination won't be created on ZoneIngress.

The problem exists only for `backendRef.Kind: MeshServiceSubsets`. New way of configuring backend ref with `MeshService` and `MeshMultizoneService` doesn't have this issue.

**Comment by lukidzi** [comment]
> Let's do not do this now, in favor of MeshService. Please comment if needed
