### ISSUE TITLE
Kuma CP on k8s adds `k8s.kuma.io/namespace` label for synced resources

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#10882]
### What happened?

When global-k8s receives resource from zone-uni it's going to add `k8s.kuma.io/namespace: kuma-system` label.

It's bad for a few reasons:
* `kuma.io/zone` and `k8s.kuma.io/namespace` labels are part of the hash, so the invariant for synced resources:
    ```
    name = hashedName(mesh, name, labels[kuma.io/zone], labels[k8s.kuma.io/namespace])
    ```
    is not preserved.
* we should be able to tell if the resource us synced from k8s or uni zone by looking at `k8s.kuma.io/namespace` label. We need this for validation of labels in `backendRef` when referencing MeshService.

**Comment by lukidzi** [comment]
> we shouldn't add namespace labels for resources created on universal and synced, lets look into it
