### ISSUE TITLE
MeshMultiZoneService & MeshLoadBalancingStrategy

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#10935]
### Description

- Potentially we need a MADR

**Comment by jakubdyszkiewicz** [comment]
Blocked on policy matching on MeshMultiZoneService

**Comment by jakubdyszkiewicz** [comment]
Seems like spec stays the same for MeshMultiZoneService.

Add a static validation that if someone is using real MeshService (with port) you cannot do fallback to other zones.
