### ISSUE TITLE
VIP outbounds on Kubernetes + Standalone should be opt-in

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#1096]
### Summary

In 99% cases, users using Kubernetes on Standalone won't use `.mesh`, because they want to leverage builtin Kubernetes naming, but we still do the work of managing VIPs and generating outbound listeners for those VIPs (which means double of outbound listeners). 

Right now user may want to use it for external service, but this should be gone with support for ExternalName type of the Service.

**Comment by lahabana** [comment]
This was done there: https://github.com/kumahq/kuma/pull/3143
