### ISSUE TITLE
`kumactl get mesh` output shows logging, tracing, metrics as off even if the right `Mesh*` policies exist

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#10973]
### Description

We should update/remove these columns

**Comment by bartsmykla** [comment]
> triage: gui is updated to do the right thing - in kumactl we should probably just not show the column and people should be able to do something like kumact get meshinsight

**Comment by jakubdyszkiewicz** [comment]
> Triage: remove columns
