### ISSUE TITLE
HostnameGenerator: Zone Name not interpolated into template

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma#10990]
### What happened?

HostnameGenerator Zone Name not interpolated into template:

For example:

`"hostname": "app-2.svc..mesh.local"`

note the double dots

**Comment by michaelbeaumont** [comment]
Note: we didn't have the `kuma.io/zone` tag on the service

**Comment by lukidzi** [comment]
should be fixed by https://github.com/kumahq/kuma/pull/11062/files

**Comment by lahabana** [comment]
@lukidzi can you confirm this is done and close this if it is?
Thanks!

**Comment by michaelbeaumont** [comment]
Not fixed until https://github.com/kumahq/kuma/pull/11334

**Comment by michaelbeaumont** [comment]
With https://github.com/kumahq/kuma/pull/11334 I think this is automatically fixed.
