### ISSUE TITLE
Always add kuma.io/origin and kuma.io/env to MeshService

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#11014]
### Description

We need it at least for MeshService. Default hostname generators are based on this

Similar as https://github.com/kumahq/kuma/pull/10457

As a part of this, change default hostname generators

**Comment by lobkovilya** [comment]
> triage: we need to check but we probably already add `kuma.io/origin`

**Comment by michaelbeaumont** [comment]
AFAICT we already set `kuma.io/origin`
