### ISSUE TITLE
HELM chart versioning

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#1105]
I want to start a thread about HELM chart versioning. Would be great to have some rules for it.

### Requirements
* Maintain the chart for different versions of Kuma (1.1.x release, 1.0.x release, 1.0-rc releases?) 
* Make it clear to users when it is a breaking change
* Release new version of chart without releasing new version of Kuma

### Info
https://helm.sh/docs/topics/charts/#charts-and-versioning
```
Every chart must have a version number. A version must follow the SemVer 2 standard
More complex SemVer 2 names are also supported, such as version: 1.2.3-alpha.1+ef365. But non-SemVer names are explicitly disallowed by the system.
```

### Questions
Is adding a new parameter to chart results in a new minor or major?
Can the chart version be somewhat in sync with Kuma version?

I'd like to hear your feedback and ideas on this.

**Comment by austince** [comment]
Thanks for starting this thread Jakub! The questions you've posed are great and seem to center around making the chart as straightforward as possible to users.

If we can keep the chart version semantics as if it were truly its own deployment, where new breaking parameters are major, non-breaking are minor, and fixes are patches, that might be both easiest to maintain and to understand as a user.

Keeping the chart version in sync with Kuma sounds like it would make it easier for users to choose a version of Kuma and immediately understand which version of the chart to pick. I think this is something very difficult to achieve and ultimately might be more harmful than forcing users to disassociate the two from the start. A good example of how a chart might change over time is [Prometheus](https://artifacthub.io/packages/helm/prometheus-community/prometheus/11.16.5), which initially versioned matched in [v1.3.1](https://artifacthub.io/packages/helm/prometheus-community/prometheus/1.3.1) but broke with that in v2.0.0. They also have a nice section in the chart readme specifically about migrating between chart versions.

**Comment by nickolaev** [comment]
But, what if we need to bump the chart and not the App itself

**Comment by austince** [comment]
Coming from closed PR https://github.com/kumahq/kuma/pull/1152, here is a good example of releasing an app and charts in the same github repo: https://github.com/kubernetes/autoscaler/releases

**Comment by michaelbeaumont** [comment]
With #3924 we now theoretically have the ability to:

* Maintain the chart for different versions of Kuma (1.1.x release, 1.0.x release, 1.0-rc releases?)
* Release new version of chart without releasing new version of Kuma

Nevertheless, we will leave the following as is:
* `kumactl` will use the Helm chart for `install control-plane`
  * Eventually, we want to implement #1116 
* `kumactl` releases will coincide with Helm chart releases
* `kumactl` releases will coincide with Kuma releases

This implies that Helm chart release versions are 1-1 in sync with Kuma versions which implies the same versioning strategy as Kuma itself.
This implies:

* Is adding a new parameter to chart results in a new minor or major?
  * This depends on whether the new parameter comes in a minor or major release of Kuma
* Can the chart version be somewhat in sync with Kuma version?
  * Yes, it is in sync with it.
