### ISSUE TITLE
Dataplane fails to run if Envoy version is mismatched

### ISSUE THREAD

**Issue by EyeCantCU** [kumahq/kuma#11086]
### What happened?

# The issue

The Kuma dataplane currently fails to run if the version of Envoy used at runtime doesn't precisely align with the version used at buildtime, down to the patch level. 

# Why is this a problem?

If I were to build Kuma from source, currently there's a limitation in place where the version of Envoy defined in `mk/dev.mk` must match exactly with the version provided at runtime.

We end up with this interdependent behavior where if we wanted to upgrade to a newly patched version of Envoy, we'd need to rebuild Kuma, even though there really isn't a reason to do so.

Validating the correct version is in use is important, but it shouldn't stop someone from being able to patch Envoy without needing to do another rebuild for Kuma.

# The solution

I suggest only validating the major and minor version of Envoy align with the version used at buildtime in the version check here: https://github.com/kumahq/kuma/blob/master/app/kuma-dp/pkg/dataplane/envoy/compatibility.go

I do not foresee compatibility issues being a problem for Kuma between patched releases of Envoy, and as far as I can tell, there is not a direct dependency anywhere in the source code on an explicit patched version of Envoy

**Comment by slonka** [comment]
> triage: there will be a PR soon to fix it

**Comment by lahabana** [comment]
@EyeCantCU would https://github.com/kumahq/kuma/pull/11095 solve your problem?

**Comment by EyeCantCU** [comment]
Yes! Thank you so much. That should do the trick :)
