### ISSUE TITLE
Watchdog waits an entire period before first tick

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#11094]
### What happened?

From the code:

https://github.com/kumahq/kuma/blob/ae945b01999633d1e7bd68ad74ae3979ad99b511/pkg/util/watchdog/watchdog.go#L21-L53

We probably should not wait an entire tick before triggering first call. This can delay things unecessarilly (for example sending the configuration).

**Comment by slonka** [comment]
> triage: accepted
