### ISSUE TITLE
How do I use kuma on the intranet that Can't connect to the internet . Because DP (data-plane) dynamically inject into my services pod, I cannot set up to pull DP (data-plane) docker images from my private mirror warehouse harbor.

### ISSUE THREAD

**Issue by huangkaiyan10** [kumahq/kuma#1109]
How do I use kuma with kubernetes on the intranet that Can't connect to the internet . Because DP (data-plane) dynamically inject into my services pod, I cannot set up to pull DP (data-plane) docker images from my private mirror warehouse harbor.

**Comment by nickolaev** [comment]
I have noted your other issue in `kuma-demo`, pasting my answer here for completeness:

Please check [`docker save`](https://docs.docker.com/engine/reference/commandline/save/) and [`docker load`](https://docs.docker.com/engine/reference/commandline/load/).
