### ISSUE TITLE
Deprecate yes/no values for boolean annotations

### ISSUE THREAD

**Issue by jijiechen** [kumahq/kuma#11108]
### Description

We introduced and supported `yes` and `no` as boolean values for Kuma annotation incorrectly in version 2.7 in #8939 
We already have `true/false`, so `yes/no` are not required.

Code location: https://github.com/kumahq/kuma/blame/master/pkg/plugins/runtime/k8s/metadata/annotations.go#L222

**Comment by lukidzi** [comment]
> Triage: Let's deprecate it, but we might need to add information about it in UPGRADE.md

**Comment by jijiechen** [comment]
We did not document the support of these values though.
