### ISSUE TITLE
allow MeshHTTPRoute with backendRef having appProtocol set to tcp

### ISSUE THREAD

**Issue by bcollard** [kumahq/kuma#11115]
### Description

In the context of a gradual migration to the mesh,
a customer of ours wants to do HTTP routing with upstream services that do TLS offloading (historically).
It's impossible to turn off TLS offloading in the upstream services as long as the mTLS is not global and is set to STRICT mode.

In the meantime, one idea is to allow the creation of MeshHTTPRoutes with backend refs that have `appProcotol: tcp`

<img width="1024" alt="image" src="https://github.com/user-attachments/assets/81fc47dc-5481-439d-bf0e-469f64b556bb">

See AHA! [MESH-I-76](https://konghq.aha.io/ideas/ideas/MESH-I-76)

**Comment by michaelbeaumont** [comment]
Closing for https://github.com/kumahq/kuma/issues/11120 since it's not really about having `appProtocol: tcp` but rather configuring a gateway to open a TLS connection to a backend that terminates TLS.
