### ISSUE TITLE
keep CP running and strive for next leader once leader election lost

### ISSUE THREAD

**Issue by Icarus9913** [kumahq/kuma#11123]
### Description

Currently, the cp would exit once the k8s leader election lost. And we're using the `controller-runtime` SDK with these logics.
I was wondering, could we do extra error judgement and let it run again? In such condition, the container could keep going without restart.

```golang

RESTART:
	err := cm.Manager.Start(ctx)
	if err != nil {
	  if err.Error() == "leader election lost" && config.EnableLeaderElectionLostRestart {
            goto RESTART
          }
         ...
	}

```

Further consideration: we should be careful with the leader lost conditions and make sure what kinds of services that the CP could still provide.

**Comment by michaelbeaumont** [comment]
It's not a bad idea but it seems it's intended or at least common that the program exits:

https://github.com/kubernetes-sigs/controller-runtime/blob/main/pkg/manager/internal.go#L601-L604

**Comment by Icarus9913** [comment]
I've checked several CNCF programs which use the controller-runtime SDK with the `LeaderElection`, all of them just exit once the leader lost. Maybe I did the nonstandard way in the past.

Close it.

**Comment by michaelbeaumont** [comment]
See https://github.com/kumahq/kuma/pull/11106 https://github.com/kumahq/kuma/issues/11090
