### ISSUE TITLE
Add E2E test for application probes proxy and virtual probes

### ISSUE THREAD

**Issue by jijiechen** [kumahq/kuma#11122]
### Description

We are introducing the new feature "Application Probes Proxy" in `2.9`, and we want user to be able to switch back to Virtual Probes if they face any problems.

We want both the features work correctly and so does the switching mechanism.
So we need some E2E tests to make sure of this.

xref https://github.com/kumahq/kuma/pull/10624

**Comment by lukidzi** [comment]
> Triage: sounds good
