### ISSUE TITLE
kumactl install HELM-like

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#1116]
### Problem

Right now we've got 2 ways of install control plane on Kubernetes
1) kumactl install control-plane parametrized by CLI args
2) HELM parametrized by `--set key=value` or Values file.

As Kuma grows, it's clear that we need more and more settings. Recently we moved to HELM templates to have a single source of truth about parameters, but the way of parametrizing is different.

Adding new parameters is cumbersome, because you need to add this to HELM then figure out the equivalent in the CLI.
Some of the parameters are impossible to reflect in the CLI like Secrets, so they are missing

### Solution

Adopt HELM way to set parameters, so instead of having this
```
Install Kuma Control Plane on Kubernetes in a 'kuma-system' namespace.

Usage:
  kumactl install control-plane [flags]

Flags:
      --cni-bin-dir string                  set the CNI binary directory (default "/var/lib/cni/bin")
      --cni-chained                         enable chained CNI installation
      --cni-conf-name string                set the CNI configuration name (default "kuma-cni.conf")
      --cni-enabled                         install Kuma with CNI instead of proxy init container
...
```
and
```
kumactl install control-plane --cni-conf-name asdf
```
use
```
kumactl install control-plane --set cni.confName=asdf
```
just like you would use
```
helm install kuma/kuma --set cni.confName=asdf
```

Additionaly, you can pass the list of params
```
kumactl install control-plane --values Values.yaml
```

**How does a user know what are available parameters?**
We can introduce a command that prints default values (straight from the Values.yaml)
```
kumactl install control-plane-config > Values.yaml
vim Values.yaml
kumactl install control-plane --values Values.yaml
```

**Benefits**
* Consistency across kumactl / HELM
* Access to all parameters (some are hard to reflect in CLI)
* Sometimes it's easier to install via Values.yaml
* Less logic in the kumactl install, we can just pass through those params (or Values) to HELM

**Drawback**
* More loosely coupled. Right now the params are rigid, make a typo and you will be notified that CLI arg is not there

What do you think?

**Comment by austince** [comment]
This sounds great!
