### ISSUE TITLE
TCP/gRPC Tracing [Question/Feature Request]

### ISSUE THREAD

**Issue by rymcol** [kumahq/kuma#1119]
### Summary

Currently traces only emit for HTTP. A while back it was mentioned that L7 and tracing was a focus for 0.4.x releases, but it seems like tracing for non-http protocols never made the priority list (https://github.com/kumahq/kuma/issues/548)

### Steps To Reproduce

1. Try to add tracing on anything but HTTP

### Additional Details & Logs

- None

**Comment by rymcol** [comment]
I'm mostly curious if this is WIP or if this is something that is not a focus for a while if anyone has any info, because it will help me make platform decisions

**Comment by jakubdyszkiewicz** [comment]
Hey!

Envoy, for now, supports tracing for HTTP only https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/trace/v3/http_tracer.proto#envoy-v3-api-msg-config-trace-v3-tracing-http

I might be missing something, but I haven't seen tracing with TCP yet. How would you carry tracing data with TCP? There are no metadata headers to pass spans, trace-id etc. Can you give an example of such system?

Thanks!

**Comment by rymcol** [comment]
Yeah, I was thinking more about gRPC, but it would need to be Proto-aware and manage the TLS, which is probably technically feasible, but too many tons of work
