### ISSUE TITLE
Multizone Kubernetes: Wait for Service to be ready to start KDS

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#1134]
### Summary

When we start Remote CP it immediately connects the Global syncing resources. Service is not yet ready therefore validation webhook on Remote fails. Global of course retries sending resources so they are created eventually when Service is ready but we see errors in the code

Related to https://github.com/kumahq/kuma/issues/1001

**Comment by nickolaev** [comment]
Isn't that fixed already?
