### ISSUE TITLE
Kuma 2.6.0 upgrade issues

### ISSUE THREAD

**Issue by sridhar-pulluri** [kumahq/kuma#11416]
### What happened?

I'm trying to upgrade Kuma from 2.5.10 to 2.6.0 and observed that it's adding some extra traffic permissions with random strings appended. 

I have an argocd installed in my cluster, but when I try to upgrade the version, Kuma appends a random text to the end of the zone's traffic permissions. For example, if we create a traffic permissions with the name deny-all, it is propagated to the zone cluster but with a random alphanumeric at the end: deny-all-2648ffwwxx9z. 

It also propagates the labels related to argocd, which makes these new policies appear in the argocd UI, and because they are not produced by argocd, it is shown as out of sync, and when synced, it will prune the resources, which in this  case is trafficpermissions. 

    labels: 

    argocd.argoproj.io/instance: kuma 

    kuma.io/origin: global  

When I upgraded Kuma to version 2.5.10, I didn’t notice these additional traffic permissions and labels. 

At my end, there has been no change to the argocd configuration; everything is operating as expected until Kuma version 2.5.10; nevertheless, it appears that something has changed significantly with Kuma 2.6.0. I attempted to upgrade to version 2.7.0 but was unable; the same issue was found. 

Attached are the issue screen shots for your reference.
<img width="951" alt="Screenshot 2024-09-13 at 9 28 40 AM" src="https://github.com/user-attachments/assets/2cec7ae8-a661-496b-893d-0df8a8438a4d">
<img width="1098" alt="Screenshot 2024-09-13 at 9 28 18 AM" src="https://github.com/user-attachments/assets/923f4bd4-2c9b-4a31-84f2-ab381e614989">

Simulation steps:
1. cluster should have argocd setup
2. install kuma 2.5.10
3. try to upgrade kuma version from 2.5.10 to 2.6.0

**Comment by slonka** [comment]
> Triage: we'll reproduce and fix it
