### ISSUE TITLE
rename argument cp-address to dp-address for kuma-dp run command

### ISSUE THREAD

**Issue by sudeeptoroy** [kumahq/kuma#1145]
kuma-dp run \
  --name=backend-1 \
  --mesh=default \
  --cp-address=https://127.0.0.1:5678 \
  --dataplane-token-file=/tmp/kuma-dp-backend-1-token

earlier kuma-dp had --cp-address as an argument but now it is changed to point to dp server. This is not very intuitive. I would suggest this to be changed to --dp-address

**Comment by jakubdyszkiewicz** [comment]
Hey,

I don't think that
```
kuma-dp run --dp-address=https://127.0.0.1:5678
```
is intuitive. Kuma DP does not connect to Kuma DP, but to Kuma CP. I also don't think the fact that Kuma DP connects to the Kuma CP on the CP management port and then reconnect to another server was intuitive and easy to understand.

I understand this is a breaking change and might be frustrating, but the upcoming release is huge and we strive to simplify Kuma as much as possible. This might be confusing while trying RC versions, but for the final release, we will provide a migration path.

Please read the motivation for this change here https://github.com/kumahq/kuma/pull/1092

**Comment by sudeeptoroy** [comment]
Hi @jakubdyszkiewicz , sure kuma-dp does not connect to kuma-dp but it does connect to kuma-cp on dp-server's address now.
Again kumactl connect to kuma-cp on api server.
Both of them uses --cp-address as an argument. Ita very confusing. The new changes are definitely welcoming. If the argument is charged to something which is easy to understand will really help.

**Comment by lahabana** [comment]
Closing this as there doesn't seem to be a better/clear way than what's done currently.
Also the doc is pretty clear: `--cp-address string                         URL of the Control Plane Dataplane Server. Example: https://localhost:5678 (default "https://localhost:5678")`

It's possible this would get clearer with #3333 but it's not sure whether this issue will get done or not.
