### ISSUE TITLE
Disable targetting MeshCircuitBreaker, MeshHealthCheck and MeshLoadBalancingStrategy in `to[].targetRef.kind` of MeshExternalService

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#11472]
### Description

We're disabling support for these policies because the actual execution happens between Egress and outside world and therefor should have different syntax.

xrel: https://github.com/kumahq/kuma/pull/10921 https://github.com/kumahq/kuma/issues/10897

- [x] https://github.com/kumahq/kuma/pull/11476
- [x] https://github.com/kumahq/kuma/pull/11477
- [x] https://github.com/kumahq/kuma/pull/11478

**Comment by lobkovilya** [comment]
you're probably missing the word "MeshExternalService" in the title right?
