### ISSUE TITLE
Add mesh to openAPI spec

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#11507]
(this issue has been edited by @slonka)

### Description

Other resources we want to have: Mesh, MeshGateway, Secret/GlobalSecret, Zone.

This is part of "[As a user I want to manage mesh resources using OpenAPI spec](https://docs.google.com/document/d/1Ewe0yRx-vvAuQn5CWRFhJbBPLzdbBQ2wsQosZXk4Go8/edit?tab=t.0#heading=h.6j6867jtxnwu)" user story.

We need to find a way to add Mesh to the openAPI spec.

This is tricky because unlike existing resources in the openAPI spec where we go with resource plugins etc, this has a protobuf first approach.

If this could be automatic in some ways that would be ideal as we could add other resources that are still in protobuf and potentially get a complete openAPI spec.

**Comment by slonka** [comment]
coming from: https://github.com/Kong/kong-mesh/issues/6644 

> have default policies inside a mesh but it should be easy to turn them off.

we have [skip_creating_initial_policies](https://github.com/kumahq/kuma/blob/f8179d7a8d0348a67ac7e7983e6d65c1fee339ed/api/mesh/v1alpha1/mesh.proto#L77) - is it just being able to configure this?

**Comment by slonka** [comment]
In an ideal world we would have a flag "publishToOAS" and it would just work.
