### ISSUE TITLE
Feature Request > Sqlite

### ISSUE THREAD

**Issue by wahmedswl** [kumahq/kuma#1160]
### Summary

Postgres is good for production grade cluster but for staging/non-critical environments, its bit hurdle. It would be great if Sqlite etc is supported for zero-config setup or atleast configuration can be provided via files etc and persisted during restarts.

Thanks

**Comment by lahabana** [comment]
Maybe it's a good alternative to memory as it would be closer to the postgres implementation for tests...

**Comment by wahmedswl** [comment]
Yup, also it would be persistent as well. Atleast for deployments, where complexity needs to be reduced. Kuma can provide single robust pkg that is easy to run and work with.

**Comment by lahabana** [comment]
The cost benefit of this feature is a little too high
