### ISSUE TITLE
Consider adding mirrors to dockerfiles to avoid unavailability of archive.ubuntu.com causing a build failure

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#11786]
### Description

![image](https://github.com/user-attachments/assets/293b4990-303b-4530-ad0e-8e7593baa2ba)

Recently we experienced an issue ([link](https://github.com/kumahq/kuma/actions/runs/11379894053/job/31658616714#step:9:678)) with 

```
Unable to connect to archive.ubuntu.com:80
```

if we add mirrors `/etc/apt/sources.list` that could make it more reliable

**Comment by jijiechen** [comment]
Dockerfiles are used in many places, including local builds and on different CI runners, etc.
I'm thinking while adding a static mirror may benefit some scenarios, it can also bring negative effects to other scenarios. So at least this needs to be configurable.

**Comment by slonka** [comment]
> negative effects to other scenarios

can you go into details of this? how can an additional mirror have negative effects?

**Comment by slonka** [comment]
If you're worried about throughput then AFAIK there are tools that detect the closes mirror based on throughput and set up `sources.list` accordingly.

**Comment by slonka** [comment]
https://apt-mirror.github.io/ could work

**Comment by jijiechen** [comment]
Yeah, a public mirror may work.
By `negative effects` I meant when the mirror is not correctly configured, it may break some builds. For example, if we configure it to use Hetzner mirror, then the build will not work on other places.

**Comment by slonka** [comment]
I'm only planning on using public mirrors

**Comment by slonka** [comment]
closed via https://github.com/kumahq/kuma/issues/11809
