### ISSUE TITLE
Cleanup the code that automatically adds namespace labels before the KDS sync

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#11797]
### Description

The problem and reasoning are described in the description https://github.com/kumahq/kuma/pull/11794.

We can't simply remove the code in 2.10, because https://github.com/kumahq/kuma/pull/11794 adds labels dynamically before KDS sync and if the resource was created in 2.7 it's still won't have the label in the store. 

It's not the first time we have this problem. When we add new label on Create/Update this doesn't include resources that were already created in previous Kuma versions. Usually we solve by handling the lack of label when reading the resource. 

What we could try to do is to have a job on CP startup that brings all resources to the same format, i.e. adds required labels to resources in the store.

**Comment by lukidzi** [comment]
> let's keep it
