### ISSUE TITLE
Restrict MeshGateway resource tags validation

### ISSUE THREAD

**Issue by Automaat** [kumahq/kuma#11806]
### What happened?

Right now, MeshGateway tags validation is more loose than validation of tags in Mesh*Route which lets you create Gateway you won't be able to reference in Mesh*Route. 

We have lots of examples of this in our docs, which resulted in this issue: https://github.com/kumahq/kuma-website/issues/1810

**Comment by lukidzi** [comment]
> Triage: Let's figure out how to make the tags validation consistent on the MeshRoute and MeshGateway. We should allow using `/` in tags value
