### ISSUE TITLE
Fix the cross compiling on building image for kuma-init

### ISSUE THREAD

**Issue by jijiechen** [kumahq/kuma#11804]
### What happened?

We are having issues building image for kuma-init, and it's related to the latest version (`24.04`) of the GH public runners:

Here is the failing CI:
* https://github.com/kumahq/kuma/actions/runs/11294867947/job/31442107968#step:9:4051

Here is a discussion of similar issue found in other repos:
* https://github.com/actions/runner-images/issues/10636#issuecomment-2397720931

We've temporarily fixed this issue by pining the runner image version to `22.04-latest` but we need a permanant way to fix.
https://github.com/kumahq/kuma/blob/master/.github/workflows/_build_publish.yaml#L91

**Comment by lukidzi** [comment]
xref: https://github.com/kumahq/kuma/issues/11809

**Comment by jijiechen** [comment]
Duplication of https://github.com/kumahq/kuma/issues/11809
Closed via https://github.com/kumahq/kuma/pull/5945

**Comment by jijiechen** [comment]
Let's use this issue to track if the CI passes with PR   https://github.com/kumahq/kuma/pull/5945 merged.

**Comment by jijiechen** [comment]
Let's use this issue to track if the CI passes with PR https://github.com/kumahq/kuma/pull/11826 merged.
