### ISSUE TITLE
Kuma admission controller rejects specs with non-numerical probe ports. Causing issues with Kong's helm chart.

### ISSUE THREAD

**Issue by arctiqgreg** [kumahq/kuma#1216]
### Summary

Kuma admission controller rejects specs with non-numerical probe ports.
Using a named port is officially supported :
https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#use-a-named-port

### Steps To Reproduce

kubectl create namespace kong
kubectl annotate namespace kong kuma.io/sidecar-injection=enabled
helm install kong  kong/kong -n kong --set ingressController.installCRDs=false
kubectl describe  pods -n kong

- Version 1.0.1

- Error logs
---
bash-3.2$ kubectl describe  pods -n kong | tail -n 1
  Warning  FailedToGenerateKumaDataplane  34s (x23 over 2m54s)   k8s.kuma.io/dataplane-generator                 Failed to generate Kuma Dataplane: admission webhook "validator.kuma-admission.kuma.io" denied the request: spec.probes.endpoints[2].inboundPort: port has to be in range of [1, 65535]; spec.probes.endpoints[3].inboundPort: port has to be in range of [1, 65535]

### Additional Details & Logs
- Configuration
- Platform and Operating System: GKE

**Comment by lobkovilya** [comment]
Yes, that's true, we don't support non-numerical probe ports right now. We already have it on our road map and prioritize it since more people are facing that problem. Use this issue to track the progress.

**Comment by denniseffing** [comment]
Also facing this issue.

**Comment by lobkovilya** [comment]
@arctiqgreg, @denniseffing btw I replied in another [issue](https://github.com/kumahq/kuma/issues/1217) about the workaround, copy it here as well:

> Hey! It seems like your application is using a non-numerical port for HTTPProbe.Port. We don't support named ports for probes in Kuma 1.0.1. There is issue #1216 to track the progress.
>
> Since Envoy captures all inbound traffic for Pod, Kubernetes probes won't work with mTLS enabled. That's why Kuma generates Virtual Probe based on Pod's HTTP Probe. As a workaround you have 2 options right now:
>
> - Disable Virtual Probes. In this case, you can't enable mTLS on the Mesh (by default it's disabled). [How to disable virtual probes?](https://kuma.io/docs/1.0.1/documentation/dps-and-data-model/#kubernetes-probes)
> - Use a numerical value for HTTPProbe.Port
