### ISSUE TITLE
ZoneEgress add support for MeshService and MeshMutliZoneService

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#12288]
### Description

I saw TODOs, haven't found the issue https://github.com/kumahq/kuma/blob/acc6cf8151658dfe898b8c931d0cf424ef5c0e59/pkg/xds/generator/egress/internal_services_generator.go#L40-L41

**Comment by lahabana** [comment]
Duplicate of https://github.com/kumahq/kuma/issues/10728
