### ISSUE TITLE
kuma gui stuck on dataplanes loading

### ISSUE THREAD

**Issue by oded-rosi-spot** [kumahq/kuma#1240]
### Summary

Hey, Im testing the mesh as we are looking for a full kong solution. Ive configured it but Im still somewhat of a beginner on meshes.

### Steps To Reproduce

1. installed on k8s with `kumactl install control-plane | kubectl apply -f -`
2. configured a specific namespace to use this annotations: kuma.io/sidecar-injection: enabled
3. made sure each pod has two ready containers
4. logged in to /gui/all/dataplanes and supposed to see around 80 dataplains. as you can see it blocks me from using every feature.

### Additional Details & Logs

- Version
kuma 1.0.1
- Error logs
[https://pastebin.com/qnPPVN9g]() error log from chrome

[https://ibb.co/BzknvmR]( ) ui screenshots
[https://ibb.co/GcFV0sH]()
No errors from kuma-control-plane
No errors from envoy
- Configuration
running on eks k8s 1.15 without any limits on pods
- Platform and Operating System

**Comment by jakubdyszkiewicz** [comment]
Hey, is the problem still visible in 1.0.4? We've made some changes along the way to dataplane list view.
