### ISSUE TITLE
Dataplane Inspect CLI format

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#1244]
### Summary

@jewertow is working on bringing up info about DP version and wanted to add this as a part of `kumactl inspect dataplanes`. The problem is that the output of the command is already big
```
MESH      NAME         TAGS                                STATUS    LAST CONNECTED AGO   LAST UPDATED AGO   TOTAL UPDATES   TOTAL ERRORS   CERT REGENERATED AGO   CERT EXPIRATION       CERT REGENERATIONS
default   experiment   service=metrics,mobile version=v1   Online    2h                   never              30              3              22h                    2020-05-08 08:28:22   10
default   example      service=example                     Offline   never                never              0               0              never                  -                     0
```
If we add a `KUMA-DP VERSION` and `ENVOY VERSION`, it will be even bigger.

### Idea
One of the ideas how we can solve it is that we can serve only essential info on `kumactl inspect dataplanes`
```
MESH      NAME         TAGS                                STATUS    DP VERSION
default   experiment   service=metrics,mobile version=v1   Online    1.0.1
default   example      service=example                     Offline   1.0.1
```

then we could do `kumactl inspect dataplanes --all` to print all the info
```
MESH      NAME         TAGS                                STATUS    LAST CONNECTED AGO   LAST UPDATED AGO   TOTAL UPDATES   TOTAL ERRORS   CERT REGENERATED AGO   CERT EXPIRATION       CERT REGENERATIONS   DP VERSION   ENVOY VERSION
default   experiment   service=metrics,mobile version=v1   Online    2h                   never              30              3              22h                    2020-05-08 08:28:22   10                   1.0.1        1.16.1
default   example      service=example                     Offline   never                never              0               0              never                  -                     0                    1.0.1        1.16.1
```

but also we can segment info so user can pick what they want to print
* `--xds` prints `LAST CONNECTED AGO`, `LAST UPDATED AGO`, `TOTAL UPDATES`, `TOTAL ERRORS` in addition to default columns
* `--certs` prints `CERT REGENERATED AGO`, `CERT EXPIRATION`, `CERT REGENERATIONS` in addition to default columns
* `--version` prints `DP VERSION`, `ENVOY VERSION` in addition to default columns

@subnetmarco what do you think?

**Comment by jakubdyszkiewicz** [comment]
Hey, @jewertow 

we decided to just expand the `inspect` with 2 extra column regardless if this will break in the terminal. If you could create inspect for with `KUMA-DP VERSION` and `ENVOY VERSION` that would be great

**Comment by jewertow** [comment]
Ok, I will implement it this week.
