### ISSUE TITLE
For services across multi-zones which are publicly reachable ingress need not be provisioned

### ISSUE THREAD

**Issue by sudeeptoroy** [kumahq/kuma#1272]
For scenarios mostly for universal mode, services residing in two separate zones are publicly reachable. For such cases ingress which is used for cross-zone communication may not be needed at all. 

Presently there is no provision for this and ingress is a must. 
This issue is raised to decide on a setting which can be added to take of such scenario.

reference: slack, https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1606750361315300

**Comment by subnetmarco** [comment]
Wouldn't this big a standalone deployment with flat network, or am I wrong? @nickolaev @jakubdyszkiewicz

**Comment by jakubdyszkiewicz** [comment]
Correct. For this case, it's definitely better and simpler to go with a big standalone deployment.

Closing, feel free to reach out to me to reopen if needed.
