### ISSUE TITLE
Missing dataplane version in dataplane insight

### ISSUE THREAD

**Issue by jewertow** [kumahq/kuma#1283]
### Summary

Yesterday [this](https://github.com/kumahq/kuma/pull/1192) PR was merged and now I am working on adding kuma DP and envoy versions to the output of `kumactl inspect dataplanes`.
The problem is that kuma-cp does not return field `dpVersion` in a response from the endpoint `/meshes/{mesh}/dataplanes+insights/{dataplane}`.
I got a response:
```
{
  ...
  "dataplaneInsight": {
    "subscriptions": [
      "version": {
        "dpVersion": {},
        "envoy": {
          "version": "1.15.0",
          "build": "50ef0945fa2c5da4bff7627c3abf41fdd3b7cffd/1.15.0/clean-getenvoy-2aa564b-envoy/RELEASE/BoringSSL"
       }
    }
```

The cause of this bug is incorrect deserializing of `DiscoveryRequest.Node.Metadata` in `dataplane_status_tracker`.

I see two options to fix this bug:

1. Make consistent names of field that represent kuma DP version in `kuma.mesh.v1alpha1.Version` and `bootstrap.yaml`. For now these fields have different names: `dpVersion` and `kumaDp` - and therefore deserialization does not work correctly.

dataplane_insight.proto:
```
message Version {
  // Version of Kuma Dataplane
  KumaDpVersion dpVersion = 1;
  // Version of Envoy
  EnvoyVersion envoy = 2;
}
```

bootstrap.yaml:
```
node:
  metadata:
    version:
      envoy:
      kumaDp:
```

2. Fix a [function](https://github.com/kumahq/kuma/blob/master/pkg/xds/server/dataplane_status_tracker.go#L198) that deserialize metadata.

### Steps To Reproduce

1. Run kuma-cp
2. Run kuma-dp
3. Execute GET request to `/meshes/{mesh}/dataplanes+insights/{dataplane}`

### Fix PR
@jakubdyszkiewicz 
I can fix it today, but first please tell me which option do you prefer.

**Comment by jakubdyszkiewicz** [comment]
@jewertow let's change `dpVersion` to `kumaDp`so 1. option
