### ISSUE TITLE
provide config to set "request_timeout" for streams

### ISSUE THREAD

**Issue by sudeeptoroy** [kumahq/kuma#1320]
https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#stream-timeouts

Continuing our discussion from slack:
https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1607927232406400

**Comment by jakubdyszkiewicz** [comment]
Native Kuma Timeout policy is on our roadmap, approximate estimate is January 2021

**Comment by jakubdyszkiewicz** [comment]
Timeout is now a native policy in Kuma.
