### ISSUE TITLE
Feature Request: circuit-breaker based on max-connections, max-requests, max-pending-requests

### ISSUE THREAD

**Issue by johnniemorrow** [kumahq/kuma#1324]
### Summary

I have a Kubernetes application which includes an ML model. The model is served using [Seldon Core](https://www.seldon.io/tech/products/core/) which provides a REST endpoint for the model.

I want to limit the number of concurrent requests being sent to the model as it can get overloaded. Seldon-core has integrations with [Istio](https://istio.io/latest/docs/tasks/traffic-management/circuit-breaking/) & [Ambassador](https://docs.seldon.io/projects/seldon-core/en/v1.5.0/examples/ambassador_circuit_breakers.html) which both support circuit-breakers based on max-connections, max-requests, and max-pending-requests, responding with a 503/504 if it hits those limits.

We were planning on using Kuma as our service mesh so I was wondering if I could limit the number of connections & requests with that instead. I see Kuma does have [circuit breakers for error counts](https://kuma.io/docs/0.5.1/policies/circuit-breaker/), but is there a way to circuit break based on max-connections, max-requests, and max-pending-requests with Kuma? Or maybe with Kuma+Kong?

**Comment by jakubdyszkiewicz** [comment]
Hey,

yes - we do not have native Kuma policy for configuring those limits. You can however use ProxyTemplate now https://kuma.io/docs/1.0.3/policies/proxy-template to patch cluster of Envoy with those settings.

**Comment by subnetmarco** [comment]
Would this be an update to the existing Circuit Breaker policy? @lobkovilya

**Comment by johnniemorrow** [comment]
Thanks for the link @jakubdyszkiewicz !

I wasn't sure if max-connections/max-pending-requests would fall under any of the categories listed there (Listeners, Clusters, Network Filters, HTTP Filters, VirtualHost) - Envoy lists them on their [circuit breaking overview](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/upstream/circuit_breaking).

But looking through the HTTP Filters on your link, there's an [Adaptive Concurrency](https://www.envoyproxy.io/docs/envoy/latest/api-v2/config/filter/http/adaptive_concurrency/v2alpha/adaptive_concurrency.proto) one which is pretty interesting. I found [a talk by Tony Allen from Lyft](https://www.youtube.com/watch?v=CQvmSXlnyeQ) which gives more details - it looks like it can be easier to tune than a circuit breaker. In his examples though, he does suggest placing a circuit breaker behind it as a safety net :)

I'll play around with using ProxyTemplate to add an Adaptive Concurreny HTTP Filter over the holidays. I'm not sure if ProxyTemplate would allow me to put a circuit breaker behind it too?

**Comment by jakubdyszkiewicz** [comment]
ProxyTemplate allows to:
* add HTTP filter, so you can play around with Adaptive Concurrency HTTP Filter
* Modify cluster so you can modify circuit breaker on the cluster

@subnetmarco this is "bulkhead" that we were talking about a couple of days ago

**Comment by johnniemorrow** [comment]
Ah ok, I didn't look at the Clusters link on that page, I see the circuit breakers there.

That's great, I'll give that a go. Thanks again @jakubdyszkiewicz  !

**Comment by jakubdyszkiewicz** [comment]
https://kuma.io/docs/1.2.1/policies/circuit-breaker/#usage we now have thresholds
