### ISSUE TITLE
Update MeshInsights with DP versions

### ISSUE THREAD

**Issue by subnetmarco** [kumahq/kuma#1327]
Like:

```json
"dp_versions": {
  "kuma_dp": {
    "1.0.0": {
      "total": 10,
      "online": 7,
      "offline": 3
    }
  },
  "envoy": {
    "XYZ": {
      "total": 10,
      "online": 7,
      "offline": 3
    }
  }
}
```

So that this information can be returned in both the GUI and in the CLI.

Related to https://github.com/kumahq/kuma/pull/1291.

**Comment by jewertow** [comment]
I will do it.

**Comment by subnetmarco** [comment]
@jewertow do you have any updates on this work, or should somebody else implement it?

**Comment by jewertow** [comment]
I will submit a pull request this week.
