### ISSUE TITLE
Feature request: Make Trace and Log Backend Part of Mesh

### ISSUE THREAD

**Issue by rucciva** [kumahq/kuma#1328]
### Summary

To leverage the security and multizone feature of kuma for shipping trace and log.

Maybe add these field under `conf`

```
      port: 5670 # envoy listener port to receive trace or log
      path: /metrics # only for trace
      tags: # tags of the trace or log dataplane 
        kuma.io/service: log-or-trace-backend
```

### Additional Details & Logs

- Version: 1.0.3

**Comment by lahabana** [comment]
THis is done already
