### ISSUE TITLE
Versions of the Remote CP in Global CP

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#1364]
### Summary

Just like we now have Kuma DP and Envoy version in Dataplane view in GUI and kumactl we should do the same with Remote and Global CP.

1. Remote CP sends it's version in Metadata of DiscoveryRequest
2. Global CP reads this and put this in ZoneInsight
3. We can now display the version in GUI and kumactl

Not only this will help us present info about versions but it can help us with backward compatibility changes in the future.

**Comment by tharun208** [comment]
@jakubdyszkiewicz I can pick this up
