### ISSUE TITLE
Error: failed to flush zone status

### ISSUE THREAD

**Issue by chris-makaio** [kumahq/kuma#1403]
### Summary

After deleting some K8s services, resources are not synced anymore

### Steps To Reproduce

(no idea)

### Additional Details & Logs

I'm not sure how it happened. I can only confirm that it started happening after removal of the kuma-demo namespace. I've already tried to find the actual execute query params - but no chance. 

 ```
 ERROR   kds-global      failed to flush zone status     {"zone": "ovh-sbg-1", "error": "failed to execute query UPDATE resources SET spec=$1, version=$2, modification_time=$3 WHERE name=$4 AND mesh=$5 AND type=$6 AND version=$7;: pq: payload string too long", "errorVerbose": "pq: payload string too long\nfailed to execute query UPDATE resources SET spec=$1, version=$2, modification_time=$3 WHERE name=$4 AND mesh=$5 AND type=$6 AND version=$7;\ngithub.com/kumahq/kuma/pkg/plugins/resources/postgres.(*postgresResourceStore).Update\n\t/go/src/github.com/kumahq/kuma/pkg/plugins/resources/postgres/store.go:106\ngithub.com/kumahq/kuma/pkg/core/resources/store.(*paginationStore).Update\n\t/go/src/github.com/kumahq/kuma/pkg/core/resources/store/pagination_store.go:34\ngithub.com/kumahq/kuma/pkg/metrics/store.(*MeteredStore).Update\n\t/go/src/github.com/kumahq/kuma/pkg/metrics/store/store.go:46\ngithub.com/kumahq/kuma/pkg/core/resources/store.(*customizableResourceStore).Update\n\t/go/src/github.com/kumahq/kuma/pkg/core/resources/store/customizable_store.go:38\ngithub.com/kumahq/kuma/pkg/core/resources/manager.(*resourcesManager).Update\n\t/go/src/github.com/kumahq/kuma/pkg/core/resources/manager/manager.go:97\ngithub.com/kumahq/kuma/pkg/core/managers/apis/zoneinsight.(*zoneInsightManager).Update\n\t/go/src/github.com/kumahq/kuma/pkg/core/managers/apis/zoneinsight/zone_insight_manager.go:48\ngithub.com/kumahq/kuma/pkg/core/resources/manager.(*customizableResourceManager).Update\n\t/go/src/github.com/kumahq/kuma/pkg/core/resources/manager/customizable_manager.go:43\ngithub.com/kumahq/kuma/pkg/core/resources/manager.Upsert.func1\n\t/go/src/github.com/kumahq/kuma/pkg/core/resources/manager/manager.go:141\ngithub.com/kumahq/kuma/pkg/core/resources/manager.Upsert\n\t/go/src/github.com/kumahq/kuma/pkg/core/resources/manager/manager.go:147\ngithub.com/kumahq/kuma/pkg/kds/server.(*zoneInsightStore).Upsert\n\t/go/src/github.com/kumahq/kuma/pkg/kds/server/status_sink.go:103\ngithub.com/kumahq/kuma/pkg/kds/server.(*zoneInsightSink).Start.func1\n\t/go/src/github.com/kumahq/kuma/pkg/kds/server/status_sink.go:64\ngithub.com/kumahq/kuma/pkg/kds/server.(*zoneInsightSink).Start\n\t/go/src/github.com/kumahq/kuma/pkg/kds/server/status_sink.go:79\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374"}
github.com/go-logr/zapr.(*zapLogger).Error
        /go/pkg/mod/github.com/go-logr/zapr@v0.1.1/zapr.go:128
github.com/kumahq/kuma/pkg/kds/server.(*zoneInsightSink).Start.func1
        /go/src/github.com/kumahq/kuma/pkg/kds/server/status_sink.go:68
github.com/kumahq/kuma/pkg/kds/server.(*zoneInsightSink).Start
        /go/src/github.com/kumahq/kuma/pkg/kds/server/status_sink.go:79
```

**Comment by nickolaev** [comment]
Can you please provide K8s and Kuma versions. Also is this a standalone or multicluster setup?

**Comment by jakubdyszkiewicz** [comment]
also, can you execute `SELECT * FROM resources WHERE type = ZoneInsight` ?
I'd like to see how long is the current `ZoneInsight` object, because it seems we hit some Postgres limits

**Comment by chris-makaio** [comment]
Currently not next to screen, but k8s 1.19 and latest kuma release (downloaded yesterday)

multi-cluster setup with kuma cp running on multiple universal nodes, dps running ok two k8s clusters

**Comment by chris-makaio** [comment]
Pasting from GUI:

`{"subscriptions":[{"id":"52124e48-73a0-473b-a906-6c6a4460b32b","globalInstanceId":"ubuntu-s-2vcpu-4gb-fra1-01-bae3","connectTime":"2021-01-10T11:37:09.545963032Z","status":{"lastUpdateTime":"2021-01-10T12:07:52.588325650Z","total":{"responsesSent":"18","responsesAcknowledged":"17","responsesRejected":"1"},"stat":{"CircuitBreaker":{"responsesSent":"1","responsesAcknowledged":"1"},"Config":{"responsesSent":"1","responsesAcknowledged":"1"},"Dataplane":{"responsesSent":"4","responsesAcknowledged":"4"},"ExternalService":{"responsesSent":"1","responsesAcknowledged":"1"},"FaultInjection":{"responsesSent":"1","responsesAcknowledged":"1"},"HealthCheck":{"responsesSent":"1","responsesAcknowledged":"1"},"Mesh":{"responsesSent":"1","responsesAcknowledged":"1"},"ProxyTemplate":{"responsesSent":"1","responsesAcknowledged":"1"},"Retry":{"responsesSent":"1","responsesAcknowledged":"1"},"Secret":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficLog":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficPermission":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficRoute":{"responsesSent":"2","responsesAcknowledged":"1","responsesRejected":"1"},"TrafficTrace":{"responsesSent":"1","responsesAcknowledged":"1"}}}},{"id":"3ab8df7d-6fb4-4502-83fe-98e07df96c29","globalInstanceId":"ubuntu-s-2vcpu-4gb-fra1-01-c553","connectTime":"2021-01-10T13:00:45.132417055Z","status":{"lastUpdateTime":"2021-01-10T13:00:46.800790546Z","total":{"responsesSent":"14","responsesAcknowledged":"14"},"stat":{"CircuitBreaker":{"responsesSent":"1","responsesAcknowledged":"1"},"Config":{"responsesSent":"1","responsesAcknowledged":"1"},"Dataplane":{"responsesSent":"1","responsesAcknowledged":"1"},"ExternalService":{"responsesSent":"1","responsesAcknowledged":"1"},"FaultInjection":{"responsesSent":"1","responsesAcknowledged":"1"},"HealthCheck":{"responsesSent":"1","responsesAcknowledged":"1"},"Mesh":{"responsesSent":"1","responsesAcknowledged":"1"},"ProxyTemplate":{"responsesSent":"1","responsesAcknowledged":"1"},"Retry":{"responsesSent":"1","responsesAcknowledged":"1"},"Secret":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficLog":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficPermission":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficRoute":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficTrace":{"responsesSent":"1","responsesAcknowledged":"1"}}}},{"id":"21ecc367-1c6e-4836-b45e-c879d758397f","globalInstanceId":"ubuntu-s-2vcpu-4gb-fra1-01-16d6","connectTime":"2021-01-10T13:06:25.835508673Z","status":{"lastUpdateTime":"2021-01-10T13:06:27.344762831Z","total":{"responsesSent":"14","responsesAcknowledged":"14"},"stat":{"CircuitBreaker":{"responsesSent":"1","responsesAcknowledged":"1"},"Config":{"responsesSent":"1","responsesAcknowledged":"1"},"Dataplane":{"responsesSent":"1","responsesAcknowledged":"1"},"ExternalService":{"responsesSent":"1","responsesAcknowledged":"1"},"FaultInjection":{"responsesSent":"1","responsesAcknowledged":"1"},"HealthCheck":{"responsesSent":"1","responsesAcknowledged":"1"},"Mesh":{"responsesSent":"1","responsesAcknowledged":"1"},"ProxyTemplate":{"responsesSent":"1","responsesAcknowledged":"1"},"Retry":{"responsesSent":"1","responsesAcknowledged":"1"},"Secret":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficLog":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficPermission":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficRoute":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficTrace":{"responsesSent":"1","responsesAcknowledged":"1"}}}},{"id":"830c6c58-f863-432d-b0d6-d1f8444a3512","globalInstanceId":"ubuntu-s-2vcpu-4gb-fra1-01-8f2f","connectTime":"2021-01-11T11:14:40.681091775Z","status":{"lastUpdateTime":"2021-01-11T11:14:42.330709216Z","total":{"responsesSent":"14","responsesAcknowledged":"14"},"stat":{"CircuitBreaker":{"responsesSent":"1","responsesAcknowledged":"1"},"Config":{"responsesSent":"1","responsesAcknowledged":"1"},"Dataplane":{"responsesSent":"1","responsesAcknowledged":"1"},"ExternalService":{"responsesSent":"1","responsesAcknowledged":"1"},"FaultInjection":{"responsesSent":"1","responsesAcknowledged":"1"},"HealthCheck":{"responsesSent":"1","responsesAcknowledged":"1"},"Mesh":{"responsesSent":"1","responsesAcknowledged":"1"},"ProxyTemplate":{"responsesSent":"1","responsesAcknowledged":"1"},"Retry":{"responsesSent":"1","responsesAcknowledged":"1"},"Secret":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficLog":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficPermission":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficRoute":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficTrace":{"responsesSent":"1","responsesAcknowledged":"1"}}}},{"id":"f30f9580-3eb5-49b3-83b8-cb928dda0542","globalInstanceId":"ubuntu-s-2vcpu-4gb-fra1-01-fdd0","connectTime":"2021-01-11T11:20:20.247243487Z","status":{"lastUpdateTime":"2021-01-11T11:20:21.751313693Z","total":{"responsesSent":"14","responsesAcknowledged":"14"},"stat":{"CircuitBreaker":{"responsesSent":"1","responsesAcknowledged":"1"},"Config":{"responsesSent":"1","responsesAcknowledged":"1"},"Dataplane":{"responsesSent":"1","responsesAcknowledged":"1"},"ExternalService":{"responsesSent":"1","responsesAcknowledged":"1"},"FaultInjection":{"responsesSent":"1","responsesAcknowledged":"1"},"HealthCheck":{"responsesSent":"1","responsesAcknowledged":"1"},"Mesh":{"responsesSent":"1","responsesAcknowledged":"1"},"ProxyTemplate":{"responsesSent":"1","responsesAcknowledged":"1"},"Retry":{"responsesSent":"1","responsesAcknowledged":"1"},"Secret":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficLog":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficPermission":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficRoute":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficTrace":{"responsesSent":"1","responsesAcknowledged":"1"}}}}]}`

and the other zone
`{"subscriptions":[{"id":"81570665-984c-485f-b851-ee8f3c35d65d","globalInstanceId":"ovh-gate.meetever.dev-3598","connectTime":"2021-01-10T12:05:48.669964070Z","status":{"lastUpdateTime":"2021-01-10T12:40:24.033612945Z","total":{"responsesSent":"221","responsesAcknowledged":"16","responsesRejected":"205"},"stat":{"CircuitBreaker":{"responsesSent":"1","responsesAcknowledged":"1"},"Config":{"responsesSent":"1","responsesAcknowledged":"1"},"Dataplane":{"responsesSent":"54","responsesAcknowledged":"3","responsesRejected":"51"},"ExternalService":{"responsesSent":"1","responsesAcknowledged":"1"},"FaultInjection":{"responsesSent":"1","responsesAcknowledged":"1"},"HealthCheck":{"responsesSent":"1","responsesAcknowledged":"1"},"Mesh":{"responsesSent":"52","responsesAcknowledged":"1","responsesRejected":"51"},"ProxyTemplate":{"responsesSent":"1","responsesAcknowledged":"1"},"Retry":{"responsesSent":"1","responsesAcknowledged":"1"},"Secret":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficLog":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficPermission":{"responsesSent":"52","responsesAcknowledged":"1","responsesRejected":"51"},"TrafficRoute":{"responsesSent":"53","responsesAcknowledged":"1","responsesRejected":"52"},"TrafficTrace":{"responsesSent":"1","responsesAcknowledged":"1"}}}},{"id":"8151a8d0-87f1-477f-ab92-7fe436a2e596","globalInstanceId":"ovh-gate.meetever.dev-9aa9","connectTime":"2021-01-10T13:00:56.958538465Z","status":{"lastUpdateTime":"2021-01-10T13:00:58.292991482Z","total":{"responsesSent":"14","responsesAcknowledged":"14"},"stat":{"CircuitBreaker":{"responsesSent":"1","responsesAcknowledged":"1"},"Config":{"responsesSent":"1","responsesAcknowledged":"1"},"Dataplane":{"responsesSent":"1","responsesAcknowledged":"1"},"ExternalService":{"responsesSent":"1","responsesAcknowledged":"1"},"FaultInjection":{"responsesSent":"1","responsesAcknowledged":"1"},"HealthCheck":{"responsesSent":"1","responsesAcknowledged":"1"},"Mesh":{"responsesSent":"1","responsesAcknowledged":"1"},"ProxyTemplate":{"responsesSent":"1","responsesAcknowledged":"1"},"Retry":{"responsesSent":"1","responsesAcknowledged":"1"},"Secret":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficLog":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficPermission":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficRoute":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficTrace":{"responsesSent":"1","responsesAcknowledged":"1"}}}},{"id":"bcb8d95b-b223-4329-857d-51dbd5a410b7","globalInstanceId":"ovh-gate.meetever.dev-30d6","connectTime":"2021-01-10T13:05:30.881621082Z","status":{"lastUpdateTime":"2021-01-10T13:05:32.247323465Z","total":{"responsesSent":"14","responsesAcknowledged":"14"},"stat":{"CircuitBreaker":{"responsesSent":"1","responsesAcknowledged":"1"},"Config":{"responsesSent":"1","responsesAcknowledged":"1"},"Dataplane":{"responsesSent":"1","responsesAcknowledged":"1"},"ExternalService":{"responsesSent":"1","responsesAcknowledged":"1"},"FaultInjection":{"responsesSent":"1","responsesAcknowledged":"1"},"HealthCheck":{"responsesSent":"1","responsesAcknowledged":"1"},"Mesh":{"responsesSent":"1","responsesAcknowledged":"1"},"ProxyTemplate":{"responsesSent":"1","responsesAcknowledged":"1"},"Retry":{"responsesSent":"1","responsesAcknowledged":"1"},"Secret":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficLog":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficPermission":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficRoute":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficTrace":{"responsesSent":"1","responsesAcknowledged":"1"}}}},{"id":"7cbd957f-d5c3-4d35-be47-42580dbaca99","globalInstanceId":"ovh-gate.meetever.dev-e10a","connectTime":"2021-01-10T13:09:39.898302188Z","status":{"lastUpdateTime":"2021-01-10T13:09:41.219230878Z","total":{"responsesSent":"14","responsesAcknowledged":"14"},"stat":{"CircuitBreaker":{"responsesSent":"1","responsesAcknowledged":"1"},"Config":{"responsesSent":"1","responsesAcknowledged":"1"},"Dataplane":{"responsesSent":"1","responsesAcknowledged":"1"},"ExternalService":{"responsesSent":"1","responsesAcknowledged":"1"},"FaultInjection":{"responsesSent":"1","responsesAcknowledged":"1"},"HealthCheck":{"responsesSent":"1","responsesAcknowledged":"1"},"Mesh":{"responsesSent":"1","responsesAcknowledged":"1"},"ProxyTemplate":{"responsesSent":"1","responsesAcknowledged":"1"},"Retry":{"responsesSent":"1","responsesAcknowledged":"1"},"Secret":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficLog":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficPermission":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficRoute":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficTrace":{"responsesSent":"1","responsesAcknowledged":"1"}}}},{"id":"5dc320b1-2b75-40ca-ba0e-5d1a68d2919c","globalInstanceId":"ovh-gate.meetever.dev-2e46","connectTime":"2021-01-10T19:53:06.057856332Z","status":{"lastUpdateTime":"2021-01-10T19:53:07.375246022Z","total":{"responsesSent":"14","responsesAcknowledged":"14"},"stat":{"CircuitBreaker":{"responsesSent":"1","responsesAcknowledged":"1"},"Config":{"responsesSent":"1","responsesAcknowledged":"1"},"Dataplane":{"responsesSent":"1","responsesAcknowledged":"1"},"ExternalService":{"responsesSent":"1","responsesAcknowledged":"1"},"FaultInjection":{"responsesSent":"1","responsesAcknowledged":"1"},"HealthCheck":{"responsesSent":"1","responsesAcknowledged":"1"},"Mesh":{"responsesSent":"1","responsesAcknowledged":"1"},"ProxyTemplate":{"responsesSent":"1","responsesAcknowledged":"1"},"Retry":{"responsesSent":"1","responsesAcknowledged":"1"},"Secret":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficLog":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficPermission":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficRoute":{"responsesSent":"1","responsesAcknowledged":"1"},"TrafficTrace":{"responsesSent":"1","responsesAcknowledged":"1"}}}}]}`

**Comment by jakubdyszkiewicz** [comment]
Thanks!

@lobkovilya I think we are hitting the limit of payload when we notify the control plane of the change https://www.postgresql.org/docs/9.4/sql-notify.html

> The "payload" string to be communicated along with the notification. This must be specified as a simple string literal. In the default configuration it must be shorter than 8000 bytes. (If binary data or large amounts of information need to be communicated, it's best to put it in a database table and send the key of the record.)

The large `spec` can cause to hit the limit. I see that we are not using `spec` at all, we only rely on `type`, `name` and `mesh`. Can we trigger the event by omitting `spec`?

@chris-makaio 
As a workaround for now I'd suggest just deleting ZoneInsight. It will be recreated.
