### ISSUE TITLE
Feature Request: FIPS 140-2 support for Kuma

### ISSUE THREAD

**Issue by coreywagehoft** [kumahq/kuma#1455]
### Summary
Envoy Proxy has support for [FIPS 140-2](https://www.envoyproxy.io/docs/envoy/latest/intro/arch_overview/security/ssl#fips-140-2) if Envoy is built with the `--define boringssl=fips`

For FIPS 140-2 support you also need the ability to set specific TLS ciphers.  It would be great if Kuma could produce an image with FIPS 140-2 support enabled in Envoy and the ability to select TLS ciphers in the `Mesh` custom resource.

Users would need to still provide a CA certificate for Kuma that was generated using a FIPS approved crypto module, if this was not something that Kuma would support on its own.  I don't see that as requirement for Kuma to support generating the CA with FIPS support for those who want to use it, and I suspect most users with this requirement would prefer to generate their own CA cert.

Support for FIPS 140-2 would differentiate Kuma from other service mesh solutions out there, as I have not found direct support in other service meshes yet.

**Comment by lahabana** [comment]
This doesn't solve the problem but you can easily switch the envoy version inside the kuma image by building a docker image like this:

```
FROM istio/proxyv2:1.8.1 AS envoy

FROM kong-docker-kuma-docker.bintray.io/kuma-dp:1.0.4

COPY --from=envoy /usr/local/bin/envoy /usr/local/bin/envoy
```

This grabs the istio envoy binary and replace it in the kuma-dp image.
I used this to have the WASM plugin in Kuma and that worked well.

**Comment by coreywagehoft** [comment]
Great advice @lahabana for short term possibilities.  Thanks!

**Comment by cThrice** [comment]
This may be a bit late for you, but all the same:

If you have the ability to change your OS to RHEL - https://developers.redhat.com/blog/2019/06/24/go-and-fips-140-2-on-red-hat-enterprise-linux/

This combo helps solve the entire FIPS 140-2 problem set.  Upon enabling FIPS mode it ensures all controls are met ( Including ciphers ) 


Additional references - https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/security_hardening/using-the-system-wide-cryptographic-policies_security-hardening


This would require building a RHEL image for Kuma, and running on a RHEL Host.  But with those two changes, you would be fully FIPS 140-2 compliant ( assuming you are in FIPS mode ) with relation to Network Traffic.  It is also very easy to prove to auditors, as they are very familiar with RHEL and FIPS mode.

**Comment by lahabana** [comment]
This hasn't moved in a while and there are existing workarounds.
