### ISSUE TITLE
Custom port for VIPs

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#1461]
Vips are pretty useful in Kuma.
However, they are always bound to port 80 (see: https://github.com/kumahq/kuma/blob/master/pkg/dns/outbound.go#L14).
From a technical POV it's ok but for ease of use I'd like to be able to specify which port my service is going to be exposed on (It's weird for people to not use 5432 for Postgres or 9092 for Kafka).

I think this can be an extra configuration either as tags or as a new entry in the `dataplane.inbound` config and will be carried forward on `ingress.available` services.

If we agree on the right way to configure this I believe the code change is pretty simple and I can write it.

**Comment by nickolaev** [comment]
We had lots of debates when designing this feature and we settled for port `80`. I do agree that it would ake sense to be able to override this in case one needs it.
I'd call for @subnetmarco's opinion here.

**Comment by lahabana** [comment]
Thinking about this a little more it like a tag like `kuma.io/port` would work for Ingress, ExternalServices and regular DPs.
If it's unset we use port 80 (Original behavior) If it's set we use whatever is set in there.

WDYT?

**Comment by thirdeyenick** [comment]
Would it be possible to actually use the port which is defined in the k8s service automatically?

**Comment by lahabana** [comment]
This will be possible with: #1978 so closing this
