### ISSUE TITLE
Add test cases to test only universal or only kubernetes mode

### ISSUE THREAD

**Issue by nikita15p** [kumahq/kuma#1486]
### Summary
In the make file, there should be a target available to test only universal mode or only kubernetes mode.

SUMMARY_GOES_HERE
for eg: 
`kumactl install` is used for kubernetes mode and not for universal mode. Similarly `kumactl apply` is available only for universal mode. So if a user uses only universal mode, he can just run `make test/universal_mode` and get all the modules used in that mode tested.

### Steps To Reproduce
NA

### Additional Details & Logs
Refer: https://kuma.io/docs/1.0.6/documentation/cli/#kumactl for available commands as per each mode.

**Comment by nickolaev** [comment]
@nikita15p do you plan to work on this?

**Comment by nikita15p** [comment]
Will take it up.

**Comment by lahabana** [comment]
Inactive for too long. Let's close this as there isn't much traction to work on it.
