### ISSUE TITLE
Some tests are not running due to missing test_suite files.

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#1492]
While working on #1489 I've noticed that the tests in `pkg/plugins/runtime/universal/outbound` were not running because of a missing suite_test file.

From a quick look around I've noticed another package that doesn't have a test_suite (`pkg/dns/vips`).

We probably:

a) Fix all missing `test_suite`
b) Add a check to ensure that new tests do actually run

**Comment by jpeach** [comment]
> From a quick look around I've noticed another package that doesn't have a test_suite (`pkg/dns/vips`).

This particular case seems OK now ...

https://github.com/kumahq/kuma/blob/cf671dd0b88760b0dd25f926cebfdfabf0aafe31/pkg/dns/vips/vips_suite_test.go#L9-L11
