### ISSUE TITLE
Kuma Documentation for prometheus-sd run command still shows http protocol instead of grpc / grpcs

### ISSUE THREAD

**Issue by nikita15p** [kumahq/kuma#1515]
### Summary

SUMMARY_GOES_HERE
kuma-prometheus-sd needs grpc/grpcs protocol of kuma control plane to be provided on --cp-address flag, otherwise it fails.

But in following snap of doc, there is no mention of grpc/grpcs
![image](https://user-images.githubusercontent.com/37657012/106891450-b2183280-6710-11eb-9a72-ae45a4dc15ba.png)

### Steps To Reproduce
Run following command with --cp-address having http/https protocol:
kuma-prometheus-sd run \
  --cp-address=http://kuma-control-plane.internal:5676 \
  --output-file=/var/run/kuma-prometheus-sd/kuma.file_sd.json

### Additional Details & Logs
Refer https://kuma.io/docs/1.0.6/policies/traffic-metrics/
- Version
v1.0.6
- Error logs
- Configuration
- Platform and Operating System

**Comment by nickolaev** [comment]
@bradamant3 might be able to help
