### ISSUE TITLE
Disable check for an update

### ISSUE THREAD

**Issue by ip1981** [kumahq/kuma#1553]
Is there a way to disable this check for the latest version?

![Screenshot_2021-02-11_20-08-22](https://user-images.githubusercontent.com/131844/107679238-fa04ff80-6ca4-11eb-8a95-1a50d6cb28c3.png)

**Comment by nickolaev** [comment]
I am not aware of such.

**Comment by lahabana** [comment]
Not a lot of interest in getting this done.
On the Kuma side we like to motivate people to upgrade to a recent more stable version.
