### ISSUE TITLE
Consider creating RPM and Deb packages for kuma

### ISSUE THREAD

**Issue by jgrund** [kumahq/kuma#1566]
Hi,

We are currently running a universal deployment, and it would be very useful to have pre-built packages for both RPM and Deb.

**Comment by subnetmarco** [comment]
In Kong we are creating these packages via https://github.com/jordansissel/fpm with great success. Perhaps we can think of doing the same with Kuma.

**Comment by jgrund** [comment]
We would still find this useful; we are currently building RPMs and DEB packages from source for universal deployment.

**Comment by lahabana** [comment]
There hasn't been much ask for this so deprioritizing this
