### ISSUE TITLE
support auto discovery of mesh services to remove .mesh requirement for transparent mode 

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1623]
### Summary

Support auto discovery of mesh services to remove .mesh requirement for transparent mode. Instead of requiring the `.mesh` (or `KUMA_DNS_SERVER_DOMAIN`) for DNS resolution and routing of transparent mode services. For example, create an external service to `httpbin.org` named `httpbin`. Instead of requiring `httpbin.mesh` allow for routing to the envoy `httpbin` cluster using `httpbin.org`. 

Non mesh-services that are not matched to an existing service will be passthrough.

**Comment by nickolaev** [comment]
This can be supported once we have Envoy DNS by @lahabana.

**Comment by lahabana** [comment]
Yes this should be possible. Here's the spec: https://github.com/kumahq/kuma/blob/master/docs/proposals/dns-using-envoy.md . Let me know if you think this doesn't work out

**Comment by subnetmarco** [comment]
@nickolaev @lahabana what is the status on the Envoy DNS work?

**Comment by jakubdyszkiewicz** [comment]
This now works with ExternalServices.
