### ISSUE TITLE
chrome fails to load the kuma UI 

### ISSUE THREAD

**Issue by sudeeptoroy** [kumahq/kuma#1626]
looking at the console i can see 2 errors:
1. TypeError: Cannot read property 'substring' of null
2. uncaught (in promise) TypeError: Cannot read property 'split' of null.

**Comment by bartsmykla** [comment]
Hi @sudeeptoroy could you give us some more information? 
- What is the version of kuma you are using?
- Is there anything interesting in the `Network` tab of your browser?
- Does your browser points at any particular object/element which is `null`?

**Comment by bartsmykla** [comment]
@sudeeptoroy is it still an issue?
