### ISSUE TITLE
document which images must be pulled

### ISSUE THREAD

**Issue by aaronhmiller** [kumahq/kuma#1627]
### Summary

When installing into a secure network, Kuma pulls down multiple images from different locations. This will fail without either:
 1. adding those domains to an allow list
 2. pulling all those images and placing them on a secure image repository

Both need a list of what images are in the chart(s) and their domains.

### Steps To Reproduce

1. Be behind a firewall
2. Attempt to install Kuma
3. Receive multiple ImagePullBackoff errors

### Additional Details & Logs

- Version: Kuma 1.0.8
- Error logs: ImagePullBackoff
- Configuration: n/a
- Platform and Operating System: n/a

**Comment by austince** [comment]
I believe these are documented sufficiently for now, but am open to adding more places if you'd like + they make sense. Closing for now.
