### ISSUE TITLE
Support latency-based fail-fast

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1632]
### Summary

Provide a mechanism (e.g. load-balancer plugin) where a DPP to a service will fail-fast (e.g. remove an offending endpoint from a lb cluster) when a configurable number of previous requests to that endpoint have exceeded a configurable latency threshold. The endpoint would be added back to the lb rotation after some configurable time. 

L4 and L7 latency

**Comment by jakubdyszkiewicz** [comment]
> Triage: requires Envoy contrib. There is no such functionality right now

**Comment by jakubdyszkiewicz** [comment]
> Triage: closing for now as there is no interest currently in this
