### ISSUE TITLE
Expose all Envoy health_check parameters through Kuma API

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1633]
### Summary

Expose all Envoy health_check parameters through Kuma API. The following are not currently exposed and require a ProxyTemplate:

interval_jitter_percentage
no_traffic_interval
event_log_path
always_log_health_check_failure

**Comment by jakubdyszkiewicz** [comment]
https://kuma.io/docs/1.2.1/policies/health-check/ done
