### ISSUE TITLE
add Zipkin shared_span_context Configuration

### ISSUE THREAD

**Issue by ericmustin** [kumahq/kuma#1656]
### Summary
👋 Hello, would y'all take a PR to add support for configuring [shared_span_context](https://github.com/envoyproxy/envoy/blob/1d1b708c7bf6efa02c41d9ce22cbf1e4a1aeec2c/api/envoy/config/trace/v3/zipkin.proto#L63) on the [`zipkin` tracing configuration](https://github.com/kumahq/kuma/blob/d24b69d660662a06af519c1ef007f1f965d46278/pkg/xds/envoy/listeners/v2/tracing_configurer.go#L59-L64)?

https://github.com/kumahq/kuma/blob/d24b69d660662a06af519c1ef007f1f965d46278/pkg/xds/envoy/listeners/v2/tracing_configurer.go#L59-L64

This config option, which controls whether to reuse span_id for both `client` and `server` spans (a concept largely unique to zipkin), causes some users to experience issues downstream in Opentelemetry, so having the configurability would be super helpful. for context: 

- https://github.com/open-telemetry/opentelemetry-specification/issues/1007
- https://github.com/open-telemetry/opentelemetry-collector-contrib/pull/2622

**Comment by jakubdyszkiewicz** [comment]
Hey @ericmustin 

Sounds reasonable to add it, feel free to send a PR!

**Comment by ericmustin** [comment]
@jakubdyszkiewicz pushed up a pr, lmk what u think

**Comment by ericmustin** [comment]
just chiming in to say i tested the pr here and this does work as expected: 

And now look, some nice, connected distributed traces of kong/kuma/envoy/nodejs in zipkin+opentelemetry, being displayed in datadog :)

<img width="997" alt="Image 2021-03-15 at 4 26 56 AM" src="https://user-images.githubusercontent.com/14250318/111129044-00a8c000-854c-11eb-8dc3-c6832d11482b.png">
