### ISSUE TITLE
Kuma Dashboard doesn't show the correct services status on 1.1.0

### ISSUE THREAD

**Issue by notsofunctional** [kumahq/kuma#1662]
### Summary

I updated 3 hours ago Kuma, everything went fine, then i redeployed my DPs to update kuma-dp, DPs appear to be online but services don't:

![image](https://user-images.githubusercontent.com/3385668/110706683-df4b7b00-81bd-11eb-8fe5-334a2a033ae0.png)

but using CLI they appear online:

![image](https://user-images.githubusercontent.com/3385668/110706745-f38f7800-81bd-11eb-9b38-6cf54ee489fd.png)

Any feedback about this?

### Steps To Reproduce

1. Upgrade Kuma from 1.0.8 to 1.1.0 with existent services and DPs
2. Dashboard shows DPs online and Services Offline

### Additional Details & Logs

- Version: 1.1.0
- Error logs
- Configuration
- Platform and Operating System

**Comment by nickolaev** [comment]
Solved in 1.1.1
