### ISSUE TITLE
Warning on kuma mesh creation resulting to missing pods

### ISSUE THREAD

**Issue by reenolesigues** [kumahq/kuma#1680]
### Summary

SUMMARY_GOES_HERE

### Steps To Reproduce

1. Run `kumactl install control-plane | kubectl apply -f -`
2. Observe warnings
3. Run `kubectl get pod -n kuma-system`
4. Notice `No resources found in kuma-system namespace`

### Additional Details & Logs

- Version

> kubectl: v1.20.4
> kumactl: 1.1.1

- Error logs

> namespace/kuma-system unchanged
> serviceaccount/kuma-control-plane unchanged
> secret/kuma-tls-cert unchanged
> configmap/kuma-control-plane-config unchanged
> Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
> customresourcedefinition.apiextensions.k8s.io/circuitbreakers.kuma.io unchanged
> customresourcedefinition.apiextensions.k8s.io/dataplanes.kuma.io configured
> customresourcedefinition.apiextensions.k8s.io/serviceinsights.kuma.io configured
> customresourcedefinition.apiextensions.k8s.io/timeouts.kuma.io unchanged
> customresourcedefinition.apiextensions.k8s.io/trafficlogs.kuma.io unchanged
> customresourcedefinition.apiextensions.k8s.io/trafficpermissions.kuma.io unchanged
> customresourcedefinition.apiextensions.k8s.io/trafficroutes.kuma.io unchanged
> customresourcedefinition.apiextensions.k8s.io/traffictraces.kuma.io unchanged
> customresourcedefinition.apiextensions.k8s.io/zoneinsights.kuma.io unchanged
> customresourcedefinition.apiextensions.k8s.io/zones.kuma.io unchanged
> customresourcedefinition.apiextensions.k8s.io/dataplaneinsights.kuma.io configured
> customresourcedefinition.apiextensions.k8s.io/externalservices.kuma.io unchanged
> customresourcedefinition.apiextensions.k8s.io/faultinjections.kuma.io unchanged
> customresourcedefinition.apiextensions.k8s.io/healthchecks.kuma.io unchanged
> customresourcedefinition.apiextensions.k8s.io/meshinsights.kuma.io configured
> customresourcedefinition.apiextensions.k8s.io/meshes.kuma.io configured
> customresourcedefinition.apiextensions.k8s.io/proxytemplates.kuma.io configured
> customresourcedefinition.apiextensions.k8s.io/retries.kuma.io unchanged
> clusterrole.rbac.authorization.k8s.io/kuma-control-plane unchanged
> clusterrolebinding.rbac.authorization.k8s.io/kuma-control-plane unchanged
> role.rbac.authorization.k8s.io/kuma-control-plane unchanged
> rolebinding.rbac.authorization.k8s.io/kuma-control-plane unchanged
> service/kuma-control-plane unchanged
> deployment.apps/kuma-control-plane configured
> Warning: admissionregistration.k8s.io/v1beta1 MutatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 MutatingWebhookConfiguration
> mutatingwebhookconfiguration.admissionregistration.k8s.io/kuma-admission-mutating-webhook-configuration configured
> Warning: admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+, unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration
> validatingwebhookconfiguration.admissionregistration.k8s.io/kuma-validating-webhook-configuration configured

- Platform and Operating System: kubernetes | Ubuntu 20
- Installation Method: kumactl | kubernetes

![kuma warnings](https://user-images.githubusercontent.com/1477158/111071113-983bed80-850f-11eb-81c3-a391bc6fd07e.PNG)

**Comment by reenolesigues** [comment]
I believe the fix would be updating those warning parameters from /v1beta1 to /v1 and adding/updating the parameter pre-requisites.

**Comment by nickolaev** [comment]
Might be relevant to https://github.com/kumahq/kuma/pull/1108

**Comment by austince** [comment]
I don't think we have an issue yet for the webhooks @nickolaev, I'll make one.

**Comment by nickolaev** [comment]
> I don't think we have an issue yet for the webhooks @nickolaev, I'll make one.

I addressed the webhook upgrade in the last commit to #1108 it's a small change so I hope we can squeeze it there too.

**Comment by jakubdyszkiewicz** [comment]
Those warnings are now solved
