### ISSUE TITLE
Integrate with Kong Ingress Controller

### ISSUE THREAD

**Issue by codyde** [kumahq/kuma#1689]
### Summary

When mTLS is enabled on a Kuma/Kong Mesh cluster, an ingress resource needs to be used in order to connect to services within the mesh. Out of the box this isn't provided today however it would be relatively straight forward to integrate Kong's ingress controller using kumactl. A command such as `kumactl install kong-ingress | kubectl apply -f -` would be a pretty great user experience add and would simplify the process for getting started.

**Comment by PinOliver** [comment]
@codyde  Hi, I am facing this exact issue. Could you please elaborate how to make it work or point me there. 
Thanks!

**Comment by codyde** [comment]
> @codyde Hi, I am facing this exact issue. Could you please elaborate how to make it work or point me there.
> Thanks!

Hi @PinOliver! Currently this "integrated" option isn't in Kuma. This issue is a feature request to have the option added to kumactl. 

Getting the Kong Ingress Controller configured out of band isn't too bad though today. This blog roughly covers the process - https://konghq.com/blog/exposing-kuma-service-mesh-using-kong-api-gateway/ - give that a read and feel free to ping back if you have any issues. I'll look at getting an updated blog together for this.

**Comment by subnetmarco** [comment]
I believe this can be addressed quickly in the next release.

**Comment by subnetmarco** [comment]
It should probably be `kumactl install kong-gateway` so that we don't confuse it with our own Kuma ingress object.

**Comment by jakubdyszkiewicz** [comment]
we now have `kumactl install gateway --type kong`
