### ISSUE TITLE
Use consistent port (9901) for envoy admin api/console between k8s and universal

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1724]
Currently the ports are different ... k8s uses the 9901 standard and universal uses 30001.

**Comment by subnetmarco** [comment]
@kumahq/kuma-maintainers this should be an easy fix?

**Comment by jakubdyszkiewicz** [comment]
I'd change this in the next major. Technically it's "internal" port, but just so we don't break something, let's do this in next major.

**Comment by lahabana** [comment]
Duplicate of #3281
