### ISSUE TITLE
config to modify service names

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1752]
### Summary

I'd like to deploy a service to both a k8s zone and a universal zone and configure the service name. Currently the k8s service is: `kuma.io/service: <name>_<namespace>_svc_<port>` so I need to use this for the universal service. 

Which doesn't make sense for a universal service since there is no namespace.

**Comment by lahabana** [comment]
Seems like it's indeed not feasible yet.
Should adding a `kuma.io/service` annotation to the k8s service (or the pod for serviceless pods).

**Comment by jpeach** [comment]
So the underlying request here is to set a consistent service name across zones?

**Comment by lahabana** [comment]
duplicate of #3238
