### ISSUE TITLE
PostgreSQL password in clear text 

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1787]
### Summary

Password should not be in clear text

### Steps To Reproduce

`2021-04-08T22:13:16.512Z	INFO	kuma-cp.run	Current config {"apiServer":{"auth":{"allowFromLocalhost":true,"clientCertsDir":"/home/ec2-user"},"corsAllowedDomains":[".*"],"http":{"enabled":true,"interface":"0.0.0.0","port":5681},"https":{"enabled":true,"interface":"0.0.0.0","port":5682,"tlsCertFile":"/home/ec2-user/ip-172-31-32-87.us-east-2.compute.internal.crt","tlsKeyFile":"/home/ec2-user/ip-172-31-32-87.us-east-2.compute.internal.key"},"readOnly":false},"bootstrapServer":{"apiVersion":"v3","params":{"adminAccessLogPath":"/dev/null","adminAddress":"127.0.0.1","adminPort":0,"xdsConnectTimeout":"1s","xdsHost":"","xdsPort":5678}},"defaults":{"skipMeshCreation":false},"diagnostics":{"debugEndpoints":false,"serverPort":5680},"dnsServer":{"CIDR":"240.0.0.0/4","domain":"mesh","port":53},"dpServer":{"auth":{"type":"dpToken"},"hds":{"checkDefaults":{"healthyThreshold":1,"interval":"1s","noTrafficInterval":"1s","timeout":"2s","unhealthyThreshold":1},"enabled":true,"interval":"5s","refreshInterval":"10s"},"port":5678,"tlsCertFile":"/home/ec2-user/ip-172-31-32-87.us-east-2.compute.internal.crt","tlsKeyFile":"/home/ec2-user/ip-172-31-32-87.us-east-2.compute.internal.key"},"environment":"universal","general":{"dnsCacheTTL":"10s","tlsCertFile":"/home/ec2-user/ip-172-31-32-87.us-east-2.compute.internal.crt","tlsKeyFile":"/home/ec2-user/ip-172-31-32-87.us-east-2.compute.internal.key","workDir":"/root/.kuma"},"guiServer":{"apiServerUrl":""},"metrics":{"dataplane":{"enabled":true,"subscriptionLimit":10},"mesh":{"maxResyncTimeout":"20s","minResyncTimeout":"1s"},"zone":{"enabled":true,"subscriptionLimit":10}},"mode":"standalone","monitoringAssignmentServer":{"assignmentRefreshInterval":"1s","grpcPort":5676},"multizone":{"global":{"kds":{"grpcPort":5685,"refreshInterval":"1s","tlsCertFile":"/home/ec2-user/ip-172-31-32-87.us-east-2.compute.internal.crt","tlsKeyFile":"/home/ec2-user/ip-172-31-32-87.us-east-2.compute.internal.key","zoneInsightFlushInterval":"10s"},"pollTimeout":"500ms"},"remote":{"kds":{"refreshInterval":"1s","rootCaFile":""}}},"reports":{"enabled":true},"runtime":{"kubernetes":{"admissionServer":{"address":"","certDir":"","port":5443},"controlPlaneServiceName":"kuma-control-plane","injector":{"caCertFile":"","cniEnabled":false,"exceptions":{"labels":{"openshift.io/build.name":"*","openshift.io/deployer-pod-for.name":"*"}},"initContainer":{"image":"kuma/kuma-init:latest"},"sidecarContainer":{"adminPort":9901,"drainTime":"30s","envVars":{},"gid":5678,"image":"kuma/kuma-dp:latest","livenessProbe":{"failureThreshold":12,"initialDelaySeconds":60,"periodSeconds":5,"timeoutSeconds":3},"readinessProbe":{"failureThreshold":12,"initialDelaySeconds":1,"periodSeconds":5,"successThreshold":1,"timeoutSeconds":3},"redirectPortInbound":15006,"redirectPortOutbound":15001,"resources":{"limits":{"cpu":"1000m","memory":"512Mi"},"requests":{"cpu":"50m","memory":"64Mi"}},"uid":5678},"sidecarTraffic":{"excludeInboundPorts":[],"excludeOutboundPorts":[]},"virtualProbesEnabled":true,"virtualProbesPort":9000},"marshalingCacheExpirationTime":"5m0s"},"universal":{"dataplaneCleanupAge":"72h0m0s"}},"sdsServer":{"dataplaneConfigurationRefreshInterval":"1s"},"store":{"cache":{"enabled":true,"expirationTime":"1s"},"kubernetes":{"systemNamespace":"kuma-system"},"postgres":{"connectionTimeout":5,"dbName":"kuma","host":"localhost","maxOpenConnections":0,"maxReconnectInterval":"1m0s","minReconnectInterval":"10s","password":"*****","port":5432,"tls":{"caPath":"","certPath":"","keyPath":"","mode":"disable"},"user":"kumauser"},"type":"postgres","upsert":{"conflictRetryBaseBackoff":"100ms","conflictRetryMaxTimes":5}},"xdsServer":{"dataplaneConfigurationRefreshInterval":"1s","dataplaneStatusFlushInterval":"10s","nackBackoff":"5s"}}`

**Comment by austince** [comment]
Ok, thanks for the confirmation @tharun208 ! @bdecoste, please ping if this is not what you're seeing.
