### ISSUE TITLE
Support yaml configuration for rest api

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1788]
### Summary

kumactl supports yaml while the rest api supports json. I'd like to be able to use the same config/format for each.

**Comment by tharun208** [comment]
@austince I like to work on this

**Comment by jakubdyszkiewicz** [comment]
what are the requirements? Kuma CP returns YAML from the API? Kuma CP accepts YAML when applying resources?

**Comment by jpeach** [comment]
Not sure why we would do this. It's pretty simply to convert YAML to JSON in a tool if you are writing some scripts.

**Comment by tharun208** [comment]
unassigning myself from this issue
