### ISSUE TITLE
Support  ingress annotations (kuma.io/ingress-public-address and kuma.io/ingress-public-port) in helm

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1795]
### Summary

I'd like to provide ingress annotations (kuma.io/ingress-public-address and kuma.io/ingress-public-port) in helm

https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/templates/ingress-deployment.yaml#L23-L24

**Comment by austince** [comment]
I think an `ingress.extraAnnotations` value with an empty object default would be good here – any bandwidth to make that PR?
