### ISSUE TITLE
broken link at https://kuma.io/docs/1.1.2/documentation/cli/#kumactl

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1810]
### Summary

The link at **_used to generate Dataplane Token is bad_**: https://kuma.io/docs/1.1.2/documentation/cli/#kumactl

**Comment by bdecoste** [comment]
The link has been broken since 1.0.7

**Comment by austince** [comment]
Thanks for reporting, closing in favor of https://github.com/kumahq/kuma-website/issues/418
