### ISSUE TITLE
Mark dps as `healthy: unknown` if dps are not connected to envoy

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#1883]
This started in [this slack thread](https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1618567828142500).

From @lobkovilya:

Let’s look at 2 situations:
1. Envoy is running, Application is down. In this case HDS will work properly and you’ll see healthy: ready: false . So this Dataplane will be excluded from ClusterLoadAssignments and everything great. This case was a primary reason for introducing ServiceProbes - having a healthy Envoy we want to make sure that the application is not dead.
2. Envoy is down, Application is running (or dead as well). In this case we will mark Dataplane as offline using Dataplane insights (so you’ll see this in GUI), but we won’t exclude this from ClusterLoadAssignments. Like you correctly noticed it can be a connectivity issue between kuma-dp and kuma-cp. If Envoy is dead for real then HealthCheck and CircuitBreaker should catch this. Yes, you’ll see healthy: ready: true in the Store and that’s probably a really confusing moment. What if we change it to healthy: ready: unknown to explicitly show that we’re struggling to get the application status?

Sounds like option 2 would make things more understandable and provide visibility inside the health flag.

**Comment by jakubdyszkiewicz** [comment]
> Triage: "duplicate" of https://github.com/kumahq/kuma/issues/2346
> If we have a separate status for xds and health we can show a warning in the GUI that you cannot fully trust health.
