### ISSUE TITLE
Bintray Images Unavailable, New Location?

### ISSUE THREAD

**Issue by markramach** [kumahq/kuma#1884]
### Summary

All kuma bintray images seem to be unavailable because of the decommissioning of the bintray registry. Is there a new location for these images? I can't find any details on new image locations.

### Steps To Reproduce

1. docker pull kong-docker-kuma-docker.bintray.io/kuma-cp:1.1.4

### Additional Details & Logs

```
$ docker pull kong-docker-kuma-docker.bintray.io/kuma-cp:1.1.4
1.1.4: Pulling from kuma-cp
ba3557a56b15: Pulling fs layer 
139abb0fa6cb: Pulling fs layer 
bdfdf695dc3d: Pulling fs layer 
6aa848f52980: Waiting 
09bea9fadc58: Waiting 
67e5dd11d8e1: Waiting 
b2f98db9e48a: Waiting 
b6f115b12645: Waiting 
error pulling image configuration: error parsing HTTP 403 response body: invalid character 'F' looking for beginning of value: "Forbidden!"
```

**Comment by austince** [comment]
I think you likely hit yesterday's BinTray brown-out: https://status.bintray.com/incidents/kh3zbvqkvj2c

BinTray is being sunset, so we are going to be moving the images in the coming months.

**Comment by austince** [comment]
See: https://github.com/kumahq/kuma/pull/1901

**Comment by markramach** [comment]
Thanks for the response. After I determined it was a brownout, I was able to resolve the following day. The sunset date on Bintray is May 1, 2021. So, I'm assuming the updates are days, not months away.

**Comment by austince** [comment]
Yes, we should be fully on Docker Hub now: https://hub.docker.com/u/kumahq
