### ISSUE TITLE
`kuma-prometheus-sd` doesn't work with MADs v1

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#1886]
### Summary

Apparently conversion from `*observability_v1.MonitoringAssignment` to `[]*targetgroup.Group` happens with errors. 
`kuma-prometheus-sd` receives 4 targets from Kuma Control Plane, but `kuma.file_sd.json` contains only 1 target.

### Steps To Reproduce

1. Run `kuma-prometheus-sd` with v1

**Comment by austince** [comment]
Thanks for reporting, will look into.

**Comment by austince** [comment]
Were there errors in the log, or was the lack of targets the only indication something went wrong? Do you have the list of the 4 present DPs and produced `kuma.file_sd.json` by any chance? 

I think there might be an issue with the [handler](https://github.com/kumahq/kuma/blob/19d3b806b63edf388d9a690be3282555cf1d8f5c/app/kuma-prometheus-sd/pkg/discovery/xds/v1/handler.go) using the `targetgroup.Group.Source` property as a unique identifier, and am wondering if this is related or a separate issue.

**Comment by austince** [comment]
Draft PR #1896 might address this, if it is the cause.
