### ISSUE TITLE
support kuma-prometheus-sd listening on multiple CPs 

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1928]
### Summary

I'd like to run a single kuma-prometheus-sd against multiple control planes and have the resulting config aggregated into the single file. Currently only a single CP is supported.

**Comment by jakubdyszkiewicz** [comment]
Could you tell us more about the use case?

Are you talking about CPs from different remote zones or many standalone CPs?

**Comment by austince** [comment]
This should be supported via [a native SD in Prometheus](https://github.com/austince/prometheus/pull/1) (by specifying multiple scrape jobs). In the meantime, what are the issues with running multiple sidecars, 1 per CP, with a unique `--output-file` flag? Is it just the overhead of multiple sidecars?

**Comment by MevinFernando** [comment]
> Could you tell us more about the use case?
> 
> Are you talking about CPs from different remote zones or many standalone CPs?

Is it possible to scrape remote control planes metrics using a single prometheus deployed in global control plane.
Currently, the prometheus in global control plane is only showing global control plane metrics.

**Comment by lahabana** [comment]
We've deprecated kuma-prometheus-sd in favour of the native SD so closing htis.
