### ISSUE TITLE
UI Overview inaccurately represents DPPs

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#1943]
### Summary

1) Licensed DPPs = 13, DPPs = 16. Which can be interpreted as 3 are unlicensed. The 3 delta is from Ingress and Gateway DPPs but not clear from the UI
2) DPP indicates there are Offline DPPs but all are Online from the DPPs page

![Screen Shot 2021-05-04 at 1 26 51 PM](https://user-images.githubusercontent.com/688754/117065534-7fb0ae00-acdc-11eb-803b-923fc0d64e1f.png)

### Steps To Reproduce

KongMesh 1.2.4

**Comment by jakubdyszkiewicz** [comment]
Hey, this is Kong Mesh issue. Please create this in a proper repository. Thank you!
