### ISSUE TITLE
TrafficLog v2 

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#2007]
### Summary

I'd like to use a TrafficLog policy (i.e. Envoy Access Logging) to enable access logs for destination services/DPPs. Currently only source DPPs are enabled for access logging via a TrafficLog policy. 

Only outbound listeners are configured for access logging. 

### Steps To Reproduce

Note in the attached config_dump that inbound:echo-service_default_svc_8080 is not configured for access logging while all outbound listeners have access logging configured. 

[config_dump.txt](https://github.com/kumahq/kuma/files/6510252/config_dump.txt)

**Comment by jakubdyszkiewicz** [comment]
xref #271

**Comment by lahabana** [comment]
The new version of traffic log should support both inbound and outbound trafficLog.

**Comment by lahabana** [comment]
Duplicate of #4733
