### ISSUE TITLE
I'd like to be able to configure exposing the full Envoy Admin Console on 0.0.0.0

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#2016]
### Summary

Currently, the full Envoy Admin Console is only exposed on localhost and an auth token is requires tor access the Envoy Admin Console on 0.0.0.0. I'd like a configuration option to expose the full admin console on 0.0.0.0 without the token requirement.

**Comment by jakubdyszkiewicz** [comment]
duplicate of of #1585
Closing this one.
