### ISSUE TITLE
In GUI, DPP.All shows Type=Standard for all DPP Types

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#2017]
![Screen Shot 2021-05-20 at 2 17 12 PM](https://user-images.githubusercontent.com/688754/119049999-1e443c80-b976-11eb-9c66-6975eb774e9b.png)
![Screen Shot 2021-05-20 at 2 16 57 PM](https://user-images.githubusercontent.com/688754/119050000-1f756980-b976-11eb-90df-bf5a9e15f307.png)

**Comment by tomaszwylezek** [comment]
Hi @bdecoste 
It was resolved in https://github.com/kumahq/kuma-gui/pull/175. If the issue happens again, please reopen it.
