### ISSUE TITLE
Support access token on kumactl

### ISSUE THREAD

**Issue by sudeeptoroy** [kumahq/kuma#2041]
Kuma-cp may be protected behind a oauth server. Kumactl would need support for it to be configured with access token. Access token can be created out of band and supplied as argument to kumactl.

**Comment by jakubdyszkiewicz** [comment]
This effectively means that we need to send an extra header, right?

I'd vote to code this in a more generic way like "add header to requests sent by kumactl". We don't have built-in OAuth on Kuma CP right now and I'd like to avoid confusing users that there is one.
