### ISSUE TITLE
Let kuma-init to run with --verbose flag

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#2080]
### Summary

As a summary of last discussion on our community slack and a result of my last investigations here: https://github.com/kumahq/kuma/issues/2046 I think we should let us run `kuma-init` with `--verbose` flag which would show more information about iptables etc. without manually changing https://github.com/kumahq/kuma/blob/19a906795d47ff0006ab62e12211b48204ad5a0d/pkg/plugins/runtime/k8s/webhooks/injector/injector.go#L439-L454 and then rebuilding whole `kuma-cp` image to just run tests

I think it can be a great first time issue and I'm up to mentor somebody from the community if there will be will to pick it up.

The idea I have in mind is to maybe introduce additional flag for `kumactl install control-plane` like `--dataplane-init-verbose` or ever more configurable `--dataplane-init-args` where we could specify more arguments (with equivalent for helm too).

Here is the link for slack conversation I mentioned earlier: https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1622608006132200?thread_ts=1622604264.121300&cid=CN2GN4HE1

**Comment by jakubdyszkiewicz** [comment]
done by @bartsmykla
