### ISSUE TITLE
Validators in proto definitions

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#2081]
### Summary

The current situation about validators in .proto is awkward. We tried using this back in the days and it was very inconvenient - error messages were not user-friendly. Also, it was not that flexible so we ended up writing our own validators. Back when we introduced validators for the first time, the project lead wanted to keep proto validators.
I think we may need to revisit this decision, so we either

1. Remove all validators from proto, because we don't even execute them in the code.
2. Keep the proto validators in proto and try to execute them instead of our validators (at least the one we can) and try to translate errors to our format
3. Keep the proto validators in proto and try to execute them after our own validators.

Ref https://github.com/envoyproxy/protoc-gen-validate

**Comment by jpeach** [comment]
> * Keep the proto validators in proto and try to execute them instead of our validators (at least the one we can) and try to translate errors to our format

I think that this is worth exploring. Writing validation by hand when we could be generating code it really pretty tedious. The generate errors do have an internal structure which is a starting point for the transformation. The biggest challenge is that the generated validators return on the first error, while the hand-rolled code tried to accumulate multiple errors in a single pass.

**Comment by lahabana** [comment]
@jpeach mentioned that protoc-gen-validate now supports returning all errors at once. So it might worth revisiting this ticket.

**Comment by lahabana** [comment]
Triage: Errors in envoy are still cryptic. We should review that along with CRD validation and openAPI spec gen

**Comment by lahabana** [comment]
@lobkovilya how does this fit in the context of the new policies that have openAPI specs and CRD schemas? Seems like most of this would work out the box and we'd add extra `Validator()` methods for more complex validation right?

**Comment by lobkovilya** [comment]
Yep, that's right. Now if we have openAPI spec, Kubernetes will check types automatically. Additional validation could be done in extra `validate()` [method](https://github.com/kumahq/kuma/pull/4197/files#diff-aee73c9aa5c6af6519155f7aee50e949a94ac8a35d00f3fe1db5548adb476f68R57). 

Also, I guess this issue could be closed since we already did option 1:
> 1. Remove all validators from proto, because we don't even execute them in the code.

**Comment by lahabana** [comment]
Triage: still unclear. With the new impl we should look if there's a way to have the json-schema have validators derived from the proto definition. This would give us basic validation but not contextual validation.

**Comment by lahabana** [comment]
In proto you can set the kubebuilder comments to add the validation to the json-schema which would add basic validation on both JSON/Protos.
