### ISSUE TITLE
Lower the timeout for kumactl API version check

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#2097]
### Summary

version check uses a regular client that has a timeout of 60s. In case a CP is very slow, kumactl gives no feedback for the user, it is just stuck.

We should either change the timeout for this operation or maybe for all operations altogether.

**Comment by jpeach** [comment]
One approach to this is to reset `http.DefaultClient` to one that has a default timeout on the round tripper (works as long as you don't intend to do long downloads). 

Another approach is to use contexts consistently. I recently experimented with updating golangci-lint checks and there's a new check to enforce use of contexts with HTTP calls. Adopting that with a standard timeout could work.

**Comment by lahabana** [comment]
That's done already
