### ISSUE TITLE
Support for generate logs to logfile and rotate it for kuma-cp

### ISSUE THREAD

**Issue by nikita15p** [kumahq/kuma#2099]
### Summary
Currently kuma-cp support logs on stdout and not stored in file. It is needed in case kuma needs to be integrated with any logging agent

### Steps To Reproduce
kuma-cp run --help

Usage:
  kuma-cp run [flags]

Flags:
  -c, --config-file string   configuration file
  -h, --help                 help for run

Global Flags:
      --log-level string     log level: one of off|info|debug (default "info")
 
### Additional Details & Logs
NA

- Version
- Error logs
- Configuration
- Platform and Operating System
- Installation Method (Helm, kumactl, AWS CloudFormation, etc.)

**Comment by austince** [comment]
Can this not be handled by the logging agent itself? i.e. won't fluentd/ fluentbit pull from stdout and handle the rotation, if necessary? Which logging agent are you using where this is not supported?

**Comment by nikita15p** [comment]
@austince actually I also explored that. Then found fluentbit open issue https://github.com/fluent/fluent-bit/issues/215

**Comment by austince** [comment]
@nikita15p that's wild, I had no idea! Thanks for the reference 👍🏼

**Comment by jpeach** [comment]
Is this primarily useful for running in Universal right? Normally people just add a logrotate(8) config to their puppet/chef/etc recipe; is there any reason that's not the recommendation here?

**Comment by nikita15p** [comment]
@jpeach these flags will be available both for universal and kubernetes mode. Is there any reason you think log rotation may not be useful in kubernetes mode. Irrespective of environment in which kuma control plane is running, we should be able to do log rotate for eg fluentbit doesn't support log rotation.

**Comment by jpeach** [comment]
> Is there any reason you think log rotation may not be useful in kubernetes mode.

In most Kubernetes deployments, pods are expected to log to stdout and the node takes care of log shipping and any necessary rotation.

> we should be able to do log rotate for eg fluentbit doesn't support log rotation.

For people using fluentbit in Universal, why is logrotate not sufficient? Are they doing any sort of configuration management when they deploy kuma?

**Comment by nikita15p** [comment]
log rotation feature is not available with fluentbit, so has to be done by application. In kubernetes mode , node might take care of log shipping but may not be case with everyone. As different tenants on kubernetes might require to ship their logs to different paths and monitor. Also these are app logs, one tenant shouldn't be able to look into other tenant logs.

**Comment by jpeach** [comment]
> log rotation feature is not available with fluentbit, so has to be done by application. In kubernetes mode , node might take care of log shipping but may not be case with everyone. As different tenants on kubernetes might require to ship their logs to different paths and monitor. Also these are app logs, one tenant shouldn't be able to look into other tenant logs.

In a Kubernetes deployment, rotating the logs inside the pod doesn't help anyone, since the kubelet & container runtime do that. Outside of that, I still don't understand why using logrotate isn't the right approach.

https://forge.puppet.com/modules/puppet/logrotate
https://supermarket.chef.io/cookbooks/logrotate
https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.logrotate.html

Not sure about ansible, there was no obviously standard logrotate module.

**Comment by nikita15p** [comment]
Thanks @jpeach for the info. So in restrictive environment (mostly in enterprise), using kubernetes cluster nodes require priviledged access and hence cannot use logrotate. Hence they support defined logging agent. Also to support in kube and universal env, pushing logs to file and rotating it becomes part of application. I have seen same being used in other service meshes like istio https://istio.io/latest/docs/ops/diagnostic-tools/component-logging/#:~:text=Istio%20control%20plane%20components%20can,used%20for%20individual%20log%20files.

**Comment by jpeach** [comment]
> using kubernetes cluster nodes require priviledged access and hence cannot use logrotate

But a kubernetes cluster is already doing log rotation because pod logs are rotated by the kubelet and the CRI. Is built-in log rotation solving a problem you have in a production kubernetes deployment?
