### ISSUE TITLE
Investigate stronger typing for Kubernetes resources

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2107]
### Summary

Looking at the Kuma API resources for Kubernetes, all the `Spec` fields for the objects are of the form:

```Go
type HealthCheckSpec = map[string]interface{}

type HealthCheck struct {
...
        Spec HealthCheckSpec `json:"spec,omitempty"`
}
```

This erases the actual type of the spec object from the API server. This has a number of undesirable consequences
* No automatic validation (i.e. by using [kubebuilder tags](https://book.kubebuilder.io/reference/markers/crd-validation.html)) or defaulting (xref #2081)
* No support for [kubectl explain](https://kubernetes.io/docs/reference/generated/kubectl/kubectl-commands#explain)
* No ability to generate Kubernetes API documentation

I'm reasonably sure that protogen will propagate kubebuilder tags to the Go code, so simply removing the type erasure may be enough.

If desired, the [kubetype-gen](https://github.com/istio/tools/tree/master/cmd/kubetype-gen) tool can be used to generate the CRD wrapper.

**Comment by jpeach** [comment]
> removing the type erasure may be enough.

I think that this would break enums, since the JSON representation uses string enum names rather than numeric values.

**Comment by lahabana** [comment]
Being done with #3330

**Comment by michaelbeaumont** [comment]
As part of the new schema generation, we generated typed CRDs
