### ISSUE TITLE
TrafficRoute HTTP header rewriting validator should reject special headers.

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2122]
### Summary

Following on from [here](https://github.com/kumahq/kuma/pull/2072#discussion_r646202092). If the traffic policy requests a rewrite of a header that Envoy regards as not modifiable (ie. "Host", or a HTTP/2 pseudoheader), Envoy will reject the update. Presumably things go wrong when that happens, so it's probably best to avoid that at validation time.

**Comment by jakubdyszkiewicz** [comment]
They added such validators in Envoy 1.18 so I also added this to TrafficRoute. Done.

**Comment by jpeach** [comment]
> They added such validators in Envoy 1.18 so I also added this to TrafficRoute. Done.

Can you please link the PR here?
