### ISSUE TITLE
Enforce strong parsing for Kuma resources

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2131]
### Summary

Kuma universal resources are always parsed from YAML in loose mode that allows unknown fields. This is needed because there is no structural distinction between metadata and spec, as one would find in Kubernetes resources. The lack of full validation makes it harder for users to know when they have constructed a valid resource.

I think that we can solve this by making some assumptions about the structure of universal resources.

```go
func UmarshalToCore(b []bytes) (Resource, error) {
     var obj map[string]interface{}

    yaml.Unmarshal(b, obj)

    meta := MakeResourceMeta(obj) // fish out ResourceMeta fields

    // Delete top-level meta elements.
    for _, k := range GetListofResourceMetaFields {
        delete(obj, k)
    }

    p := NewProtoOfType(resourceType)

    // Now convert what's left to the spec (still need to round trip this through JSON)
    proto.FromMap(obj, p)
}
```

**Comment by jakubdyszkiewicz** [comment]
I think the bigger problem here is the lack of versioning of resources.

**Comment by lahabana** [comment]
Was done with: https://github.com/kumahq/kuma/pull/4197
