### ISSUE TITLE
Dataplane without any inbound

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#2142]
It's currently impossible to run a dataplane without specifying at least one inbound.
There are use cases where you'd want to run a Dataplane which doesn't receive data:

- test jobs
- consumers (.e.g Kafka consumers would only initiate connections)

Is there any reason why we'd keep this limitation?

**Comment by jakubdyszkiewicz** [comment]
The limitation is that for mTLS you need an identity of a service that is inferred from the inbound.

What you may want to do is use Gateway dataplane for that. I know that seems like a "hack". We may need to somehow introduce a concept of "Consumer Dataplane".

**Comment by lahabana** [comment]
Covered by: https://github.com/kumahq/kuma/issues/3832
