### ISSUE TITLE
How to setup metrics for multi zone kuma mesh deployment in kubernetes ?

### ISSUE THREAD

**Issue by MevinFernando** [kumahq/kuma#2153]
### Summary
We have deployed multi-zone Kuma Mesh in AWS EKS. 
 Each plane in a separate EKS.
- Global CP - EKS1
- Remote CP1 - EKS2
- Remote CP 2  - EKS3
The zones and dataplanes are getting identified in the kuma gui, and able to route traffic between zones. But facing issue with respect to exporting metrics to prometheus.

### Steps 
- Launced kuma mesh in multi zone as per above configuration
- Enabled metrics in the default mesh for all the control planes using the yaml attached
- Applied `kumactl install metrics | kubectl apply -f -`  in the **global control plane**

### Issue
We are able to view global cp in prometheus metrics, but the remote cp metrics are not visible.
How should metrics be configured for multi zone deployments ? 
Is the prometheus in global cp responsible for scraping metrics from the remote cps or should their metrics be exported individually ?

### Additional Details & Logs
- Version: Kuma 1.1.6
- Platform:Kubernetes (AWS EKS)
- Installation Method: (kumactl)
![image](https://user-images.githubusercontent.com/42856943/121690413-7092fc00-cae3-11eb-9049-639678c7758b.png)
![image](https://user-images.githubusercontent.com/42856943/121690508-8dc7ca80-cae3-11eb-9b76-a4563be6416d.png)

**Comment by jakubdyszkiewicz** [comment]
You need to have Prometheus in every zone and then do Prometheus Federation to collect metrics to one cluster.

**Comment by lahabana** [comment]
Docs issue for this: https://github.com/kumahq/kuma-website/issues/628
