### ISSUE TITLE
Inconsistent kuma.io/service tag generation in Kubernetes with multiple services 

### ISSUE THREAD

**Issue by codyde** [kumahq/kuma#2170]
When deploying a deployment in Kubenetes that has multiple services registered to it, like Kong Ingress Controller, Kuma has unpredictable service name registration. In the case of Kong Ingress Controller, the name alternates between `kong-proxy_namespace_svc_80` and `kong-validation-webhook_namespace_svc_443`. 

I suspect this is happening because both services use the same selector, so they both come up at different times and whichever one finishes coming online "last" gets the registration name. 

This results in struggles when configuring policies such as TrafficPermissions or TrafficRoutes which depend on the `kuma.io/service: serviceName` tag. 

Validated with @parkanzky

**Comment by lahabana** [comment]
Fixed in #2500
