### ISSUE TITLE
Log rotation flags should not be global

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2177]
### Summary

The log rotation flags `--log-output-path`, `--log-max-age` and so on are global in `kuma-cp` and `kuma-dp`, but probably should only be attached to the `run` subcommand. There's no need for log rotation with `kuma-cp version`, for example.

**Comment by nikita15p** [comment]
Hi @jpeach . This was done for being in line with --log-level. This is also a global flag.
eg ./kuma-cp version --log-level=info
Kuma: 1.0.0-rc2-455-g254a2cdd

I think its ok to have with with run and migrate, only with version we need to check.  @jakubdyszkiewicz what are your thoughts?

**Comment by jakubdyszkiewicz** [comment]
I'm ok either way. If we go this way, we need to be careful for subcommand like `migrate` that we don't forget to add those settings

**Comment by jpeach** [comment]
Since this is consistent with existing log flags, I can live with it. Even if we do change, it will need deprecation and compatibility, so it's unlikely to be worth the effort.
