### ISSUE TITLE
Kuma UI 1.2.0 Broken

### ISSUE THREAD

**Issue by skaravad** [kumahq/kuma#2182]
### Summary

KUMA UI create mesh wizard is broken.

### Steps To Reproduce

Access UI and navigate to Meshes, click Create Mesh
Expected Result: Navigation wizard for creating new mesh
Observed: Blank Page

### Additional Details & Logs

- Version: 1.2.0
- Error logs: NA
- Configuration
- Platform and Operating System
- Installation Method (Helm, kumactl, AWS CloudFormation, etc.)

**Comment by bartsmykla** [comment]
fixed by: https://github.com/kumahq/kuma-gui/pull/165 https://github.com/kumahq/kuma/pull/2187 and backported by: https://github.com/kumahq/kuma/pull/2188
the next release will contain this fix
