### ISSUE TITLE
Collapse bootstrap generator abstractions

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2185]
In `kuma-dp` there is an abstraction for generating an Envoy bootstrap file:

```Go
type BootstrapConfigFactoryFunc func(url string, cfg kuma_dp.Config, params BootstrapParams) ([]byte, types.BootstrapVersion, error)
..
func NewRemoteBootstrapGenerator(client *http.Client) BootstrapConfigFactoryFunc {
         rb := remoteBootstrap{client: client}
         return rb.Generate
}
```
In `kuma-cp` there's a really similar one:
```Go
type BootstrapGenerator interface {
        Generate(ctx context.Context, request types.BootstrapRequest) (proto.Message, types.BootstrapVersion, error)
}
```

We can collapse `BootstrapConfigFactoryFunc` into something that implements the`BootstrapGenerator` interface.

**Comment by lahabana** [comment]
Issue opened for 2 years without anyone pointing this would be useful. The code has a clear separation of client vs server so just closing this for now
