### ISSUE TITLE
Warning in gui: Envoy (1.18.3) is unsupported by the current version

### ISSUE THREAD

**Issue by gerardborst** [kumahq/kuma#2194]
### Summary

Kuma version 1.2.0. There is a warning in the gui in the dataplane proxy pages:
```
Envoy (1.18.3) is unsupported by the current version of Kuma DP (1.2.0) [Requirements: ~1.17.0] 
```
I think 1.18.3 should be the supported version.

**Comment by bartsmykla** [comment]
Yes you are right, and I fixed it today: https://github.com/kumahq/kuma/pull/2193

It will be available with the next release
