### ISSUE TITLE
Universal ZoneIngress is showing offline in gui

### ISSUE THREAD

**Issue by gerardborst** [kumahq/kuma#2197]
### Summary

While the zone ingress from a universal zone is online it is showing offline in the gui.

kuma 1.2.0

![image](https://user-images.githubusercontent.com/56296132/123071974-693ded80-d415-11eb-9a99-fbc9ec95e884.png)

**Comment by gerardborst** [comment]
The universal zone ingress doesn't have any insights:
![image](https://user-images.githubusercontent.com/56296132/123107870-35c18a00-d43a-11eb-8933-b009062b7ab4.png)

**Comment by jpeach** [comment]
@lobkovilya Do you have any suggestions?

**Comment by lobkovilya** [comment]
That's weird there is no ZoneIngressInsight, @gerardborst could you please share logs from Zone CP?

**Comment by gerardborst** [comment]
I did an upgrade from 1.1.6.

[zone-cp.log](https://github.com/kumahq/kuma/files/6708493/zone-cp.log)

**Comment by lobkovilya** [comment]
@gerardborst sorry for the long response, I was able to reproduce it and prepared a fix. Thanks a lot for spotting this!
