### ISSUE TITLE
Remove embedded Go modules

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2200]
### Summary

The use of embedded Go modules causes some dependency problems, #2088 and #2087, and makes it harder to upgrade dependencies across the repository. However IIUC, these modules were originally introduced because they were needed to solve problems with mutually incompatible dependencies, so this needs to be explored carefully.

This issue is tracking the consensus that we should attempt to remove the embedded Go modules, and collecting the experiences of anyone who makes the attempt. If you remove one of them, or try to, please link the PR or comment below.

**Comment by jpeach** [comment]
@jakubdyszkiewicz @lobkovilya Do we want to remove the `./api` module too? It's easy to do, but I wonder whether there are cases where it makes sense to import `github.com/kumahq/kuma/api` without dragging in the rest of Kuma?

**Comment by jpeach** [comment]
> @jakubdyszkiewicz @lobkovilya Do we want to remove the `./api` module too? It's easy to do, but I wonder whether there are cases where it makes sense to import `github.com/kumahq/kuma/api` without dragging in the rest of Kuma?

See discussion in #2414

**Comment by lahabana** [comment]
@jpeach you're done with this no?

**Comment by jpeach** [comment]
> @jpeach you're done with this no?

There are still a few more IIRC.
