### ISSUE TITLE
Support for kubectl explain

### ISSUE THREAD

**Issue by scottslowe** [kumahq/kuma#2240]
### Summary

As a user/consumer of Kuma, I'd like to be able to use `kubectl explain` to explore the fields that are available/required for Kuma objects.

### Steps To Reproduce

1. Run `kubectl explain CircuitBreaker.spec` against a Kubernetes cluster that has Kuma installed.
2. Note that the output is empty.

### Additional Details & Logs

- Version: only tested against 1.2.0
- Error logs: None
- Configuration: "Vanilla" Kubernetes 1.20.7 running Kuma 1.2.0
- Platform and Operating System: Ubuntu 20.04.2
- Installation Method (Helm, kumactl, AWS CloudFormation, etc.): Installed via `kumactl install`

**Comment by jpeach** [comment]
xref #2130

**Comment by scottslowe** [comment]
I think this feature request still has value for Kuma users and feel like we should keep this issue open.

**Comment by jakubdyszkiewicz** [comment]
> Triage: check if MeshTrafficPermission supports it

**Comment by lahabana** [comment]
This works with new policies CRDs because they have full schema.
