### ISSUE TITLE
`kuma-prometheus-sd` error with different filesystems

### ISSUE THREAD

**Issue by austince** [kumahq/kuma#2249]
### Summary

The current Prometheus sidecar for discovering Kuma targets contains a bug when the output file parent directory is on a different filesystem.

This affects all MADS API versions. Perhaps it's an issue with the Prometheus custom SD adapter. 

Likely an edge case and hopefully solved by replacing the `kuma-prometheus-sd` sidecar with a native SD.

```
2021-06-29T23:55:47.276+0200    INFO    http://kuma-prometheus-sd.run.xds_sdadapter {"level": "error", "component": "sd-adapter", "err": "rename /
tmp/sd-adapter634097080okok: invalid cross-device link"}
```

### Steps To Reproduce

1. Install Kuma 1.2.0 on k8s with a dedicated host fs link in /tmp
2. Run the kuma-prometheus-sd with an output file pointing to /tmp/another-dir/targets.json
3. See error

### Additional Details & Logs

Probably caused by:
https://github.com/kumahq/kuma/blob/3dfed930d152e0947d3e9c05e7beb4afd480c3ec/vendored/github.com/prometheus/prometheus/documentation/examples/custom-sd/adapter/adapter.go#L131-L137

- Kuma 1.2.0
- K8s on Linux

**Comment by jpeach** [comment]
I stared at this for a while and I think what happens is that the output path is not fully-qualified, e.g. something like "foo.json". that would cause the directory component to by "", which would make TempFile use the system temp directory.

**Comment by jpeach** [comment]
> I stared at this for a while and I think what happens is that the output path is not fully-qualified, e.g. something like "foo.json". that would cause the directory component to by "", which would make TempFile use the system temp directory.

So one possible fix is to apply `filepath.Abs` before passing the path down.

**Comment by lahabana** [comment]
kuma-prometheus-sd is deprecated closing this issue
