### ISSUE TITLE
Generate Go package mappings for Envoy protobuf API

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2270]
### Summary

In [api/Makefile](https://github.com/kumahq/kuma/blob/master/mk/api.mk#L25-L53) we have a static Go package mapping that is needed for protoc to generate Go protobuf code that references Envoy protobufs. We should be able to write a simple script that generates this mapping for a give Envoy version so that we don't have to maintain it by hand.

**Comment by jakubdyszkiewicz** [comment]
This requires 0 maintaince since this issue was created. Closing
