### ISSUE TITLE
kuma-init logs is bloated

### ISSUE THREAD

**Issue by nhamlh** [kumahq/kuma#2279]
### Summary

Currently kuma-init emits entire iptables configuration lines to stdout. I think it's better to suppress those logs line and emit more concise logs like it's initializing, it's finished.

### Additional Details & Logs

- Version 1.2..0

**Comment by nhamlh** [comment]
After searching through the code. I think the solution is adding some configuration to modify initContainer's verbose flag.
https://github.com/nhamlh/kuma/blob/8b13853da2a445c725d98d18b52e1dc15262f4f5/pkg/transparentproxy/kubernetes/kubernetes.go#L122

**Comment by jpeach** [comment]
cc @bartsmykla

**Comment by lahabana** [comment]
This is done or will be done in kumahq/kuma-net
