### ISSUE TITLE
Switch from github.com/cncf/udpa to github.com/cncf/xds

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2336]
### Summary

Per the [README](https://github.com/cncf/udpa#readme), the UDPA repo is deprecated and we should be switching over to https://github.com/cncf/xds.

**Comment by Jayita10** [comment]
I would like to contribute to this issue

**Comment by jpeach** [comment]
> I would like to contribute to this issue

Great! There may be some issues in the build with package paths and things like that. Call out if you run into any problems :)

**Comment by VedRatan** [comment]
In which file the changes are needed? I would like to work on this one if no one is working on this issue.
