### ISSUE TITLE
Use Service Mesh Interface

### ISSUE THREAD

**Issue by jeffhollan** [kumahq/kuma#234]
Would be awesome if kuma could implement SMI (Service Mesh Interface) for easier interoperability 

https://github.com/deislabs/smi-spec

**Comment by tomkerkhove** [comment]
Would be great to have support for this indeed

**Comment by Gordonby** [comment]
Any thoughts on this guys...  ?
The SMI eye-chart is filling up. 🥼 
https://smi-spec.io/#ecosystem

**Comment by lahabana** [comment]
Looking at: https://smi-spec.io/blog/announcing-smi-gateway-api-gamma/ I'm not sure there's a future to SMI and we're looking at GAMMA
