### ISSUE TITLE
Stop using ':' in envoy resource names

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2363]
### Summary

Lots of the envoy admin pages format their state using ":"-separated fields. When we use ":" in our resource names, it becomes difficult to distinguish between fields.

Here's an example where I've hacked up a listener named `"8080/HTTP/edge-gateway"`:
```
$ curl http://127.0.0.1:30001/listeners
8080/HTTP/edge-gateway::127.0.0.1:8080
```

Using the standard Kuma naming convention, this resource would be `"8080:HTTP:edge-gateway"`.

**Comment by jakubdyszkiewicz** [comment]
What would be the alternative that you suggest? In stats `:` are replaced with `_`

**Comment by jpeach** [comment]
> What would be the alternative that you suggest? In stats `:` are replaced with `_`

Personally, I like '/', but it doesn't really matter.

**Comment by jpeach** [comment]
> > What would be the alternative that you suggest? In stats `:` are replaced with `_`
> 
> Personally, I like '/', but it doesn't really matter :)

The workaround is to use the `format=json` query parameter, e.g. `curl http://127.0.0.1:30001/listeners?format=json`.

**Comment by lahabana** [comment]
Question for triage. How much of this is a breaking changes? Especially as stats are not affected.

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's do `/`.

**Comment by lahabana** [comment]
The backward compatibility of this is fun :)

My guess is implement this with a flag tell everyone/ adapt observability and then change the default.
