### ISSUE TITLE
The deploy/example/minikube build target doesn't set up minikube properly

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2376]
### Summary

`make deploy/example/minikube` will only work properly if you first do `minikube start --vm-driver=docker --kubernetes-version=`. the circle-ci script does this, but the makefiles don't.

**Comment by jpeach** [comment]
Even once you start minikube manually, it still doesn't work because the image loading targets depend on something having already done a docker/save. Again, only CI does the right magic sequence of steps.

**Comment by lahabana** [comment]
We're removing this
