### ISSUE TITLE
Add additional debug logging for api-server

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#2400]
### Summary

Needed to debug the product and version returned to `kumactl generate dataplane-token ...`

**Comment by jpeach** [comment]
The error message `WARNING: You are using kumactl version XXX, but the server returned version: YYY` comes from a server version pre-flight check in `kumactl`. This does a GET on '/' for the API server that it is configured for, and that GET request returns hostname, tagline(?) and version fields.

So in this case, any `kumactl` command ought to emit that warning as  long as it reaches the same in API server instance. This was added in #736.

I don't see any code in the token issuance path that knows the Kuma version of the client.
