### ISSUE TITLE
Support transparent proxy mode in universal docker

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#2406]
### Summary

I would like to be able to run transparent mode when I run Kuma in universal mode with docker components. One issue is conflicting docker and transparent iptables rules. The DNS configuration is another issue. 

### Steps To Reproduce
[docker-compose.yaml.tar.gz](https://github.com/kumahq/kuma/files/6855271/docker-compose.yaml.tar.gz)

I have attached a docker-compose file for deploying the Kuma components in containers. I tested by installing transparent in the client container: `./kong-mesh-1.3.1/bin/kumactl install transparent-proxy --kuma-dp-user bdecoste --kuma-cp-ip 172.24.0.2 --skip-resolv-conf --redirect-dns`

**Comment by lahabana** [comment]
@bdecoste I've managed to do it here: https://github.com/kumahq/kuma-tools/tree/master/docker-compose am I missing something?

**Comment by lahabana** [comment]
Ping @bdecoste :)
