### ISSUE TITLE
Outbound Envoy VIPs only listen on port 80

### ISSUE THREAD

**Issue by scottslowe** [kumahq/kuma#2407]
### Summary

Kuma creates outbound Listeners for VIPs that represent Clusters. However, regardless of the traffic the Cluster is expecting or configured to receive, the VIP listens only on port 80.

For example, in a Kubernetes cluster running the Kuma demo app (installed via `kumactl install demo | kubectl apply -f -`), there is a VIP in the 240.x.x.x range for the Redis layer. The Redis cluster is configured to use TCP port 6379, but the VIP's Listener listens only on port 80.

### Steps To Reproduce

1. Stand up a Kubernetes cluster.
2. Install Kuma via whatever means you prefer.
3. Install the Kuma demo app.
4. Examine the Envoy configuration on the "demo-app" Pod; you will see an Envoy listener that points to a VIP that points to the Redis cluster. This listener will be configured to listen on port 80, even though the cluster is configured for port 6379.

### Additional Details & Logs

- Version: Kuma 1.1.6 (no indication this has changed in newer versions)
- Error logs: N/A
- Configuration: As described above
- Platform and Operating System: Kubernetes 1.20.7
- Installation Method (Helm, kumactl, AWS CloudFormation, etc.): Using `kumactl install control-plane | kubectl apply -f -`

**Comment by lahabana** [comment]
This feature will be part of a larger change which should enable users to set the correct ports: https://github.com/kumahq/kuma/pull/1978

@scottslowe  You can still reach your redis instance right? It's just on port 80 instead of 6379 isn't it?
If that's not the case there's a separate issue that may need investigations

**Comment by scottslowe** [comment]
@lahabana Yes, the Redis instance is reachable on port 80. For applications that allow target port to be adjusted, this isn't a problem, but when we run into an application that won't allow us to adjust the target port (for whatever reason) then this will become a major roadblock.

Thanks for the update on the larger change.

**Comment by lahabana** [comment]
virtual-outbound makes this possible so closing this
