### ISSUE TITLE
Support wildcards/globbing in selectors

### ISSUE THREAD

**Issue by scottslowe** [kumahq/kuma#2409]
Currently, the `sources` and `destinations` selectors support _either_ `"*"` (to represent any value) _or_ the full value of the specified tag. For example, when specifying a particular service as a source, one can use `"*"` _or_ `"name_namespace_svc_port"`, but one cannot use `"name_namespace_svc_*"` to capture _all_ matching instances of the specified tag.

There are a number of use cases where this could be useful:

* Allowing for the selection of multiple zone names when using Traffic Permissions to limit inter-zone traffic
* Allowing for the selection of multiple services that might need to be affected by a particular policy

**Comment by lahabana** [comment]
Are there cases where adding a separate tag to specify these groupings not possible?

There might be an underlying useful feature but I believe specific tags may be a possible workaround.

If we add this feature rather than prefix should we go with regular expressions?

**Comment by scottslowe** [comment]
@lahabana Yes, I would suggest either a) a shell-like globbing mechanism, or b) a regex implementation.

In this particular instance, the use of other tags _may_ be a workaround, although it will impose/require additional work from the cluster operators.

**Comment by jpeach** [comment]
> @lahabana Yes, I would suggest either a) a shell-like globbing mechanism, or b) a regex implementation.

I think I'd prefer to avoid the complexity of regexes here (obligatory xkcd). It binds deployments to the precise construction of service names, and doesn't directly express user intent. I'd prefer that all the components of the constructed service name were directly available as matching tags.

Could this work:
```
sources:
  kuma.io/service: '*'
  kuma/io/namespace: my-namespae
```

**Comment by lahabana** [comment]
I like this idea. Introducing `kuma.io/name`, `kuma.io/namespace` and `kuma.io/port` might a good way to make this work without requiring extra work from the operator.

I'm not sure using the kuma.io is the right thing though as it may be confusing (there's no such thing as a namespace in kuma for .e.g).
`k8s.io/service`, `k8s.io/namespace`, `k8s.io/port` might be better WDYT?

**Comment by jpeach** [comment]
> I like this idea. Introducing `kuma.io/name`, `kuma.io/namespace` and `kuma.io/port` might a good way to make this work without requiring extra work from the operator.
> 
> I'm not sure using the kuma.io is the right thing though as it may be confusing (there's no such thing as a namespace in kuma for .e.g).
> `k8s.io/service`, `k8s.io/namespace`, `k8s.io/port` might be better WDYT?

Universal doesn't have namespaces, but it does have service and port. We could expose kubernetes-only labels under `k8s.io`, but I'd argue it's less confusion for Kuma to just claim a single tag namespace.

**Comment by lahabana** [comment]
There's now namesapce port etc tags auto added and it's a preferred way to go about this so closing this.
