### ISSUE TITLE
make dev/tools doesn't install clang-format

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#2441]
This ignores `clang-format` when running `make check` locally and `clang-format` is not installed.
This is frustrating for the dev as they only discover in CI that the protobufs are not correctly formatted.

Another option is to use a more complete, protobuf specific tool like https://github.com/bufbuild/buf

**Comment by michaelbeaumont** [comment]
Another option is to use a more complete, protobuf specific tool like https://github.com/bufbuild/buf

**Comment by lahabana** [comment]
I'm curious to see if we could switch to `buf` completely for protobuf gen.
