### ISSUE TITLE
Should http and http2 infer common protocol to be tcp?

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#2445]
In this https://github.com/kumahq/kuma/blob/6c6224880eefddfe01533a0ebba9940b1eceead2/pkg/xds/generator/protocol.go#L23-L54 we can see that http2 and http will return tcp which makes sense.

However, this is used in 2 places:

1) `generateCDS()`
https://github.com/kumahq/kuma/blob/ba6bebea4b5baadd1dcb699ddec34cd0541b9582/pkg/xds/generator/outbound_proxy_generator.go#L173-L220
In this case it looks it should be using the protocol of the specific cluster and not infer the protocol from all the clusters.

2) `generateLDS()`
https://github.com/kumahq/kuma/blob/ba6bebea4b5baadd1dcb699ddec34cd0541b9582/pkg/xds/generator/outbound_proxy_generator.go#L91-L171
Where it treats http and http2 the same way.

For (1) it seems that we could configure the cluster with AutoHttpConfig (`ALPN`) in the case where a cluster has a mix of http and http2 endpoints (which seems to be a rare usecase at the cluster level).

It might good enough to introduce a `ProtocolHttpX` and then handle on a case by case where it makes sense. I think this would be a better behaviour than risking downgrading to TCP when things would work the same for HTTP and HTTP2.

**Comment by jpeach** [comment]
> In this
> 
> https://github.com/kumahq/kuma/blob/6c6224880eefddfe01533a0ebba9940b1eceead2/pkg/xds/generator/protocol.go#L23-L54

``Go
 // a common protocol between HTTP and HTTP2 is HTTP2, 
...
 // a common protocol between HTTP and HTTP2 is HTTP. 
```

Only one of these can be true.

> we can see that http2 and http will return tcp which makes sense.

Maybe it makes sense in terms of protocol layering, but it makes no sense semantically. Any server that is offering a http/2 service can offer the same service on http, as only the wire protocol is different.

> It might good enough to introduce a `ProtocolHttpX` and then handle on a case by case where it makes sense. I think this would be a better behaviour than risking downgrading to TCP when things would work the same for HTTP and HTTP2.

I agree that we don't want to downgrade to TCP. I'm not sure what the protocol tag is supposed to mean in these cases. If the application can't handle HTTP/2 that doesn't mean that the mesh can't still speak HTTP/2 over the wire.

**Comment by lahabana** [comment]
> I agree that we don't want to downgrade to TCP. I'm not sure what the protocol tag is supposed to mean in these cases. If the application can't handle HTTP/2 that doesn't mean that the mesh can't still speak HTTP/2 over the wire.

It makes sense indeed that the mesh could talk http/2 and the only needed downgrade is between the instance and the proxy.

It seems like the only place where we need to make a difference between http and http/2 is in the `inbound_proxy_generator` when creating the CDS resource (which already seem to be happening correctly).

 For outbound things already happen correctly by simply forcing http2 (at least for http).

**Comment by lahabana** [comment]
Here's the use-case where this causes problem:

1. set 2 dps with `kuma.io/protocol: http` and tracing. This works well!
2. change one of these dps to use `kuma.io/protocol: http2`. This fails because tracing is only set for http and http2 and we infer the common protocol as tcp.

This code is used both for configuring the Listener and the Cluster.
In the case of Listener I believe it's fine to infer http and http2 to http2 because envoy http2 listeners can downgrade to http1.1 when needed
In the case of Cluster it's more problematic as we have no guarantee that the downstream app we're proxying for will be able to support http2.

So it seems we need 2 things:
- in Cluster context: http and http2 get inferred to http so if the downstream app doesn't support http2 there's no problem
- in Listener context: http and http2 get inferred to http2 because Envoy h2 listeners will work with h1.1 clients.

@jakubdyszkiewicz WDYT?

**Comment by jakubdyszkiewicz** [comment]
> Triage: this protocol inference should not be used on the inbound side at all. With this in mind let's try to specify what to infer for inbound/outbound listener and inbound/outbound cluster.

**Comment by michaelbeaumont** [comment]
@lahabana any more info on this? Should we plan to look at this/hand as an on duty task?

**Comment by lahabana** [comment]
Yes I think so. I'm also unclear why `this protocol inference should not be used on the inbound side at all.` @jakubdyszkiewicz could you explain?

**Comment by jakubdyszkiewicz** [comment]
For specific DP proxy, you don't need to do any inference on inbound side, you have an explicit protocol in `kuma.io/protocol`.

**Comment by lahabana** [comment]
Question for triage: Feels like we have a path forward now right?

**Comment by kleinfreund** [comment]
**Triage**: We don’t need any inference on the inbound side (it’s already annotated on the DPP). See https://github.com/kumahq/kuma/issues/2445#issuecomment-1223880149 for the rest.

**Comment by jakubdyszkiewicz** [comment]
Closing. @lukidzi is working on this as a part of https://github.com/kumahq/kuma/issues/6589
