### ISSUE TITLE
Merge api/Makefile back to the main build

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2495]
### Summary

Due to the history of `./api/` being a Go submodule, it has its own Makefile with a number of necessary rules. We should merge this all back into `./mk` so that there is one less place to understand how the build works.

**Comment by jpeach** [comment]
Re-opening, since `api/Makefile` is still present.

**Comment by lahabana** [comment]
My bad :) I think I started and gave up on this and thought I finished it!
