### ISSUE TITLE
Deterministically order inbound by service when running a deployment with multiple services.

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#2500]
### Summary

This makes it complicated to do anything with service tags as not all pods will have the same service.
We need further investigation to understand at which level this is happening (are the inbounds not sorted on creation?, is the sorting method not stable?...).

### Steps To Reproduce

1. Have kuma running
2. Create 3 services
3. Create a deployment which is bound to these 3 services with a few pods
4. Look at the kuma gui and notice that in list view and they don't have the same service

![image](https://user-images.githubusercontent.com/702355/128308324-026f7e1d-7189-4851-a0c5-026b589bafc9.png)

**Comment by lahabana** [comment]
Actually I've noticed this is cross zones. And that's probably because services are not created in the same order in each zone.
It might be simpler to sort by name on these kind of things instead of the default k8s sort which is by creationTime

**Comment by lahabana** [comment]
For the more specific case of the gateway I'm not sure it makes sense to use the service to identify it.
Shouldn't we just use the `servicelessInbound` as gateways are not meant to have inbounds?

**Comment by jpeach** [comment]
Sounds like https://github.com/kumahq/kuma/issues/2170
