### ISSUE TITLE
No single way to identify a service when it has multiple `inbounds`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#2501]
### Summary

Currently traffic coming out of the pod in identified by the `TagSet` of its inbounds.
If it has multiple inbounds all inbounds are included.

This has 2 major problems:

1. When defining a trafficPermissions the `source` is an `inbound` this is conceptually wrong as the traffic doesn't come out of the `listener` identified by the inbound it comes from the container that also happens to have a listener. This becomes even more confusing when there are multiple `inbounds` (what makes traffic coming out part of a listener and not  another?).
2. It's impossible to define a service without `inbounds`  (see: #2142). One use-case for this is a queue consumer (it only pulls and doesn't need to expose a listener)...

### Idea for improvement

One possibility could be to have dps next to `inbound/outbound` an `identity` (or a better name) which would be used for any policy that has a `source` (trafficPermission, tracing...).

```
Type: Dataplane
Mesh: foo
Networking:
  Inbounds:
    ...
 Outbounds:
    ....
 Identity:
     "kuma.io/client": "kafka-consumer"
```

I think an identity should still be a set of tags but maybe `kuma.io/service` as a required tag would be confusing, maybe `kuma.io/client` making it logical that `source` is the client and `destination` is the service.
The spiffe would also need to be different between the `client` identification and the `service` identification to keep having a single cert.

**Comment by lahabana** [comment]
This comes up in #2170 too

**Comment by jpeach** [comment]
If we are introducing the notion of identity, we could do worse than research SPIRE notions of workload identity.

**Comment by lahabana** [comment]
This also shows up in metrics where it's complicated to identify which service it's coming from as it picks a service.

**Comment by lahabana** [comment]
Covered by: #3832
