### ISSUE TITLE
TimeoutConfigurer doesn't set idle timeout for GRPC clusters

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2520]
### Summary

https://github.com/kumahq/kuma/blob/3351d4e6d8378aa2cb6920d2fc8b4f04cb428345/pkg/xds/envoy/clusters/v3/timeout_configurer.go#L26-L49

The TimeoutConfigurer will set the IdleTimeout field for HTTP/2 protocol clusters, but not for GRPC clusters. But GRPC clusters are also HTTP/2 clusters, so they should get HTTP/2 timeout settings as well.

**Comment by lahabana** [comment]
@lobkovilya I know you've done some work on this recently and https://kuma.io/docs/1.7.x/generated/resources/policy_timeout/ seems to point that the grpc section is deprecated.

So sounds like this ticket should be closed. Can you please close it if you agree?

**Comment by lobkovilya** [comment]
Apparently, issues are not close if PR has them on a list like:
```
Fix #3630 #3629 #2520
```
Closing it manually.
