### ISSUE TITLE
xDS generators should require resource names

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2538]
### Summary

The xDS generators do not require xDS resources to be named, and there's no checking for that until you get to the consistency snapshot.

Code that *looks* like it should do nothing will generate anonymous  resources, e.g:
```Go
b := envoy_routes.NewRouteConfigurationBuilder(envoy.APIV3)
r, err := b.Build()

// r doesn't have a resource name here ...
```

There are cases where its OK to generate xDS resources that don't have names, but maybe it's more robust to always require them.

Discuss :)

**Comment by jakubdyszkiewicz** [comment]
> Triage
> Option 1: `b.Build(name)`
> Option 2: validate that the name is set in `.Build()`, but this is a runtime error instead of build error

**Comment by jakubdyszkiewicz** [comment]
Seems like all builders in pkg/xds/envoy requires names now. Closing
