### ISSUE TITLE
Delete method GetLatestSubscription for Insights

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#2557]
### Summary

Since we always append the newest subscription at the end of the list, we don't need a method that sorts subscriptions by the `ConnectTime` and picks the latest. That's why method `GetLatestSubscription` could be deleted, all usages replaced with `GetLastSubscription`

**Comment by tharun208** [comment]
@lobkovilya I like to work on this

**Comment by tharun208** [comment]
@lobkovilya I like to work on this
