### ISSUE TITLE
Kuma operator for Kubernetes deployments

### ISSUE THREAD

**Issue by dhruv** [kumahq/kuma#257]

**Comment by austince** [comment]
Hey @dhruv, what specific features are you looking for in an operator? Managing multi-zone deployments? Or just something that integrates with the Operator Framework like the [operator-registry](https://github.com/operator-framework/operator-registry)? There's been talk in the community about trying to find the pain points of installing/ managing kuma, so any details you can add would be great!

**Comment by subnetmarco** [comment]
@austince it would be about installing and scaling Kuma in both standalone and multi-zone mode. @austince do you have any experience with operators?

**Comment by austince** [comment]
@subnetmarco in the sense that Kuma itself is an operator, yes, and another small one I've built. We'll be building a fully-fledged operator in the coming months at Ververica (i.e. integrates with [OpenShift's OLM](https://access.redhat.com/documentation/en-us/openshift_container_platform/4.1/html/applications/operators#olm-understanding-olm)).
