### ISSUE TITLE
Create Must* functions for registry.Global

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#2572]
### Summary

Today there are several places where it's known for sure there won't be any error when creating an object of a certain type:
```go
res, _ := registry.Global().NewObject(resType)
```
or
```go
list, _ := registry.Global().NewList(typ)
```

It would be great to create `MustNewObject/MustNewList` functions that'd allow dropping an error.

**Comment by tharun208** [comment]
@lobkovilya I see that the error is not dropped in the `NewObject()` and `NewList()` methods.

**Comment by lahabana** [comment]
It should really panic.

**Comment by bartsmykla** [comment]
It's not the case anymore that we are dropping errors:
![image](https://github.com/kumahq/kuma/assets/11655498/d46d4f94-3a9b-4c76-8257-5d16553638f6)
