### ISSUE TITLE
kumactl does not log iptables errors when transparent proxy setup fails

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2625]
### Summary

If installing the transparent proxy rules fails, kumactl exits with an error code, but is otherwise silent:

```sh
root@efd9275f917b:/# /tmp/kumactl install transparent-proxy --kuma-dp-user kuma-dp --kuma-cp-ip 172.18.0.3 --skip-resolv-conf --redirect-dns --redirect-dns-upstream-target-chain DOCKER_OUTPUT
WARNING: Unable to confirm the server supports this kumactl version
kumactl is about to apply the iptables rules that will enable transparent proxying on the machine. The SSH connection may drop. If that happens, just reconnect again.
root@efd9275f917b:/# echo $?
1
```

### Steps To Reproduce

1. Use recent Docker (doesn't generate a `DOCKER_OUTPUT` chain
2. Try to run Kuma e2e tests
3. Debug

The root cause of this is that the `tp.Setup()` call that kumactl makes into the vendored Istio modules never actually returns on error. We end up in `istio.io/istio/tools/istio-iptables/pkg/dependencies`, where the `(r *RealDependencies) RunOrFail()` function formats an error with `fmt.Errorf` but doesn't log it, and exits directly (added in https://github.com/kumahq/kuma/pull/1852).

**Comment by jpeach** [comment]
xref #2585

**Comment by jpeach** [comment]
kumactl assumes this whole thing can fail, which is sort-of can, but not at the part where we exec iptables. At that point, it seesm like stdout and stderr are closed or redirected, so logging an error in `RunOrFail` is actually silent.

*sigh* we swizzle `osStderr` in the `IstioTransparentProxy` wrapper

**Comment by bartsmykla** [comment]
I actually was wrong, and it looks like `kuma-net` is not hiding errors: 
![image](https://user-images.githubusercontent.com/11655498/169816461-8954ec75-1e93-4f6b-96c1-ac051b45e9d4.png)
