### ISSUE TITLE
Remove kuma dependencies on Kong infrastructure.

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2627]
### Summary

* the script `./tools/releases/distros.sh` uses a Kong service named `pulp` and a `kong/release-script` Docker image to push packages to download.konghq.com.
* Envoy builds seem to come from https://download.konghq.com/mesh-alpine
* the e2e framework fetches historical Kuma releases from https://download.konghq.com/mesh-alpine/kuma-%s-ubuntu-amd64.tar.gz

It's not clear to me how much dependency on Kong infrastructure is OK, but it's at least worth documenting it in the release tooling and providing contact information for the right Kong folks.

**Comment by michaelbeaumont** [comment]
> * the e2e framework fetches historical Kuma releases from https://download.konghq.com/mesh-alpine/kuma-%s-ubuntu-amd64.tar.gz

This is a good reason for us to publish everything as artifacts on the github release.

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's close it for now. We will reopen this when we have enough information to take a decision on the replacement.
