### ISSUE TITLE
Add support for `kube-prometheus` 

### ISSUE THREAD

**Issue by tuananh2508** [kumahq/kuma#2649]
### Summary

We are using Kuma on Kubernetes. and we already has `kube-prometheus` on our cluster with all the components. We would want to use `TrafficMetrics` Policy but seem like we would have to install another Promtheus Server, Node Exporter, ... on another namespace. And if we do this, Prometheus Node Exporter come with `kumactl install metrics` will have the `Pending` State
Is there a way to collect metrics with the `kube-prometheus` ?

### Additional Details & Logs

- Version: Kuma-1.2.3 
- Platform and Operating System: Kubernetes 1.20
- Installation Method (Helm, kumactl, AWS CloudFormation, etc.): Helm

**Comment by lahabana** [comment]
If you are using an existing prometheus you can simply add [kuma-sd](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#kuma_sd_config) to your existing scrape_configs.

Marking this issue as closed as it's already supported.
