### ISSUE TITLE
TLS Inspector should not affect TCP health checks for non-TLS traffic

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#2651]
### Summary

For some reason, if TLS Inspector is configured on the inbound unconditionally it's causing TCP Health check failures. 

### Steps To Reproduce

1. Configure TLS Inspector on the inbound
2. Run the test `should mark host as unhealthy if it doesn't reply on health checks` in `policy_tcp.go`

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's check again if this is a problem
