### ISSUE TITLE
Asynchronous cluster id dependencies

### ISSUE THREAD

**Issue by parkanzky** [kumahq/kuma#2664]
### Summary

On kuma-cp startup, clusterId is generated asynchronously with the rest of the initialization process. Some of the system initializations and related services require the id, but run before it is generated. We don't have a standard way for dependent services to block until it becomes available. We could block the whole process or individual services. Either way, it should be evident in the code that there are facilities and examples to follow.

**Comment by jakubdyszkiewicz** [comment]
What components depend on cluster ID?

In case of Zone CP, we sync Cluster ID from Global CP to the Zone CP.

**Comment by lahabana** [comment]
> What components depend on cluster ID?
I think reports mainly

**Comment by lahabana** [comment]
Closing as it can be done in #1001 and it's not that important anyway
