### ISSUE TITLE
Move to upstream go-control-plane from fork

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2719]
### Summary

- [x] In `pkg/util/xds/v3/cache.go` we have a forked version of go-control-plane's `SnapshotCache` type. This was forked so that we can use it for non-Envoy xDS resources.
So that we don't have to maintain the fork we should consider
  * moving to `LinearCache`, which allows a single arbitrary resource
  * refactoring upstream to allow `SnapshotCache` to be type oblivious, envoyproxy/go-control-plane#489
- [x] Move from [current fork](https://github.com/kumahq/go-control-plane/commit/d35edcf0813a3b4a456697d45eaceb028d889c33) with fix for [deadlock issue](https://github.com/envoyproxy/go-control-plane/issues/503)

**Comment by jpeach** [comment]
xref https://github.com/kumahq/kuma/issues/2004

**Comment by jakubdyszkiewicz** [comment]
What I think we can do is to use LinearCache with MuxCache. But I'm looking forward to whether we can make Snapshot an interface in upstream go-control-plane

**Comment by jpeach** [comment]
> But I'm looking forward to whether we can make Snapshot an interface in upstream go-control-plane

See https://github.com/envoyproxy/go-control-plane/pull/491.
