### ISSUE TITLE
CircuitBreaker without outlier_detection options still creates outlier_detection config

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#2727]
### Summary

CircuitBreaker without outlier_detection options still creates outlier_detection config

### Steps To Reproduce

The default circuit-breaker-all-default CirctuiBreaker has no outlier_detection config but creates the following:

```
      "circuit_breakers": {
       "thresholds": [
        {
         "max_connections": 1024,
         "max_pending_requests": 1024,
         "max_requests": 1024,
         "max_retries": 3
        }
       ]
      },
      "outlier_detection": {
       "enforcing_consecutive_5xx": 0,
       "enforcing_success_rate": 0,
       "enforcing_consecutive_gateway_failure": 0,
       "enforcing_consecutive_local_origin_failure": 0,
       "enforcing_failure_percentage": 0
      },
```

```
echo-service_default_svc_8080::outlier::success_rate_average::-1
echo-service_default_svc_8080::outlier::success_rate_ejection_threshold::-1
echo-service_default_svc_8080::outlier::local_origin_success_rate_average::-1
echo-service_default_svc_8080::outlier::local_origin_success_rate_ejection_threshold::-1
```

**Comment by jpeach** [comment]
AFAICT, this is by design and reflects that no outlier detectors are enabled in the default circuit breaker (i.e. all the enforcing fields are disabled). Kuma always populated the outliers, but some valued are omitted from the JSON because they are the default (omitempty).

Are you recommending that enforcement should be enabled by default?

**Comment by jakubdyszkiewicz** [comment]
> Triage: Make sense to skip the Envoy config if detectors are missing

**Comment by lahabana** [comment]
Address in #4736 if we do
