### ISSUE TITLE
1.3.0 ExternalServices don't show any info/yaml in GUI

### ISSUE THREAD

**Issue by bdecoste** [kumahq/kuma#2728]
### Summary

1.3.0 ExternalServices don't show any info/yaml in GUI

### Steps To Reproduce

1. Create an ExternalService
2. Go to /gui/#/mesh/all/external-services
3. No data or yaml is shown. **Gets stuck in Data Loading ...**

![Screen Shot 2021-09-04 at 5 35 00 AM](https://user-images.githubusercontent.com/688754/132094622-0663b001-b8c2-406f-a4dc-8355162bf0c8.png)

**Comment by tomaszwylezek** [comment]
Hi @bdecoste!
I will take a look on it and then I will inform you on a status of this one

**Comment by tomaszwylezek** [comment]
The PR with a solution was created, thanks @bdecoste  for your report and big apologies for that!

**Comment by jakubdyszkiewicz** [comment]
Closing, fix is merged.
