### ISSUE TITLE
Kuma-metrics Grafana init-plugins container error

### ISSUE THREAD

**Issue by mjmonroe** [kumahq/kuma#2767]
### Summary
Used kumactl version 1.3.0 to generate a kuma-metrics yaml file. Then edited the Prometheus node-exporter ports and changed them to port 9200. After applying the kuma-metrics yaml, the grafana pod's init-plugins container errors with, `wget: bad address 'github.com`. The container will stay in CrashLoopBackOff status, never coming up. 

Disabling the Kuma sidecar injection will allow the container to reach github, but then the grafana pod is outside of the mesh.

### Steps To Reproduce

1. Generate a kuma-mrtrics yaml using `./kumactl install metrics > kuma-metrics-master.yaml`
2. Change the Prometheus node-exporter ports and set them to something else.
3. Apply the yaml `kubectl apply -f kuma-metrics-master.yaml`

### Additional Details & Logs
# Versions
Kubernetes version: 1.19.8

Setup with Calico networking:
Calico  Client Version:    v3.14.0
Cluster Version:   v3.14.0
Cluster Type:      typha,kdd,k8s,bgp

## Configurations
# Mesh
```yml
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  annotations:
    k8s.kuma.io/mesh-defaults-generated: "true"
  creationTimestamp: "2021-08-03T19:50:55Z"
  generation: 23
  name: default
  resourceVersion: "10791081"
  selfLink: /apis/kuma.io/v1alpha1/meshes/default
  uid: 4f624f7f-6123-4bec-9cca-843c3cf11edc
spec:
  metrics:
    backends:
    - conf:
        path: /metrics
        port: 5670
        tags:
          kuma.io/service: dataplane-metrics
      name: prometheus-1
      type: prometheus
    enabledBackend: prometheus-1
  mtls:
    backends:
    - conf:
        caCert:
          RSAbits: 2048
          expiration: 10y
      dpCert:
        rotation:
          expiration: 1d
      name: ca-1
      type: builtin
    enabledBackend: ca-1
  networking:
    outbound:
      passthrough: true
```
# Kuma-metrics namespace
```yml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    kuma.io/mesh: default
    kuma.io/sidecar-injection: enabled
  creationTimestamp: "2021-09-13T14:12:52Z"
  name: kuma-metrics
  resourceVersion: "12316579"
  selfLink: /api/v1/namespaces/kuma-metrics
  uid: 2b262558-8f88-45cf-a964-0fb203eed646
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```
# Kuma traffic routes
```yml
apiVersion: kuma.io/v1alpha1
kind: TrafficRoute
mesh: default
metadata:
  annotations:
  creationTimestamp: "2021-08-26T21:27:11Z"
  generation: 1
  name: route-all-default
  ownerReferences:
  - apiVersion: kuma.io/v1alpha1
    kind: Mesh
    name: default
    uid: 4f624f7f-6123-4bec-9cca-843c3cf11edc
  resourceVersion: "6604717"
  selfLink: /apis/kuma.io/v1alpha1/trafficroutes/route-all-default
  uid: bc2cacbf-5596-4786-b79e-57d26ed6bbc6
spec:
  conf:
    destination:
      kuma.io/service: '*'
    loadBalancer:
      roundRobin: {}
  destinations:
  - match:
      kuma.io/service: '*'
  sources:
  - match:
      kuma.io/service: '*'
```

### Kuma-metrics yaml file used
[kuma-metrics-master.yaml.txt](https://github.com/kumahq/kuma/files/7155100/kuma-metrics-master.yaml.txt)

**Comment by FabianHardt** [comment]
We are facing the same issue on OpenShift platform. Running Kuma version 1.4.1 on OpenShift 4.9.11.

**Comment by lahabana** [comment]
Does adding github.com as an externalService fix this issue?

**Comment by lahabana** [comment]
It's fixed with github.com as an externalService in my experiments so closing this
