### ISSUE TITLE
Upgrade to 1.3.0, Gui has a warning that 1.3.0 Data Plane (DP) is not supported

### ISSUE THREAD

**Issue by desktophero** [kumahq/kuma#2770]
### Summary

Recently updated from 1.2.3 to 1.3.0 and the GUI shows warnings that 1.3.0 DP is not supported

### Steps To Reproduce

1. deploy 1.3.0 CP and DP
2. open GUI
3. check on DP proxies
4. View warnings

### Additional Details & Logs

- Version: 1.2.3 to 1.3.0
- Error logs
- Configuration
- Platform and Operating System
- Installation Method (Helm, kumactl, AWS CloudFormation, etc.)

![Screen Shot 2021-09-13 at 3 53 39 PM](https://user-images.githubusercontent.com/4552926/133167330-9aadb5d0-2227-442a-8976-6cf2a8b91157.png)

**Comment by jpeach** [comment]
Hi @desktophero , thanks for reporting this. 

This is a bug in the 1.3.0 release. It was fixed in https://github.com/kumahq/kuma/pull/2707, and will be included in the upcoming 1.3.1 release.
