### ISSUE TITLE
Allow TXT DNS Lookups When Using Builtin DNS

### ISSUE THREAD

**Issue by DaytonG** [kumahq/kuma#2776]
### Summary

Currently, TXT DNS record lookup does not function when `KUMA_RUNTIME_KUBERNETES_INJECTOR_BUILTIN_DNS_ENABLED=true` (which is the default). I noticed this while using a `mongo+srv://` connection, which in part does a TXT lookup for connection parameters.

Talking with @lobkovilya, this is because envoy itself does not currently support TXT lookups.

```
localizedMessage":"Unable to look up TXT record for host mongo.default.svc.cluster.local","message":"Unable to look up TXT record for host mongo-rsc.default.svc.cluster.local","name":"com.mongodb.MongoConfigurationException","cause":{"commonElementCount":27,"localizedMessage":"DNS operation not supported [response code 4]","message":"DNS operation not supported [response code 4]","name":"javax.naming.OperationNotSupportedException","extendedStackTrace":"javax.naming.OperationNotSupportedException: DNS operation not supported [response code 4]
```

### Steps To Reproduce

1. `./kumactl install control-plane | kubectl apply -f -`
2. wait for kuma to come up
3. Deploy container that does a TXT lookup, like... `kubectl run -it --rm --image gcr.io/kubernetes-e2e-test-images/dnsutils:1.3 txt-tester --command -- host -t google.com`

### Additional Details & Logs

- Version: 1.3.0
- Configuration: defaults
- Installation Method: kumactl

**Comment by lahabana** [comment]
Do you except the mesh DNS to respond to the TXT question? Or do you expect the DNS behind the mesh to resolve?

If this is the second problem we've just fixed: https://github.com/kumahq/kuma/pull/2761
You can set your own coreDNS config if you want to do this sooner.

**Comment by DaytonG** [comment]
With builtin DNS, yea, think I would expect it to resolve. As of now, with default config I get `DNS operation not supported`. The resolution continues to work when I disable builtin resolution.

**Comment by lahabana** [comment]
Ok so #2761 fixes your issue. You can have the benefit of #2761 by using your own coreDNS config has indicated in the docs: https://kuma.io/docs/1.3.0/networking/dns/#data-plane-proxy-dns

You would use:

```
.:{{ .CoreDNSPort }} {
    forward . 127.0.0.1:{{ .EnvoyDNSPort }}
    # We want all requests to be sent to the Envoy DNS Filter, unsuccessful responses should be forwarded to the original DNS server.
    # For example: requests other than A, AAAA and SRV will return NOTIMP when hitting the envoy filter and should be sent to the original DNS server.
    # Codes from: https://github.com/miekg/dns/blob/master/msg.go#L138
    alternate NOTIMP,FORMERR,NXDOMAIN,SERVFAIL,REFUSED . /etc/resolv.conf
    prometheus localhost:{{ .PrometheusPort }}
    errors
}
```
