### ISSUE TITLE
Tag latest container images as part of the release process

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2778]
### Summary

Looking at the [kumahq Docker org](https://hub.docker.com/u/kumahq), the images we release are tagged with version numbers, but there's no 'latest' tag.

As part of the release process, we should update the `latest` tag so that simple commands like "docker pull kumahq/kuma-cp" work as expected.

xref https://github.com/kumahq/kuma-website/issues/534

**Comment by jpeach** [comment]
```
$ docker pull kumahq/kuma-cp
Using default tag: latest
Error response from daemon: manifest for kumahq/kuma-cp:latest not found: manifest unknown: manifest unknown

```

**Comment by Bradamant3** [comment]
But specifying the latest version explicitly would still work, yes? So `docker pull kumahq/kuma-cp:1.3.0` atm?

**Comment by jpeach** [comment]
> But specifying the latest version explicitly would still work, yes? So `docker pull kumahq/kuma-cp:1.3.0` atm?

Yup.

**Comment by jakubdyszkiewicz** [comment]
If we do this, let's make sure we won't allow preview/rc versions to be latest

**Comment by lahabana** [comment]
This makes sense but we'd need to be careful not to have patch versions of older minor branches override the latest minor.
