### ISSUE TITLE
Manage Docker networks in integration test framework

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2820]
### Summary

Most of the e2e integration tests check for a magic environment variable that signals that the CI makefile has set up a kind cluster, even if they don't actually use Kubernetes. I think the reason for this is that the integration test depends on the Docker network named "kind" so that if there was a kind cluster, they could communicate with it.

So there would be fewer steps to get tests running if the framework just created the "kind" network on demand.

**Comment by lahabana** [comment]
Let's reopen if people complain about this. We now have good guides and make targets for this
