### ISSUE TITLE
kuma-sidecar does not terminate if owner is not of type Job

### ISSUE THREAD

**Issue by mjsmith1028** [kumahq/kuma#2848]
### Summary

kuma-sidecar does not terminate if owner is not of type Job. It is possible to have a CRD be the owner of a pod. In this case, the kuma-init container and application specific container run to completion. However, the kuma-sidecar continues to run indefinitely.

This is because of the check here https://github.com/kumahq/kuma/blob/fdc5f1a95b1dbbeaa976d3dbec5c8e1966a3afdd/pkg/plugins/runtime/k8s/controllers/pod_status_controller.go#L60

Could you please allow for the case where owner is not of type Job, or let this field be configurable?

### Steps To Reproduce

1. Create a Pod with owner reference of a custom resource definition. For example a custom controller that watches the CRD DummyJob and logic creates a Pod
2. Pod runs, kuma-init and application specific container run to completion
3. kuma-sidecar is stuck running

### Additional Details & Logs
Example yaml:
```  ownerReferences:
  - apiVersion: dummy.com/v1
    blockOwnerDeletion: true
    controller: true
    kind: DummyJob
    name: dummy-job-example
    uid: a1e40e60-f663-456f-89ea-55721efc4ddc
```

- Version: kuma-dp:1.3.0
- Error logs: n/a
- Configuration: n/a
- Platform and Operating System: Linux
- Installation Method (Helm, kumactl, AWS CloudFormation, etc.): Helm

**Comment by mjsmith1028** [comment]
This is still relevant. My current workaround is to provide a dummy owner reference of type Job in addition to my CRD.

**Comment by mjsmith1028** [comment]
One idea, have an annotation on the pod that can enable the desired behavior. Check for that in addition to or in place of type Job

**Comment by mjsmith1028** [comment]
One note is in this case the pod restartPolicy is Never. This may be relevant and another condition that could be checked to terminate the sidecar.

**Comment by michaelbeaumont** [comment]
> One note is in this case the pod restartPolicy is Never. This may be relevant and another condition that could be checked to terminate the sidecar.

I think this could be the way to handle this. If all other containers have terminated, we can terminate the sidecar when:
- `RestartPolicy` is `Never`
- `RestartPolicy` is `OnFailure` and all containers have terminated with `ExitCode` `0`

In both these cases, no container will ever run again and we don't have to check the owner at all.

Those are the only two `RestartPolicies` allowed for a `Pod` created by a `Job` so the `Job` case is covered.

**Comment by mjsmith1028** [comment]
> > One note is in this case the pod restartPolicy is Never. This may be relevant and another condition that could be checked to terminate the sidecar.
> 
> 
> 
> I think the `RestartPolicy` could be the way to handle this. If all other containers have terminated, we can terminate the sidecar when:
> 
> - `RestartPolicy` is `Never`
> 
> - `RestartPolicy` is `OnFailure` and all containers have terminated with `ExitCode` `0`
> 
> 
> 
> In both these cases, no container will ever run again and we don't have to check the owner `Kind` at all.
> 
> 
> 
> Those are the only two `RestartPolicies` allowed for a `Pod` created by a `Job` so the `Job` case is covered. 

That makes sense to me, thanks!

**Comment by mjsmith1028** [comment]
Ack

**Comment by mjsmith1028** [comment]
Thank you! I will give feedback confirming the fix on this issue once I have availability to test the scenario.
