### ISSUE TITLE
Deprecate `kuma-prometheus-sd`

### ISSUE THREAD

**Issue by austince** [kumahq/kuma#2851]
### Summary

Since the introduction of `kuma_sd` in mainstream Prometheus, we should point users in that direction instead of the 
`kuma-prometheus-sd` sidecar implementation.

### Proposed Plan

- [x] Ask Prometheus folks for version adoption information
- [x] Add docs to the website about migration, mainly around changed label remapping configs and which version of Prometheus to upgrade to
  - this looks documented, e.g.: https://kuma.io/docs/1.5.x/policies/traffic-metrics/#configure-prometheus
- [x] #2993
- [x] #2852
- [ ] [Remove `kuma-prometheus-sd` app](https://github.com/kumahq/kuma/pull/4878)

**Comment by lahabana** [comment]
Might be a good time to do now. This has been around for over a year no?

**Comment by jakubdyszkiewicz** [comment]
> Triage: Kuma 2.0 would be a good time to do this
