### ISSUE TITLE
Consolidate HTTP client usage

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#2919]
### Summary

As per comment here https://github.com/kumahq/kuma/pull/2892#discussion_r723859457
We could consolidate the verbosity of the raw Go HTTP client.

**Comment by lahabana** [comment]
@jakubdyszkiewicz this issue is not really clear to me and looking at the code I still don't see the issue :).
Do you remember what this is about?

**Comment by jpeach** [comment]
IIRC, it's about extracting a utility function that posts a JON object. There's 3 or 4 paces that do this.

https://github.com/kumahq/kuma/blob/e5bbd7b4f3e18c682e19503a97296adfe59b5e7e/pkg/plugins/authn/api-server/tokens/ws/client/client.go#L39-L56
