### ISSUE TITLE
e2e test, replace `ncat` external services with test-server

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#2922]
### Summary

Today external service is implemented as a `ncat` command:
```go
var UniversalAppEchoServer = Command([]string{"ncat", "-lk", "-p", "80", "--sh-exec", "'echo \"HTTP/1.1 200 OK\n\n Echo 80\n\"'"})
```
That's not convenient and doesn't allow using `CollectResponsesByInstance` without hacks.

**Comment by jakubdyszkiewicz** [comment]
It's still the case
