### ISSUE TITLE
Feature Request: Allow Ignore cert for webhooks

### ISSUE THREAD

**Issue by BloodBlight** [kumahq/kuma#2925]
### Summary

Add the same "Ignore TLS/SSL error for HTTPS websites" option for Webhook Notifications.

Thanks!

**Comment by BloodBlight** [comment]
When setting up a notification to hit a webhook, there is no option to ignore invalid SSL/self signed cert.  If you attempt to send to one, you are hit with a self signed error:
https://imgur.com/a/j3M0e0o

**Comment by jpeach** [comment]
> I was looking for the uptime-kuma rather than just kuma! Very different projects...

Ah, that makes sense. thanks @BloodBlight :)
