### ISSUE TITLE
Pidfiles for kuma-cp and kuma-dp

### ISSUE THREAD

**Issue by mmorel-35** [kumahq/kuma#2946]
When I define kuma-cp or kuma-dp as a service, I would like to use a pidfile.  I also would like to customize the path of this pidfile.

Is there already a way to do such a thing?

**Comment by mmorel-35** [comment]
I can do that to get this working now, but if you agree I would like to turn this question into a feature request.

**Comment by jpeach** [comment]
So the production system has some dependency on pidfiles? Are there any specific semantics that it relies on?

**Comment by mmorel-35** [comment]
One thing you need to now is that kuma will be installed in a  home user and not in the default system directories.
No specific semantic, It just requires a defined pidfile for each  deployed service.

Something like this would be great
mypath/kuma-cp.pid
myotherpath/kuma-dp.pid

**Comment by jakubdyszkiewicz** [comment]
> Triage: We are closing it for now. Feel free to reopen this if you are interested in contributing this feature.
