### ISSUE TITLE
Adopt Github release notes tooling

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2948]
### Summary

Github releases now has built-in support for generating release notes. We should evaluate whether to adopt this in the Kuma project. It looks similar to what we do not (i.e. build a list of merged PRs), but add some categorization based on PR labels, and can automatically exclude PRs (e.g. dependabot updates) if we want.

https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes

**Comment by jpeach** [comment]
Looks like this will be supported by goreleaser too, so we can use that for release tooling.

https://github.com/goreleaser/goreleaser/issues/2552

**Comment by lahabana** [comment]
We have something that works now let's not do this
