### ISSUE TITLE
Kuma Sidecar container cause error to Pod, which result the pod can't be create

### ISSUE THREAD

**Issue by tuananh2508** [kumahq/kuma#2982]
### Summary
Kuma Sidecar container cause error to Pod, which result the pod can't be create

### Steps To Reproduce

1. Install Loki stack through command `helm upgrade --install loki grafana/loki-stack  --set grafana.enabled=true,prometheus.enabled=true,prometheus.alertmanager.persistentVolume.enabled=false,prometheus.server.persistentVolume.enabled=false` 
2. Create new Kuma mesh or you can use the default mesh 
3. Apply Kuma Mesh to Namespace
```
....
 annotations: 
    kuma.io/sidecar-injection: enabled
    kuma.io/mesh: test-mesh" | kubectl apply -f - && kubectl delete pod --all -n demo
...
```
4. Loki Pod and other Pod can't be recreate again 

### Additional Details & Logs

- Version : 1.3.1 
- Error logs:
```
Events:
  Type     Reason                Age               From                             Message
  ----     ------                ----              ----                             -------
  Normal   Scheduled             33s               default-scheduler                Successfully assigned demo/loki-0 to pool-iaw1u8gd-f2ft12hythz3r0h5-node-jtdelova
  Normal   CreatedKumaDataplane  20s               k8s.kuma.io/dataplane-generator  Created Kuma Dataplane: loki-0
  Normal   UpdatedKumaDataplane  8s (x3 over 20s)  k8s.kuma.io/dataplane-generator  Updated Kuma Dataplane: loki-0
  Normal   Pulled                5s (x3 over 21s)  kubelet                          Container image "docker.io/kumahq/kuma-init:1.3.1" already present on machine
  Warning  Failed                5s (x3 over 21s)  kubelet                          Error: container's runAsUser breaks non-root policy (pod: "loki-0_demo(c26db72b-460c-4c1d-92fe-37002751ec31)", container: kuma-init)
```

**Comment by RicoToothless** [comment]
face same error here

**Comment by zd9KgA** [comment]
This issue might be related to a setting of `runAsNonRoot: true` at pod level, see https://github.com/kumahq/kuma/issues/571#issuecomment-1022713023.

**Comment by lahabana** [comment]
COnfirmed it's a dupe of #3925
