### ISSUE TITLE
xDS proxy routing targets are mostly not used 

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2989]
### Summary

In the `DataplaneProxyBuilder` code, `xds_topology.BuildEndpointMap` is used to build a routing map for mesh services (dataplanes), zone ingresses and external services. This dataplane routing information is never used AFAICT, so maybe we can save the cost of building the map.

**Comment by lahabana** [comment]
The current perf improvements removed this `BuildEndpointMap`.

**Comment by jakubdyszkiewicz** [comment]
Reopening. This is very relevant. We have EndpointMap in MeshContext now, but we still build it again in DataplaneProxyBuilder because of external services. We should handle this better.

**Comment by michaelbeaumont** [comment]
Also relevant for the #3024
