### ISSUE TITLE
Migrate key storage to PEM

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#2997]
### Summary

Currently, Kuma stores keys in secrets as raw ASN.1 blobs.

https://github.com/kumahq/kuma/blob/7e40b0f96f67111333cfc919ae5d2ac3b6d47884/pkg/plugins/authn/api-server/tokens/issuer/signing_key.go#L104-L120

We should wrap these in PEM so that (if we choose) it is easy to store more than one object in the secret, and so we can migrate to different key types cleanly.

**Comment by lahabana** [comment]
Triage: PEM is indeed more common and less surprising. We should implement reading PEM now and flag writing it and then after 2 versions switch to writing PEM.

**Comment by jakubdyszkiewicz** [comment]
Done long time ago when we refactored token code into `pkg/core/tokens`
