### ISSUE TITLE
Discuss the priority semantics of Dataplane and ExternalService conflicts

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3024]
### Summary

It is possible for both Dataplane and ExternalService resources to claim the same `kuma.io/service` tag. However, traffic is only ever routed to either a dataplane cluster, or an external service cluster, never both.

The mesh code generates endpoints for both Dataplanes and ExternalServices, incidentally processing Dataplanes first, so  Dataplanes get priority in the case of conflicts. The gateway code never generates endpoints for Dataplanes (it just looks in the load assignment cache), so it explicitly checks for matching ExternaServices first.

We should discuss, implement and document the precise semantics that Kuma should apply here.

- [ ] Update docs

**Comment by lahabana** [comment]
Triage: Sounds like having ExternalService have the priority over DP is closer to what users would expect and Gateway and regular service comms should behave the same way.

We should add tests for this and document it so it's clear to users what the behaviour is.
