### ISSUE TITLE
kumactl installs old gateway

### ISSUE THREAD

**Issue by gAmUssA** [kumahq/kuma#3066]
### Summary

kumactl install gateway installs kong 2.4 and kic 1.3
kong 2.6 and kic 2.0 are available 

### Steps To Reproduce

1. `kumactl install gateway kong | kubectl apply -f -`
2. 
3.
4.

### Additional Details & Logs

- Version: 

```
❱ kumactl version
Client: Kong Mesh 1.4.1
Server: Kong Mesh 1.4.1
```
- Platform and Operating System
Kubernetes

- Installation Method (Helm, kumactl, AWS CloudFormation, etc.)
kumactl

**Comment by jpeach** [comment]
Duplicate of #2807
