### ISSUE TITLE
kuma-dp HTTP client is hard-coded to skip TLS verification on bootstrap

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3092]
### Summary

https://github.com/kumahq/kuma/blob/1f507fd10de8299fae0d740d664979de42688a4b/app/kuma-dp/cmd/context.go#L28-L31

It seems reasonable to provide an option for skipping TLS verification, but I don't think this should be the default, and it should not be hard-coded.

**Comment by jakubdyszkiewicz** [comment]
To be fair, there is a big warning in the logs
```
log.Info(`[WARNING] The data plane proxy cannot verify the identity of the control plane because you are not setting the "--ca-cert-file" argument or setting the KUMA_CONTROL_PLANE_CA_CERT environment variable.`)
```
This was a tradeoff to keep UX simple.
On Kubernetes, we provide the CA cert to injected sidecars.

Not saying we should not switch to what you are proposing, I'm just giving some context to what we picked back then.

**Comment by jpeach** [comment]
Ah I see, it's assumed to be disabled then enabled later.

**Comment by lahabana** [comment]
No changing the default however this should be mentioned in: https://github.com/kumahq/kuma-website/issues/629

**Comment by michaelbeaumont** [comment]
Also note, it isn't "hard-coded". At https://github.com/kumahq/kuma/blob/5c09195c7516fbbc6eb0444765ab9423c1beb2d4/app/kuma-dp/pkg/dataplane/envoy/remote_bootstrap.go#L54-L64 the `TLSConfig` is replaced if the option mentioned in the warning is set.
