### ISSUE TITLE
kuma + codezero

### ISSUE THREAD

**Issue by mayaaravotwm** [kumahq/kuma#3099]
hello,
we have kong ingress as our ingress controller on our aws eks cluster, and kuma as our service mesh.
whenever we intercept or teleport a deployment using codezero , we can't access the service from outside, only from the inside. so the internal routes work well but the external don't work. it is relevant to both the original service and the intercepted one as well.
we have kuma sidecar added to each pod in the namespace.

what can we do?

kuma 1.2.0
@c6o/cli/1.1.1 darwin-x64 node-v14.17.3

**Comment by lahabana** [comment]
Could you maybe describe what the setup looks like. When you talk about inside/outside are you talking inside k8s or inside Kuma?
Do you know how CodeZero works? Is it very similar to kubectl port-forward?

**Comment by lahabana** [comment]
Considering the generality and lack of context on this ticket. I'd like us to review this at triage and consider closing it.

**Comment by jakubdyszkiewicz** [comment]
> Triage: Closing for now. Feel free to reopen this if you can provide more information
