### ISSUE TITLE
Refactor RetryConfigurer as a virtual host option

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3140]
### Summary

The RetryConfigurer is structured as a listener configurer, but it actually extracts the HttpConnectionManager and tweaks the retry on all the virtual hosts.

So this ought to be structured as a virtual host configurer, then we can layer something on top of that to apply it to all the virtual hosts in for a listener.

**Comment by lahabana** [comment]
We should really do this especially as the Gateway and regular outbound end up have different implems atm
