### ISSUE TITLE
Set up mergify to delete its branches

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3168]
### Summary

```
~/upstream/konghq/kuma$ git branch -a | grep mergify | wc -l
153
```

We should configure mergify to automatically delete its branches, see https://blog.mergify.com/keep-your-repository-clean--delete-your-merged-branches-/

**Comment by michaelbeaumont** [comment]
Maybe we can turn on the setting to delete any PR branch after a merge.

**Comment by lahabana** [comment]
Seems like someone did what @michaelbeaumont suggested already.
Though I think we also need some mergify specific option because if we close the PR and not merge the branch would stay around.

**Comment by jpeach** [comment]
> Seems like someone did what @michaelbeaumont suggested already.

Who did what now?

**Comment by lahabana** [comment]
Deleting PRs when they are merged is enabled already.
We still need your config to remove the rest of the branches I believe.

**Comment by michaelbeaumont** [comment]
@lahabana can you check if the delete merged branches setting is enabled? It's all that's needed to close this issue

**Comment by lahabana** [comment]
It's on and it works so closing this!
