### ISSUE TITLE
Move install CNI to kumahq

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3169]
### Summary

It's there: https://github.com/lobkovilya/kuma-cni
We should move it to kumahq and setup CI to publish it to kumahq.

**Comment by bartsmykla** [comment]
Related: https://github.com/kumahq/kuma/issues/2044

**Comment by lahabana** [comment]
Closing as dupe then!

**Comment by jpeach** [comment]
Duplicate of #2044
