### ISSUE TITLE
Possibility to expire dataplane tokens

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3197]
### Description

There's currently no way to specify an expiry date on a dataplane token.

Adding this feature might have other requirements for example being able to replace a token without restarting a dp.

**Comment by jakubdyszkiewicz** [comment]
the pattern of expiration, revocation, and signing key rotation should be carried from the user token.

**Comment by jpeach** [comment]
xref https://github.com/kumahq/kuma/issues/2955
