### ISSUE TITLE
Validate kuma-dp `kuma_control_plane_url`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3212]
### What happened?

Currently there's no validation on the control-plane-url, we should probably check it's a valid url.

There's also a typo in the error message on bootstrap: `unsupported prootocol scheme`

**Comment by tharun208** [comment]
@lahabana, we are validating the app configuration when loading the configuration into the app (ref - https://github.com/kumahq/kuma/blob/master/pkg/config/loader.go#L24).
