### ISSUE TITLE
Reuse watchdog callbacks in XDS

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3243]
### Description

What is the plan for watchdogCallbacks? I think dataplaneSyncTracker could be implemented as a watchdogCallback?

@lobkovilya mentioned this.

**Comment by lahabana** [comment]
It's very likely watchdog will be removed as part: #3684. Keeping this on the side until we work on the aforementioned ticket.

**Comment by michaelbeaumont** [comment]
I think we can close this if we want to do #3684
