### ISSUE TITLE
In snapshot versioner consider using hash instead of `proto.Equal`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3244]
### Description

There is a potential optimization. We check proto.Equal in versioner of XDS. Instead of proto.Equal we could check SHA256. It might be faster.

**Comment by lahabana** [comment]
Using Murmur3 or a hash optimized for speed might return even better perf.

**Comment by lahabana** [comment]
We'd need to benchmark this

**Comment by lahabana** [comment]
There's a bunch of usages of shasum as well when we don't need a crypto secure hash.

**Comment by slonka** [comment]
Still the case https://github.com/search?q=repo%3Akumahq%2Fkuma+sha256+language%3AGo&type=code&l=Go https://github.com/search?q=repo%3Akumahq%2Fkuma+proto.Equal+language%3AGo&type=code

**Comment by lahabana** [comment]
Actually just closing this. I think we'll figure optimizations from data we gather rather than gut feeling
