### ISSUE TITLE
Standardize envoy admin port on both Kubernetes and Universal

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3281]
### Description

Today we have different ports for what's essentially the same functionality. Let's standardize this on one port (or one port range) for both environments.

Also update documentation when this is done.

**Comment by lahabana** [comment]
It's not a "big" breaking change so we might be able to fit it in a minor version.

**Comment by lahabana** [comment]
@lobkovilya this can be closed as #3717 fixes that no? Do we now have the same defaults for K8s and Universal?

**Comment by lobkovilya** [comment]
Yes, I'm closing the issue, now we have 9901 for both environments
