### ISSUE TITLE
Services start without sidecar when CP is down

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#3293]
### What happened?

The injector webhook has a `FailurePolicy` set to Ignore. For this reason, if CP is down, then the webhook fails but the service still starts without a sidecar.
We cannot just change a `FailurePolicy` to `Fail`, because then CP can never start. We can set `namespaceSelector` in webhook for namespaces with `kuma.io/sidecar-injection: enabled` and then set this to false. But the whole reason we got rid of `namespaceSelector` was the injection of sidecars to individual pods.

I see 2 options at this moment
1) We could have 2 hooks, one with `FailurePolicy` set to `Fail` with `namespaceSelector` and one with `Ignore` without.
The problem will still be there for individual pod injection
2) We change the hook to `FailurePolicy` set to `Fail` with `namespaceSelector` and remove an option of injecting sidecars to individual pods without annotating namespace. What we can provide for users instead is ignoring the injection, so if someone wants to inject sidecar to the individual pod, they annotate the namespace and ignore all the pods they don't care about.

**Comment by jpeach** [comment]
Maybe there is an option 3 - reconcile pods and ensure that pods that should have a sidecar injected actually do. Probably needs some rate limiting and safety guards, but would ensure that the mesh eventually converges.

**Comment by jakubdyszkiewicz** [comment]
@jpeach could you elaborate on that?

Most of the metadata about a Pod is immutable. Do I understand correctly that we have two hooks like described in the issue and on top of that have a controller that kills pods that suppose to have sidecar but they don't?

**Comment by jpeach** [comment]
> 



> @jpeach could you elaborate on that?
> 
> Most of the metadata about a Pod is immutable. Do I understand correctly that we have two hooks like described in the issue and on top of that have a controller that kills pods that suppose to have sidecar but they don't?

Yeh I'd forgotten that pod containers are immutable, so I guess you'd have to kill them
