### ISSUE TITLE
:open_umbrella: Kuma Gateway MVP

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3300]
### Description

MVP tracking for Kuma Gateway

- [x] #3299
- [x] #3301
- [x] #3320 
- [x] #3316 
- [x] #3318
- [x] #3319
- [x] #3368 
- [ ] #3445 
- [x] #3393

### Notes

- evaluate naming (current gateway support -> external?, `Gateway` -> `BuiltinGateway`?)

**Comment by lahabana** [comment]
Descoped faultInjection from MVP.
