### ISSUE TITLE
:open_umbrella: Kubernetes zone support for Gateway

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3301]
### Description

Tracking issue for Kubernetes zone support for Gateway. The proposal is that we layer this:

1. Add builtin gateway dataplane mapping
2. Add kubernetes native API controller

This issue tracks (1).  Operators should be able to use Kuma Gateway APIs, deploy dataplane capacity for them, and expose the listener ports outside the cluster. 

https://docs.google.com/document/d/1trM4QCo5mG8_1M7G17Ym-S05zjfnBQG7_42mxxQafu4/edit?usp=sharing

- [x] #3321
- [x] #3427 
- [x] #3448
- [x] #3451
- [x] #3502 
- [x] #3509 
- [x] #3551 
- [x] #3597

**Comment by jpeach** [comment]
triage: Next step is making a plan around #3427. This should define how Kuma Gateway works in Kubernetes zones, so then we can layer the ingress controller on top of that.

**Comment by jpeach** [comment]
Moved Kubernetes Gateway API support to #3445. This issue is just tracking Kuma Gateway support in Kubernetes zones.

**Comment by michaelbeaumont** [comment]
Closing this, any known issues with `GatewayInstance`/`Gateway`/`GatewayRoute`/builtin `Dataplane`s in k8s have been resolved.
