### ISSUE TITLE
Gateway listener connection limit support

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3303]
### Description

Add support for gateway listener connection limits. This needs a design. My initial inclination is to say that this probably should be a property of the Gateway, but the connection resources themselves are in the Dataplane, so needs some thought.

- [ ] https://github.com/kumahq/kuma/issues/3302
- [x] #3304

**Comment by lahabana** [comment]
Triage: Is this a new policy for any dpp type or should it be specific to Gateway
