### ISSUE TITLE
Send Dataplane host resources in xDS metadata

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3304]
### Description

We have a few use cases where Kuma ought to be able to automatically tune envoy based on knowledge of the host environment

* concurrency
* connection limits

To enabled these kinds of features, kuma-dp ought to send some information about its available resources in the bootstrap request, which can then be round tripped through the xDS node metadata.

**Comment by jpeach** [comment]
triage: Re-evaluate when we look at production readiness more.

**Comment by michaelbeaumont** [comment]
I think this issue is more of a method for implementing other features. We should simply send the resources we need and introduce them when the time comes.
