### ISSUE TITLE
Support PROXY protocol on Gateway listeners

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3306]
### Description

Add a per-listener configuration that enables PROXY protocol support.

https://www.envoyproxy.io/docs/envoy/latest/configuration/listeners/listener_filters/proxy_protocol

**Comment by jpeach** [comment]
triage: Probably needs protobuf changes.

**Comment by lahabana** [comment]
We should at least look at this before GA to see if we'll be able to support it without serious change

**Comment by jakubdyszkiewicz** [comment]
> Triage: closing for now, because of no interest
