### ISSUE TITLE
Support trusted downstream configuration on Gateway listeners

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3307]
### Description

The gateway proxy may be somewhere in the middle of a proxy hierarchy (in which case we want to propagate trusted headers) or it might be an edge proxy (in which case we don't).

https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_conn_man/headers.html#x-forwarded-for

Ref the above discussion of x-forwarded-for, trusted client addresses, and internal vs. external requests.

**Comment by jpeach** [comment]
triage: Probably needs protobuf changes.

**Comment by jpeach** [comment]
Once we add fault injection support #3315, we ought to also restrict the relevant [headers](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/fault_filter) to trusted downstream clients.

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's check what do we do with headers. Do we treat requests are internal or external right now?

**Comment by jakubdyszkiewicz** [comment]
> In general, use_remote_address should be set to true when Envoy is deployed as an edge node (aka a front proxy), whereas it may need to be set to false when Envoy is used as an internal service node in a mesh deployment.

We already set `use_remote_address` to builtin Gateway only. The ticket is then about configuring this value. Nobody ever asked about this so far, should we just leave it to MeshProxyPatch for now?

**Comment by jakubdyszkiewicz** [comment]
> Triage: closing. We can just use MeshProxyPatch if needed and we can reopen if needed
