### ISSUE TITLE
Kubernetes ecosystem support for Gateway

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3308]
### Description

Ensure that Gateway integrates with important Kubernetes ecosystem projects. Depends on #3301 and https://github.com/kumahq/kuma/issues/3445.

- [ ] external-dns
- [ ] cert-manager
- [ ] knative serving

**Comment by jpeach** [comment]
triage: When someone investigates this, spin out more issues for project-specific tasks.

**Comment by jakubdyszkiewicz** [comment]
> Triage: just use gateway api.
