### ISSUE TITLE
Scope DNS or VIP integration for universal gateways

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3309]
### Description

Clients need to be directed to a gateway IP address somehow. This is usually done with some combination of DNS records and IP routing. 

We need to get some basic requirements and understanding of what we want to do in this area. Users will want to be able to integrate a gateway with their existing infrastructure.

**Comment by jpeach** [comment]
triage: Will need this. Kubernetes has better answers, but should talk to field folks about universal options.

**Comment by jakubdyszkiewicz** [comment]
> Triage: it seems that we cannot do much about this. It's up to the env on which Kuma is deployed.
