### ISSUE TITLE
Support graceful traffic draining for gateway dataplanes

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3310]
### Description

When a builtin gateway DP instance is being shut down, we need to cleanly drain requests so that it doesn't drop any traffic.

There should be an upper bound to the drain time.

There should be a way to integrate this with external load balancing or traffic steering so that new traffic isn't still coming in while we are draining.

**Comment by jpeach** [comment]
triage: Need this for production deployments, not for MVP.

**Comment by lahabana** [comment]
This may be done by #4229 so just need to double check if this works once it's merged
