### ISSUE TITLE
Support FaultInjection policies in Gateway

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3315]
### Description

FaultInjection is a connection policy, so it ought to be applied on a source+destination tuple.

The envoy HTTPFault protobuf has an UpstreamCluster field, which looks promising, except any mesh destination can end up configuring multiple upstream clusters because the context-specific policies make them unique, and because splitting based on tags makes them unique. I think that the tag splitting makes it impossible to use these because there can be more than one upstream cluster for a service and we can't specify them all there.

So we are left with the header matcher, which is what the mesh uses to configure faults. Maybe that can work, if we can inject values into the header beforehand. Though, I don't think that it will work, because we don't know the destination until we configure the route action, and all the HTTP filters have been executed by that time.

**Comment by jpeach** [comment]
triage: We could probably live without this in the MVP if we had to.

**Comment by jpeach** [comment]
Looking at the existing `FaultInjection` configurer. It enabled all the fault injection filter configurations on the HTTP filters, but attaches a matcher that checks the `x-kuma-tags` header. This is used to match the source tags of the policy that are propagated from the mesh client.

So in gateway, we don't have mesh source tags in the HTTP layer. The source for a `FaultInjection` policy is the gateway listener. If we use the Envoy unified matcher API (or composite filter?), we can configure a fault injection filter per virtual host, which gives us the source match.

However, there's no way to make a destination match. The fault injection policy settings can be overridden for a service cluster (IIUC this is the value of the `--service-cluster` flag, not the xDS cluster that envoy forwards traffic to). That configuration looks at the `x-envoy-downstream-service-cluster` header to construct the runtime settings keys. But we can't hack it like this because we can't inject a header before the HTTP filters, and anyway at that time we would not know what to put in the tag.

On the bright side, if we emitted the `x-kuma-tags` header to the upstream, then when the upstream was a mesh service, the fault would be correctly injected there. Maybe that's how this should behave in the first place?

**Comment by jpeach** [comment]
> On the bright side, if we emitted the `x-kuma-tags` header to the upstream, then when the upstream was a mesh service, the fault would be correctly injected there. Maybe that's how this should behave in the first place?

Oh, I forgot about the `UpstreamCluster` field, which can give us a match for the destination. I think that this can work, but it is a bit tricky because we will need to delay adding the rate limit filters until the cluster names are known.

**Comment by jpeach** [comment]
So if we implement the fault injection policy in the Gateway using the upstream cluster field, then a policy that matches the gateway to the sources and a mesh service to the destinations would be implemented *both* on the gateway proxy and on the mesh proxy of the destination service.

@subnetmarco @jakubdyszkiewicz Can you confirm your ideas on how fault injection should work for Gateway? I'm inclined to think that doing nothing for Gateway is the right approach, though we could implement it only for external services (not sure that the complexity is worth it though).

**Comment by lahabana** [comment]
This was done in MeshFaultInjection
