### ISSUE TITLE
Initial support for Kubernetes Gateway API

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3322]
### Description

Add a new controller that reconciles Kubernetes Gateway API resources and creates the corresponding Kuma Gateway objects. ~The controller should automatically create a Kuma GatewayClass.~ Users handle creating a `GatewayClass`. The controller should ~optionally~ create a kuma-dp deployment with dataplane capacity. 

For multizone, this needs the zone control plane to be writable, so we may need a design doc, and to spin off separate issues for that work.

- [ ] https://github.com/kumahq/kuma/pull/3109

**Comment by michaelbeaumont** [comment]
> The controller should optionally create a kuma-dp deployment with dataplane capacity.

From reading the Gateway API spec it _feels_ like the expected default behavior is to deploy the gateway for the user. As a non-authoritative example, [Istio's default behavior](https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#deployment-methods) is also to deploy a gateway but allows users to manually handle the `Deployment` and `Service` by setting `Gateway.spec.addresses` explicitly.

**Comment by jpeach** [comment]
> > The controller should optionally create a kuma-dp deployment with dataplane capacity.
> 
> From reading the Gateway API spec it _feels_ like the expected default behavior is to deploy the gateway for the user. 

Yup, I agree that this is a totally reasonable default.

**Comment by jpeach** [comment]
triage: :+1:
