### ISSUE TITLE
[question] mix of kubernetes and traditional vm environment

### ISSUE THREAD

**Issue by rucciva** [kumahq/kuma#333]
what is the recommended way of deploying kuma when services to be managed exist both in kubernetes and virtual machine environment? 

Thanks

**Comment by devadvocado** [comment]
Support for kuma-cp to manage two different environments is a planned feature, expected in January. Just to double-check, @yskopets is this correct?

**Comment by rucciva** [comment]
Great,,, looking forward to it.

Just out of curiosity, if we deploy the current version of kuma separately for the two environments, will it possible to merged them when the feature is available?

**Comment by yskopets** [comment]
@rucciva @devadvocado I cannot vouch for the timeline, but I can confirm that this feature is crucial and definitely will be implemented.

@rucciva Regarding the second question, we consider this a separate feature.
E.g., in the first case it would be enough to have 1 control plane to manage services in both `kubenetes` and `virtual machines`.
In the second case you want coordination between multiple control planes.
It's a different use case with a different timeline. But it's in our plans as well.

**Comment by subnetmarco** [comment]
@rucciva for context, what environments/platform/OS are you planning to use?

**Comment by rucciva** [comment]
@subnetmarco , the VMs are mostly ubuntu and centos. The kubernetes are from openshift. The hosts running kubernetes are in the same subnet as the VMs

**Comment by ddysher** [comment]
IIUC, what we are discussing here is 'kuma-controlplane managing multiple environments', is it planned that kuma-dataplane can across both kubernetes and vm environment, e.g. service in kubernetes can address service in vm environment?

**Comment by subnetmarco** [comment]
@ddysher this is what we are working on, we will update this issue with progress.

**Comment by ddysher** [comment]
cool, thanks for the update

**Comment by jakubdyszkiewicz** [comment]
Now it's possible with multizone capabilities. You can have Remote CP on Kubernetes and on VMs and manage them with Global CP.

**Comment by subnetmarco** [comment]
Link to docs: https://kuma.io/docs/latest/documentation/deployments/#usage
