### ISSUE TITLE
PolicySelector 2.0

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3330]
### Description

Umbrella issue that covers all the migration to policy 2.0

Design for migration: https://docs.google.com/document/d/145cyQValxzxVZ7ZXKgjt5txK2ShFZVB6NJOiRipgV7Q/edit#heading=h.8pd0y3mjhkxf

Design for Matching: https://docs.google.com/document/d/1FM72PCThcTD6kg920g8LTw7oeBgSZ-0HaRi6D6TrcrU/edit

**Comment by lahabana** [comment]
#3067 and #3074 are related to enable easy migration

**Comment by michaelbeaumont** [comment]
@lahabana should this really be closed? Where's the issue tracking implementation?

**Comment by lahabana** [comment]
- #4732 
- #4733 
- #4734 
- #4735
- #4736
- #4737 
- #4738 
- #4739
- #4740 
- #4741

Track the reimplementation of this selector in each policies
