### ISSUE TITLE
Normalise apis for insights and overview

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3336]
### What happened?

There is `/dataplane` and `/dataplane-insights`. The `/dataplane+insights` was supposed to be a combination of dataplane + insight therefore overview. 
Maybe change it to `/dataplane-overview`

**Comment by tomaszwylezek** [comment]
If we want to do it then we might consider doing it mutually with the change of `/zones+insights`  and `/zoneingresses+insights` following with same pattern as for `dataplanes`
