### ISSUE TITLE
Add policy configuration for Fallback in TrafficRoute policy

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3338]
### Description

Right now NO_FALLBACK policy is hardcoded.
If you split traffic by version then it does make sense. But if you split traffic between 2 zones then probably you want traffic to be redirected to zone-2 if zone-1 is running out of dataplanes.

**Comment by michaelbeaumont** [comment]
@lahabana I think we definitely need `ANY_ENDPOINT` and it's a simple flag to add. Do we also need `DEFAULT_SUBSET`? or can we leave it out of the first iteration

**Comment by lukidzi** [comment]
@lahabana It seems to be fixed by https://github.com/kumahq/kuma/issues/2689 also we are moving to Mesh*Route so is it required there?

**Comment by lahabana** [comment]
Ok we're good then! Thx
