### ISSUE TITLE
Rewrite CNI

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3341]
### Description

Our CNI is not perfect and we should look at improving it.
This is an umbrella ticket and probably covers a lot of subtickets.

- [x] #2044 
- [ ] #2262

**Comment by lahabana** [comment]
See: #2262

**Comment by lahabana** [comment]
xref: #2044

**Comment by subnetmarco** [comment]
This is also needed in preparation for the support of eBPF instead of `iptables`.
