### ISSUE TITLE
`tracing` in `kumactl get meshes` not consistent

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3345]
### What happened?

```sh
$ kumactl get meshes
NAME      mTLS   METRICS                   LOGGING   TRACING     AGE
default   off    prometheus/prometheus-1   off       my-zipkin   3s
```

Shouldn't `TRACING` be `zipkin/my-zipkin` (`{type}/{name}`) like `mtls` and `metrics` ?

**Comment by tharun208** [comment]
@lahabana I like to work on this. Also, can we implement the same change for logging like `file/log`?

**Comment by lahabana** [comment]
@tharun208 go for it and I agree for doing this for logs too
