### ISSUE TITLE
Make `--proxy-type` optional when passing YAML in `kuma-dp`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3347]
### Description

When passing a YAML to `kuma-dp`, don't require the `--proxy-type` argument since we can infer it. If the YAML is not passed, then we need to require it.

**Comment by WorldVirus** [comment]
Hi, 
Can I try to take the issue ?

**Comment by lahabana** [comment]
Yes please :) ! Feel free to ping me on Kuma slack for help!

**Comment by lahabana** [comment]
This is already the case
