### ISSUE TITLE
Zone Egress

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3349]
### Description

The mirror of ingress which captures all mesh external traffic and sends it along.

This enables:

- ExternalService become conceptually just Service which makes it easier to apply policies
- Egress talk to Ingress in multizone
- Auditing traffic is easier.

**Comment by lahabana** [comment]
This is an umbrella ticket.

**Comment by lobkovilya** [comment]
Proposal: https://docs.google.com/document/d/1CLh-JGRiviijNv9TwNRO5IjEk7_XqbKsZQ6HOPNpszI/edit?usp=sharing

**Comment by lahabana** [comment]
Other issues will be created for actual implementation
