### ISSUE TITLE
Prune service configuration following TrafficPermissions

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3350]
### Description

Currently all Envoy are aware of all the Envoy clusters.
TrafficPermissions can restrict some access.

We shouldn't send the clusters when there's no permission.
This has 2 advantages:

- Performance wise it reduces the configuration size
- It avoids someone learning about a service they shouldn't by looking at configuration

**Comment by jakubdyszkiewicz** [comment]
We implemented this using reachable services. Should we close it?

**Comment by johnharris85** [comment]
Is reachable services still required though? Or can / do we compute them if we have traffic permissions in place? Still agree with the original issue I think?

**Comment by lahabana** [comment]
The latest conversation around this was to use routes instead. Clusters get added depending on the presence of a route. For this to happen we'd need a MeshTCPRoute

**Comment by lahabana** [comment]
I'm going to make this a dupe of https://github.com/kumahq/kuma/issues/6551 so we make sure all the discussion happens in a single place.
