### ISSUE TITLE
Provide documentation how to setup a `Linux network namespace` when deploying dataplanes in `universal` case

### ISSUE THREAD

**Issue by yskopets** [kumahq/kuma#336]
### Summary

Question from `Norbert Kiesel` on [Slack](https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1570559997077200):

> Is there any documentation about the `Linux network namespace` approach? This would be a very strong selling point for the `universal` mode because it would provide the isolation provided by k8s for legacy apps.

**Comment by yskopets** [comment]
Right now, we don’t have such documentation or example setup.
We need feedback from you guys (early adopters) to find out what solution would be acceptable in your environment.
The problem we have to solve is how to run both `Kuma` dataplane and your application in the same Linux network namespace. And solution will vary depending on your organization.
E.g., if your company allows usage of `docker` (or `podman`, or `rkt`)  on VMs, we could prepare an example around that.
On the other hand, if `docker` is not an option, we could focus on example around `systemd`. Personally, I was planning to try approach described in https://cloudnull.io/2019/04/running-services-in-network-name-spaces-with-systemd/
So, let us know what kind of constraints you have to deal with and what we should focus on.

**Comment by lahabana** [comment]
Moved to docs
