### ISSUE TITLE
Review how Kuma policies apply to gateway

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3368]
### Description

It's been a while since we originally reviewed how Kuma policies apply to gateway resources, and it's possible that some context was lost in moving issue to Github. This issue is to review the Gateway implementation of each Kuma policy, and ensure that we have a clear understanding of which policies are fully supported, and which are not. In the latter case, ensure that we have issues tracking the gaps.

**Comment by jpeach** [comment]
| Policy | Supported | Discussion |
| --- | --- | --- |
| CircuitBreaker | | |    
| ExternalService |       
| FaultInjection | | |    
| HealthCheck | |      
| ProxyTemplate |    
| RateLimit |    
| Retry |        
| Timeout |    
| TrafficLog |            
| TrafficPermission |    
| TrafficRoute | No | Use GatewayRoute. |    
| TrafficTrace |    
| VirtualOutbound |

**Comment by jpeach** [comment]
triage: @jpeach to update and finalize

**Comment by jpeach** [comment]
Audit complete. We have issues tracking the remaining policy work.

**Comment by michaelbeaumont** [comment]
| Policy            | Supported | Discussion                                                                                                                                                                                                        |
| ----------------- | --------- | ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- |
| CircuitBreaker    | Yes       |                                                                                                                                                                                                                   |
| ExternalService   | Yes       |                                                                                                                                                                                                                   |
| FaultInjection    | No        | #3315                                                                                                                                                                                                             |
| HealthCheck       | Yes       |                                                                                                                                                                                                                   |
| ProxyTemplate     | Yes       | Use "gateway-proxy" profile.                                                                                                                                                                                      |
| RateLimit         | Yes       | Local rate limiting make sense to start with #3393.                                                                                                                                                               |
| Retry             | Yes       | Added in #3319.                                                                                                                                                                                                   |
| Timeout           | Yes       | HTTP request timeout added in #3318.                                                                                                                                                                              |
| TrafficLog        | Yes       | The only possible matching policy is the wildcard policy (#3316)                                                                                                                                                  |
| TrafficPermission | Yes       | Supported as a side-effect of mTLS mesh support.                                                                                                                                                                  |
| TrafficRoute      | No        | Use GatewayRoute.                                                                                                                                                                                                 |
| TrafficTrace      | Yes       | It's specified in the mesh. Gatway gets it for free from `TracingProxyGenerator` and from `envoy_listeners.Tracing()`.                                                                                            |
| TrafficMetrics    | Yes       | TrafficMetrics isn't a policy, though the website makes it seem like it is. Gateway supports metrics hijacker and the Prometheus endpoint generator.                                                              |
| VirtualOutbound   | No        | I don't think that virtual outbound makes sense for Gateway. Maybe it could be used for cases where you need to direct metrics of other ancillary traffic somewhere, but the use cases aren't really clear to me. |
