### ISSUE TITLE
Benchmarking define dimensions we want to exercise

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3373]
### Description

Define a set a cases we want to exercise for our benchmarking.

For example:

- 1 service with 1000 dataplanes
- 1000 service with 1 dataplane each
- 10 zones with 100 different services (1 dpp in for each service in each zone).
...

We can then track each of these cases and easily refer to issues which block which types of tests.

**Comment by lahabana** [comment]
@parkanzky can you link your document and close this ticket?

**Comment by parkanzky** [comment]
Goals have been added to the beginning of this document -https://docs.google.com/document/d/12tcWH9DEsXIxVJY_EWxZ2mmkhV-7D1exWYQhLnhRLlA/edit#
