### ISSUE TITLE
Unify subscriptions stats between insights.

### ISSUE THREAD

**Issue by tomaszwylezek** [kumahq/kuma#3380]
### Description

DPP insights subscription information stats are directly in `DiscoverySubscriptionStatus` (`cds`, `eds`, `lds`, `rds`)

https://github.com/kumahq/kuma/blob/master/api/mesh/v1alpha1/dataplane_insight.proto#L85

whereas in Zone Insights it's in `stat` field in `KDSSubscriptionStatus` 

https://github.com/kumahq/kuma/blob/master/api/system/v1alpha1/zone_insight.proto#L66

If possible I think it would be great to unify way how we provide `stats` of different services.

**Comment by bartsmykla** [comment]
These stats are different as in the `KDSSubscriptionStatus` contains in the `stats` field the stats for resources and the `DiscoverySubscriptionStatus` contains `xDS` subscriptions, so after the discussion we decided to close this issue with @tomaszwylezek
