### ISSUE TITLE
Should mTLS permissive be set by default on mesh creation

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3383]
### Description

By default currently we create meshes without mTLS. Maybe by default we should have meshes with mTLS in permissive mode on.

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's discuss it again with a discussion of profiles.

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's not do this. This can cause more problems when someone is deploying the default deployment.
