### ISSUE TITLE
Build versions shouldn't depend on the git tag at build time

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#3400]
### Description

We should be able to build all artifacts for a release in CI without pushing a tag, i.e. prepare a release without "announcing" it officially via a tag or release.

This would likely involve explicitly setting and reading the version as a variable in the source.

One side effect after doing this is that `master` builds could have a more sensible version. For example at the time of writing, with the `release-1.4` branch being the latest, `master` builds have a version like `1.4.0-rc1-67-g2e0a6881` since `1.4.0-rc1` is the most recent common ancestor tag of `master` and `release-1.4`. We could instead mark them as prerelease version of the "next" version (e.g. `1.5.0-dev`).

Related: https://github.com/kumahq/kuma/issues/3365

Docker issues with `+`: https://github.com/distribution/distribution/issues/1201

**Comment by lahabana** [comment]
For master shouldn't the version simply be `master-<githash>` ?
It's weird to do the +1 on the minor when maybe the release will be a major no?

**Comment by michaelbeaumont** [comment]
Yes that's also fine.

Another issue with the current state is that because the `release-1.4` and `master` branches have a common ancestor tag of `1.4.0-rc1`, we end up with a version like `1.4.0-rc1-1-g56ae432` on _both_ branches, which is semantically nonsensical.

**Comment by michaelbeaumont** [comment]
On a release branch we should essentially what we do now with `1.4.0-rc1` but make intermediate builds semver compliant with something like `1.4.0-rc1+<#commits>-<githash>`.

For `master` the problem comes down to that you either have a:
* prerelease version, which would require picking a specific "next" version. This isn't ideal because you don't yet know the next release version.
* postrelease (i.e. version + build metadata) but this might collide with the postreleases on the `release-*` branch as mentioned above.

I see the following options for versioning `master`:

1. On `master` we have always `dev+<githash>` i.e. `dev` or `master` plus build metadata. This version isn't semver compliant :shrug:
2. We remove the collisions for postreleases by putting a `dev` in the metadata. So we'd have `1.4.0-rc1+dev.<#commits>+<githash>` for `master` and `1.4.0-rc1+<#commits>+<githash>` for `release-1.4` like above. It's not super obvious what's going on :shrug:
3. We just pick a "next" version by incrementing the minor and have `master` be a prerelease. If we end up changing it :shrug:

**Comment by lahabana** [comment]
I like the first option (`<branch>+<githash>`) I think there's value in always publishing artifacts from each branch:

1. We always have "preview builds"
2. Automation for releasing always runs
3. If one day we add CD clusters we already have the build for them

Unfortunately we can't just retag existing builds for releases because that's my favourite way to do releases :)
However, we can have everything but the announcement run on every merge which is already really good.

**Comment by lahabana** [comment]
Isn't this done now?

**Comment by lahabana** [comment]
Triage: it is done
