### ISSUE TITLE
Add a kumactl subcommand to deploy gateway dataplanes

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3415]
### Description

Since #3294, kuma will generate builtin gateway dataplanes from pods that have the right gateway annotations. We should make an easy installer to create deployments that will generates these pods correctly (similar to the approach that zone ingress takes).

Operators that are using the gateway controller (we expect that to be most people) won't need this. The gateway controller should automatically manage a gateway deployment and its corresponding service. The kumactl support here is for when you are doing something by hand.

We can have multiple gateway deployments, so something like `kumactl install gateway-deployment` would then

- create a deployment in the kuma-system namespace (by default)
- the deployment should run the kuma-dp container
- the deployment will add the right pod annotations
- Should create a service (with specified name) to target the ports

There's a bit of a layering problem with the service, since the ports exposed by the service depend on the gateway listeners, which means that we really need a controller to rewrite the service ports dynamically. This probably needs the service to be linked to the gateway through annotations.

**Comment by jpeach** [comment]
Blocked by #3427

**Comment by jpeach** [comment]
triage: We probably want this so that users can easily create capacity in Kubernetes zones without needing crazy amount of YAML. The exact form this takes and UX depends on the discussion in #3427.

**Comment by lahabana** [comment]
With the `GatewayDataplane` CRD doesn't provisioning a gateway is as simple as creating a CRD it might not be necessary anymore to add an install command for this no? We don't have an install command for zoneIngress for example.

**Comment by michaelbeaumont** [comment]
Yes, we create `ZoneIngress` resources only as part of `install control-plane`.
Closing this
