### ISSUE TITLE
:open_umbrella: Support Kubernetes Gateway API as a Kuma add on

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3445]
### Description

Once Kuma supports Kuma Gateway is Kubernetes zones, we want to support Kubernetes Gateway API so that operators can use a familiar API and Kuma can integrate cleanly with the Kubernetes ingress ecosystem

This umbrella issue tracks the work needed for the ingress controller.

- [x] #3322
- [x] #3446 
- [x] #3515 
- [x] #3613
- [x] #3517
- [ ] #3450
- [x] #3503
- [ ] #3464 (maybe not MVP)

Gateway API conformance:
- [x] #3616
- [x] #3615
- [ ] #3617
- [x] #3624
- [ ] #3679
- [x] #3701

Installation (maybe not MVP):
- [ ] #3317 
- [ ] #3612
- [x] #3447 
- [ ] #3416

**Comment by lahabana** [comment]
Favouring project tracking to this ticket.
