### ISSUE TITLE
Create an optional installation path for the Gateway API controller

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3447]
### Description

In Kubernetes clusters, create a way to optionally install the Gateway API ingress controller.

My preference is that this is installed as a separate component from kuma-cp so that 
* it can be truly optional and we don't accidentally assume it
* it can have separate RBAC (least privilege)

**Comment by jpeach** [comment]
xref #3612

**Comment by lahabana** [comment]
Duplicate of #3702
