### ISSUE TITLE
Introduce CRD to handle deploying and managing `kuma-dp` for `Gateway`s

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#3448]
### Description

As discussed in https://github.com/kumahq/kuma/issues/3427#issuecomment-988497525, we've decided to make running `kuma-dp` as a builtin gateway in Kubernetes the responsibility of a new CRD (tentatively `GatewayDataplane`). This issue covers the introduction of the new CRD itself.

**Comment by jpeach** [comment]
Since we are introducing a new CRD, we need to run crd-gen and deepcopy-gen for the API machinery, so we will either need to land #3453 or make some way to just generate this specific CRD and not the rest of the Kuma types.
