### ISSUE TITLE
Add `localityAwareLoadBalancing` to TrafficRoute

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3456]
### Description

We should be able to set `localityAwareLoadBalancing` as an option in the TrafficRoute.
This is mainly because you might not want all or none the services to have the same behaviour.

This is especially useful for prometheus federation (you want to stick to a zone even if it's unavailable).

**Comment by jakubdyszkiewicz** [comment]
Duplicate of https://github.com/kumahq/kuma/issues/2689
It's not 100% clear if we want to add it to the new MeshHTTPRoute

**Comment by lahabana** [comment]
I think we wanted to add it to something different as this is cluster based. I think it's a similar problem as load balancer types
