### ISSUE TITLE
Optionally install Gateway CRDs with published Helm chart

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#3475]
### Description

At the moment we embed the Helm chart at `deployments/charts/kuma` to get the resources for `kumactl install control-plane`. `kumactl` optionally installs the gateway CRDs based on whether the `gateway` build tag is set at build time.

The Helm chart alone has no option to disable installing the CRDs, which means when we publish the next >= minor release Helm chart, they'll be included.

We likely have to remove them at publish time because optionally installing CRDs doesn't appear to be possible with Helm.

**Comment by jpeach** [comment]
By "Gateway CRDs", are we specifically talking about Kuberentes Gateway API CRDs, or the full stack of Kuma Gateway types?

**Comment by michaelbeaumont** [comment]
Just the Kuma Gateway CRDs
