### ISSUE TITLE
Auto generate helper functions

### ISSUE THREAD

**Issue by parkanzky** [kumahq/kuma#3477]
### Description

In `api/system/v1alpha1/` and `api/mesh/v1alpha1/` there are functions which are repeated in every helper file for each type. They should be auto-generated. 

Note - This includes a repeated `DeepCopy` function which calls the repeated `DeepCopyInto` function. It might be better to call the proto `Clone` method instead.

**Comment by lahabana** [comment]
Let's not do this we do it well in the new polcies
