### ISSUE TITLE
Benchmark Kubernetes resource marshalling

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3478]
### What happened?

We should add a benchmark for Kubernetes resource marshaling patterns so that we can understand the performance effects of changing the way it's done.

**Comment by lahabana** [comment]
What shape do you think this benchmark should take? Should it include the store or simply look at K8s apis perf for marshalling/unmarshalling to avoid falling back to what we did before?

**Comment by jpeach** [comment]
A Go benchmark for marshaling and unmarshaling would be pretty helpful.

**Comment by lahabana** [comment]
Not sure we'll get around to do this and haven't required to for a while
