### ISSUE TITLE
MeshInsights includes a Mesh field. 

### ISSUE THREAD

**Issue by parkanzky** [kumahq/kuma#3480]
### What happened?

The `MeshInsights` struct includes a `Mesh` field. This does not seem correct. Need to determine why this is and remove it if possible.

**Comment by lahabana** [comment]
Can we at least make the `Mesh` field optional?

**Comment by lahabana** [comment]
Part of #3330

**Comment by lahabana** [comment]
Let's not cover this as we're reviewing MeshInsights and Mesh very soon
