### ISSUE TITLE
DataplaneInsights Status field in place of Spec?

### ISSUE THREAD

**Issue by parkanzky** [kumahq/kuma#3481]
### What happened?

`DataplaneInsights` does not have a `Spec` member. Instead, it has `Status` which is treated exactly like `Spec` with special cases to marshal and unmarshal spec data. The `GetSpec()` and `SetSpec()` methods operate on `Status` member. Need to determine if this is for some reason necessary and replace with `Spec` if possible.

**Comment by jpeach** [comment]
> Need to determine if this is for some reason necessary and replace with `Spec` if possible.

That would be a breaking change to the CRDs, right? We would need to rev the version and do conversions, etc.

**Comment by lahabana** [comment]
Yes

**Comment by lahabana** [comment]
We'll never fix this. Let's just close this
