### ISSUE TITLE
Tools for visibility: See all dataplanes impacted by a specific policy

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3486]
### Description

Part of #3074 .
A new api endpoints which returns all the dataplanes impacted by a policy which is useful for troubleshooting policy matching.

**Comment by jpeach** [comment]
@lobkovilya Should builtin gateway dataplanes be included in this API endpoint?

**Comment by lobkovilya** [comment]
The issue for gateway: https://github.com/kumahq/kuma/issues/3718
