### ISSUE TITLE
Tools for visibility: dry-run when applying policies

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3487]
### Description

Part of #3074. We should expand the apply endpoint to be able to add a dry-run which shows which dataplanes will be impacted by this policy update.

**Comment by ravish-kumar-maersk** [comment]
@lahabana 

This is a much-required feature. We are running Global CP in K8s (multi-zone). 
We would like to validate policies (dry-run) before the actual-apply.

Any alternative solution (if available) would be appreciated.

**Comment by lukidzi** [comment]
Haven't shadow policies done it?  @lobkovilya

**Comment by michaelbeaumont** [comment]
> triage: shadow policies are implemented
