### ISSUE TITLE
API to retrieve the full XDS config for an Dataplane

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3488]
### Description

This is useful for debugging issues. It should be a rest endpoint for each DP that outputs the generated XDS configuration.

This is complementary to #3460 to make it easier for users to understand their proxy configuration.

**Comment by lahabana** [comment]
There's already some ways to access the admin api with the support of k8s Jobs (which calls /quitquitquit admin endpoint).
This can likely be built on top of this.

**Comment by jpeach** [comment]
> It should be a rest endpoint for each DP that outputs the generated XDS configuration.

Does this need to go to the DP? The CP has the configuration cached already, so maybe we can fish that out.

**Comment by lahabana** [comment]
Doesn't the dp potentially has rejected config errors that we wouldn't get on the CP?

**Comment by jpeach** [comment]
> Doesn't the dp potentially has rejected config errors that we wouldn't get on the CP?

If Envoy NACKed a snapshot, then the CP would get the NACK and know about it. Might be hard to fish this out of the xDS server, but Envoy doesn't know anything that the CP doesn't already know.
