### ISSUE TITLE
Update references to deprecated protobuf lib

### ISSUE THREAD

**Issue by parkanzky** [kumahq/kuma#3499]
### What happened?

Kuma code imports `github.com/golang/protobuf/proto` in a number of places. This package is deprecated in favor of `google.golang.org/protobuf/proto`. Should update everything to recommended package.

Unfortunately, the two packages are not compatible, so need to update all dependencies of any changed module at the same time.

**Comment by jpeach** [comment]
I think the main blocker is the generated Envoy protobufs, https://github.com/envoyproxy/go-control-plane/issues/524.

**Comment by lukidzi** [comment]
Looks like there is one more place: https://github.com/kumahq/kuma/blob/master/pkg/plugins/policies/meshloadbalancingstrategy/plugin/xds/lbconfigurer.go#L5

**Comment by Icarus9913** [comment]
Unfortunatlly, the latest v0.12.0 `go-control-plane` still use golang/protobuf.
https://github.com/envoyproxy/go-control-plane/blob/989e83d4a05c74448fdc72e5a67df5529387c021/go.mod#L9

I'll do this migration once our dependency implemented it.

**Comment by Icarus9913** [comment]
> The latest still supports v1 protobuf but the main branch doesn't, see https://github.com/envoyproxy/go-control-plane/blob/main/go.mod

The main branch still include the `github.com/golang/protobuf v1.5.4`

https://github.com/envoyproxy/go-control-plane/blob/108116100bc16c91f49cd50d4b09495471c711c2/go.mod#L24

**Comment by Icarus9913** [comment]
> Yes but that's not a direct dependency 😅.

Oh, you're right. 
I gonna get a try with the next go-control-plane version.

**Comment by Icarus9913** [comment]
still blocked by https://github.com/envoyproxy/go-control-plane/issues/875

**Comment by Icarus9913** [comment]
We can't get rid of the old protobuf dependency due to https://github.com/golang/protobuf/issues/1374
So, we would just only keep the `github.com/golang/protobuf/jsonpb` dependency but update of all others.
