### ISSUE TITLE
Multizone support for Kubernetes Gateway API

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3503]
### Description

When you deploy the Kubernetes Gateway API controller in a multizone Kuma configuration, it will need to create Kuma Gateway resources in a non-global zone. Normally in multi-zone, only the global control plane is writable, so we need to weaken this restriction for the controller to work as expected in multizone configurations.

**Comment by lahabana** [comment]
@michaelbeaumont @jakubdyszkiewicz wasn't the conclusion on this that it didn't make sense to support gatewayAPI on multizone?

**Comment by lahabana** [comment]
Closing this we might reconsider it in the future but it's not a priority because of the many technical complexities
