### ISSUE TITLE
Automatically update helm charts with generated CRD changes

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3504]
### What happened?

CRDs are (or used to be) generated to `pkg/plugins/resources/k8s/native/config/crd/bases/`, but the helm char machinery picks them up from the copies in `deployments/charts/kuma/crds/`.

We should have either a single source or CRD yaml, or build machinery that guarantees the consistency.

**Comment by jpeach** [comment]
xref #2130

**Comment by lahabana** [comment]
I believe this is not an issue anymore but sending to Triage for the team to confirm

**Comment by lahabana** [comment]
> Triage: @michaelbeaumont to check if it's done or not

**Comment by michaelbeaumont** [comment]
We now generate resources directly into `deployments/charts/kuma/crds`.
