### ISSUE TITLE
Use k8s API to create Gateway-related objects in Gateway controllers.

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#3517]
### Description

* Using the Kuma store interface makes owner references unusable (see https://github.com/kumahq/kuma/pull/3482).
* See also discussion about cleaner interfaces https://github.com/kumahq/kuma/pull/3476#discussion_r769128465. 

The foundation for this was added in https://github.com/kumahq/kuma/pull/3610

**Comment by jpeach** [comment]
I looked at the Gateway API controller as part of the change to switch Kuma Gateway resources from namespaced to cluster scoped. Just a note to remind us that in the controller, the code that calls `K8sNamespacedNameToCoreName()` will change as part of this issue, and we ought to use `GenerateName` to create the name of the Kuma Gateway resource that will be owned by the gateway API resources.

**Comment by michaelbeaumont** [comment]
@jpeach Now that kuma `Gateway` resources are cluster-scoped, they can no longer be owned by the namespace-scoped Gateway API objects.

**Comment by jpeach** [comment]
> @jpeach Now that kuma `Gateway` resources are cluster-scoped, they can no longer be owned by the namespace-scoped Gateway API objects. Maybe we can just annotate the `Gateway`/`GatewayRoute` objects with the `namespace/name/uid` of the `Gateway`/`HTTPRoute` and garbage collect them ourselves.

Ouch, that's unfortunate. Yeh, I don't see an alternative other than doing our own garbage collection when gateway API objects are deleted. We should annotate the objects in both directions so that we can clean up from either end if we need to.
