### ISSUE TITLE
Skip authentication check on / and /gui to help exposing GUI using Gateways

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#3576]
### Description

Right now we put an authentication filter on the whole API server including `/` and `/gui`.

If you put Kuma GUI behind an API gateway with another authentication mechanism like Okta, the gateway may pass authenticated JWT token down to the Kuma GUI. Kuma then is trying to authenticate the user using the User Token mechanism which of course fails.

We can configure the gateway to not pass down the authentication header, but we can also ease this process for end-users by not authenticating on `/` and `/gui`. After all, we don't enforce authorization on those paths anyways.

**Comment by VedRatan** [comment]
can  you please elaborate a little bit about this issue, and also the particular file causing this issue?
@jakubdyszkiewicz
