### ISSUE TITLE
HTTP request timeout policy not work for non-mesh service request.

### ISSUE THREAD

**Issue by webliupeng** [kumahq/kuma#3614]
### What happened?

Kuma version : 1.4.1 in kubernetes

Description: 
I'm not sure this whether is bug or in expect.
There is a http service  has some high latency api (more than 20s to response) and I had added Timeout policy.
When an external service requests this api (direct request k8s service)got 504 response after 15s.
I found these code, It's looks like no timeout setting for some reason.

https://github.com/kumahq/kuma/blob/5a5fa71e3101c184149fd72ee5f05d0375bd5043/pkg/xds/envoy/routes/v3/routes_configurer.go#L158

**Comment by jakubdyszkiewicz** [comment]
Hey, thanks for the report, but I need more info about the setup.

Is the service that you are consuming added as `ExternalService` or is it just some service outside of the mesh that you are consuming directly?

**Comment by webliupeng** [comment]
@jakubdyszkiewicz it's not ExternalService . It's just outside of mesh, Actually it's ingress service and direct request in kubernetes

**Comment by jakubdyszkiewicz** [comment]
If the service is outside of the mesh, then the traffic goes through "passthrough" cluster, which is just passing TCP traffic.
Envoy is not aware of the HTTP protocol so the only timeouts which is applied are
* connection timeout. Connection timeout checks only connection initialization, not the request itself. The default connection timeout on passthrough cluster is 10s
  https://github.com/kumahq/kuma/blob/master/pkg/xds/envoy/clusters/configurers.go#L135
  https://github.com/kumahq/kuma/blob/master/pkg/xds/envoy/clusters/v3/timeout_configurer.go#L15
* idle timeout. Idle timeout closes the connection after no traffic is sent on the wire. This is not set on passthrough clusters which means it's 1h by default https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto

Is the high latency on establishing the connection or processing a request and generating a response?

Are you sure it's Envoy that returns 504, can you post whole response with headers? Maybe it's this service or some other reverse proxy / load balancer in front of this service?

Could you attach the stats of Envoy (port forward 9901 and `curl localhost:9901/stats`)?

**Comment by webliupeng** [comment]
> If the service is outside of the mesh, then the traffic goes through "passthrough" cluster, which is just passing TCP traffic. Envoy is not aware of the HTTP protocol so the only timeouts which is applied are
> 
> * connection timeout. Connection timeout checks only connection initialization, not the request itself. The default connection timeout on passthrough cluster is 10s
>   https://github.com/kumahq/kuma/blob/master/pkg/xds/envoy/clusters/configurers.go#L135
>   https://github.com/kumahq/kuma/blob/master/pkg/xds/envoy/clusters/v3/timeout_configurer.go#L15
> * idle timeout. Idle timeout closes the connection after no traffic is sent on the wire. This is not set on passthrough clusters which means it's 1h by default https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/tcp_proxy/v3/tcp_proxy.proto
> 
> Is the high latency on establishing the connection or processing a request and generating a response?
> 
> Are you sure it's Envoy that returns 504, can you post whole response with headers? Maybe it's this service or some other reverse proxy / load balancer in front of this service?
> 
> Could you attach the stats of Envoy (port forward 9901 and `curl localhost:9901/stats`)?

The 504 response includes text "upstream request timeout".
The actual case is a download file api (> 100m), It's broken after 15s . I simulate an api (server side sleep 20s )to investigate.
I don't think it's  passing TCP traffic . because. I have change code at here https://github.com/kumahq/kuma/blob/5a5fa71e3101c184149fd72ee5f05d0375bd5043/pkg/xds/envoy/routes/v3/routes_configurer.go#L159  
```go
	routeAction := &envoy_route.RouteAction{
		Timeout: durationpb.New(time.Second * 1200),
	}
```
Then I re-build and deploy to test. It's worked. 
By the way I have set annotation in service:
```yaml
80.service.kuma.io/protocol: http
```
It's work if I set protocol as tcp.

**Comment by webliupeng** [comment]
I think the problem is envoy sidecar to upstream no timeout config.

**Comment by jakubdyszkiewicz** [comment]
Hey, you are right. Timeout is applied on inbound connection to Envoy so even that the destination is unknown and will go through passthrough cluster, default 15s timeout is still applied.

Unfortunately, this setting is not yet natively configurable yet https://github.com/kumahq/kuma/issues/3274
TCP will work because there is no request timeout, but you will get less stats. Let me know if having `tcp` is a blocker, we can figure out ProxyTemplate in the meantime.

Thanks for reporting, closing this issue in favor of #3274

**Comment by yyefet** [comment]
"we can figure out ProxyTemplate in the meantime" ...    Can you supply an example proxy template that modifies the request timeout?  15s is too low for us.
