### ISSUE TITLE
Set Gateway API `Gateway` status

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#3617]
### Description

https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.GatewayStatus

- [x] Conditions
  - [x] [Route related info](https://github.com/kumahq/kuma/pull/3711)
- [x] Addresses
- [ ] Listener conditions
  - [x] [ResolvedRefs & Ready](https://github.com/kumahq/kuma/pull/3609)
  - [ ] [Conflicts](https://github.com/kumahq/kuma/pull/3954)
  - [ ] [Detached](https://github.com/kumahq/kuma/pull/3956)

Outstanding issues:

- [x] ~Decide how to handle non-unique listener names, see https://github.com/kumahq/kuma/pull/3609#discussion_r781738410~, handled upstream https://github.com/kumahq/kuma/pull/3609#discussion_r782615931

**Comment by jpeach** [comment]
>   Decide how to handle non-unique listener names, see feat(gateway): initial support for GatewayStatus.Listeners #3609 (comment)

I was totally wrong on this one. Listener names must be unique within a Gateway, and the CRD has listmap annotations so that the API server enforces that. So it *is* safe to assume they are unique.

**Comment by michaelbeaumont** [comment]
Closing now that the major pieces are done. There are future TODOs that will come with #3450 and https://github.com/kumahq/kuma/issues/3618
