### ISSUE TITLE
include usage examples into `--help` messages of all `kumactl` commands

### ISSUE THREAD

**Issue by yskopets** [kumahq/kuma#362]
### Summary

* include usage examples into `--help` messages of all `kumactl` commands

### Steps To Reproduce

1. Run
```
kumactl config control-planes add --help
```
the output will be
```
Add a Control Plane.

Usage:
  kumactl config control-planes add [flags]

Flags:
      --address string   URL of the Control Plane API Server (required)
  -h, --help             help for add
      --name string      reference name for the Control Plane (required)

...
```

### Expected behaviour

* `--help` message should include `Examples:` section, e.g.

```
kumactl install database-schema --help
```

```
Install Kuma schema on DB.

Usage:
  kumactl install database-schema [flags]

Examples:

1. kumactl install database-schema --target=postgres | PGPASSWORD=mysecretpassword psql -h localhost -U postgres

2. sql_file=$(mktemp) ; \ 
kumactl install database-schema --target=postgres >$sql_file ; \
psql --host=localhost --username=postgres --password --file=$sql_file ; \
rm $sql_file

Flags:
  -h, --help            help for database-schema
      --target string   Database type: one of postgres (default "postgres")
...
```

**Comment by Gabitchov** [comment]
I would like to help for this one.

**Comment by yskopets** [comment]
@Gabitchov Hi!

Awesome! Please go ahead!

If you have any questions, we're always ready to help on our [Slack](https://kuma.io/community/)

**Comment by Gabitchov** [comment]
Did you have already an idea how I can takle this issue? What I analysed,it's that there is no help set with Cobra framework(cf. https://github.com/spf13/cobra#help-command). Do I have to follow this idea?

**Comment by yskopets** [comment]
@Gabitchov Sorry, may be I'm not following you.

As part of this issue we need to set `Example` field on every cobra command. E.g.

```
cmd := &cobra.Command{
	Use:   "database-schema",
	Short: "Install Kuma schema on DB",
	Long:  `Install Kuma schema on DB.`,

	Example: `1. kumactl install database-schema --target=postgres | PGPASSWORD=mysecretpassword psql -h localhost -U postgres`,

	RunE: func(cmd *cobra.Command, _ []string) error {
            ...
        },
}
```

Then, users of `kumactl` will be able to see that example by running

```
kumactl install database-schema --help
```  

or 

```
kumactl help install database-schema
```

So, this task doesn't require any development. Only documentation.

**Comment by Gabitchov** [comment]
@yskopets Thanks for your explanation, I didn't know this approach to add help in Cobra command.

**Comment by devadvocado** [comment]
Hey @Gabitchov, just checking in to see if you need any help or clarification

**Comment by jakubdyszkiewicz** [comment]
> Triage: if we do this, let's do it organically as we go
