### ISSUE TITLE
Consistent Docker containers

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#3663]
### Description

We could use some consistency for our Docker containers with some explanation

* Users are created and used in kuma-cp, kuma-init and kumactl, but not in kuma-dp and kuma-prometheus-sd. Why?
* User IDs of created users are not consistent
* ADD vs COPY - is there a reason for mixing those two?
* Explain why we are installing a package. For example, in `kuma-init` we install iproute2, but why?
* Explain why we are using ubuntu as base image for kuma-init
* Do we need to add Kuma CP settings to `/etc/kuma` if we are not using it? If this serves as example, it should not be in `/etc/kuma`
* Why the CMD (and not ENTRYPOINT) is set to `/bin/sh` for kumactl container?

**Comment by slonka** [comment]
[WORK IN PROGRESS]

> Users are created and used in kuma-cp, kuma-init and kumactl, but not in kuma-dp and kuma-prometheus-sd. Why?

In general we should use non-root users to limit possible attack surface. Kuma-init just adds a user but does not use it 🤦. Kuma-dp now uses a user. And `kuma-prometheus-sd` has been removed.

> User IDs of created users are not consistent

There is some consideration about this for openshift ([1](https://developers.redhat.com/blog/2020/10/26/adapting-docker-and-kubernetes-containers-to-run-on-red-hat-openshift-container-platform#), [2](https://docs.openshift.com/container-platform/4.11/openshift_images/create-images.html)).

> ADD vs COPY - is there a reason for mixing those two?

We should use copy for files - https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#add-or-copy 

"For other items (files, directories) that do not require ADD’s tar auto-extraction capability, you should always use COPY."

Also this makes me think we should use some sort of a linter for dockerfiles:
- https://github.com/replicatedhq/dockerfilelint
- https://github.com/hadolint/hadolint
- something else?

> Explain why we are installing a package. For example, in kuma-init we install iproute2, but why?



> Explain why we are using ubuntu as base image for kuma-init

> Do we need to add Kuma CP settings to /etc/kuma if we are not using it? If this serves as example, it should not be in /etc/kuma

> Why the CMD (and not ENTRYPOINT) is set to /bin/sh for kumactl container?
