### ISSUE TITLE
Support Gateway API TLS Gateway listeners

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#3679]
### Description

We already have support for TLS in Kuma Gateway, we just need to translate the GAPI TLS configuration.

#### `kubernetes.io/tls` secrets

Right now Kuma reads all secrets using the [secret store](https://github.com/kumahq/kuma/blob/master/pkg/plugins/secrets/k8s/store.go). On Kubernetes, this store is limited to reading secrets of type `system.kuma.io/global-secret`/`system.kuma.io/mesh-secret` and _only_ from the `kuma-system` namespace.
Additionally, the Gateway implementation reads all the data stored in a secret as a PEM block which makes it incompatible with `kubernetes.io/tls`.

**Comment by jpeach** [comment]
> Additionally, the Gateway implementation reads all the data stored in a secret as a PEM block which makes it incompatible with `kubernetes.io/tls`.

AFAIK all ingress controllers require TLS secrets to be serialized PEM objects. The upstream docs are confusing and might be wrong.

**Comment by jpeach** [comment]
> Right now Kuma reads all secrets using the [secret store](https://github.com/kumahq/kuma/blob/master/pkg/plugins/secrets/k8s/store.go). On Kubernetes, this store is limited to reading secrets of type `system.kuma.io/global-secret`/`system.kuma.io/mesh-secret` and _only_ from the `kuma-system` namespace.

The gateway controller should use native Kubernetes APIs to read secrets and obey ReferencePolicy restrictions for cross-namespace references. It will need to copy gateway secrets up to Kuma secrets in the `kuma-system` namespace. kuma-cp will need cluster-wide access to read secrets (which is one of the arguments for making this a separate controller).

**Comment by michaelbeaumont** [comment]
> It will need to copy gateway secrets up to Kuma secrets in the kuma-system namespace. kuma-cp will need cluster-wide access to read secrets (which is one of the arguments for making this a separate controller).

What's preventing us from just having the Kuma Gateway implementation read the secrets directly via the Secrets store then? Instead of copying secrets around? Kuma is statically limited to only read from the `kuma-system` namespace but there's nothing preventing us from exposing a way to read from a secret a specific namespace, like interpreting `secret: namespace.name`.

**Comment by jpeach** [comment]
> What's preventing us from just having the Kuma Gateway implementation read the secrets directly via the Secrets store then?

I don't think there's anything that technically prevents this, but I'd prefer to keep the Gateway API controller as a distinct layer on top of Kuma, and using the Kuma secrets store binds it into the kuma-cp server.

**Comment by jakubdyszkiewicz** [comment]
I agree with @jpeach that it's better to copy the secrets. I like the argument of Gateway API being later on top of Kuma, but here are the more practical reasons that I can see:

1) Mesh hash / reconciliation trigger. We trigger XDS regeneration if any mesh secret has changed. How do we detect if some Kubernetes secret has changed? We need to distinguish which secret from all secrets in the cluster is Kuma secrets.
We can ask users for explicitly labeling/annotating secrets (for example with kuma.io/mesh or some other thing), but that break the conformance.
2) kumactl/API/(+GUI in the future) visibility. I like that all Kuma secrets are visible in kumactl/API, it's convenient. In case of mixed secrets, we again need some indication which are Kuma secrets.
3) "auto mesh". How to support mesh in Gateway is broader topic, but if we copy the secret, we can explicitly set `kuma.io/mesh` for the user. Imagine that mesh is defined on Gateway or even on GatewayClass. Why user would need to remember about putting mesh on secret too if we can do this for them when we are converting a resource.
4) A bit farfetched but - abstract the Kuma secret standard. If we change the way how we do Secrets or Gateway API does, we can automatically convert it.
5) If we support secrets from different namespaces directly, we have to expose this in resource store and policies. I worry that we may accidentally expose this for other things like provided CA etc.
