### ISSUE TITLE
Smooth the Gateway API installation experience for Kuma 

### ISSUE THREAD

**Issue by jpeach** [kumahq/kuma#3702]
### Description

To use Gateway API with Kuma, users need to perform a number of steps:

1. Install the right Gateway API CRDs
2. Install Gateway API validating admission controller
3. Create a "kuma" GatewayClass 

It would be useful to figure out some installation tooling that smooths this over for Kuma users, while being cognizant that the cluster might also have other gateway controllers.

xref https://github.com/kubernetes-sigs/gateway-api/discussions/934

**Comment by jakubdyszkiewicz** [comment]
## Step 1 - Install Gateway API CRDs
1. Option 1 - Install manually
Kong does it with kustomize from official link
Will this be embedded in Kubernetes in the future?
 
2. Option 2 - Embed into our HELM crds and install conditionally
Cons: Maintaince?

4. Option 3 - HELM hook + kumactl install gateway-crd that goes to the internet
Pros: Simple implementation
Con: Is it safe to install some YAML fetched over network?

## Step 2 - Install Gateway API validating admission controller
1. Option 1 - opt-in with kumactl arg / HELM value
2. Option 2 - Install by default with Ignore hook

## Step 3 - Create a “kuma” GatewayClass
1. Option 1 - Install manually
2. Option 2 - Automatically create if Gateway feature is enabled


[Using Gateway API (v1alpha2) with Contour](https://projectcontour.io/guides/gateway-api/)
[Using Gateway API - v2.2.x | Kong Docs](https://docs.konghq.com/kubernetes-ingress-controller/2.2.x/guides/using-gateway-api/)


triage: We decided to go with option 1 for all steps for now. We can iterate on that
