### ISSUE TITLE
Switch gateway build flag to be a feature flag

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3722]
### What happened?

We currently only build gateway with a build flag.
We should instead use a feature flag wether or not gateway is enabled.
The flag should probably be a kuma-cp config like: `--preview-gateway`

**Comment by michaelbeaumont** [comment]
We add some RBAC stuff to the Helm chart for Kubernetes, it might be a good idea to only add that if the feature flag is used on `kumactl` (right now it's _always_ added).
