### ISSUE TITLE
Use hadolint for linting Dockerfiles

### ISSUE THREAD

**Issue by tharun208** [kumahq/kuma#3725]
### Description

Since kuma repo has a number of docker files. can we use [hadolint](https://github.com/hadolint/hadolint) to lint/error check the docker-files and include the above through a make target ?. I also understand that there is no use in using this linting in ci/or the make target as there are no frequent changes to existing docker files or the addition of new ones. Maybe, a PR to fix the existing lint failures?

**Comment by lahabana** [comment]
xref #3663

**Comment by slonka** [comment]
done via #3663
