### ISSUE TITLE
include "debug info" in `metadata` field of Envoy objects, e.g. Listener, Cluster, etc

### ISSUE THREAD

**Issue by yskopets** [kumahq/kuma#373]
### Summary

* to be able to trace why generated Envoy configuration looks the way it is, it would be helpful to have "debug info" injected into `metadata` field of Envoy objects, e.g. `Listener`, `Cluster`, etc
* it should be possible to enable "debug info" at `Dataplane` level
* such information could be used by devs/admins for troubleshooting
* such information could be used by UI tools to explain Envoy config to the end users

**Comment by jakubdyszkiewicz** [comment]
Can you provide some examples how this debug info in metadata would look like?

**Comment by jakubdyszkiewicz** [comment]
> Triage: closing in favor of https://github.com/kumahq/kuma/issues/4053
