### ISSUE TITLE
kumactl support for inspect api

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3730]
### Description

We now have 2 new apis (dataplanes affected by a policy and policies applying to a dataplane) to troubleshoot policy matching.
We should add kumactl commands for this.

**Comment by tharun208** [comment]
@lobkovilya @lahabana I like to work on one of the APIs ( endpoint for returning policies by data plane ).

**Comment by lahabana** [comment]
I believe @lobkovilya is already working on this so just make sure you 2 don't step on each other's toes
