### ISSUE TITLE
(charts) service prometheus annotations are wrong

### ISSUE THREAD

**Issue by gardun0** [kumahq/kuma#3737]
### What happened?

Hello,

There's an issue about the annotations set within the control plane service for metrics scrapping, it's configured [here](https://github.com/kumahq/kuma/blob/e733780cba4bd69bd8ef3e12b46b5993e11cb888/deployments/charts/kuma/templates/cp-service.yaml#L9), and has a wrong port configured.

Also i believe it will be nice to have the ability to add some custom annotations in it too.

**Comment by lahabana** [comment]
What port would you expect to be there?
I don't seem to be able to reproduce this issue.

**Comment by lahabana** [comment]
Closing as we're not getting more info
