### ISSUE TITLE
automate testing of `Getting Started` workflow

### ISSUE THREAD

**Issue by yskopets** [kumahq/kuma#374]
### Summary

* as part of `kuma-release` workflow
  * for each supported platform
    * test workflow describe in `Getting Started`
      * download artifact (`wget ...`)
      * unarchive it (`tar xvzf ...`)
      * check release version (`kumactl version`, `kuma-cp version`, `envoy --version`, etc)

**Comment by jakubdyszkiewicz** [comment]
We have E2E tests with such scenarios. Closing.
