### ISSUE TITLE
Support for imagePullSecrets in the Helm chart

### ISSUE THREAD

**Issue by scottslowe** [kumahq/kuma#3751]
### Description

The Helm chart does not currently support the ability to add imagePullSecrets when pulling the Kuma images from a private repository that requires authentication. Customers mirroring the Kuma images to a private repository are likely to need this support in the Helm chart.

**Comment by johnharris85** [comment]
/assign

Few options / questions here:

1. Do we want the ability to specify different `imagePullSecrets` for the cp, cni, ingress etc? Or just blanket all the same?
2. If no, do we want to just add the `imagePullSecrets` to the Service Account? Or specify on each deployment / daemonset?

**Comment by scottslowe** [comment]
My 2 cents: if a customer is mirroring the images to a private repository, then it's probably likely to be a single private repository and therefore a single `imagePullSecrets` that blankets all the components would be sufficient. My initial thought would be to specify on each Deployment/DaemonSet, but I'm open to using the Service Account instead.
