### ISSUE TITLE
Avoid depending on specific version in Bootstrap API

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#3756]
### Description

In https://github.com/kumahq/kuma/pull/3739 we parse response from bootstrap server to get AdminPort, this means we're depending on specific Bootstrap proto. 

As noted in https://github.com/kumahq/kuma/pull/3739#discussion_r791864473, we can introduce BootstrapResponse type and return bootstrapVersion and adminPorts in the separate fields.

**upd**: apparently link to the resolved comment doesn't work as expected, so copying @jakubdyszkiewicz comment right here:
> I'm slightly concerned that we are tying the logic here to API V3. In the case of API V4, we will need to fix it. I think the better solution would be to have a response in JSON format like this

> {
  "bootstrapVersion": "v3",
  "bootstrapBytes": "...", # inline string that we dump to the file
  "adminPort": 1234
}
> This way we don't have a dependency on the Bootstrap version and we can pass additional metadata.
The alternative is also to respond with an extra HTTP header that indicates the port.

> However, that's a pretty substantial change to already big PR. I think we can postpone it.

**Comment by jakubdyszkiewicz** [comment]
API v4 is not happening. We also have now additional values next to bootstrap itself (just like described above) so we can use it if needed
