### ISSUE TITLE
KDS Reconciles all DP related insights

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3783]
### What happened?

I think something is wrong with reconciliation of insights. At the beginning I thought it's only related to Zone{In,E}gressInsights, but it looks like it's for all dataplane related insights.
I went to the doctor and forget to stop my CPs and have a lot of updates (every 2.5 minutes).

![image](https://user-images.githubusercontent.com/702355/151997048-c957d4a2-e562-465b-beea-167e1b436d07.png)

This shouldn't happen if no change happen on the cluster

**Comment by parkanzky** [comment]
These inherit from DataplaneInsights, which has the field - 

```
  // Generation is an integer number which is periodically increased by the
  // status sink
  uint32 generation = 7;
```

Logging the objects it is evident that this is, indeed, increasing on every sync and appears in the `GetSpec()` output we compare to decide whether a change occurred.

May need to handle this differently.

**Comment by lahabana** [comment]
Ho this was introduced with: https://github.com/kumahq/kuma/pull/2526 which makes sense... Should we remove the generation in the KDS code to avoid syncing things that do not really matter outside of the local zone?
@jakubdyszkiewicz @lobkovilya WDYT?

**Comment by lahabana** [comment]
Maybe there's something to be done with the ResourceMapper to strip this info?
