### ISSUE TITLE
ExternalService - TLS cert/key from k8s Secret - which type?

### ISSUE THREAD

**Issue by pxpnetworks** [kumahq/kuma#3808]
### What happened?

Hi!
I'm trying to add TLS context to an external service however i'm stuck how to actually provide the clientCert and clientKey from a Secret.

In the docs it says Secret and i see two different Secret names are used for clientCert and clientKey but as far as i know a Secret type kubernetes.io/tls must contain both tls.cert and tls.key in data.

Can you point me to more specific example how to derive them from the Secret objects? Thanks! (PS config below)

```
    tls:
      enabled: true
      allowRenegotiation: false
      sni: pt2fw.logs-processing.svc.cluster.local
      clientCert: 
        secret: client-cert
      clientKey: 
        secret: client-cert
```
```
apiVersion: v1
data:
  tls.crt: LS0tLS............
  tls.key: LS0tLS1CR.............
kind: Secret
metadata:
  creationTimestamp: "xxxxxxxxxx"
  name: client-cert
  namespace: ptx
  ownerReferences:
  - apiVersion: bitnami.com/v1alpha1
    controller: true
    kind: SealedSecret
    name: client-cert
    uid: xxxxxxxxxxx
  resourceVersion: "xxxxxxx"
  uid: xxxxxxxxxxxxxxx
type: kubernetes.io/tls
```

BR,
Stoyan

**Comment by pxpnetworks** [comment]
Oh.., i see :) thanks for the tip! 
I just wonder now if I can still use SealedSecrets with "type: system.kuma.io/secret" though... have to check this later.

**Comment by michaelbeaumont** [comment]
@pxpnetworks That'd be good to know, report back whether it works!

**Comment by lahabana** [comment]
@pxpnetworks any updates?

**Comment by michaelbeaumont** [comment]
@pxpnetworks We're going to close this issue now, definitely let us know if you have updates on SealedSecrets!
