### ISSUE TITLE
Keep a record of the built and vendored `kuma-gui` commit

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#3863]
### Description

We update `kuma-gui` by pulling the latest version from `master` but it's not possible to tell from `kuma` which commit is actually in use.
We should record this (a la `go.sum`)

**Comment by michaelbeaumont** [comment]
@lahabana you mean not vendored at all? Yeah that's also a good option

**Comment by lahabana** [comment]
Triage: Vote is to not vendor it

**Comment by lahabana** [comment]
Discussion about where gui should live in: https://github.com/kumahq/kuma/pull/4338

**Comment by lahabana** [comment]
Depends on: https://github.com/kumahq/kuma-gui/issues/367

**Comment by kleinfreund** [comment]
One can now look up the commit in use by looking up the latest commit with the header `chore(deps): bump kuma-gui`. Its body includes the Kuma GUI commit hash.
