### ISSUE TITLE
Datadog backend for `TrafficMetrics`

### ISSUE THREAD

**Issue by subnetmarco** [kumahq/kuma#3867]
### Description

Per title.

**Comment by lahabana** [comment]
Is this a trafficMetrics backend type? We already have tracing support for datadog.

**Comment by lahabana** [comment]
This is part of a larger discussion WRT otel and if we should support each backend or just rely on otel magic.

**Comment by lahabana** [comment]
Deal with it in: https://github.com/kumahq/kuma/issues/5708
