### ISSUE TITLE
Fix flaky RateLimit tests and reenable them

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#3874]
### Description

The RateLimit tests on Universal were disabled with https://github.com/kumahq/kuma/pull/3871 because of the flakiness of the way we check whether the RateLimit is enforced. We should investigate how to test the RateLimit in a non-flaky way and then reenable these tests.

**Comment by michaelbeaumont** [comment]
The final test with external services is being flaky, especially for some reason since #3967

**Comment by lahabana** [comment]
We need to check if this ticket can be closed now that a patch has landed
