### ISSUE TITLE
Allow mutual authentication between zonal and global control planes

### ISSUE THREAD

**Issue by mbyio** [kumahq/kuma#3884]
### Description

Currently, zonal control planes can authenticate the global control plane if you share the CA certificate served by the global control plane with the zones. But currently there is no way to authenticate the zonal control planes. This means that anyone with network connectivity to the global control plane can connect and add themselves as a new zone. We should be able to authenticate both sides of the connection, perhaps using mutual TLS or an API key or something similar.

**Comment by lahabana** [comment]
Triage: it's not a priority atm for the team but we'll accept the contrib :)

**Comment by felderi** [comment]
This is supported in Kong Mesh:  https://docs.konghq.com/mesh/1.6.x/features/kds-auth/

**Comment by cmulk** [comment]
I also am looking for this feature, this is currently preventing me from being able to use kuma. I understand Kong has this as a premium feature but this seems like an essential security requirement. (Doesn't allowing unauthenticated zones basically undermine all the benefits of mTLS data planes?)

In the mean time, does anyone have any third-party extensions or workarounds they are using to solve this problem of authenticating new zones in a multi-zone mesh? I would love to hear any feedback!

**Comment by mbyio** [comment]
FYI I no longer use Kuma/Kong Mesh, so I'm fine with closing this issue.
