### ISSUE TITLE
Rethink CHANGELOG.md

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#3894]
### Description

As it stands, `CHANGELOG.md` contains a lot of changes uninteresting to most people.
A commit-by-commit view can easily be obtained using `git` if necessary or even the GitHub UI. 

We have Release Notes that highlight the "high level changes".
IMO `CHANGELOG.md` should be somewhere in the middle. It should be the place to start looking for users to see what new features they can use, bugs were fixed or breaking changes they need to watch out for (and can include links to `UPGRADE.md` for more info)

I suggest adopting a format like [Keep a Changelog](https://keepachangelog.com/en/1.0.0/) for readability. We can also automate the generation of this file from commit messages or PR labels.

**Comment by lahabana** [comment]
I looked at: https://github.com/Kong/changelog-generator
It has the benefit of taking the info from the PR rather than the commit which enables us to fix it if it's not correct.

Jakub also suggested the the UPGRADE.md could also be generated at the same time which I think makes sense.

**Comment by lahabana** [comment]
See #4135

**Comment by lahabana** [comment]
This looks good enough now. Closing this
