### ISSUE TITLE
Support urlRewrite in MeshGatewayRoute

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3908]
### Description

It's one of the most common use cases in gateways
GatewayAPI does it this way: https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPURLRewriteFilter

**Comment by wjrbetts** [comment]
We would really like to see this, specifically for removing a path prefix after matching on it.
