### ISSUE TITLE
Ability to set custom configuration on the sidecar container

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3925]
### Description

Currently we've been asked for: `SecurityContext` I believe it's not going to be an isolated event. Can we do something flexible?

**Comment by jakubdyszkiewicz** [comment]
Waiting for feedback / more info from user that reported this problem

**Comment by johnharris85** [comment]
I've come across the need for custom volume mounts as well. Would be good to have some kind of ~template override system.

**Comment by lahabana** [comment]
Decided to just stick with exposing `SecurityContext`

**Comment by johnharris85** [comment]
We probably need to revisit this (after this week) @lahabana, there have been a number of cases recently where additional sidecar customization is required for various reasons. 

One specific use case that came up was being able to add preStop hooks (as a hack to drain envoy prior to application shutdown).

**Comment by subnetmarco** [comment]
@lahabana let's take a look at this issue, since it's also an FTI.

**Comment by lahabana** [comment]
xref: https://github.com/kumahq/kuma/issues/2213

**Comment by lahabana** [comment]
xref: #1920 customizing envoy flags is not directly there but it's something to keep in mind too

**Comment by konczbenedek** [comment]
Just to confirm my previous comment, I have set up a Mutating Admission Webhook which modifies the security context of the kuma-init container to `runAsNonRoot` as `false` once added to the pod. This indeed solved the init error (non-root policy break).

**Comment by lahabana** [comment]
@parkanzky is working on a proposal for this

**Comment by parkanzky** [comment]
We were using this issue to track the proposal and have another one to track the implementation - https://github.com/kumahq/kuma/issues/4273

There is consensus on the proposal, so will close this as soon as doc PR is merged. https://github.com/kumahq/kuma/pull/4241
