### ISSUE TITLE
Make VirtualOutbound work cross Zone

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3927]
### Description

VirtualOutbound currently do not fully work for cross zone traffic.

This should be improved.

**Comment by lahabana** [comment]
This is required for doing pod addressability across zones

**Comment by istar2metal** [comment]
Hi, any news? Currently no idea to run kafka cluster in cross-zone kuma mesh :(

**Comment by lahabana** [comment]
Hey! Still something that needs to happen but noone is working on it right now.

**Comment by jimmidyson** [comment]
Still relevant for me!

**Comment by lahabana** [comment]
xref https://github.com/kumahq/kuma/issues/4741

**Comment by jakubdyszkiewicz** [comment]
> Triage: We need to take ZoneIngress into account in available services as well as generate filter chain matches in this ZoneIngress
