### ISSUE TITLE
make health checks part of the default configuration for dataplanes

### ISSUE THREAD

**Issue by yskopets** [kumahq/kuma#393]
### Summary

* at the moment, default configuration for dataplanes doesn't include health checks
* without health checks (or, alternatively, without health statuses delivered via `EDS`), `Envoy` cannot exclude a non-responsive upstream endpoint from the list of valid targets for load balancing
* there are several ways how `Envoy` can be configured to obtain health statuses for upstream endpoints
  * `Envoy` can do "active" health checks
    *  for TCP it means that `Envoy` will periodically try establishing a connection
  * `Envoy` can do "passive" health checks
    *  for TCP it means that `Envoy` will be remembering statuses of recent connection attempts
  * `Envoy` can receive health statuses from the Control Plane as part of `EDS` API

### Expected behaviour

First stage/iteration:
  * we need to enable a combination of "active" and "passive" health-checking out-of-the-box
  * we need to give users an option to turn off "active" checks
    * TBD: what resource should we use for that ? This is a setting per `service` as a whole, while we only have `Dataplane` resource

To be added later:
  * we could additionally use `EDS` path on `k8s`
  * we could additionally use `EDS` path on `universal`. For that, we need to give users a way to manually provide endpoint statuses
    * e.g., by filling in a respective field in the `Dataplane` resource

Outstanding questions:
  * What should the user experience be to turn on/off health checks? Should we re-visit `ServiceProfile`s?

**Comment by jakubdyszkiewicz** [comment]
We've got HC as an opt-in. This should be a conscious decision of user to enable them since they may generate a lot of traffic.
