### ISSUE TITLE
Rewrite compatibility matrix test

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#3946]
### Description

The compatibility matrix test is quite complex and we should rewrite it so that it doesn't break all the time.

Our current strategy is to have a compatibility matrix so we have a central place in which we define which version of Kuma expects a specific version of Envoy. 
https://github.com/kumahq/kuma/blob/e1a88c3a3b95f7913ec94d393d2edcdb7cac0001/pkg/version/compatibility.go#L18

The whole point of this is to detect if by accident we use an incompatible version of Envoy.

The alternative is to embed this information into Kuma DP.
Kuma DP will have a hardcoded expected version of Envoy.
On Kuma DP start, it will check it for version compatibility and in case of incompatibility, we embed this information into DataplaneMetadata (through bootstrap).
Next, we save this information in DataplaneInsight and we can present it in the GUI.

**Comment by parkanzky** [comment]
@lahabana Should "DataplanMetadata" above actually read "DynamicMetadata" ?

**Comment by lahabana** [comment]
@jakubdyszkiewicz is your man he edited the issue with this info :)
