### ISSUE TITLE
Revamp logging for XDS

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4033]
### Description

XDS is the most important element of the CP, we need to do a better job at logging. Look at the high level of this component and list all the things that should be logged at INFO level, for example
* data plane proxy connected
* data plane proxy disconnected
* config sent
* config acked/nacked

Figure out logs on debug level (more details about XDS configuration).
Watch out for secrets.

**Comment by lahabana** [comment]
xref #2400 might be useful to add some logging to api-server too
