### ISSUE TITLE
Allow specifying an environment variable to a file with the instance hostname

### ISSUE THREAD

**Issue by Tahvok** [kumahq/kuma#4037]
### Description

Currently kuma-dp is requiring us to configure the ip address or the domain (hostname) of the instance for each new instance that goes up.

We have a "baked" process. It means we create an image of a regular instance, that includes all configuration, including configuration of kuma-dp. Then we would like to use that image to bring up any amount of instances we need, basically each instance will go up with everything already configured (this process potentially saves time during up scaling).

Because everything already is supposed to be configured - there is no way for us to update the configuration of ip address or the domain of the instance for kuma-dp.

We had a similar issue with other services, and the simplest solution was to provide an environment variable to a service, that env var will point to a file with a string of the current hostname.

This will also make it possible to run kuma-dp on a universal instance as a container (non k8s) -  you can then mount the host /etc/hostname inside some path of kuma-dp, and then simply point the environment variable to the mounted file path.

**Comment by jakubdyszkiewicz** [comment]
Hey! Not sure if I understand the problem correctly, but wouldn't templating solve this? For example
```
cat dp.yaml
type: Dataplane
mesh: default
name: {{ name }}
networking:
  address: {{ address }}
  inbound:
  - port: 8000
    servicePort: 80
    tags:
      kuma.io/service: backend
      kuma.io/protocol: http
  outbound:
  - port: 10000
    tags:
      kuma.io/service: redis

kuma-dp run \
  --cp-address=https://127.0.0.1:5678 \
  --dataplane-file=dp.yaml \
  --dataplane-var name=`hostname -s` \
  --dataplane-var address=192.168.0.2 \
  --dataplane-token-file=/tmp/kuma-dp-backend-1-token
```

You could also do something like
```
export MY_IP=127.0.0.01
...
kuma-dp run \
  --dataplane-var address=$MY_IP \
```

**Comment by Tahvok** [comment]
The process is as follows (simplified):
1. Create an instance
2. Docker run the service
3. Docker run kuma-dp
4. Take an image of the instance
5. Deploy how many instances you need from that image

Because the kuma-dp is being created only once at step 3, when we create the instances at step 5, the old configuration of the original instance will be used - including the env var configuration (as you have suggested) - and it will load with the old instance address, which will be incorrect.

**Comment by lahabana** [comment]
You need a dp for each instance you can't share dps between instances.

**Comment by lahabana** [comment]
@Tahvok did my last comment answer your question/issue?

**Comment by lahabana** [comment]
No more news so assuming this was solved. Please reopen if not
