### ISSUE TITLE
Ability to limit the number of DPPs in a mesh

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4038]
### Description

There are use-cases where mesh admins might want to limit the total numbers of DPPs in a mesh. This can be used to avoid an accidental deployment to bring the cluster to a halt.

**Comment by johnharris85** [comment]
Good first issue?

**Comment by jakubdyszkiewicz** [comment]
Mesh constraints sound like a good place to set this
https://github.com/kumahq/kuma/blob/master/api/mesh/v1alpha1/mesh.proto#L61

**Comment by gdasson** [comment]
I'd like to take a stab at this. Will reach out on slack if I hit road bumps. Thanks!

**Comment by lahabana** [comment]
Noone asked for this for a while
