### ISSUE TITLE
Observability whether the policy is applied on DP

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4053]
### Description

We introduced observability of what policies are matched on the DP, but we don't know if they were actually applied - meaning, if Envoy received the XDS configuration that includes the changes of X policy.

It's not trivial to solve because policy can modify different parts of the Envoy configuration.

We could attach `metadata` to Listeners and Clusters to indicate type, name and version of a resource.
This way, on demand we can fetch XDS config and interpret that X, Y, Z policy is applied with current config.

Another potential solution is to store in memory in CP what were the policies (name, type, version) used for matching for given XDS config version. If we receive ACK, we store this information in DataplaneInsight.
Then, we can aggregate this in MeshInsight or maybe in policy Status (that we don't have now) to have an overview of how many DPs received the config.

**Comment by lahabana** [comment]
I like the idea of DataplaneInsight as it's nice and simple (it's very similar to what we do with Certs and backend for rotation in the end)

**Comment by lahabana** [comment]
3 options:

1. Policy status: Each policy has a list of which DPs received the configuration (grouped by version)
2. DataplaneInsight: The dataplane info has knowledge of which policies were used to generated the latest ACKed config
3. Metadata: In listener and cluster metadata add info of policy name --> version

3 has some advantages:

- Clear what part of the config is being influenced by which policy
- Simpler to track (we generate this at the time we generate the config, no out of bound tracking).

How does that work for MeshGateway and ZoneIngress/Egress?

**Comment by jakubdyszkiewicz** [comment]
Didn't policy matching solve this?

**Comment by michaelbeaumont** [comment]
> triage: We have better insight into which policies affect an Envoy config but still don't know which policy has configured a given part of the Envoy config
> let's close this for now
