### ISSUE TITLE
Fix DeferCleanup in E2E tests

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4082]
### What happened?

An example for gateway HELM test
```
		Expect(NewClusterSetup().
			Install(Kuma(core.Standalone,
				WithInstallationMode(HelmInstallationMode),
				WithHelmOpt("experimental.meshGateway", "true"),
				WithHelmReleaseName(fmt.Sprintf("kuma-%s", strings.ToLower(random.UniqueId()))),
			)).
			Install(NamespaceWithSidecarInjection(TestNamespace)).
			Install(testserver.Install()).
			Setup(cluster)).To(Succeed())

		E2EDeferCleanup(func() {
			Expect(cluster.DeleteNamespace(TestNamespace)).To(Succeed())
			Expect(cluster.DeleteKuma()).To(Succeed())
			Expect(cluster.DismissCluster()).To(Succeed())
		})
```
DeferCleanup should be called first. Otherwise if `testserver.Install` fails, we won't cleanup Kuma and test namespace.
Fix this for all the tests in the project.

That means that we need to structure tests that we first deal with cleanup and then the setup.

Alternativly we could use AfterAll/AfterSuite.
For me, the more intuitive way of structuring test in a way that we write setup first and then cleanup.

**Comment by lahabana** [comment]
So what's the story here in the end?

**Comment by jakubdyszkiewicz** [comment]
The story is to migrate to AfterEach/AfterAll/AfterSuite.

Issue is still valid.
