### ISSUE TITLE
Support projected service account tokens

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#4121]
### Description

Kuma uses Kubernetes service account tokens (SAT) to identify dataplanes to the control-plane during bootstrapping. These tokens have no expiry. It is best practice / probably default soon for things to use projected service account tokens (PSAT) instead for pod identity. These tokens have a customizable audience field and TTL.

The issue with using PSAT for Kuma to authn against the CP now is that if an initial token is used, then is rotated (by the Kubelet), then the DP disconnects and has to re-connect, it will use the same (now invalid) initial token.

**Comment by lahabana** [comment]
> Triage: the trick here is that token is read once on startup and never re-read. There's something we'll need to figure out there.

**Comment by johnharris85** [comment]
The token is in the bootstrap section of Envoy config, which is not dynamically controllable afaik. Maybe Envoy's hot restart functionality would work here, if it reloaded the full newly-generated config? Then we could detect upcoming expiration in kuma, generate a new config and hot reload Envoy (to avoid connection drops). Other solutions would all require a 'fuller' Envoy restart as far as I could see and we'd drop connections momentarily.

**Comment by lahabana** [comment]
@jakubdyszkiewicz is the issue that the token is read once for the bootstrap request and we reuse the same for the whole lifetime of the envoy sidecar?
Is there anyway to do this restart without Envoy restarting? If not should we have the DP track the expiration and restart Envoy before it's expired. How do other folks manage this with Envoy?
