### ISSUE TITLE
Storage of autogenerated certs

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#413]
### Summary

Right now we autogenerate certificates for SDS server (only when they are not provided) and store them in `/tmp` directory. This is not ideal, because `/tmp` can be read by a different process.
We also want to autogenerate certs for dataplane token public server. We should choose better way to store those certs.

### Current ideas
1) Store autogenerated certs in ResourceStore (postgres/memory on universal)
2) Introduce concept of working directory

**Comment by subnetmarco** [comment]
Can these be stored in the new Secrets entity? @jakubdyszkiewicz

**Comment by nickolaev** [comment]
pkg/core/bootstrap/autoconfig.go:89

```go
func saveKeyPair(pair tls.KeyPair) (string, string, error) {
	crtFile, err := ioutil.TempFile("", "*.crt")
```
