### ISSUE TITLE
SIGTERM signal arrives first to kuma and stops all active application connections immediately

### ISSUE THREAD

**Issue by shahar-rel** [kumahq/kuma#4134]
### What happened?

Hi, we have applications that work with Kafka (MSK), we noticed that once pod is starting to shutdown (during autoscaling or deployment) the app container loses all active connections and the SIGTERM signal causes Kuma to close all connections immediately which cause data loss due to unfinished sessions (which doesn’t get closed gracefully) on the app side and after that we receive connection errors to the kafka brokers, 
is anyone have an idea how to make Kuma wait some time once it gets the SIGTERM signal to let the sessions close gracefully? 
or maybe any other idea ?

**Comment by lahabana** [comment]
Triage: We need to review how the termination happens. Technically what should happen is on pod shutdown: stop accepting new connection and the app pod will start shutdown which should finish outstanding requests/connections, once there's no more active connections the sidecar stops (or after a timeout).

**Comment by johnharris85** [comment]
Right now the issue (I think) is that containers are sent SIGTERMs in an unordered / simultaneous way. I think the way forward (initially) here would be to add preStop hooks (tough right now as the sidecar container configuration is not customizable, ref: #3925) to synchronize the shutdown order, and upon receiving a SIGTERM we could trigger Envoy to drain. Would also require the `TerminationGracePeriodSeconds` (or whatever it's called) on the pod to be aligned. There are a few moving pieces here but there might be something better we could add to improve the UX.

**Comment by shahar-rel** [comment]
Hi, thank you for helping.
What happens here is once the Kuma gets the SIGTERM signal it instantly closing all connections and doesn't wait for no more active connections. that is exactly the way we wish it would be. 
As you said, the sidecar container configuration is not customizable, so we can't add the preStop hooks to it.

**Comment by shahar-rel** [comment]
As I mentioned above, the sidecar container configuration is not customizable, so we can't add the preStop hooks to it.

**Comment by lahabana** [comment]
Yes @shahar-rel I'm not saying you can fix it :) Just adding notes for the person who will implement the fix :)
