### ISSUE TITLE
Gateway API Policy Attachment

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#4137]
### Description

Gateway API has published [a guide](https://gateway-api.sigs.k8s.io/v1alpha2/references/policy-attachment/) on how implementors can integrate existing "policy" support with Gateway API support. We should consider how this applies for Kuma.

**Comment by lahabana** [comment]
Triage: We should have a look at this. What we should answer is should we extend our policy matching to support the matching exposed in this document?

**Comment by michaelbeaumont** [comment]
This is now in discussion, with #4222 and revisions to the policy matching proposal

**Comment by michaelbeaumont** [comment]
Our current iteration on policies that moves us towards Policy Attachment is in https://github.com/kumahq/kuma/pull/4474.
