### ISSUE TITLE
Explore Interceptors instead of Managers

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4143]
### Description

as per comment https://github.com/kumahq/kuma/pull/4136#discussion_r843850578

**Comment by lahabana** [comment]
> Triage: the manager abstraction is not used on K8s at all which makes the behaviour potentially different. 2 options: relying on events or adding interceptor before calling the `Store` interface.
It's not completely clear what would be the best and this issue probably needs some experimenting with different solutions first.
