### ISSUE TITLE
Prometheus seems to crash with kuma-sd and multiple CP restarts

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4154]
### Description

With one cp instance and prometheus setup with kuma-sd (full setup there: https://github.com/kumahq/kuma-tools/pull/25).

I was doing tests and restarted the cp with `kubectl rollout restart -n kuma-system kuma-control-plane` and noticed that after a few tries prometheus would crash.

There's a single instance of the CP. I'm wondering if maybe there's a bug in the scraper but we should confirm here.

**Comment by jakubdyszkiewicz** [comment]
Cannot reproduce. Tried with
* K3D
* Google Cloud with the newest Kuma 1.7.0.
* Script linked in the issue
