### ISSUE TITLE
Bug? - Multiple entries for monitor on dashboard

### ISSUE THREAD

**Issue by wmnnd** [kumahq/kuma#4165]
### What happened?

I recently set up some site monitors with Kuma (v1.13.2) and it’s been working great so far. Thank you for your amazing work!

One thing I noticed today is that one of the monitors was showing up three times in my dashboard. Twice with the correct status ("Up") and once as "Down" with a timeout message.

All other numbers on the main dashboard are correct (reporting 7 sites as "Up" and 0 as "Down").

![Screenshot 2022-04-12 at 13-56-25 Uptime Kuma](https://user-images.githubusercontent.com/7488303/162957495-2700e2ee-da4a-4995-b97c-fdea91ca5316.png)
  
  
All three entries lead to the same monitor URL (`dashboard/4`) and on that page, the status changes that might have been behind the display bug on the main dashboard are visible:
![Screenshot 2022-04-12 at 14-00-39 Uptime Kuma](https://user-images.githubusercontent.com/7488303/162958376-ee45323f-2186-49b4-86ed-e508fb06ad3c.png)

**Comment by lahabana** [comment]
Thanks for the report @wmnnd. I'm not super familiar with this setup can you tell me a little more about it?
How are things configured? What is being monitored? Which endpoint?

Thanks!

**Comment by wmnnd** [comment]
Sure! I’m running Kuma 1.13.2 from the official Docker image. This monitor is a HTTPS endpoint with a heartbeat interval of 54 seconds.

**Comment by jakubdyszkiewicz** [comment]
Hey, this is Kuma the Service Mesh

Please report this in Uptime Kuma :) https://github.com/louislam/uptime-kuma
