### ISSUE TITLE
Parse error when running helm chart 1.6.0

### ISSUE THREAD

**Issue by wjrbetts** [kumahq/kuma#4171]
### What happened?

I get the following error when running kuma chart version 1.6.0.

` Error: parse error at (kuma/templates/_helpers.tpl:113): unexpected unclosed action in if`

My helm version is 3.8.1

**Comment by lahabana** [comment]
Interesting looking at: https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1649746498657799 it seems other users managed to make it work with helm > 3.8.0 and @michaelbeaumont's testing also shows this.
Can you double check your helm version?

**Comment by killerzwelch** [comment]
I had the same problem. Upgrading to latest helm solved it, thanks @lahabana
