### ISSUE TITLE
Ability to offload to Kuma sidecar the getting of JWT from an IdP

### ISSUE THREAD

**Issue by braghettos** [kumahq/kuma#4173]
### Description

As discussed here: https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1649873274317209 I would like to understand if the following use case - and related feature - would be interesting for the Kuma community.

The use case is based on security enforcement: let's say that microservice A wants to send a request to an authenticated API of microservice B. If the microservice A needs a JWT token from a IdP, the first solution would be to implement via application code the interaction with the IdP.

Since that Kuma provides mTLS and traffic policy, it would be great to offload this phase of getting the JWT token from an Idp to the Kuma sidecar instead of implementing it in the application.

I would like to get some feedbacks from the community!

**Comment by bdecoste** [comment]
Can you please provide more detail on the use-case this is intended to solve? Implementing an Envoy filter to generate and attach a JWT via an iDP is certainly possible but I am unclear on what this solves. I assume there would need to be a new policy that provides the iDP credentials per source service. I also assume there would need to be a JWT caching mechanism within the source so that the iDP isn't called for every request. Are you looking to do finer grained service-to-service auth beyond what mTLS provides (e.g. based on claims/scopes?) that is offloaded to the iDP and would need to be implemented as RBAC in the mesh?

**Comment by braghettos** [comment]
If an attacher gets access to the pod the mTLS and traffic policies are useless so yes I'm looking for a finer grained service-to-service auth exactly as you described. I also agree with your assumptions.

**Comment by bdecoste** [comment]
If an attacker got access to the pod they would also have access to the iDP credentials and would be able to generate a valid JWT. For finer grained auth, have you considered using OPA? You could write an OPA policy for the server side where the auth decision could be made based on any criteria in the request.

**Comment by braghettos** [comment]
What if I use one-time valid JWT token? If the idp is i.e. HashiCorp Vault then there is no need to store the token

**Comment by scottslowe** [comment]
@braghettos Do you _really_ want to have your microservice make a call to Vault to retrieve a JWT for every outbound service call? I would anticipate this would create a) a notable amount of latency; b) quite a bit of extra traffic; and c) quite a bit of load on the Vault infrastructure as your environment scales up. _Can_ it be done? Perhaps. _Should it be done?_ That's another question entirely. I think what @bdecoste is getting at is understanding the exact security risk you're trying to mitigate. I'm not sure that limiting lateral movement in the event of a Pod breach is a valid use case for introducing the overhead of obtaining and verifying JWTs for every single service-to-service call.

**Comment by braghettos** [comment]
I think that something like this would be really interesting: https://github.com/istio-ecosystem/authservice. I do understand that's for end-user requests but it could be adapted for microservice requests.

**Comment by lahabana** [comment]
Triage: is there a use-case other than defence in depth here?

**Comment by lahabana** [comment]
@braghettos @scottslowe WDYT?

**Comment by lukidzi** [comment]
@braghettos @scottslowe Do you have any thoughts on this?

**Comment by scottslowe** [comment]
I know that some users have use cases for this functionality, but it does come with some significant drawbacks/considerations.

**Comment by braghettos** [comment]
I moved the interaction with the IdP at the application level in front of the API Gateway.

**Comment by slonka** [comment]
Moving to pending so we can decide if we can close this.

**Comment by kleinfreund** [comment]
**Triage**: There don’t seem to be enough use cases for this. Feel free to comment to get this re-opened if you need this.
