### ISSUE TITLE
Kuma support for multi-zone service-mesh deployments in Flagger

### ISSUE THREAD

**Issue by mhumeSF** [kumahq/kuma#4174]
### Description

This might be redundant but cross-posting to track. Looking for kuma mesh when used in tandem with flagger to support multi-zone deployment mode. More details in the issue below.

https://github.com/fluxcd/flagger/issues/1170

**Comment by lahabana** [comment]
https://github.com/fluxcd/flagger/issues/1170 was closed because it was already possible so closing this :)
