### ISSUE TITLE
Improve logging for Unviersal E2E

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4187]
### Description

Right now logs are printed on stdout, but there is no way of inspecting logs container by container when using `test/e2e/debug-fast`.

Additionally, it should work in parallelized environment https://github.com/kumahq/kuma/pull/4164#discussion_r851205622

**Comment by jakubdyszkiewicz** [comment]
> Triage: Bart suggests using supervisord

**Comment by jakubdyszkiewicz** [comment]
closed with #4688

**Comment by jakubdyszkiewicz** [comment]
Reopening. The current solution has a problem that if the test process dies, we do not see further logs which makes debugging after test dies difficult.

**Comment by lukidzi** [comment]
@bartsmykla Has it been fixed in the newest version?
