### ISSUE TITLE
Mesh gateway listener forces clients to use ALPN

### ISSUE THREAD

**Issue by wjrbetts** [kumahq/kuma#4198]
### What happened?

The mesh gateway envoy listener gets the following filter_chain_match config when configured to terminate TLS:

```json
"filter_chain_match": {
  "transport_protocol": "tls",
  "application_protocols": [
   "h2",
   "http/1.1"
  ]
 }
```

This is coming from `kuma/pkg/plugins/runtime/gateway/filter_chain_generator.go:123`

The inclusion of the application_protocols means that the filter does not match for clients not doing ALPN. There is no other filter so their connection is closed.

This seems to be too restrictive when it comes to clients of the mesh gateway.

Is there any need for the filter chain match given that there is only one filter in the chain? If there is some reason to have it, could it be more relaxed, ie not specify application_protocols?

**Comment by jakubdyszkiewicz** [comment]
@michaelbeaumont what do you think about this?

Do we expect scenarios when we will be using ALPN to pick a proper filter chain on one listener?

**Comment by michaelbeaumont** [comment]
I think we shouldn't match on ALPN unless we only want HTTP2 traffic, [the envoy docs](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener_components.proto#envoy-v3-api-field-config-listener-v3-filterchainmatch-application-protocols) have a blurb about this as well
