### ISSUE TITLE
Not able to setup multizone cluster communication

### ISSUE THREAD

**Issue by kelvinwijaya** [kumahq/kuma#4218]
### What happened?

Environment: kuma:1.5.x

Helm installation parameters in zone1- similarly for zone2 and global cp has also been installed with helm:
```
helm install kuma \
--namespace kuma-system \
--set controlPlane.mode=zone \
--set controlPlane.zone=zone1 \
--set ingress.enabled=true \
--set egress.enabled=true \
--set experimental.meshGateway=true \
--set cni.enabled=true \
--set cni.chained=true \
--set cni.netDir=/etc/cni/net.d \
--set cni.binDir=/opt/cni/bin \
--set cni.confName=10-calico.conflist \
--set cni.logLevel=info \
--set controlPlane.kdsGlobalAddress=grpcs://xx.xxx.xxx.xx:5685 \
--set controlPlane.logLevel=info kuma/kuma
```

Hi everyone. i am new to Kuma. I am getting some kind of issue when setting up multi-cluster deployment with 2 zones (e.g. zone1, zone2)

I can see that my kuma-egress-xxx pod logs in zone1 is showing some error:
```
[2022-04-26 06:48:07.489][20][warning][config] [source/common/config/grpc_subscription_impl.cc:126] gRPC config for type.googleapis.com/envoy.config.endpoint.v3.ClusterLoadAssignment rejected: malformed IP address: xxx.region.elb.amazonaws.com. Consider setting resolver_name or setting cluster type to 'STRICT_DNS' or 'LOGICAL_DNS'
```
I am not able to successfully make connection across from zone1 to zone2.
I tried to do some curl from one of the kuma-sidecar enabled pod in zone1 to test the respective services hosted in zone2 and I am getting connection reset:
```
/ $ curl http://helloworld_kuma-demo_svc_5000.mesh/hello -vvv
*  Trying 240.0.0.9:80...
* Connected to helloworld_kuma-demo_svc_5000.mesh (240.0.0.9) port 80 (#0)
> GET /hello HTTP/1.1
> Host: helloworld_kuma-demo_svc_5000.mesh
> User-Agent: curl/7.82.0-DEV
> Accept: */*
>
* Recv failure: Connection reset by peer
* Closing connection 0
curl: (56) Recv failure: Connection reset by peer
```

I have make sure that all the firewall connection has been open as I managed to reach the target zone (e.g. zone2) ingress successfully using telnet:
```
/ $ curl -v telnet://xxx.region.elb.amazonaws.com:10001
*  Trying 122.248.xxx.xxx:10001...
* Connected to xxx.region.elb.amazonaws.com (122.248.xxx.xxx) port 10001 (#0)
```
I have also make sure the helloworld deployment in zone2 has been deployed successfully and with sidecar enabled

The global controlplane dataplanes also have successfully populated service entries from zone1 and zone2

How do I fix this issue on : Consider setting resolver_name or setting cluster type to 'STRICT_DNS' or 'LOGICAL_DNS'

**Comment by lahabana** [comment]
Slack thread: https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1650956049134179

**Comment by lahabana** [comment]
@lobkovilya mentioned:
> It’s seems we support, but not for ZoneEgress. See pkg/xds/topology/dataplanes.go:71, I guess we should call it when generate zoneegress proxy

This seems correct. A workaround is to resolve the DNS manually and set: `kuma.io/ingress-public-address` and `kuma.io/ingress-public-port` on zone-ingress deployments.

We'll patch this to make this work correctly

**Comment by kelvinwijaya** [comment]
Thanks for the quick fix!
