### ISSUE TITLE
Graceful shutdown on Universal - HDS should include Envoy healthcheck

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4230]
### Description

HDS should also probe Envoy. When Kuma DP receives SIGTERM, it drains listeners and marks Envoy as unhealthy, HDS should mark this Dataplane as unhealthy in order to achieve a graceful shutdown.

**Comment by lahabana** [comment]
Done in: https://github.com/kumahq/kuma/pull/4246
