### ISSUE TITLE
Kuma policy for Adaptive concurrency

### ISSUE THREAD

**Issue by bbuddha** [kumahq/kuma#4237]
### Description

Would be a useful mesh enhancement  to have a kuma policy to implement adaptive concurrency. Envoy already supports this as a filter.
https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/adaptive_concurrency_filter

**Comment by jakubdyszkiewicz** [comment]
Make sense, we need a proposal first with a design for user-facing policy

In the meantime, you can always use ProxyTemplate to apply this by hand.
