### ISSUE TITLE
Graceful startup and shutdown of ZoneIngress / ZoneEgress

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4251]
### What happened?

ZoneIngress / ZoneEgress do not support `ready:true` on inbound therefore the graceful startup and shutdown are missing.

**Comment by lahabana** [comment]
> Triage: Yes of course makes sense :) Let's try to figure out how to implement this

**Comment by jakubdyszkiewicz** [comment]
Graceful shutdown works as long as there is a load balancer in front of all instances which is what usually is, especially on Kubernetes.

There is however a problem with a graceful startup. We include the instance to load balancer whenever it's ready, but we should only include it if it's ready has a configuration. It's not a problem for regular dps becuase the probe is on listener of app, so ready app = ready Envoy. Here it's different and it's the same problem for MeshGateway
