### ISSUE TITLE
Deprecate additional sidecar config options

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#4279]
### Description

Once the ability to customize the sidecar and init containers is merged, there will be some existing 'band aid' configuration settings that can be deprecated, this is to track the high-level list (and maybe decide if / how / when to do those deprecations).

Annotations:
- kuma.io/sidecar-env-vars
- kuma.io/service-account-token-volume

**Comment by lahabana** [comment]
Sidecar injection will be released in 1.7 so can't do this before 1.9

**Comment by afzal442** [comment]
hi @lahabana, wanna contribute here. 

Any help?

**Comment by lahabana** [comment]
Hey unfortunately it's a little too early to contribute this as our deprecation policy is to keep things around for 2 releases before we remove them. This is to enable users to migrate to the new way of doing things.

If you are looking for other simpler changes to do look at: https://github.com/kumahq/kuma/labels/good%20first%20issue
