### ISSUE TITLE
remove all non helm args in `kumactl install`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4287]
### Description

before the introducing of `--set` we used to add parameters for each option in kumactl. Now that this is not required anymore we should deprecated these.

!!! There are method params (.e.g --zone will set 2 helm params, we should keep these).

**Comment by lahabana** [comment]
Someone pointed out that sometimes "super args" (I think --cni is one) that would require multiple different helm options are nice addition.
If yes:

- Could these "super args" also exist in Helm?
- Should we repurpose this issue to track args that should be removed in favour on Helm options?

**Comment by jakubdyszkiewicz** [comment]
> Triage: there is no super args
