### ISSUE TITLE
Applying policies on the Zone CP

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4318]
### Description

It's more of a brainstorming issue.

Right now, all the policies are applied on Global CP and are synced to all Zone CPs. It's an easy 0-conflict model. However, it has a challenge. If the multicluster scenario in your org has a topology of cluster = team. The team needs to apply policies on the Global CP which means they need to have an access to this cluster including proper RBAC.

There are other advantages to being able to apply policies on Zone CP:
* better HA, if Global CP is down, you can manipulate policies. (technically possible today if you bypass webhook)
* tools that want to manage policies automatically like Flagger

The alternative would be to be able to apply policies on the Zone CP by specific teams. This creates multiple problems to solve.

### How to provide Mesh-wide policies?
Policies applied on Zone CP should only be executed in the given zone. How then apply policies that are applicable to all zones.
If we constraint the topology to "mesh can live in one zone", then it's not really a problem. But assuming this topology, why not deploy standalone Kuma in all clusters.

### Can policies be applied to Zone CP AND Global CP?
Even if policies are applied on Zone CP by teams, Mesh Operator should still have the last word when it comes to applying the setting.
One option is that Mesh Operator has an access to Zone CP and can modify policy, which solves the problem.
The second is that Mesh Operator can still apply policies on Global, which brings two-way sync problem.

### Two-way sync
The current way of managing resources is elegant, there is one source of truth. If we were to sync resources from Zone CP to Global CP, how do we handle it?
Policies applied on Zone CP should be synced to Global CP for visibility (not synced to other zones).
We could restrict those policies to not being managed from the Global CP (which eliminates conflicts problems etc.)

Another option would be to allow policies to be applied on both Global and Zone CP, but only managed from the CP it was applied on.
For example, teams may want to create policies that are relevant to their clusters and those are synced to Global CP for visibility. However, Mesh Operator can apply policies on Global CP that are synced to all the zones, but teams cannot manage them.

**Comment by lahabana** [comment]
> Policies applied on Zone CP should only be executed in the given zone. How then apply policies that are applicable to all zones.

Can't this be left to the user by adding the zone in the selector? The policy would be synced everywhere but only apply to DPPs in the zone they want.

My idea of this was to add a "controllingZone" to the mesh. Something like:

```
type: Mesh
name: foo
conf:
   controllingZone: "zone-1"
```

If a controllingZone is defined it's impossible to apply a change to a mesh from Global and can only be done from this zone. The advantage of this is keeping the single writer principle.
For modifying the policies when the Global is down we could have a "break-through" glass and global would overwrite if it needed.

One advantage of this "controllingZone" is that it makes moving from standalone to multi-zone easier (just sync your meshes and the rest will follow).

2 implications:

- mesh admin would require access to the "controllingZone" to things in the mesh
- meshes can only be managed from Global (But we're talking more and more about having very few things in the Mesh object anyway).

**Comment by lobkovilya** [comment]
Is it possible to change `controllingZone`? It feels like tricky to synchronise because `controllingZone` is changed on Global CP while it's checked on Zone CP
