### ISSUE TITLE
Error should be more explicit when product taglines aren't equal

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#4347]
### Description

When trying to add a control plane to Kong Mesh from a Kuma `kumactl` the error returned is: `Error: provided address is not valid Kuma Control Plane API Server`. We should make this clearer about what the issue is (this is the only place that error is returned).

**Comment by lahabana** [comment]
Indeed this should be clearer:

https://github.com/kumahq/kuma/blob/master/app/kumactl/pkg/config/validate.go#L45-L47
