### ISSUE TITLE
Internal resource which keeps info for each gateway that's reachable XMesh

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4359]
### Description

https://github.com/kumahq/kuma/pull/4274#discussion_r880710451

Currently to generate the gateway outbounds we need to iterate over all the gateways in all the meshes.
We should probably have a centralized object that keeps info from all gateways accessible XMesh and this would avoid having to read a lot of data to generate these outbounds.

**Comment by jakubdyszkiewicz** [comment]
> Triage: Is it really a problem with cached Mesh contexts?

**Comment by michaelbeaumont** [comment]
> Let's make sure we use the cached mesh context in gateway

**Comment by michaelbeaumont** [comment]
I'm gonna close this since we calculate this in the mesh context builder, cache that context and use that context to generate config for cross mesh outbounds
