### ISSUE TITLE
sidecar injection not working on arm / m1 macs on some versions of k3d

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#4429]
### What happened?

Kuma-demo (counter with redis) seems to not work on some versions of k3d and kind. It fails during transparent-proxy installation with errors like:

```
iptables-restore: unable to initialize table 'raw'
```

or

```
iptables-restore v1.8.4 (legacy): iptables-restore: unable to initialize table 'nat'
```

Versions that seem to work:
- k3d version v5.3.0 - k3s version v1.22.6-k3s1

Versions that do not work:
- k3d version v5.4.1 - k3s version v1.22.7-k3s1
- kind 0.12.0

Possible solutions:
* make the demo work regardless of version
* add note to docs which versions work

**Comment by lahabana** [comment]
@lukidzi @slonka was this solved in the end?

**Comment by slonka** [comment]
I re-checked `kind` with:

```
make kind/start
kumactl install demo | kubectl apply -f -
```

And it's working so 👍  to close this from my side.
