### ISSUE TITLE
Kuma Delete Zone doesn't delete dataplanes from this zone.

### ISSUE THREAD

**Issue by ravish-kumar-maersk** [kumahq/kuma#4434]
### What happened?

Kuma version 1.6.0

Post deleting zones, the corresponding resources like Dataplanes are **not** getting deleted automatically from Global CP. 
These Dataplanes are visible in Global CP GUI as **Offline**. 

Reference used - https://kuma.io/docs/1.6.x/deployments/multi-zone/#delete-a-zone

Manual deletion of dataplanes from Global CP will show error as, 
`Error from server (Forbidden): admission webhook "validator.kuma-admission.kuma.io" denied the request: Operation not allowed. Kuma resources like Dataplane can be updated or deleted only from the ZONE control plane and not from a GLOBAL control plane.`

**Comment by lobkovilya** [comment]
Did you delete `Zone` resource from Global? Like 
```
kubectl delete zone <zone-name>
```

**Comment by ravish-kumar-maersk** [comment]
Yes @lobkovilya . 

Command used at Global CP - 

`kubectl delete zone <zone_name>`

**Comment by lahabana** [comment]
I feel that 3 is the simplest but I'd love to have other opinions.

**Comment by michaelbeaumont** [comment]
> Kuma validates that Dataplanes could be deleted through the Zone cluster unless a service account name is not equal to system:serviceaccount:kuma-system:kuma-control-plane

Does the CP need to check this? Can it be handled via k8s RBAC?

**Comment by lobkovilya** [comment]
Decision-making process is little bit more complicated than just checking service account:
```go
// Note that this func does not validate ConfigMap and Secret since this webhook does not support those
func (h *validatingHandler) isOperationAllowed(resType core_model.ResourceType, userInfo authenticationv1.UserInfo) admission.Response {
	if userInfo.Username == h.cpServiceAccountName {
		// Assume this means sync from another zone. Not security; protecting user from self.
		return admission.Allowed("")
	}

	descriptor, err := h.coreRegistry.DescriptorFor(resType)
	if err != nil {
		return syncErrorResponse(resType, h.mode)
	}
	if (h.mode == core.Global && descriptor.KDSFlags.Has(core_model.ConsumedByGlobal)) || (h.mode == core.Zone && resType != core_mesh.DataplaneType && descriptor.KDSFlags.Has(core_model.ConsumedByZone)) {
		return syncErrorResponse(resType, h.mode)
	}
	return admission.Allowed("")
}
```
So I think it's not possible to handle via k8s RBAC
