### ISSUE TITLE
Update e2e tests to use new transparent-proxy

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4442]
### Description

It's ready we should switch CI to use it.

**Comment by lahabana** [comment]
Ideally we should run tests with the old and then the new version

**Comment by lahabana** [comment]
Both new transparent and eBPF

**Comment by lahabana** [comment]
exclude eBPF and v6 and universal. Should it run for the whole suite? Only do for `test/e2e-kubernetes` ? More thinking to do

**Comment by jakubdyszkiewicz** [comment]
Let's do CNI+ebpf tests since init container is not ready.

Let's try to do:
* Multizone with one zone that is run with ebpf
* e2e-kubernetes that runs with ebpf

**Comment by lahabana** [comment]
Some inflight work: https://github.com/jakubdyszkiewicz/kuma/commit/56b68b5d244bdbcd3f91458fa142dd48c1fe5850

**Comment by lahabana** [comment]
> since we want transparent proxy v1 deprecated eventually, do we want to run all tests with transparent proxy v2?
> we do not want to run any tests more than once in a eBPF/no-eBPF matrix, correct?
> we want to run tests with both new CNI and new CNI/eBPF

All these are good questions. Ideally running in a matrix would be good but costly. 
Note that at the moment ipv6 is not supported by the new TP.

Can we pick a few tests to still run with the old TP? Especially as it's still the default.

**Comment by lahabana** [comment]
Leave e2e-legacy with v1 use v2 for all the rest

**Comment by lahabana** [comment]
Let's just use the new iptables based Transparent-proxy so we can get ready to delete the old implem
