### ISSUE TITLE
Switch from cherry-picking from newest branch to merging from oldest branch

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4471]
### What happened?

Currently:
- Open PR against master (through label backport-to-stable)
- Cherry-pick master to release-X.Y
- Cherry-pick release-X.Y release-X.Y-1

Proposed change:
- Open PR against oldest branch (here release-X.Y-1)
- Merge oldest branch to release-X.Y
- Merge release-X.Y to master

Benefits:
- Have the same commit in multiple branches (as we're using merges instead of cherry-picks)
- Harder to miss a version (you put in the first affected branch and then automation takes it forward)

This will need a MADR as it's a pretty important change.
We would also need to figure out the transition period as older branches have diverged (likely do the old thing in the past, do the new thing from now).

**Comment by lahabana** [comment]
Maybe we should only merge during stabilization week and still rely on cherry-picking for cross branch changes.

In other words:

- Use `@mergify backport release-1.7 release-1.8` for fixes to younger releases
- On stabilization week work on the `release-1.8` branch and after the release merge release-1.8 with master

This will make changelog generation easier because everything in release-1.8 up until 1.8.0 is also on master.

**Comment by slonka** [comment]
I like this approach ☝️, it has the following benefits:
- we only work on fixes to release, no features "slip" to main branch
- no extra work to cherry pick things, wait for mergify to open PR
- if done correctly (or we could even prevent all merges to master during this period) merge from release branch to master will be FF so only 1 extra PR vs X PRs for every fix implemented during stabilisation

I can only see one downside:
- it feels weird that main branch is behind other branches ... but I think this is purely psychological
