### ISSUE TITLE
Enhance the kuma RetryPolicy with few more options which envoy supports already

### ISSUE THREAD

**Issue by pranavkevadiya** [kumahq/kuma#4494]
### Description

Source code:
https://github.com/kumahq/kuma/blob/master/pkg/xds/envoy/listeners/v3/retry_configurer.go#L18

The code above sets the RetryPolicy field retry_on as 
`connect-failure,refused-stream,retriable-status-codes`
These values however don't include retrying for a socket timeout or a closed connection. We have encountered such failures in our integration testing and we think a retry would have helped.  

As per our analysis, if Kuma supports either of the following retry_on values to be propagated to the underlying envoy configuration,  it should solve our purpose. 
```
- reset
- connect-failure
- refused-stream
- http3-post-connect-failure
- retriable-status-codes
```

OR

```
- 5xx
- http3-post-connect-failure
- retriable-status-codes
```

Envoy configuration options for retry_on:
[https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-on](https://www.envoyproxy.io/docs/envoy/latest/configuration/http/http_filters/router_filter#x-envoy-retry-on)

**Comment by johnharris85** [comment]
Was closed accidentally by merging the MADR, re-opened.
