### ISSUE TITLE
Add a pre-commit hook to not allow pushing commits without sign-off or add sign-off automatically

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#4504]
### Description

Fairly frequently we get PRs without the sign-off. We could automate the handling of that with a pre-commit hook (note: this can be disabled by using `--no-verify`). I think there are two approaches:
1. `exit 1` to prevent the commit from happening and display a message that we only accept signed-off commits
2. add the sign-off automatically and warn the user that we did that because we only accept signed-off commits

Envoy does something similar to this: https://github.com/envoyproxy/envoy/pull/2283/files#diff-04bbd2d0d7e2f88731cabb03e77ca84e3583abc712d2e7d290abc234acd80491R33

AC:
- there are no* PRs issued without signed-off commits

(* - people can still bypass this but let's make it harder for them)

**Comment by michaelbeaumont** [comment]
Note that the user has to install the hooks before they can run, so the cases caught by the hook might be limited

**Comment by lahabana** [comment]
Feels like now that we have merge time sign-off this is not needed anymore. To discuss at triage.

**Comment by kleinfreund** [comment]
**Triage**: Not needed anymore as per https://github.com/kumahq/kuma/issues/4504#issuecomment-1271280693.
