### ISSUE TITLE
Skip tests on non-code changes

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#4514]
### Description

It is a bit annoying that we run full test suite on [MADR](https://github.com/kumahq/kuma/pull/4445) PRs (and there are probably more cases like this). If we are not changing code we could just skip running build/test phases.

CircleCI [doc](https://circleci.com/docs/2.0/using-dynamic-configuration#execute-specific-workflows-or-steps-based-on-which-files-are-modified) on how to do this.

AC:
- only run build / test steps when code changes

**Comment by slonka** [comment]
@afzal442 - I don't think we have a bot for assigning.

@lahabana - Judging from https://github.com/kumahq/kuma/blame/92720d5d61213da115dd73e86792dc7c8916029e/CONTRIBUTING.md#L103 this is now fixed, right?

**Comment by lahabana** [comment]
Yes indeed!
