### ISSUE TITLE
Implement DEL, CHECK commands in CNI plugin

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#4606]
### Description

The original CNI plugin and the Istio CNI plugin do not have `DEL` and `CHECK` [commands implemented](https://github.com/istio/istio/blob/764e6688921e326bdaa530d5ef3a9ed5d87372f7/cni/pkg/plugin/plugin.go#L303-L309).

Here is the [spec](https://github.com/containernetworking/cni/blob/main/SPEC.md#cni-operations) for the commands.

**Should we implement them in kuma CNI?**

**Comment by jakubdyszkiewicz** [comment]
> Triage: we don't need DEL and CHECK for now.
