### ISSUE TITLE
Kuma "metrics hijacking"/exposing application metrics not setting Accept header.

### ISSUE THREAD

**Issue by erikbergsten** [kumahq/kuma#4607]
### What happened?

Wat happen?
------------------

When using the kuma metrics hijacking feature introduced in 1.7.0 to gather metrics from keycloak the accept header wasn't set so keycloak responds with 406 (Not Acceptable).

How reproduce?
----------------------

Install keycloak (using the bitnami helmchart) and enable metrics hijacking, try curling the metrics endpoints and see whats up.

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's check what accept header keycloak requires. If it's reasonable, we can hardcode this as default. If not, we can introduce header configuration in the `aggregate` section of metrics in Mesh.

**Comment by erikbergsten** [comment]
Using `Accept: */*` works, using `Accept: text/plain` (which is the correct type for metrics according to the [prometheus docs](https://prometheus.io/docs/instrumenting/exposition_formats/#text-based-format)) also works.
