### ISSUE TITLE
Kuma "metrics hijacking"/exposing application metrics times out often.

### ISSUE THREAD

**Issue by erikbergsten** [kumahq/kuma#4608]
### What happened?

Wat happen?
------------------

When using the kuma metrics hijacking feature introduced in 1.7.0 to gather metrics from kafka exporter (which takes a long time since it forwards the requests to the actual kafka brokers) the kuma sidecar regularly times out. Prometheus allows you to set a max scrape timeout for this reason but according to the [docs](https://kuma.io/docs/1.7.x/policies/traffic-metrics/#expose-metrics-from-data-plane-proxies) kuma does not.

How reproduce?
----------------------

Install kafka (using the bitnami helmchart) and enable metrics exporter and hijacking, look at the kuma sidecar logs to attain deeper knowledge.

**Comment by jakubdyszkiewicz** [comment]
> Triage: get rid of the timeout on HTTP client to aggregate targets. This way we rely on the timeout specified in the scraper configuration in Prometheus Server.
