### ISSUE TITLE
Kuma CNI daemonset containersecuritycontext missing from template

### ISSUE THREAD

**Issue by erikbergsten** [kumahq/kuma#4636]
### What happened?

Helmchart values not used in template
---------------------------------------------------

`cni.containerSecurityContext` is in the helm chart [default values](https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/values.yaml) bit not in the actual [cni-daemonset template](https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/templates/cni-daemonset.yaml).

PR #4111 did add it to the template but it was closed in favour of #4153 which did include this update.

**Comment by jakubdyszkiewicz** [comment]
> Triage: we missed it. Sorry about that.
