### ISSUE TITLE
Support direct responses in `MeshGatewayRoute`

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#4639]

**Comment by tharun208** [comment]
@michaelbeaumont I like to work on this. do we also want to send any message to the user other than the status 500

**Comment by michaelbeaumont** [comment]
@tharun208 OK! No, the important part is returning a status _in place of a backend_. For example, I should be able to create a route that returns a 202 status 33% of the time and forwards the request to a service the other 66% of the time. Get in touch on slack if you need pointers/help.

**Comment by lahabana** [comment]
Superseeded by [#5798](https://github.com/kumahq/kuma/issues/5798)
