### ISSUE TITLE
Use of CodeQL? 

### ISSUE THREAD

**Issue by mmorel-35** [kumahq/kuma#4646]
### Description

Have you considered using CodeQL to look for potential security vulnerabilities?

See https://docs.github.com/en/code-security/code-scanning/automatically-scanning-your-code-for-vulnerabilities-and-errors/about-code-scanning-with-codeql

**Comment by jakubdyszkiewicz** [comment]
> Triage: @johnharris85 will look into this

**Comment by jakubdyszkiewicz** [comment]
@johnharris85 did you maybe find some time to check this?

**Comment by lukidzi** [comment]
@johnharris85 Did you maybe have time to look at this issue?

**Comment by slonka** [comment]
Pinging @johnharris85 again :)

**Comment by kleinfreund** [comment]
**Triage**: Yeah, we’re doing this (@johnharris85’s words)
