### ISSUE TITLE
Add support for 3rd party CNI along with ours

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4648]
### Description

Calico/Cillium comes to mind but there's also one in OpenShift.

**Comment by slonka** [comment]
Calico was the only one that I managed to test. I will create issues for `cilium` and `openshift`

**Comment by mmorel-35** [comment]
Hi! Would you consider adding Cisco CNI to this list?

**Comment by slonka** [comment]
Hi :) can it be installed on `kind` or `k3d`? If so can you link to the installation docs?

**Comment by mmorel-35** [comment]
I don't know about kind or k3d, but concerning the installation, you shall find it [here](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/kb/b_Kubernetes_Integration_with_ACI.html#task_od5_5yb_41b) and [here](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/white_papers/Cisco-ACI-CNI-Plugin-for-OpenShift-Architecture-and-Design-Guide.html).

**Comment by slonka** [comment]
Isn't the Cisco CNI used in OpenShift? If so there is already an [issue](https://github.com/kumahq/kuma/issues/4818) for that.

**Comment by mmorel-35** [comment]
Yes, it's used in Openshift. 

> If so there is already an https://github.com/kumahq/kuma/issues/4818 for that.

Do you think that there won't be any particularities associated with it ?
