### ISSUE TITLE
Kubernetes jobs are not considered completed due to kuma-sidecar not being terminated

### ISSUE THREAD

**Issue by tibuntu** [kumahq/kuma#4649]
### What happened?

Hi there!

After upgrading our Kuma installation to 1.7.0 we have a couple of CronJobs/Jobs that are not working properly anymore.

These jobs are part of the mesh, hence the kuma-sidecar container is part of the pods. I am quite sure that this behaviour is related to the newly introduced graceful shutdown.

This is the observed behaviour:

```
emails-27640010-1-nqjrq          1/2     NotReady    0          98s
```

Based on the logs of the sidecar, I can't see any hint about a SIGTERM signal (or similar) being received.

The main container of the pod is working as intendend and is usually already done with his task.

After a certain amount of time, Kubernetes marks the job as failed/uncompleted.

```
emails-27640010        0/1           4m43s      4m43s
```

I also wrote some details about it here: https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1657788087121919?thread_ts=1654251437.225539&cid=CN2GN4HE1

I already tried using the new annotation for the graceful shutdown period but they didn't change the bevahiur at all. Is there a way of simply disabling the graceful shutdown?

Thank you in advance!

**Comment by jakubdyszkiewicz** [comment]
Hey, it is a bug. That's being fixed in https://github.com/kumahq/kuma/issues/4582
