### ISSUE TITLE
`kumactl get dataplane --config-dump` should be marked as deprecated

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4655]
### Description

It's replaced by `--type`

**Comment by jakubdyszkiewicz** [comment]
> Triage: it's about HELP.md

**Comment by tharun208** [comment]
@lahabana I like to work on this

**Comment by tharun208** [comment]
first, this is `kumactl inspect dataplane` and not `get`.

right now, cobra doesn't give any information about deprecated flags in the help command and also in the generated markdown. I created an issue on cobra https://github.com/spf13/cobra/issues/1764.

**Comment by lahabana** [comment]
We've done this for metrics: https://github.com/kumahq/kuma/blob/7e5e5fbfe029814ec85c3758bcb497efa7027a95/app/kumactl/cmd/install/install_metrics.go#L26

Maybe adding to the help message that the flag is deprecated would be a good addition?

**Comment by tharun208** [comment]
yes, that can be an improvement. but, still, it won't update the docs.

**Comment by lahabana** [comment]
I think it will as the docs are generated from the help messages I believe

**Comment by tharun208** [comment]
no, it is not, we are already doing the above in multiple places but it is not updating the docs

**Comment by lahabana** [comment]
@tharun208 I looked at this an in the end it was just 2 lines that were switched around so ended up just opening the PR.
