### ISSUE TITLE
Ability to filter admin API output

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#4663]
### Description

Would be useful to have the ability to filter the queries to the admin API for endpoints that return all items of a type. Open to ideas how this should work, specific fields? Groups of fields? A more structured query?

From Slack: https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1658162653326599

cc/ @wjrbetts

**Comment by jakubdyszkiewicz** [comment]
> Triage: we could use more information on what do we want to filter on.

**Comment by lukidzi** [comment]
@johnharris85 Could you take a look and add more information?

**Comment by slonka** [comment]
Moving this to pending so during today's meeting John could add more info here.

**Comment by johnharris85** [comment]
Additional detail: 
- Looking to filter resources according to prefix primarily
- Regex filtering would be super useful here
- Do we want more advanced filtering syntax / querying?
- Should be add a GraphQL layer?

**Comment by lahabana** [comment]
Let's stick to something simple with tags and name prefix search on the dataplane-overview endpoint.

So now with #5340 (and other existing features) you can do: `/meshes/{name}/dataplanes+insights?gateway={true,false,delegated,builtin}&tag={key:value}&name={prefixSearch}` (tag can be repeated). Good examples are present in this test: https://github.com/kumahq/kuma/blob/master/pkg/api-server/dataplane_overview_endpoints_test.go#L188

We can always add more features with regex, generalizing to all resources but I believe starting small will unblock the GUI and answer most of the user's needs.
