### ISSUE TITLE
Support full TrafficRoute functionality for MeshGatewayRoute

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#4690]
### Description

Not all features of the TrafficRoute (https://kuma.io/docs/1.7.x/policies/traffic-route/#usage) policy are supported by the mesh gateway MeshGatewayRoute (https://kuma.io/docs/1.7.x/policies/mesh-gateway-route/). 

For example: 
- Request and response modification
- Load balancing

**Comment by johnharris85** [comment]
Should be addressing this as part of MeshTrafficRoute (so we can get rid of MeshGatewayRoute).

**Comment by michaelbeaumont** [comment]
Yes, it's linked in that issue

**Comment by lahabana** [comment]
In the future MeshHTTPRoute will be used in place of MeshGatewayRoute. This will mean everything will be supported
