### ISSUE TITLE
Support absence of header via present_match in TrafficRoute

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#4691]
### Description

There isn't support for matching the absence of headers and routing to a service on that basis, for example via present_match in an envoy header matcher, see: https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-msg-config-route-v3-headermatcher

**Comment by johnharris85** [comment]
Both, but primarily MeshGateway. Is this part of / allowed by Gateway API spec @michaelbeaumont ?

**Comment by michaelbeaumont** [comment]
I don't think so, looking at https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io%2fv1alpha2.HTTPRouteMatch and https://gateway-api.sigs.k8s.io/references/spec/#gateway.networking.k8s.io/v1alpha2.HTTPHeaderMatch

**Comment by michaelbeaumont** [comment]
The spec being what it is at the moment, we have some workarounds/options:

* Write the rules in such a way that a fallback rule effectively matches any requests without a header. If all rules match on the header being non empty via `RegularExpression`, then a final rule without this match effectively matches on the header being not present
* Add a sentinel `.value` that we convert into a `MeshGatewayRoute` that uses `present_match`
* We can set `treat_missing_header_as_empty` and match on the empty value (oftentimes a rule likely wants to treat the empty header value the same as the header missing)

**Comment by lahabana** [comment]
From an implem POV it's setting both: `invert_match` and `present_match`. I guess extending the type with `absent` would be great
