### ISSUE TITLE
Support best practices for Envoy edge gateways in MeshGateway

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#4692]
### Description

Ensure Kuma gateway follows [Envoy best practices for an edge gateway](https://www.envoyproxy.io/docs/envoy/latest/configuration/best_practices/edge):

#### TCP

- [x] restrict access to the admin endpoint,
- [x] [overload_manager](https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/overload_manager/overload_manager#config-overload-manager) #3305 
- [x] [listener buffer limits](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-field-config-listener-v3-listener-per-connection-buffer-limit-bytes) to 32 KiB,
- [x] [cluster buffer limits](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/cluster/v3/cluster.proto#envoy-v3-api-field-config-cluster-v3-cluster-per-connection-buffer-limit-bytes) to 32 KiB. https://github.com/kumahq/kuma/pull/4696

#### HTTP

- [x] use_remote_address to true (to avoid consuming HTTP headers from external clients, see HTTP header sanitizing for details)
- [x] [connection timeouts](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#connection-timeouts)
  - as in best practices
- [x] [stream timeouts](https://www.envoyproxy.io/docs/envoy/latest/faq/configuration/timeouts#stream-timeouts)
  - as in best practices example but don't set `request_timeout`
- [x] HTTP/2 maximum concurrent streams limit and HTTP/3 maximum concurrent streams limit to 100
- [x] HTTP/2 initial stream window size limit to 64 KiB
  - [x] listeners
  - [x] clusters https://github.com/kumahq/kuma/pull/4779
- [x] HTTP/2 initial connection window size limit to 1 MiB
  - [x] listeners
  - [x] clusters https://github.com/kumahq/kuma/pull/4779
- [x] headers_with_underscores_action setting to REJECT_REQUEST, to protect upstream services that treat ‘_’ and ‘-‘ as interchangeable
- [x] Listener connection limits https://github.com/kumahq/kuma/pull/4755
- [x] Global downstream connection limits https://github.com/kumahq/kuma/pull/4724
- [x] Enable normalize_path setting.
- [x] Enable merge_slashes setting.
- [x] Additionally the [path_with_escaped_slashes_action setting](https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/network/http_connection_manager/v3/http_connection_manager.proto#envoy-v3-api-field-extensions-filters-network-http-connection-manager-v3-httpconnectionmanager-path-with-escaped-slashes-action) should be set according to following recommendations:
  > * REJECT_REQUEST if dowstream clients are expected to use [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) compliant normalized paths (i.e. gRPC clients).
  > * UNESCAPE_AND_REDIRECT if downstream client supports HTTP redirect (i.e. a browser). This option minimizes possibility of path confusion by forcing request to be re-issued with the same path across all parties: downstream client, Envoy and upstream server. Note that gRPC requests will still be rejected with the INTERNAL (13) error code, as gRPC clients do not support redirect.
  > * KEEP_UNCHANGED for servers that are not [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt) compliant and require encoded slashes.
  > * UNESCAPE_AND_FORWARD for servers that are known to treat escaped and unescaped slashes equivalently. Choosing this option may increase probablity of path confusion vulnerabilities if intermediaries perform path based access control.
  * [Set to `UNESCAPE_AND_REDIRECT`](https://github.com/kumahq/kuma/pull/4719)

**Comment by michaelbeaumont** [comment]
:partying_face:
