### ISSUE TITLE
Perform security analysis / pen testing / etc and document results (& planned efforts)

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#4705]
### Description

We should:
- Develop and frequently run security tests
- Document (on Kuma.io) the security testing that is performed against Kuma today (and any results)
- Document (on Kuma.io) any future planned security-related testing / initiatives

The above are all useful to further establish trust and increase the maturity of the Kuma project.

**Comment by slonka** [comment]
I think this is ongoing (correct me if I'm wrong @johnharris85) - removing stale.

**Comment by slonka** [comment]
There is some activity here, moving to triage so we can talk about it.
