### ISSUE TITLE
Support DR strategy for Global control plane - Blue/green

### ISSUE THREAD

**Issue by brunda-bs** [kumahq/kuma#4707]
### Description

Hi Team,

We are trying to apply a Blue-green deployment strategy for the global control plane by shifting the KDS global address traffic using ATM, based on the health check status of the endpoint from the Blue global control plane to green or Vice versa.

DNS Configuration (High level):
kds address -> Blue Global CP Ingress IP
                     -> Green Global CP Ingress IP

Once the traffic is shifted from Blue to the green global CP, if we restart all the Zonal CP pods then Zonal CPs are able to reestablish the connection to green global CP using the kds address.

 Is there any way to avoid the manual pod restart in order to re-establish the connection?

It would really help us to have a seamless DR implementation in place for Global CP.

**Comment by jakubdyszkiewicz** [comment]
> Traige:

How critical is the latency of reconnecting to the new instance?

We are considering a strategy of dropping the connection every X minutes (configurable) to LB the gRPC connection.
Here is the issue for XDS https://github.com/kumahq/kuma/issues/4039

**Comment by brunda-bs** [comment]
Hi @jakubdyszkiewicz ,

Until and unless we recreate the zonal CP pods, a New connection is not getting established to the Green Global CP.

**Comment by jakubdyszkiewicz** [comment]
> Triage: would reconnecting to the CP every X minute without pod restart solve the issue?

**Comment by brunda-bs** [comment]
Hi @jakubdyszkiewicz ,

Yes, I believe that should fix the issue.

**Comment by jakubdyszkiewicz** [comment]
Ok, I added a note of KDS to https://github.com/kumahq/kuma/issues/4039 ticket. Closing this one in favor of 4039.

Feel free to reopen this one if you have other ideas
