### ISSUE TITLE
New ProxyTemplate design

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4737]
### Description

With the new policy matching. How about ZoneIngress/Egress override?

- https://github.com/kumahq/kuma/issues/4542

**Comment by jakubdyszkiewicz** [comment]
Notes:
* What is inconvenient right now is that modifications are not stacked, so you can by accident cancel more general modifications set by Mesh Operator
* `imports` is awkward to use and might be unnecessary
* `resources` is unnecessary with `modifications`

**Comment by jakubdyszkiewicz** [comment]
Take into account https://github.com/kumahq/kuma/issues/5209
