### ISSUE TITLE
Move from circleci to github actions

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4754]
### What happened?

github actions is free for OSS so we'd save some money.

In the past there were blockers to do this. The ones I remember of were: `parallel runs` and `arm worker`.
We should first check if we have everything to move to github actions and then maybe do it.

Apparently parallel runs is possible with:  https://rubyyagi.com/how-to-run-tests-in-parallel-in-github-actions/

**Comment by slonka** [comment]
I found GH actions limits:

![image](https://user-images.githubusercontent.com/2753650/184347423-1c87f3b0-eacc-434e-8afd-de1b31f021c7.png)

we use 400 minutes per one run (including parallel runs) so that would only last for 5 runes. If the table above is right we might want to just close this or consider self-hosted runners.

**Comment by michaelbeaumont** [comment]
We need to compare the price of credits/minutes and check the number of free minutes for CircleCI

**Comment by slonka** [comment]
It's [up to* 6000](https://circleci.com/pricing/?utm_source=google&utm_medium=sem&utm_campaign=sem-google-dg--emea-en-brandAuth-maxConv-auth-brand&utm_term=g_p-circleci%20free_c__freePlan1_20220111&utm_content=sem-google-dg--emea-en-brandAuth-maxConv-auth-brand_keyword-text_eta-circleCIFree_mixed-) build minutes / month
![image](https://user-images.githubusercontent.com/2753650/184828490-502590d7-9e8c-4455-837e-126da3710090.png)

`* - using small docker resource class which we're probably not using`

**Comment by aktech** [comment]
Hey @slonka Sorry for jumping on this. "self-hosted" got my attention. 

> If the table above is right we might want to just close this or consider self-hosted runners.

You can achieve this with https://cirun.io It creates on demand runners for GitHub Actions on your cloud and manages the complete lifecycle. You simply connect your cloud provider and define what runners you need in a simple `yaml` file and that's it.

See https://docs.cirun.io/reference/examples.html#aws for example. Let me know if you have any questions. I am the creator of Cirun.

**Comment by slonka** [comment]
Hi @aktech - if you can show that it is significantly more cost efficient then we will consider it.

**Comment by lahabana** [comment]
Free for org is different from OSS free. AFAIU github actions is 100% free for OSS projects.

**Comment by aktech** [comment]
> Free for org is different from OSS free. AFAIU github actions is 100% free for OSS projects.

That's absolutely true, my suggestion was for  ARM runners, which are only available via self-hosted.

**Comment by lahabana** [comment]
One thing we've discussed with @slonka to enable a progressive move is to have a workflow that [waits for circleci checks](https://github.com/marketplace/actions/wait-for-check) to be green.
This way downstream automation can rely on this and we can progressively move things from circleCI to GH actions by extending this workflow.

**Comment by jijiechen** [comment]
Closing this as we've done this by a few PRs.
