### ISSUE TITLE
Serviceless pods and provided gateway should use deployment,daemonset,jobs name

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#4768]
### Description

As #4747 and https://github.com/kumahq/kuma/pull/4703#discussion_r934918173 revealed the way we extract deployment name in serviceless pods doesn't support: Jobs, DaemonSets and Stateful sets.
For provided gateway we're adding support of deployments which looking at the parentRef (#4703), this a better more reliable way that we should use for [serviceless pods](https://github.com/kumahq/kuma/blob/060d45d61cd311c3424decd53dcf4da673e66f9c/pkg/plugins/runtime/k8s/controllers/inbound_converter.go#L77) and extends to pods created by Jobs, DaemonSets and StatefulSets.

**Comment by jakubdyszkiewicz** [comment]
As part of this issue, test if we fixed this problem https://github.com/kumahq/kuma/issues/4747
