### ISSUE TITLE
Remove configuration option`EnableLocalhostInboundClusters` from control-plane

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#4772]
### Description

In a https://github.com/kumahq/kuma/issues/4630 we are introducing a configuration option that allows us to turn off new behavior. We want to make it a default behavior, so in the future, we need to remove `EnableLocalhostInboundClusters` configuration option.

**Comment by bartsmykla** [comment]
Reopening as we had to revert change till https://github.com/kumahq/kuma/issues/5335 is fixed (Envoy 1.25)
