### ISSUE TITLE
Kong mesh + Kong Ingress error: other values than TCP are not allowed

### ISSUE THREAD

**Issue by yyefet-chtr** [kumahq/kuma#4802]
### What happened?

1.6.0 Kong Mesh (Kuma)
2.3.0 Kong Ingress Controller
K8s 1.20

When Kong Mesh is used with Kong Ingress Controller/Gateway, and sidecar is injected into Kong Ingress deployment..
Dataplanes are failing to register and being blocked by admission controller with the following error:

ERROR	controllers.Pod	unable to create/update Dataplane	{"pod": "kong/kong-kong-<redacted>", "operationResult": "unchanged", "error": "admission webhook \"validator.kuma-admission.kuma.io\" denied the request: spec.networking.gateway.tags[\"kuma.io/protocol\"]: other values than TCP are not allowed"}

The service kong-proxy has setting with appProtocol: http and appProtocol: https
..but the dataplane admission controller for kong only allows value of "TCP"

Behavior, Kong ingress does not register its dataplane (Sidecar fails to start) and ingress fails to any application.

**Comment by JoshuaFurman** [comment]
This issue is related to this [issue](https://github.com/kumahq/kuma/issues/4247)

It says that the issue was resolved and merged however we are still seeing this issue.

**Comment by lukidzi** [comment]
@JoshuaFurman Which version of Kuma are you using? The fix is since Kuma 1.7.0.

**Comment by JoshuaFurman** [comment]
@lukidzi I'm using Kong-Mesh helm chart 1.8.1 (https://artifacthub.io/packages/helm/kong-mesh/kong-mesh/1.8.1) 

Kuma 1.7.1
Kong-Mesh 1.8.1
kuma-cp 1.8.1
kuma-dp 1.8.1
kuma-init 1.8.1
kumactl 1.8.1
Kong Ingress Controller 2.5
