### ISSUE TITLE
Problem with a communication between services in different zones 

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#4814]
### Description 
We are experiencing an interesting issue with cross-zone communications.
We currently have 3 meshes configured (production, staging, dev).
We are experimenting with 2 very simple GRPC services on the `dev` mesh. one is a simple echo server that returns OK on a request, and the other is a simple client that makes requests against the echo server, increments a counter, and prints to log.
We run 7 K8s clusters, one contains the Global CP and the other 6 are set up as zones.
We bring up the echo server in Zone1, and the client in Zone2. Initially, the connection works great, it does a few hundred requests/s which is fine.
When we try to bring up the echo server service in Zone3 we see the issue. We see 20s-30s where the client can not reach any of the echo services. After the 30s, the client gets responses from the echo services just fine again.
If we scale the echo pods in Zone1 from 1 => 2, we see the blip again on the client in Zone2
We have captured some Debug logs from the clients kuma-sidecar. It seems to be making the requests to the Zone Ingresses on Zone1 and Zone3, but receives a connection termination
To me, it feels like the Zone Ingresses are rebuilding their configs when the services change and this causes the connection issues, but I'm not sure.
Our production mesh currently has no services
Our staging mesh has ~40 services
The dev mesh only has the 2 services

The problem was reported on the community channel
https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1660270701755139
I've asked for more info, and after that, we should try to reproduce it.

**Comment by m-augustine** [comment]
Hello! 
Attaching some more information regarding this issue

Kuma Version: 1.7.1 (on all Control Planes )
Deployed Via Helm chart, version 1.7.1
Deployed on Kubernetes version 1.24 on GKE

The `dev` mesh yaml
[mesh.txt](https://github.com/kumahq/kuma/files/9347777/mesh.txt)

The `dev` mesh has all the default policies except for trafficlogs
[trafficlogs.txt](https://github.com/kumahq/kuma/files/9347780/trafficlogs.txt)

The following logs are from throttled test where we were sending 1 request/s

The logs from the grpc-client service and its kuma-sidecar with log-level debug
[client.log](https://github.com/kumahq/kuma/files/9347727/client.log)
[client-kuma-sidecar.log](https://github.com/kumahq/kuma/files/9347728/client-kuma-sidecar.log)

The zone ingress endpoints in the log are assigned as follow:
 34.68.155.245: Zone1
34.133.202.122: Zone2

The Kuma TrafficLogs from the grpc-client 
[client-trafic-logs.log](https://github.com/kumahq/kuma/files/9347808/client-trafic-logs.log)



The zone ingress logs with log-level debug during another scale up where the blip happens
[zone-2-ingress.log](https://github.com/kumahq/kuma/files/9347765/zone-2-ingress.log)

The blip in the zone-2-ingress.log starts around `03:46:06`

**Comment by m-augustine** [comment]
Id also be happy to hop on a video call with someone if more info is needed

**Comment by m-augustine** [comment]
Also important to note that if the grpc-echo and grpc-client are brought up on the same clusters (and scaled up) the blip does _**not**_ occur.

**Comment by lobkovilya** [comment]
I tried to reproduce this locally. No luck so far, but I was using Unary RPC. Do you using GRPC streaming in your echo-client and echo-server?

**Comment by lobkovilya** [comment]
Okay, I checked bidirectional GRPC streaming, it also works as expected across different zones. 

@m-augustine could you please share the code how you configure grpc client and server. Also, please share Dataplane resources of the echo-client and echo-server. Thanks!

**Comment by lahabana** [comment]
@m-augustine any updates?

**Comment by jakubdyszkiewicz** [comment]
Please reopen if you have more updates
