### ISSUE TITLE
Add support for openshift/cisco CNI along with ours

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#4818]
### Description

AFAWK Cisco CNI is used in OpenShift, installation instructions [here](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/sw/kb/b_Kubernetes_Integration_with_ACI.html#task_od5_5yb_41b) and [here](https://www.cisco.com/c/en/us/td/docs/switches/datacenter/aci/apic/white_papers/Cisco-ACI-CNI-Plugin-for-OpenShift-Architecture-and-Design-Guide.html).

Continuation from: https://github.com/kumahq/kuma/issues/4648

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's first check manually if it works. Then we can try to create E2E test with OpenShift

**Comment by jakubdyszkiewicz** [comment]
> Triage: Closing. Reopen if needed
