### ISSUE TITLE
ARM Envoy does not send a request for listener

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4822]
### What happened?

We see this only in one E2E test out of all when it's only run on ARM.

`Test ZoneEgress for External Services in Hybrid Multizone`
test/e2e/zoneegress/externalservices/e2e_suite_test.go

Sometimes the test fails because Envoy never sends a request with Listeners to the CP

**Comment by slonka** [comment]
@jakubdyszkiewicz - have you reported this to Envoy?

**Comment by lobkovilya** [comment]
> Triage: let's reenable the test and see

**Comment by slonka** [comment]
it passed on my machine 

![image](https://github.com/user-attachments/assets/fa0e8148-7c0f-426e-a093-22e7e30ab2e6)

so we can try this on CI
