### ISSUE TITLE
Kuma-init container causes Kong-Ingress pods to fail

### ISSUE THREAD

**Issue by JoshuaFurman** [kumahq/kuma#4831]
### What happened?

I'm attempting to deploy a Zone Control Plane cluster with Kong-Ingress. My Zone CP connects and shows up in the Global Control Plane UI, however after deploying Kong-Mesh my Kong-Ingress pods need to be restarted and after they are restarted they fail to come back up because the kuma-init pod fails. I am at a loss and am unsure how to continue... 

Versions:
Kuma 1.7.1
Kong-Mesh 1.8.1
kuma-cp 1.8.1
kuma-dp 1.8.1
kuma-init 1.8.1
kumactl 1.8.1
Kong Ingress Controller 2.5

I have attached the logs from the kuma-init pod:
[kuma-init-logs.txt](https://github.com/kumahq/kuma/files/9340326/kuma-init-logs.txt)

**Comment by jakubdyszkiewicz** [comment]
> Triage: Can you share more information about the environment that you are running? Cloud vendor / OS version.

**Comment by JoshuaFurman** [comment]
Its an on-prem cluster of VMs 

OS Version:
`NAME="Rocky Linux"
VERSION="8.4 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.4"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.4 (Green Obsidian)"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:rocky:rocky:8.4:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
ROCKY_SUPPORT_PRODUCT="Rocky Linux"
ROCKY_SUPPORT_PRODUCT_VERSION="8"`

**Comment by JoshuaFurman** [comment]
The issue we were seeing was found out to be from SElinux on hosts stopping kuma-init container from calling iptables commands.

Issue will now be closed
