### ISSUE TITLE
Rewrite the helm release script without dependencies

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#4886]
### Description

We could pass [these dependencies](https://github.com/kumahq/kuma/blob/485c82aa38094d95369ef7a8592596062429400e/tools/releases/helm.sh#L39-L46) directly to the script instead of going over the `Chart.yaml` files, which then allows us to get rid of a dependency section in projects that rely on kuma's helm charts which makes the release proces easier.

**Comment by jakubdyszkiewicz** [comment]
> Triage
> Let's try to remove `dependencies` section (KM)
> Versions: let's document that appVersion and version in Chart.yaml is replaced by the script. We can try to set this to 0.0.0

**Comment by michaelbeaumont** [comment]
I think to have a valid `Chart.yaml` we should be including the dependency as long as we embed it
