### ISSUE TITLE
upgrade Kong Ingress Controller in kumactl install gateway

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#4888]
### Description

We are on `v2.0.5`, we should be on `v2.5.0`.

What process do we have to keep with upgrades?

**Comment by jakubdyszkiewicz** [comment]
> Triage:
> to automate this we need to switch to HELM charts (embed charts in kumactl). Then write a script+GH action to update upstream charts in Kuma

**Comment by slonka** [comment]
This is in conflict with https://github.com/kumahq/kuma/issues/6750 I'm assuming the later takes precedence and we should close this issue. Moving to triage to confirm closing.
