### ISSUE TITLE
Default resources shouldn't include their mesh in their name

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#4902]
### What happened?

We create default resources like the `TrafficPermission` `allow-all-default` for the `default` mesh. This is unnecessary because these resources are already unique per mesh so we can skip adding the mesh suffix. This sort of feels like a breaking change so maybe 2.0?

**Comment by jakubdyszkiewicz** [comment]
Unfortunately, in this case, we would have a clash on Kubernetes.

xref #3837
