### ISSUE TITLE
Kuma version 1.8.0 helm installation failing 

### ISSUE THREAD

**Issue by parjun8840** [kumahq/kuma#4917]
### What happened?

The version 1.8.0 throws error.
>  arjunpandey$ helm upgrade -i kuma --namespace kuma-system --create-namespace --version 1.8.0  --set controlPlane.mode=global kuma/kuma

```
Release "kuma" does not exist. Installing it now.
Error: template: kuma/templates/pre-upgrade-install-missing-crds-job.yaml:143:20: executing "kuma/templates/pre-upgrade-install-missing-crds-job.yaml" at <include "kuma.formatImage" (dict "image" .Values.kumactl.image "root" $)>: error calling include: template: kuma/templates/_helpers.tpl:168:5: executing "kuma.formatImage" at <ne $root.Values.global.image.tag (include "kuma.appVersion" $root)>: error calling ne: incompatible types for comparison
```
While the older version works smoothly.

>  arjunpandey$ helm upgrade -i kuma --namespace kuma-system --create-namespace --version 0.8.1 --set controlPlane.mode=global kuma/kuma

```
Release "kuma" does not exist. Installing it now.
NAME: kuma
LAST DEPLOYED: Fri Aug 26 18:00:02 2022
NAMESPACE: kuma-system
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
The Kuma Control Plane has been installed!

You can access the control-plane via either the GUI, kubectl, the HTTP API, or the kumactl CLI.
 arjunpandey$ 
```

It is mostly helm templating or documentation problem.

**Comment by bartsmykla** [comment]
Hi @parjun8840 could you update helm and try again?

**Comment by lahabana** [comment]
@bartsmykla pointed you need a version of Helm >= 3.8 as indicated: https://kuma.io/docs/1.8.x/installation/helm/#helm

Please let us now if the issue stiff happens after using Helm >= 3.8

**Comment by arjun-san** [comment]
Hi @bartsmykla Thanks..... Yes it seems to be an issue with Mac M1 laptops.
The Helm configurations used in this version doesn't seems to be compatible with it.

> arjunpandey$ helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
Q9JG9FWXG7:loki arjunpandey$


> arjunpandey$ helm version
> version.BuildInfo{Version:"v3.9.0+3.el8", GitCommit:"e09b16a5119e20607a4a7ae9884a96331ffff1de", GitTreeState:"clean", GoVersion:"go1.17.7"}
> Q9JG9FWXG7:helm arjunpandey$

> arjunpandey$ helm repo list
> Killed: 9
> 

I tried with different versions on my Mac but it didn't work.

Finally through a different machine it worked.

I would suggest to keep some solution ready for this issue as you would be facing it regularly in near future.

Thank you very much for the prompt response and help.

**Comment by parjun8840** [comment]
Hi @bartsmykla Thanks..... Yes it seems to be an issue with Mac M1 laptops.
The Helm configurations used in this version doesn't seems to be compatible with it.

> arjunpandey$ helm version
version.BuildInfo{Version:"v3.7.2", GitCommit:"663a896f4a815053445eec4153677ddc24a0a361", GitTreeState:"clean", GoVersion:"go1.16.10"}
Q9JG9FWXG7:loki arjunpandey$


> arjunpandey$ helm version
> version.BuildInfo{Version:"v3.9.0+3.el8", GitCommit:"e09b16a5119e20607a4a7ae9884a96331ffff1de", GitTreeState:"clean", GoVersion:"go1.17.7"}
> Q9JG9FWXG7:helm arjunpandey$

> arjunpandey$ helm repo list
> Killed: 9
> 

I tried with different versions on my Mac but it didn't work.

Finally through a different machine it worked.

I would suggest to keep some solution ready for this issue as you would be facing it regularly in near future.

Thank you very much for the prompt response and help.

**Comment by lahabana** [comment]
So on Mac M1 it did fail even with Helm 3.9?

**Comment by parjun8840** [comment]
Yes

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's double-check that we can install Kuma with Helm 3.9 + Mac M1

**Comment by lahabana** [comment]
Btw are you getting the same error in Helm 3.9?

**Comment by jakubdyszkiewicz** [comment]
I tried to repro this, but it works on my machine (M1 Mac).
```
❯❯❯ helm version
version.BuildInfo{Version:"v3.8.2", GitCommit:"6e3701edea09e5d55a8ca2aae03a68917630e91b", GitTreeState:"clean", GoVersion:"go1.17.5"}
```
Installed via the same command as stated in the issue.

Closing for now. Feel free to reopen if you still see the issue.
