### ISSUE TITLE
Not able to get ingress traffic from ALB to the NodePort service after enabling Sidecar/Kuma in the Namespace

### ISSUE THREAD

**Issue by parjun8840** [kumahq/kuma#4923]
### What happened?

Not able to get ingress traffic from ALB to the NodePort service after enabling kong.

-  EKS version: eks.5
-   Kubernetes version: 1.22
-   aws-load-balancer-controller: v2.4.3
- Kuma version: 1.8.0

Ingress is mentioned below. This ingress rule creates an ALB and 3 DNS entries .

> apiVersion: networking.k8s.io/v1
> kind: Ingress
> metadata:
>   name: ingress-name
>   annotations:
>     alb.ingress.kubernetes.io/load-balancer-name: teamsnamebase-ingress
>     alb.ingress.kubernetes.io/scheme: internet-facing
>     alb.ingress.kubernetes.io/healthcheck-protocol: HTTP 
>     alb.ingress.kubernetes.io/healthcheck-port: traffic-port
>     alb.ingress.kubernetes.io/healthcheck-interval-seconds: '15'
>     alb.ingress.kubernetes.io/healthcheck-timeout-seconds: '5'
>     alb.ingress.kubernetes.io/success-codes: '200'
>     alb.ingress.kubernetes.io/healthy-threshold-count: '2'
>     alb.ingress.kubernetes.io/unhealthy-threshold-count: '2'   
>     alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
>     alb.ingress.kubernetes.io/certificate-arn: xxxxxxxxxxxxx
>     #alb.ingress.kubernetes.io/ssl-policy: ELBSecurityPolicy-TLS-1-1-2017-01 #Optional (Picks default if not used)    
>     alb.ingress.kubernetes.io/ssl-redirect: '443'
>     external-dns.alpha.kubernetes.io/hostname: platform-b.dev.xxx.com
>     alb.ingress.kubernetes.io/subnets: subnet-09d9198123dbbc2dc, subnet-092179e8631289bf6
> spec:
>   ingressClassName: platform-aws-ingress-class   # Ingress Class                  
>   defaultBackend:
>     service:
>       name: app3-platapp-nodeport-service
>       port:
>         number: 8000     
>   rules:
>     - host: platform-a.dev.xxx.com
>       http:
>         paths:
>           - path: /
>             pathType: Prefix
>             backend:
>               service:
>                 name: app1-platapp-nodeport-service
>                 port: 
>                   number: 8000
>     - host: platform-c.dev.xxx.com
>       http:
>         paths:                  
>           - path: /
>             pathType: Prefix
>             backend:
>               service:
>                 name: app2-platapp-nodeport-service
>                 port: 
>                   number: 8000
> 

And in the deployment I am using below manifests-

> apiVersion: apps/v1
> kind: Deployment
> metadata:
>   name: app1-platapp-deployment
>   labels:
>     app: app1-platapp
>   annotations:
>     kuma.io/gateway: enabled
> spec:
>   replicas: 1
>   selector:
>     matchLabels:
>       app: app1-platapp
>   template:
>     metadata:
>       labels:
>         app: app1-platapp
>       annotations:
>         kuma.io/gateway: enabled
>     spec:
>       containers:
>         - name: app1-platapp
>           image: parjun8840/prommetricsexpose:v3
>           ports:
>             - containerPort: 8000
> 
> 
> 
> apiVersion: v1
> kind: Service
> metadata:
>   name: app1-platapp-nodeport-service
>   labels:
>     app: app1-platapp
>   annotations:
> #Important Note:  Need to add health check path annotations in service level if we are planning to use multiple targets in a load balancer    
>     alb.ingress.kubernetes.io/healthcheck-path: /
> spec:
>   type: NodePort
>   selector:
>     app: app1-platapp
>   ports:
>     - port: 8000
>       targetPort: 8000

I am expecting the TargetGroup to become healthy but it is not happening and hence I am not able to access the application page.

One of the reason could be mTLS enabled. I need to find out a way to by-pass the mTLS for ALB health check or if you have any better solution please let me know.

I have tried other options as well after reading the docs but it is not helping.

Any help highly appreciated.

**Comment by jakubdyszkiewicz** [comment]
> Triage:
> I don't think this setup will work. Service `app1-platapp-nodeport-service` is protected by mTLS so the client has to also be in the mesh. We recommend spinning up a Gateway that you put in the mesh https://kuma.io/docs/1.8.x/explore/gateway/

**Comment by parjun8840** [comment]
Hi @jakubdyszkiewicz ,
Thank you very much . 
I tried both the options : Permissive mode and Gateway . It works as expected.

The only thing I want to highlight here is that, the helm chart installation didn't work for me :-) -

> arjunpandey$ helm install kong/kong --generate-name --set ingressController.installCRDs=false
Error: INSTALLATION FAILED: Kubernetes cluster unreachable: exec plugin: invalid apiVersion "client.authentication.k8s.io/v1alpha1"

May be the team handling helm charts can take a look into this . 

I did it using "Kubectl" :-) 

Thank you very much for the prompt response.

**Comment by jakubdyszkiewicz** [comment]
It is helm related issue. I think you need to either downgrade HELM to 3.8.2 or upgrade Kube cluster. Take a look here https://github.com/helm/helm/issues/10975

Closing since the main issue is solved. Thanks!
