### ISSUE TITLE
Record outbound requests as separate Datadog services

### ISSUE THREAD

**Issue by michaelgoodrx** [kumahq/kuma#4937]
### Description

See https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1661205593905379. Currently, ingress into a service and egress are recorded on the same Datadog service as different resources, which can be confusing. Would like to add the option to separate them into different ingress and egress Datadog services.

**Comment by jakubdyszkiewicz** [comment]
> Triage: we should check if both configurations make sense. If so, this should be a configuration in datadog tracing backend.
