### ISSUE TITLE
Sidecars are not allocated ephemeral-storage by default

### ISSUE THREAD

**Issue by michaelgoodrx** [kumahq/kuma#4946]
### What happened?

We have some workloads that use ephemeral-storage. When they run on the same node as a pod running the kuma sidecar, the pod running the kuma sidecar can be evicted, because it uses some ephemeral storage even though it doesn't actually request any. This caused pod evictions which have caused other bugs.

Kuma should specify a small ephemeral-storage request by default, along with cpu and memory. I can add it myself using a patch, but most people are going to want at least a little bit of storage for cluster stability.

**Comment by jakubdyszkiewicz** [comment]
xref https://github.com/kumahq/kuma-net/issues/66

**Comment by lahabana** [comment]
This is done already right?

**Comment by michaelbeaumont** [comment]
I think actually it'd be https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#setting-requests-and-limits-for-local-ephemeral-storage

**Comment by lahabana** [comment]
@stu_at_kong
