### ISSUE TITLE
Policy naming going forward (2.0, 3.0 ...)

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#4971]
Prelude: this issue results from our conversation during `MeshAccessLog` meeting.

Right now, the new policies have a prefix `Mesh`, which is nice because it shows a clear distinction between the old policies (that use "sources and destinations") e.g. `TrafficPermission` and new policies (that use "targetRef / from / to") e.g. `MeshTrafficPermission`. Unfortunately there are problems with it:
- `MeshGateway` and `MeshGatewayRoute` use this naming convention but still use "sources and destinations". 
- When all supported policies have a prefix `Mesh` then it feels like it's unnecessarily long.

To avoid confusion for the users we should have a clear plan about the naming convention for our policies with regards to the following properties:
- old/new matching mechanism 
- scope (global / mesh)
- noun vs verb (`log` vs `logging`)
- similarity to Envoy's constructs (`traffic log` vs `access log`)

**Comment by lahabana** [comment]
Triage: Anything to do here?
