### ISSUE TITLE
Ensure `MeshGateway` generated rule order is correct

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#5010]
### Description

The Gateway API spec tells us how to sort rules generated in the presence of multiple matches and routes. We should use this as a guideline for `MeshHTTPRoute` and ensure our Gateway API implementation follows this spec.

> Proxy or Load Balancer routing configuration generated from HTTPRoutes MUST prioritize matches based on the following criteria, continuing on ties. Across all rules specified on applicable Routes, precedence must be given to the match having:
>
> * “Exact” path match.
> * “Prefix” path match with largest number of characters.
> * Method match.
> * Largest number of header matches.
> * Largest number of query param matches.
>
> Note: The precedence of RegularExpression path matches are implementation-specific.
>
> If ties still exist across multiple Routes, matching precedence MUST be determined in order of the following criteria, continuing on ties:
>
> * The oldest Route based on creation timestamp.
> * The Route appearing first in alphabetical order by “{namespace}/{name}”.
>
> If ties still exist within an HTTPRoute, matching precedence MUST be granted to the FIRST matching rule (in list order) with a match meeting the above criteria.
>
> ref. https://gateway-api.sigs.k8s.io/reference/spec/#gateway.networking.k8s.io/v1.HTTPRouteRule

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's also add a proper conformance test in GatewayAPI repo.

**Comment by bartsmykla** [comment]
Solved when introduced https://github.com/kumahq/kuma/pull/9732 by https://github.com/kumahq/kuma/pull/9472
