### ISSUE TITLE
Missing validation of CA name

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5012]
### What happened?

The ca is called differentCA on k8s it's causing problems:

Found it one the global CP: "2022-09-15T11:32:13.628Z	ERROR	controllers.Mesh	unable to ensure that mesh CAs are created	{"mesh": "/different", "error": "could not ensure CA backends of type builtin: failed to create CA for mesh \"different\" and backend \"differentCA\": failed to create k8s Secret: Secret \"different.ca-builtin-cert-differentCA\" is invalid: metadata.name: Invalid value: \"different.ca-builtin-cert-differentCA\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. '[example.com](http://example.com/)', regex used for validation is '[a-z0-9]([-a-z0-9][a-z0-9])?(\\.[a-z0-9]([-a-z0-9][a-z0-9])?)')", "errorVerbose": "Secret \"different.ca-builtin-cert-differentCA\" is invalid: metadata.name: Invalid value: \"different.ca-builtin-cert-differentCA\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.',

**Comment by svenwal** [comment]
And on the the actual data plane you get no real feedback on what went wrong - it just doesn't complete the startup and stays not being ready with no real help from the "local" logs on the DP

**Comment by ceekay47** [comment]
Hey @lahabana , I would like to work on this. Can you help me get started?

**Comment by jakubdyszkiewicz** [comment]
> Triage: also make sure to validate the length of CA
