### ISSUE TITLE
Support customization of the `Deployment`/`Pods` created by `MeshGatewayInstance`

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#5027]
### Description

Similar to #4903, the deployment should be customizable.

**Comment by conman2305** [comment]
Hey @michaelbeaumont just wanted to poke this issue and see if there's any plans to pull this in

**Comment by bartsmykla** [comment]
Hi @conman2305, we created [the MADR](https://github.com/kumahq/kuma/pull/6348) for this feature, and started discussion around it. Please fill free to join the discussion about it under the linked PR. When it'll be merged, we can start with the implementation.
