### ISSUE TITLE
Kuma should allow to define empty list of reachableServices

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#5041]
### What happened?

Sometimes services don't need to communicate with other services and in this case, they might not require changes/observer all services in the infrastructure. Currently, it is not possible to define an empty list of reachable services.
On Kubernetes you can define `kuma.io/transparent-proxying-reachable-services: "[]"` and in this case, it won't match with any outbound. But, Kuma sees this as a list of service with the name`[]`. We should define maybe some value/annotation that will allow disabling tracking of all services.

**Comment by jakubdyszkiewicz** [comment]
A workaround is to put random non-existent service like this:
```
kuma.io/transparent-proxying-reachable-services: "non-existing-service"
```

It's because in protobuf `[] = nil`

**Comment by jakubdyszkiewicz** [comment]
Yes, you can use label to select a namespace. We still treat empty `reachable-backend-refs` as "reach all" I think. I just pinged @lukidzi to make sure we fix it for the new annotation

**Comment by lahabana** [comment]
@lukidzi can you confirm we can to no service? Also we discussed a mode for MeshService which would require using ReachableServices have we got an issue to track this?
