### ISSUE TITLE
Implement `targetRef` policies support with `ExternalService` with/ without `ZoneEgress`

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#5050]
# Description

The first step of the issue should be to go over all new policies and figure out if they work with non egress ES and with egress ES.
Once we have a list of all that we can decide create issues to figure out what to add and what to document as non-supported

### Without ZoneEgress

No policies can `spec.targetRef` a `MeshService`

### With ZoneEgress

* MeshFaultInjection https://github.com/kumahq/kuma/pull/8742
* MeshRateLimit https://github.com/kumahq/kuma/pull/8743
* MeshAccessLog 
* MeshTimeout 

As inbound policies, these can be configured on the egress proxy

* MeshTrafficPermission - Already implemented

## Outbound policies

These policies can't be configured with an external service in `spec.targetRef` but external services should work in `spec.to[].targetRef`.

* MeshCircuitBreaker https://github.com/kumahq/kuma/issues/8991

* MeshHealthCheck https://github.com/kumahq/kuma/issues/8992

* MeshHTTPRoute - implemented https://github.com/kumahq/kuma/blob/master/pkg/xds/generator/egress/generator_test.go#L219

* MeshTCPRoute https://github.com/kumahq/kuma/issues/9050

* MeshLoadBalancingStrategy - implemented

* MeshRetry

* MeshMetrics https://github.com/kumahq/kuma/issues/4348

* MeshAccessLog  https://github.com/kumahq/kuma/issues/8417

* MeshTimeout https://github.com/kumahq/kuma/issues/8990

* MeshProxyPatch 

## Dataplane policies

These can't be configured with an ExternalService.

* MeshTrace https://github.com/kumahq/kuma/issues/9049

**Comment by lukidzi** [comment]
* MeshRetry - I think the client should retry in this case. We shouldn't support retry on Egress because we might multiply requests if the client has a Retry policy and Egress has its own policy. Let us document this. WDYT?
* MeshTrace - there is a use case where traffic to specific ExternalServices might be routed through a specific zone. In this case, it makes sense to have a trace of this request.
