### ISSUE TITLE
Add support for updating reachable services dynamically

### ISSUE THREAD

**Issue by vermdeep** [kumahq/kuma#5078]
### Description

There is no way to modify the `transparentProxying.reachableServices` section of a Dataplane running in universal mode without restarting it.

Policy:
https://kuma.io/docs/1.8.x/generated/resources/proxy_dataplane/

**Comment by michaelbeaumont** [comment]
@vermdeep would [using the indirect lifestyle](https://kuma.io/docs/1.8.x/explore/dpp-on-universal/#indirect) work for your use case?

**Comment by slonka** [comment]
ping @vermdeep - would the above work?

**Comment by jakubdyszkiewicz** [comment]
Closing the issue as there is no answer. Feel free to reopen if you want to proceed with discussion or ideas.

**Comment by vermdeep** [comment]
@michaelbeaumont Using indirect lifecycle won't work for us. As we are running dataplane as a sidecar to ECS service on AWS.
