### ISSUE TITLE
Change Kubernetes Service for the Pod can break the traffic for a second

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#5086]
### What happened?

Let's assume we have a client -> server communication protected by mTLS. Each with one instance

Steps to reproduce
1) Add a new instance of a server, but do not add the labels such that it is selected by the server's Service
2) Wait until the new instance is healthy (has a cert, Dataplane object etc.)
3) Change the instance labels so it is picked by the server's Service

The DP is reconciled with `kuma.io/service: server`. Now, two parallel steps take place
1) We update server's instance2 Envoy with a new cert
2) We update client with the instance 2 endpoint for server's Service

If 2. finishes before 1., then the client tries to connect to the instance and mTLS failed

context: it's visible when used with https://argoproj.github.io/argo-rollouts/features/bluegreen/

**Comment by lahabana** [comment]
@jakubdyszkiewicz any idea how to fix this?
Not propagating client change before server got the change seems complicated right?

**Comment by lahabana** [comment]
To double check with Argo
