### ISSUE TITLE
Control-Plane ciphers configuration to prevent using weak ciphers

### ISSUE THREAD

**Issue by fgunited** [kumahq/kuma#5118]
### Description

As we have to let the Kuma Control-Plane run on the hostnetwork (EKS-API connectivity needed for webhooks), it is very important to have only valid and secure tls options to be available in the TLS-communication to the Kuma Control-Plane (all TLS ports), so we need the possibility to configure the TLS ciphers for the Kuma Control-Plane TLS ports.

For example currently the weak cipher DES-CBC3-SHA is available with Kuma 1.8 , this is critical and so you must be able to adjust these ciphers to be able to act fast on security flaws.

An option would be to set a list of offered ciphers via a configmap.

**Comment by lahabana** [comment]
Duplicate of #5170
