### ISSUE TITLE
Refactor `pkg/core/xds.Proxy`

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#5124]
### Description

At the moment it's a struct with a bunch of info that may or may not be present. We should make it more explicit what kind of proxy we're dealing with `Dataplane` (Gateway? Builtin Gateway?), `ZoneIngress`/`ZoneEgress` to make it easier to understand what cases need to be handled when dealing with a `Proxy` for generation.

**Comment by lahabana** [comment]
Should this be a method is `dataplane_helpers.go` ? That's where we already have things like: `IsDelegatedGateway` or `IsBuiltinGateway`

**Comment by michaelbeaumont** [comment]
Not worth keeping this issue around
