### ISSUE TITLE
kumactl observability adapting kubernetes v1.25

### ISSUE THREAD

**Issue by neilbowman666** [kumahq/kuma#5126]
### Description

PodSecurityPolicy is not available since kubernetes v1.25

https://kubernetes.io/docs/reference/using-api/deprecation-guide/#psp-v125

> resource mapping not found for name: "grafana" namespace: "mesh-observability" from "kuma-obsv.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "loki" namespace: "mesh-observability" from "kuma-obsv.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "loki-promtail" namespace: "mesh-observability" from "kuma-obsv.yaml": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
ensure CRDs are installed first

please update command `kumactl install observability`

kuma.io documentation: https://kuma.io/docs/1.8.x/explore/observability

**Comment by jakubdyszkiewicz** [comment]
> Triage: we should update HELM charts of loki/grafana/prom. Those charts probably already solved this.
