### ISSUE TITLE
Setting serviceAddress results in immediate connect error: Invalid argument

### ISSUE THREAD

**Issue by Tahvok** [kumahq/kuma#5128]
We're running kuma-dp inside a docker network bridge with our service. This means that our service is not running on 127.0.0.1, but rather has an IP address of its own.
Kuma-dp provides a way to set that address using `serviceAddress` like so:
```yaml
type: Dataplane
mesh: default
name: {{ name }}
networking:
  address: {{ container_address }}
  advertisedAddress: {{ host_address }}
  inbound:
    - port: 1337
      servicePort: 80
      serviceAddress: 172.18.1.11
      tags:
        kuma.io/service: collector-online
```

However, this does not work. When running kuma-dp with debug log, you can observe the following errors:

```
[debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:197] [C5361] new tcp proxy session
[debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:369] [C5361] Creating connection to cluster localhost:6666
[debug][misc] [source/common/upstream/cluster_manager_impl.cc:1895] Allocating TCP conn pool
[debug][pool] [source/common/conn_pool/conn_pool_base.cc:268] trying to create new connection
[debug][pool] [source/common/conn_pool/conn_pool_base.cc:145] creating a new connection
[debug][connection] [source/common/network/connection_impl.cc:912] [C5362] connecting to 172.18.1.10:6666
[debug][connection] [source/common/network/connection_impl.cc:936] [C5362] immediate connect error: Invalid argument
[debug][conn_handler] [source/server/active_tcp_listener.cc:142] [C5361] new connection from 10.160.0.248:55896
[debug][connection] [source/common/network/connection_impl.cc:575] [C5362] raising immediate error
[debug][connection] [source/common/network/connection_impl.cc:250] [C5362] closing socket: 0
[debug][pool] [source/common/conn_pool/conn_pool_base.cc:439] [C5362] client disconnected, failure reason: immediate connect error: Invalid argument
[debug][filter] [source/common/tcp_proxy/tcp_proxy.cc:369] [C5361] Creating connection to cluster localhost:6666
[debug][connection] [source/common/network/connection_impl.cc:139] [C5361] closing data_to_write=0 type=1
[debug][connection] [source/common/network/connection_impl.cc:250] [C5361] closing socket: 1
[debug][conn_handler] [source/server/active_stream_listener_base.cc:120] [C5361] adding to cleanup list
[debug][pool] [source/common/conn_pool/conn_pool_base.cc:410] invoking idle callbacks - is_draining_for_deletion_=false
```

This goes on repeat. The inbound listener is never getting created.

Another weird observation is that it's trying to create an additional connection to cluster `localhost:6666` - but where does `localhost` is coming from?
On the log right after you can see it's trying the correct address `172.18.1.10:6666` - but it raises `immediate connect error: Invalid argument` error.

I have also verified that from inside kuma-dp container I can run curl towards `172.18.1.10:6666` and I'm getting results without issues.

**Comment by jakubdyszkiewicz** [comment]
Hey,

a couple of questions

> Can you try Kuma 1.8.1?
> Can you send full logs of server DP?
> Can you send config dump / stats of server and client (if client is also Kuma DP)?
> How are you connecting to this DP? Is the client in the docker network or outside of the docker network?

**Comment by Tahvok** [comment]
> Hey,
> 
> a couple of questions
> 
> > Can you try Kuma 1.8.1?
Will deploy tomorrow and test.
> > Can you send full logs of server DP?
The log is huge with lots of health check output (because its running in debug). What I sent here already is just a small part of it. Do you want the log as soon as the service start ups and up to 1000 rows (or how much you need)?
> > Can you send config dump / stats of server and client (if client is also Kuma DP)?
What are you referring here to as server and what is a client?
> > How are you connecting to this DP? Is the client in the docker network or outside of the docker network?
If you mean client as in our service, then yes, it's the in the same docker network as kuma-dp. I have described better the topology in my comment here: https://github.com/kumahq/kuma/issues/5127#issuecomment-1273432061

**Comment by jakubdyszkiewicz** [comment]
> Will deploy tomorrow and test.

please do. We fixed a bug that was visible when using Kuma on Universal without transparent proxy (your case).
https://github.com/kumahq/kuma/blob/master/CHANGELOG.md

> What are you referring here to as server and what is a client?

I assume that `collector-online` is a server and there is a client that tries to connect to this service.
I'd need config dump / stats / clusters from both (you can execute it via Kuma GUI now).

**Comment by Tahvok** [comment]
I have just tested 1.8.1 and it is working!
We were running 1.8.0 before that.
Thank you
