### ISSUE TITLE
When validating `Dataplane` resource, make sure that all `inbound` and `outbound` interfaces are unique and don't overshadow one another

### ISSUE THREAD

**Issue by yskopets** [kumahq/kuma#513]
### Summary

* When validating `Dataplane` resource, make sure that all `inbound` and `outbound` interfaces are unique and don't overshadow one another
   * it's invalid for an `inbound` listener to be bound to `0.0.0.0` interface (control plane cannot use this IP in configuration of an `Endpoint` that represents this `Dataplane`)
   * every `inbound` listener must have a unique `interface`, e.g.
     * it's invalid to have two `inbound` listeners bound to the same `192.168.0.1:8080` interface
   * every `outbound` listener must have a unique `interface`, e.g.
     * it's invalid to have two `outbound` listeners bound to the same `:8080` interface
     * it's invalid to have two `outbound` listeners where one is bound to `:8080` interface and another is bound to `0.0.0.0:8080` interface 
   * `outbound` interfaces must not overshadow `inbound` interfaces, e.g.
      * if a `Dataplane` has an `inbound` interface `192.168.0.1:80:8080` it would be invalid to have the following `outbound` interfaces:
         * `:8080` or `0.0.0.0:8080` (both overshadow application port `8080`)
         * `192.168.0.1:80` or `0.0.0.0:80` (both overshadow `inbound`  dataplane port `80`)
   * prometheus endpoint (configured via `metrics.prometheus`) must not overshadow `inbound` interfaces, `outbound` interfaces, original application
     * we're already checking this at the moment when we generate Envoy config (because `Mesh`-wide Prometheus settings might be updated after a `Dataplane` has been created/updated)
     * additionally, we need to check it at `Dataplane` modification time as well

**Comment by lahabana** [comment]
#2799 also suggests an annotation for precedence in case of Clashes which probably makes sense.
In the absence of precedence we should have a total order of services for k8s (headless > clusterIP > alphanumeric).

**Comment by lahabana** [comment]
Note the slightly related [ignore annotation](https://github.com/kumahq/kuma/pull/3142) which is the opposite of the `primary service` exposed in #2799

**Comment by lahabana** [comment]
Triage: Users don't seem to be hitting this so please re-open if you are hitting it :)
