### ISSUE TITLE
Sync ContainerPatch resources across zones

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#5135]
### Description

It's common to apply a ContainerPatch across a whole mesh, we should propagate this from the global to avoid having to apply it to each zone individually.

**Comment by jakubdyszkiewicz** [comment]
> Triage: not trivial to implement. ContainerPatch is not a core resource so it's not taken into account in KDS.

**Comment by lahabana** [comment]
I strongly think that containerPatch is part of the Kuma cp configuration, it would therefore not be synced across clusters.
