### ISSUE TITLE
Adding ways to add tolerations to the Kuma deployment using helm

### ISSUE THREAD

**Issue by parjun8840** [kumahq/kuma#5136]
### Description

**Adding ways to add tolerations to the Kuma deployment using helm.**
We run the Pods in a controlled environment and Pods are scheduled only on the designated planned nodes.
The problem with the current Kuma Helm chart is it doesn't have provision to specify the Tolerations and as a result of which pods go into pending state-

```
NAME                              READY   STATUS    RESTARTS   AGE
kuma-install-missing-crds-chp87   0/1     Pending   0          86m
```

In the values.yaml there has to be option to specify tolerations for the components, example:

> Job- 
> https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/templates/pre-install-patch-namespace-job.yaml#:~:text=%2D%2D%2D-,apiVersion%3A%20batch/v1,%7B%7B%2D%20end%20%7D%7D,-Footer
> 

> Egress deployment- 
> https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/templates/egress-deployment.yaml

Please modify the charts templates and provide a provision to specify those tolerations in the values.yaml file- https://github.com/kumahq/kuma/blob/master/deployments/charts/kuma/values.yaml

**Comment by rghdrizzle** [comment]
Hey I would like to work on this .

**Comment by lahabana** [comment]
@rghdrizzle let us know if you need any help!

**Comment by KrustyHack** [comment]
Ay,

I'm trying to do a PR to solves this problem : https://github.com/kumahq/kuma/pull/5549.
