### ISSUE TITLE
Create a proposal to include Envoy configuration errors into `DataplaneInsights`

### ISSUE THREAD

**Issue by yskopets** [kumahq/kuma#516]
### Summary

* Create a proposal to include Envoy configuration errors into `DataplaneInsights` to make them visible via any supported interface, i.e. `kumactl`, `Kuma UI`, REST API
* Or maybe we should revisit `Alerts` / `Warnings` we discussed in the past ?

**Comment by jakubdyszkiewicz** [comment]
Envoy config is huge. This will be too heavy to put into DataplaneInsights. What we want to do eventually is provide the capability for CP to connect to the Admin of DP to fetch the config. Closing.

**Comment by jpeach** [comment]
It sounds like this issue is about surfacing errors, not necessarily the whole configuration.
