### ISSUE TITLE
kuma control plane metrics endpoint is sending incorrect data

### ISSUE THREAD

**Issue by brunda-bs** [kumahq/kuma#5193]
### What happened?

Hi Team,

After upgrading kuma from 1.6.0 to 1.6.2 version in a multi-zone setup, We are observing incorrect data in /metrics endpoint of the kuma control plane.

**Scenario 1 :** 
Port forward the kuma control plane pod on port 5680 which is running as leader -
`kubectl port-forward pod/kuma-control-plane-dd4687b45-6mpjc  -n kuma-system 5680:5680`

Getting the correct data such as-
```
# TYPE leader gauge
leader{zone="Global"} 1
# TYPE resources_count gauge
resources_count{resource_type="CircuitBreaker",zone="Global"} 1
resources_count{resource_type="Config",zone="Global"} 5
resources_count{resource_type="Dataplane",zone="Global"} 34
```

**Scenario 2:**

Port forward the kuma control plane service on port 5680 -
`kubectl port-forward svc/kuma-control-plane   -n kuma-system 5680:5680   `

Getting incorrect data such as-
```
# TYPE leader gauge
leader{zone="Global"} 0
```
And resources_count metrics are not available.

Please help us with this.

**Comment by lahabana** [comment]
This behaviour is expected to avoid hitting too strongly on the store. In the end in prometheus you still always have the correct data (there's a single leader as indicated by the stat).

**Comment by brunda-bs** [comment]
Hi @lahabana, 

We are scraping the metrics using open telemetry collector. We still see the incorrect data in the dashboard(Datadog). The metrics in the dashboard is in sync with the incorrect metrics we see when we port forward the service.

**Comment by lahabana** [comment]
Sorry my first comment was unclear; there's no incorrect data.
1. There's only 1 leader which is why `leader{zone="Global"}=1` is only `1` on the leader CP.
2. If all CPs would report the resources_count stats you would end up double counting all resources as they'd end being rolled up. This is why only the leader report these stats. 

What is the actual issue in datadog? can you not create a dashboard with these metrics? If so why? I'd like to understand what you are trying to do here.

**Comment by brunda-bs** [comment]
Hi @lahabana,

Thanks for explaining. I understand the reason why there is only one instance of CP running as the leader and only that instance returns as ` leader{zone="Global"}=1`. In other instances, as they are not the leader they would return ` leader{zone="Global"}=0`.  We don't have an issue with that.

We are receiving incorrect metrics when we port forward the `Service` - "kuma-control-plane"

The traffic coming to the service endpoint should return the metrics from the leader instance as ` leader{zone="Global"}=1`

But we are receiving ` leader{zone="Global"}=0`. Since we are scraping the metrics from the service, we are seeing the leader is down in the dashboard even when the Kuma control plane is healthy and the leader is up.

**Comment by jakubdyszkiewicz** [comment]
> Triage: Kuma's metrics are designed in a way that they need to be scraped for every instance.
