### ISSUE TITLE
Move type,name,mesh to endpoints.yaml

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5213]
### Description

Currently we have:

https://github.com/kumahq/kuma/blob/6a019b2b0cd49f6b169768d13b3bfdc9783c894c/tools/policy-gen/templates/schema.yaml#L1-L11

this should move in:

https://github.com/kumahq/kuma/blob/master/tools/policy-gen/templates/endpoints.yaml

This would avoid building buggy schema like: https://github.com/kumahq/kuma/blob/master/pkg/plugins/policies/meshaccesslog/api/v1alpha1/schema.yaml 

Note there's no "spec"

**Comment by ADITYADAS1999** [comment]
> ### Description
> Currently we have:
> 
> https://github.com/kumahq/kuma/blob/6a019b2b0cd49f6b169768d13b3bfdc9783c894c/tools/policy-gen/templates/schema.yaml#L1-L11
> 
> this should move in:
> 
> https://github.com/kumahq/kuma/blob/master/tools/policy-gen/templates/endpoints.yaml
> 
> This would avoid building buggy schema like: https://github.com/kumahq/kuma/blob/master/pkg/plugins/policies/meshaccesslog/api/v1alpha1/schema.yaml
> 
> Note there's no "spec"



So we have to move the schema.yaml to endpoints.yaml ??

**Comment by lahabana** [comment]
Only for type, mesh and name yes

**Comment by ADITYADAS1999** [comment]
> Only for type, mesh and name yes

okey

**Comment by ADITYADAS1999** [comment]
> Only for type, mesh and name yes

openapi: 3.0.1
info:
  version: {{ .Package }}
  title: Kuma API
  description: Kuma API

type: 
   description: '' 
   type: string 
mesh: 
   description: 'Mesh is the name of the Kuma mesh this resource belongs to. 
       It may be omitted for cluster-scoped resources.' 
   type: string 
name: 
   description: 'Name of the Kuma resource' 
   type: string 

paths:
  /meshes/{mesh}/{{ .Path }}/{name}:
    get:
      summary: Returns {{ .Name }} entity
      tags: [ "{{ .Name }}" ]
      parameters:
        - in: path
          name: mesh
          schema:
            type: string
          required: true
          description: name of the mesh
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the {{ .Name }}
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: 'schema.yaml'

    put:
      summary: Creates or Updates {{ .Name }} entity
      tags: [ "{{ .Name }}" ]
      parameters:
        - in: path
          name: mesh
          schema:
            type: string
          required: true
          description: name of the mesh
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the {{ .Name }}
      requestBody:
        description: {{ .Name }} entity
        required: true
        content:
          application/json:
            schema:
              $ref: 'schema.yaml'
      responses:
        '200':
          description: Updated
        '201':
          description: Created

    delete:
      summary: Deletes {{ .Name }} entity
      tags: [ "{{ .Name }}" ]
      parameters:
        - in: path
          name: mesh
          schema:
            type: string
          required: true
          description: name of the mesh
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the {{ .Name }}
      responses:
        '200':
          description: Successful response


  /meshes/{mesh}/{{ .Path }}:
    get:
      summary: Returns a list of {{ .Name }} in the mesh.
      tags: [ "{{ .Name }}" ]
      parameters:
        - in: path
          name: mesh
          schema:
            type: string
          required: true
          description: name of the mesh
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: 'schema.yaml'
                  next:
                    type: string
                    description: URL to the next page


  /{{ .Path }}:
    get:
      summary: Returns a list of {{ .Name }} from all meshes
      tags: [ "{{ .Name }}" ]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: 'schema.yaml'
                  next:
                    type: string
                    description: URL to the next page

**Comment by ADITYADAS1999** [comment]
```
openapi: 3.0.1
info:
  version: {{ .Package }}
  title: Kuma API
  description: Kuma API


type: 
  description: '' 
  type: string 
mesh: 
  description: 'Mesh is the name of the Kuma mesh this resource belongs to. 
       It may be omitted for cluster-scoped resources.' 
  type: string 
name: 
  escription: 'Name of the Kuma resource' 
  type: string 

paths:
  /meshes/{mesh}/{{ .Path }}/{name}:
    get:
      summary: Returns {{ .Name }} entity
      tags: [ "{{ .Name }}" ]
      parameters:
        - in: path
          name: mesh
          schema:
            type: string
          required: true
          description: name of the mesh
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the {{ .Name }}
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: 'schema.yaml'

    put:
      summary: Creates or Updates {{ .Name }} entity
      tags: [ "{{ .Name }}" ]
      parameters:
        - in: path
          name: mesh
          schema:
            type: string
          required: true
          description: name of the mesh
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the {{ .Name }}
      requestBody:
        description: {{ .Name }} entity
        required: true
        content:
          application/json:
            schema:
              $ref: 'schema.yaml'
      responses:
        '200':
          description: Updated
        '201':
          description: Created

    delete:
      summary: Deletes {{ .Name }} entity
      tags: [ "{{ .Name }}" ]
      parameters:
        - in: path
          name: mesh
          schema:
            type: string
          required: true
          description: name of the mesh
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the {{ .Name }}
      responses:
        '200':
          description: Successful response


  /meshes/{mesh}/{{ .Path }}:
    get:
      summary: Returns a list of {{ .Name }} in the mesh.
      tags: [ "{{ .Name }}" ]
      parameters:
        - in: path
          name: mesh
          schema:
            type: string
          required: true
          description: name of the mesh
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: 'schema.yaml'
                  next:
                    type: string
                    description: URL to the next page


  /{{ .Path }}:
    get:
      summary: Returns a list of {{ .Name }} from all meshes
      tags: [ "{{ .Name }}" ]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: 'schema.yaml'
                  next:
                    type: string
                    description: URL to the next page

```

**Comment by ADITYADAS1999** [comment]
> Only for type, mesh and name yes

can you check the code snippet any other modification needed or not , So I send the PR

**Comment by lahabana** [comment]
These are not parameters in the request they are fields in the schema of the response

**Comment by lahabana** [comment]
Yes

**Comment by ADITYADAS1999** [comment]
> These are not parameters in the request they are fields in the schema of the response

```

openapi: 3.0.1
info:
  version: {{ .Package }}
  title: Kuma API
  description: Kuma API

paths:
  /meshes/{mesh}/{{ .Path }}/{name}:
    get:
      summary: Returns {{ .Name }} entity
      tags: [ "{{ .Name }}" ]
      parameters:
        - in: path
          name: mesh
          schema:
            type: string
          required: true
          description: name of the mesh
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the {{ .Name }}
      responses:
         type: 
     description: '' 
     type: string 
   mesh: 
     description: 'Mesh is the name of the Kuma mesh this resource belongs to. 
       It may be omitted for cluster-scoped resources.' 
     type: string 
   name: 
     description: 'Name of the Kuma resource' 
     type: string 
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: 'schema.yaml'
                   

    put:
      summary: Creates or Updates {{ .Name }} entity
      tags: [ "{{ .Name }}" ]
      parameters:
        - in: path
          name: mesh
          schema:
            type: string
          required: true
          description: name of the mesh
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the {{ .Name }}
      requestBody:
        description: {{ .Name }} entity
        required: true
        content:
          application/json:
            schema:
              $ref: 'schema.yaml'
      responses:
         type: 
     description: '' 
     type: string 
   mesh: 
     description: 'Mesh is the name of the Kuma mesh this resource belongs to. 
       It may be omitted for cluster-scoped resources.' 
     type: string 
   name: 
     description: 'Name of the Kuma resource' 
     type: string 
        '200':
          description: Updated
        '201':
          description: Created

    delete:
      summary: Deletes {{ .Name }} entity
      tags: [ "{{ .Name }}" ]
      parameters:
        - in: path
          name: mesh
          schema:
            type: string
          required: true
          description: name of the mesh
        - in: path
          name: name
          schema:
            type: string
          required: true
          description: name of the {{ .Name }}
      responses:
         type: 
     description: '' 
     type: string 
   mesh: 
     description: 'Mesh is the name of the Kuma mesh this resource belongs to. 
       It may be omitted for cluster-scoped resources.' 
     type: string 
   name: 
     description: 'Name of the Kuma resource' 
     type: string 
        '200':
          description: Successful response


  /meshes/{mesh}/{{ .Path }}:
    get:
      summary: Returns a list of {{ .Name }} in the mesh.
      tags: [ "{{ .Name }}" ]
      parameters:
        - in: path
          name: mesh
          schema:
            type: string
          required: true
          description: name of the mesh
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: 'schema.yaml'
                  next:
                    type: string
                    description: URL to the next page


  /{{ .Path }}:
    get:
      summary: Returns a list of {{ .Name }} from all meshes
      tags: [ "{{ .Name }}" ]
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: 'schema.yaml'
                  next:
                    type: string
                    description: URL to the next page
```

**Comment by ADITYADAS1999** [comment]
> > These are not parameters in the request they are fields in the schema of the response
> 
> ```
> 
> openapi: 3.0.1
> info:
>   version: {{ .Package }}
>   title: Kuma API
>   description: Kuma API
> 
> paths:
>   /meshes/{mesh}/{{ .Path }}/{name}:
>     get:
>       summary: Returns {{ .Name }} entity
>       tags: [ "{{ .Name }}" ]
>       parameters:
>         - in: path
>           name: mesh
>           schema:
>             type: string
>           required: true
>           description: name of the mesh
>         - in: path
>           name: name
>           schema:
>             type: string
>           required: true
>           description: name of the {{ .Name }}
>       responses:
>          type: 
>      description: '' 
>      type: string 
>    mesh: 
>      description: 'Mesh is the name of the Kuma mesh this resource belongs to. 
>        It may be omitted for cluster-scoped resources.' 
>      type: string 
>    name: 
>      description: 'Name of the Kuma resource' 
>      type: string 
>         '200':
>           description: Successful response
>           content:
>             application/json:
>               schema:
>                 $ref: 'schema.yaml'
>                    
> 
>     put:
>       summary: Creates or Updates {{ .Name }} entity
>       tags: [ "{{ .Name }}" ]
>       parameters:
>         - in: path
>           name: mesh
>           schema:
>             type: string
>           required: true
>           description: name of the mesh
>         - in: path
>           name: name
>           schema:
>             type: string
>           required: true
>           description: name of the {{ .Name }}
>       requestBody:
>         description: {{ .Name }} entity
>         required: true
>         content:
>           application/json:
>             schema:
>               $ref: 'schema.yaml'
>       responses:
>          type: 
>      description: '' 
>      type: string 
>    mesh: 
>      description: 'Mesh is the name of the Kuma mesh this resource belongs to. 
>        It may be omitted for cluster-scoped resources.' 
>      type: string 
>    name: 
>      description: 'Name of the Kuma resource' 
>      type: string 
>         '200':
>           description: Updated
>         '201':
>           description: Created
> 
>     delete:
>       summary: Deletes {{ .Name }} entity
>       tags: [ "{{ .Name }}" ]
>       parameters:
>         - in: path
>           name: mesh
>           schema:
>             type: string
>           required: true
>           description: name of the mesh
>         - in: path
>           name: name
>           schema:
>             type: string
>           required: true
>           description: name of the {{ .Name }}
>       responses:
>          type: 
>      description: '' 
>      type: string 
>    mesh: 
>      description: 'Mesh is the name of the Kuma mesh this resource belongs to. 
>        It may be omitted for cluster-scoped resources.' 
>      type: string 
>    name: 
>      description: 'Name of the Kuma resource' 
>      type: string 
>         '200':
>           description: Successful response
> 
> 
>   /meshes/{mesh}/{{ .Path }}:
>     get:
>       summary: Returns a list of {{ .Name }} in the mesh.
>       tags: [ "{{ .Name }}" ]
>       parameters:
>         - in: path
>           name: mesh
>           schema:
>             type: string
>           required: true
>           description: name of the mesh
>       responses:
>         '200':
>           description: Successful response
>           content:
>             application/json:
>               schema:
>                 type: object
>                 properties:
>                   items:
>                     type: array
>                     items:
>                       $ref: 'schema.yaml'
>                   next:
>                     type: string
>                     description: URL to the next page
> 
> 
>   /{{ .Path }}:
>     get:
>       summary: Returns a list of {{ .Name }} from all meshes
>       tags: [ "{{ .Name }}" ]
>       responses:
>         '200':
>           description: Successful response
>           content:
>             application/json:
>               schema:
>                 type: object
>                 properties:
>                   items:
>                     type: array
>                     items:
>                       $ref: 'schema.yaml'
>                   next:
>                     type: string
>                     description: URL to the next page
> ```

[lahabana](https://github.com/lahabana) can you check this one.
