### ISSUE TITLE
give possibility for cp logs to be json formatted

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5224]
### Description

At the moment logs are in logfmt, there are a lot of places that would prefer json format

**Comment by johnharris85** [comment]
As this is marked `good-first-issue`, can we add a little more context / an example of the change @lahabana ?

**Comment by lahabana** [comment]
Currently we set loggers in app startup like: https://github.com/kumahq/kuma/blob/master/app/kuma-cp/cmd/root.go#L46-L48

We then configure the: https://github.com/kumahq/kuma/blob/ba71efa93067e54cc0d01107f069da7c65ff1e05/pkg/log/logger.go#L67-L88

It seems like we should have an option passed and set here: https://github.com/kumahq/kuma/blob/ba71efa93067e54cc0d01107f069da7c65ff1e05/pkg/log/logger.go#L67-L88

So instead of having logs like: `2023-05-10T16:13:35.696+0200	INFO	intercp-server	starting	{"interface": "0.0.0.0", "port": 5683, "tls": true}`

We have full JSON like: `{"L":"INFO","T":"2023-05-10T16:15:00.561+0200","N":"mesh-insight-resyncer","M":"done"}`
It might be as simple as moving from `zapcore.NewConsoleEncoder` to `zapcore.NewJSONEncoder` according to cmd line flag.

The kong internal madr for logging format suggests: 
```json
{
    "ts": "UTC Date string e.g. 2021-09-22T20:17:12.187Z *OR* Epoch time int in nanosecs e.g. 1632341832187897068", # required
    "level": "log level e.g. (debug|info|warn|error}", #required
    "msg": "log message body", # required
    "caller": "method:line e.g. table.go:442",
    "geo" : "us|eu|jp|ap",
    "region" : "us-east-2|us-west-2|eu-central-1|etc.."
    "service": "Service name e.g. kauth" #required
    "service_version": "Service version or docker-tag e.g. v0.1.88" #required
    "trace_id": "Datadog distributed traceID, i.e. `x-datadog-trace-id`",
    "org_id": "Konnect organization uuid",
    "principal_id": "kauth principal id being used for an action, usually the user uuid",
    "actor_id": "the value of `act.sub` claim in an jwt, if applicable"
    "duration": "call duration in ns",
    "client_ip": "10.0.0.1", # from `x-forwarded-for` header if available, otherwise the client ip from the inbound connection
    "request": {  # REST,HTTP,GRPC Headers/Details
                  # GRPC follow the conventions in https://github.com/grpc/grpc/blob/master/doc/PROTOCOL-HTTP2.md
      "method": "HTTP method e.g. (POST|GET|...)",
      "headers": {“Referrer”: “...”, … },
    },
    "status": "http/http2 status codes",
    "uri": "API endpoint uri",
    "stack_trace": ["trace line 1", "trace line N"],
 }
```

I guess the cmd line arg should be: `--log-format logfmt|json` where logfmt is the default

**Comment by lahabana** [comment]
Noone is asking for this. Let's reopen if needed
