### ISSUE TITLE
kuma-cp memory leak

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#5227]
### What happened?

A Kuma user reported an issue on [slack](https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1666267068497759) that 
the CP grows in memory until it is killed by OOM. Below are the screenshots and a heap dump.

2 first screenshots are from the same period of time.

<img width="455" alt="Screenshot 2022-10-20 at 5 27 15 PM" src="https://user-images.githubusercontent.com/2753650/198531037-5f03ba9c-0c4d-4ce8-8fc9-13175db815a8.png">
<img width="455" alt="Screenshot 2022-10-20 at 5 27 25 PM" src="https://user-images.githubusercontent.com/2753650/198531044-465cf664-ef6f-43b9-aa1d-f03891918ffd.png">

Same period of time as well:
<img width="455" src="https://user-images.githubusercontent.com/2753650/198546164-1d2e0956-bc82-45bf-b83e-2c1dffedb7c1.png">
<img width="455" src="https://user-images.githubusercontent.com/2753650/198546330-13f3db86-bf9d-4349-b272-7913848bca28.png">
<img width="455" src="https://user-images.githubusercontent.com/2753650/198546404-57451df8-7d49-4eab-a6c7-56106c420feb.png">

[heap5.out.zip](https://github.com/kumahq/kuma/files/9886286/heap5.out.zip)

We can see that memory correlates with the number of DPs connected (which is normal) but at ~6AM 10/19 the number of connected DPs is ~300 and the memory usage is ~30% and the next day with the same number of DPs connected we have 35%. Seems like we might be leaking some memory on disconnecting.

**Comment by lukidzi** [comment]
I've tried to reproduce it without success. I've created universal CP with postgres and tried to create a bunch of connections but after scaling the connections up and down I didn't notice any problem. Could you try to upgrade Kuma to version 2.0 and check if the issue is still present? In 2.0 we have introduced a performance optimization that reduces CPU usage and optimaze Endpoints map rebuilding. In case of bigger traffic that optimization might reduce number of memory allocated during rebuilding the map.

**Comment by slonka** [comment]
I think we need to get the policies from the people who reported this, maybe we're leaking somewhere in a policy? Also even if this goes away with 2.0 we should still investigate how to deal with such situations (a way to create and analyse a heap dump somewhere in docs).

**Comment by lukidzi** [comment]
The issue is that the thing we get is not a heap dump, but a heap profile. It shows allocation in the specific time frame. The heap dump shows the objects that are on the heap. We can get the [heap dump by calling ](https://pkg.go.dev/runtime/debug#WriteHeapDump) but there are no tools to analyze it.

**Comment by slonka** [comment]
I know that we've got a heap profile and that's my exact point - we can think about introducing an endpoint like `/debug/heap-dump` that would generate a heap dump (that would be more useful in this case). And then we should at least report a need for a tool to analyse it to the golang issue tracker.

**Comment by slonka** [comment]
Tried to reproduce this again and did more research into tools.

Heap dumps:
- It seems that with the current go version there is no way to perform a heap dump that has the [type information](https://github.com/randall77/hprof/pull/6#pullrequestreview-111066791) and without it it's pretty useless
- I tried poking around (kuma branch with [heap dumps](https://github.com/kumahq/kuma/compare/master...slonka:kuma:feat-heap-dump?expand=1) enabled, modified version of [hprof export](https://github.com/jbarciauskas/hprof/compare/master...slonka:go-heap-to-hprof:fix-dump-to-hprof?expand=1)) with it to check that the above statement is true and I couldn't find a way to tie objects to types

Core dumps:
- viewcore - from [this fork](https://github.com/zchee/golang-debug/) that supposed to have a fix for new go versions fails with "bad magic sequence ..."
- according [to this](https://cockroachlabs.atlassian.net/wiki/spaces/CRDB/pages/1931018299/Using+viewcore+to+analyze+core+dumps#How-to-install-viewcore) - "as of 2021, viewcore is not actively maintained by the Go team" so not sure if that would ever work

So as of right now I don't think there is a way to easily detect **really slow** memory leaks in go (or we're missing some knowledge in how to use pprof to do this) and the fact that we were not able to reproduce this with Lukasz seems to indicate that the code responsible for the leak is triggered by some policy that the user has defined (we need to get all of them to try to reproduce again).

**Comment by lahabana** [comment]
We were never able to reproduce this
