### ISSUE TITLE
Generate systemd files

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#5279]
### Description

Can we provide a kumactl command to generate systemd files for universal components?

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's do this https://github.com/kumahq/kuma-website/issues/1146 as a first step

**Comment by jakubdyszkiewicz** [comment]
Is https://kuma.io/docs/2.8.x/production/cp-deployment/systemd/#systemd enough?

**Comment by michaelbeaumont** [comment]
Yes.
