### ISSUE TITLE
Setup Mastodon account for Kuma?

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#5283]
### Description

Lot of tech folks seem to be migrating to / also creating accounts on Mastodon. I wonder if we should have a presence there somewhere, maybe the CNCF has thoughts? Numerous tools would allow us to cross-post to both.

**Comment by slonka** [comment]
Any updates, have you reached out to CNCF @johnharris85 ?

**Comment by slonka** [comment]
Any updates @johnharris85 ?

**Comment by johnharris85** [comment]
It was done and is being managed by Marketing. Can be closed.
