### ISSUE TITLE
Add eBPF to insights / DPP information

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#5285]
### Description

We'd like to surface whether a DPP is eBPF-enabled (or iptables or cni) in the UI, this will require a little info in the backend to surface it the API response. Blocking https://github.com/kumahq/kuma-gui/issues/446

**Comment by jakubdyszkiewicz** [comment]
> Triage: we can pipe it via XDS metadata and add to DataplaneInsight
> It's hard to determine this on kuma-dp level
> We start with Kubernetes for now
