### ISSUE TITLE
Error: Failed to generate Envoy bootstrap config. invalid character 'a' looking for beginning of value

### ISSUE THREAD

**Issue by brunda-bs** [kumahq/kuma#5303]
### What happened?

Hi,

We are trying to upgrade Kuma from 1.6.2 to 1.8.1 in a multi-zone environment. The global control plane upgrade is working completely fine. But in the zonal control plane, one of the ingress and egress instance is going into the crashloopbackoff state for a couple of times with the below error and coming back to the running state later on.

> brundabs@MMDC ~ % kubectl logs po/kuma-egress-74f9757d67-5g9gj -n kuma-system --previous
> 2022-11-10T13:14:44.780Z	INFO	Skipping reading config from file
> 2022-11-10T13:14:44.780Z	INFO	kuma-dp.run	effective configuration	{"config": "{\"controlPlane\":{\"caCert\":\"\",\"caCertFile\":\"/var/run/secrets/kuma.io/tls-cert/ca.crt\",\"retry\":{\"backoff\":\"3s\",\"maxDuration\":\"5m0s\"},\"url\":\"https://kuma-control-plane.kuma-system:5678/\"},\"dataplane\":{\"drainTime\":\"30s\",\"name\":\"kuma-egress-74f9757d67-5g9gj.kuma-system\",\"proxyType\":\"egress\"},\"dataplaneRuntime\":{\"binaryPath\":\"envoy\",\"dataplaneTokenPath\":\"/var/run/secrets/kubernetes.io/serviceaccount/token\"},\"dns\":{\"coreDnsBinaryPath\":\"coredns\",\"coreDnsEmptyPort\":15055,\"coreDnsPort\":15053,\"enabled\":true,\"envoyDnsPort\":15054,\"prometheusPort\":19153}}"}
> 2022-11-10T13:14:44.781Z	INFO	kuma-dp.run	generated configurations will be stored in a temporary directory	{"dir": "/tmp/kuma-dp-445943790"}
> 2022-11-10T13:14:44.814Z	INFO	kuma-dp.run	fetched Envoy version	{"version": {"Build":"ae27fb5280d30e1400b7e9c9cbd448bfcd4ad9f5/1.22.1/Modified/RELEASE/BoringSSL","Version":"1.22.1","KumaDpCompatible":true}}
> 2022-11-10T13:14:44.814Z	INFO	kuma-dp.run	generating bootstrap configuration
> 2022-11-10T13:14:44.814Z	INFO	dataplane	trying to fetch bootstrap configuration from the Control Plane
> Error: Failed to generate Envoy bootstrap config. invalid character 'a' looking for beginning of value

We are having 3 instance of controlplane, ingress and egress running in the zonal clusters.

> brundabs@MMDC02FV5W6MD6R ~ % kubectl get pods -n kuma-system                            
NAME                                 READY   STATUS    RESTARTS      AGE
kuma-control-plane-7f988fb86-4jg4j   1/1     Running   0             85m
kuma-control-plane-7f988fb86-f6sgx   1/1     Running   0             92m
kuma-control-plane-7f988fb86-xcbgn   1/1     Running   0             92m
kuma-egress-74f9757d67-4998k         1/1     Running   3 (92m ago)   93m
kuma-egress-74f9757d67-8j9dn         1/1     Running   0             91m
kuma-egress-74f9757d67-lkxj2         1/1     Running   0             92m
kuma-ingress-6f9698476d-h2pm2        1/1     Running   3 (92m ago)   93m
kuma-ingress-6f9698476d-jr72d        1/1     Running   0             92m
kuma-ingress-6f9698476d-l9nls        1/1     Running   0             91m

**Comment by jakubdyszkiewicz** [comment]
> Triage:
> What happens here is that we support compatibility of old DPPs connecting to the new CPs
> https://kuma.io/docs/2.0.x/documentation/upgrades/
> This does not happen with sidecars, but it can happen for a short period of time with Zone Egress and Ingress because when you upgrade Kuma, CP+ZoneEgress+ZoneIngress `Deployments` are applied at the same time.
> You should not see this issue anymore (as you can see with other instances).
