### ISSUE TITLE
Redirect requests to resources under the GUI path that aren’t static resources to the index.html file

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma#5306]
## Problem

Currently, the server is not configured to redirect non-asset resources back to the index.html file that serves our Vue application. This breaks part of the Vue application’s routing since changing the app’s URLs to no longer use hashes. Specifically, reloading a page doesn’t work. In-application navigations work.

## Solution

Redirect all requests made to resources under the GUI path (e.g. `/gui/*`, configurable via https://github.com/kumahq/kuma/pull/5295) to the GUI’s index.html file (e.g. `/gui/index.html`) **if they’re not handled by already** (like static assets or the config.json asset added in https://github.com/kumahq/kuma/pull/5295).

If that solution isn’t feasible, I’ll have to revert the changes to the URL structure.

See also https://router.vuejs.org/guide/essentials/history-mode.html.

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's do 301

**Comment by kleinfreund** [comment]
Maybe we don’t need to look at the static file handling at all. As long as we can detect requests to the GUI path (which since https://github.com/kumahq/kuma/pull/5295 is configurable) when handling requests _after_ static file handling is done and _before_ the piece of logic for error handling runs (i.e. which produces the standard 404 response), we should be able to redirect anything under `$guiUrl` to `$guiUrl/index.html` because all other static resources would be handled by the earlier layer, no?

**Comment by lahabana** [comment]
This could be a workable option: https://groups.google.com/g/golang-nuts/c/Phk9r4IgfM8/m/GHISBKMQ2FsJ?pli=1
