### ISSUE TITLE
ServiceProbe is broken with transparent proxying Universal

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#5335]
### What happened?

Steps to reproduce run `should not load balance requests to unhealthy instance` on `UniCluster1` or manually
1. Spawn Envoy with Application on Unviersal with Transparent Proxying
2. Kill app
3. See that Envoy reports that the app is healthy.

After digging deeper it is caused by https://github.com/kumahq/kuma/issues/4630
When the regular traffic goes to the Envoy, it goes through the inbound listener, then to cluster that has set `upstream bind config`. This modifies the source address+port so iptables can pass this traffic further.

When the traffic is initiated by Envoy with HC it does not use the cluster therefore it does not have changed bind config.

Potential solutions that we quickly discussed:
1) Modify Envoy HDS to let it override upstream bind config
2) Move HDS to kuma-dp Go process (requires rebuilding HDS client etc.)

**Comment by jakubdyszkiewicz** [comment]
Will be solved by https://github.com/envoyproxy/envoy/pull/24053

**Comment by michaelbeaumont** [comment]
Will be solved in Envoy `v1.25`
