### ISSUE TITLE
Support multi-layered service topology

### ISSUE THREAD

**Issue by conman2305** [kumahq/kuma#5338]
### Description

Right now with Kuma, we can enable locality aware load balancing to prefer traffic stay within the same zone, but this quickly falls apart in a multi-zone deployment where a destination service is already in a different zone than the source service, but is still within the same cloud region.

In our use case, we use multiple zones within the same cloud region to facilitate independent administration of related services. What then happens is when serviceA in one zone wants to access serviceB in another zone, that request to serviceB is globally load balanced across _all_ instances of serviceB, whereas we would prefer that request stay within the same cloud region (unless there are no instances available in that region).

Essentially, it would be an awesome feature if Kuma could support service topology similar to Istio and Consul where there are tiers of locality aware load-balancing. Istio and Consul do this by looking at the `topology.kubernetes.io/zone` and `topology.kubernetes.io/region` annotations, but a better implementation could be to allow dataplanes to specify their region similarly to how they specify their zone name today. Dataplanes in the same region would receive a higher Envoy priority than Dataplanes in a different region. Perhaps as an even more advanced feature, live latency statistics could be used to dynamically build this topology as well so that Envoy always prioritizes the "closest" Dataplane.

**Comment by jakubdyszkiewicz** [comment]
Hey,

thanks for the report. It is a valid issue, but I'm closing this in favor of https://github.com/kumahq/kuma/issues/5338
Implementing 5338 would solve what you described.
