### ISSUE TITLE
Decide priority of targetRef and S&D policies and make it consistent across implementations

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#5350]
### What happened?

In my opinion we should have a consistent way of deciding which policy is applied when two functionally similar policies are used (e.g. TrafficLog and MeshAccessLog, TrafficPermission and MeshTrafficPermission, etc.).

Right now only `MeshTrafficPermission` has this - https://github.com/kumahq/kuma/blob/master/pkg/plugins/policies/meshtrafficpermission/xds/rbac_configurer.go#L31 (`MeshTrafficPermission` will take precedence over `TrafficPermission`).

The best solution would be to have this in the generator so that once we start heavily working on new permissions everything is consistent.

**Comment by jakubdyszkiewicz** [comment]
Dup of https://github.com/kumahq/kuma/issues/5039
