### ISSUE TITLE
Allow a port range in the external service

### ISSUE THREAD

**Issue by brunda-bs** [kumahq/kuma#5356]
### Description

Hi Team,

Is there a way to specify a port range for a host in the external service resource? Currently we are using Azure SQL Database and it is required to open the "11000-11999" port range from the backend application to the DB host.

Currently, the external service is accepting only the Hostname and a port number.
```
 networking:
    address: <HOST>:<PORT>
```

**Comment by brunda-bs** [comment]
I tried the exclude outbound port annotation for the port range as mentioned in the ticket - https://github.com/kumahq/kuma/issues/5082.  But the moment we add a port range in that annotation, Kuma DNS resolution is failing from the pod(In which the annotation is present)


```
* Could not resolve host: athena-ipw-svc.kuma-demo.svc.3000.mesh
* Closing connection 0
curl: (6) Could not resolve host: athena-ipw-svc.kuma-demo.svc.3000.mesh
```

**Comment by jakubdyszkiewicz** [comment]
> Triage:
> Any logs from DP?
> Does the DNS resolution also fail if you put only one value? `traffic.kuma.io/exclude-outbound-ports: "1433"`?

**Comment by brunda-bs** [comment]
Hi @jakubdyszkiewicz, For a single port number in the outbound annotation,  DNS resolution works fine. But only when there is a range, then the DNS resolution for other services is failing.

**Comment by jakubdyszkiewicz** [comment]
> Triage: a couple of things:
> We do not support ranges in `traffic.kuma.io/exclude-outbound-ports: "11000-11999"` that's a feature request.
> 
> We are struggling to understand the setup here. Did you disable outbound passthrough on the Mesh object? Connectivity to things outside the mesh should just work with regular DNS names.

**Comment by brunda-bs** [comment]
Hi @jakubdyszkiewicz , Yes we have disabled outbound passthrough mode for security concerns.. Hence we have to use external services.

**Comment by slonka** [comment]
@brunda-bs - can you try the following annotations:
- [experimental proxy engine](https://kuma.io/docs/2.0.x/reference/kubernetes-annotations/#kumaiotransparent-proxying-experimental-engine) and
- [exclude outbound tcp](https://kuma.io/docs/2.0.x/generated/cmd/kumactl/kumactl_install_transparent-proxy/#options) (or udp if they are udp) ports for uids:

```
kuma.io/transparent-proxying-experimental-engine: "true"
traffic.kuma.io/exclude-outbound-tcp-ports-for-uids: "11000-11999:65534"
```

note `65534` uid is the [nobody](https://github.com/kumahq/kuma/blob/47498b7eeeeb7678847f520ec18cf73f820e6fe5/tools/releases/dockerfiles/Dockerfile.kuma-dp#L26) uid that will change in `2.1` since we switched

**Comment by slonka** [comment]
@brunda-bs - have you tried the approach suggested above ☝️ ?

**Comment by slonka** [comment]
hey @brunda-bs - trying again - have you tried the approach suggested above ☝️ ?

**Comment by slonka** [comment]
Not getting responses from the author, moving to triage to potentially close.

**Comment by jakubdyszkiewicz** [comment]
Closing for now. Feel free to reopen if it is still valid.
