### ISSUE TITLE
Use the same scripts to build and publish images locally and on CI

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#5390]
### Description

Right now we use https://github.com/kumahq/kuma/blob/master/tools/releases/docker.sh#L29 to build the images for publishing and we use makefiles https://github.com/kumahq/kuma/blob/master/mk/docker.mk#L74 to build images for development. We should have the same flow for both of them. In my opinion this has the following benefits:
- it's easier to debug and we don't have to jump on CircleCI VM
- no need for shotgun surgery to change image build process
- the thing we run tests on are the actual images that end up on production so we should be more certain they're working

**Comment by lahabana** [comment]
That would avoid soo many problems!

**Comment by lahabana** [comment]
@slonka can you confirm that this is done now that everything is in the Makefile. See:

https://github.com/kumahq/kuma/blob/master/mk/docker.mk#L89-L91

**Comment by slonka** [comment]
Yes, this is done, we can close this.
