### ISSUE TITLE
Extra call to ResourceManager in fetchCrossMesh

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#5406]
### What happened?

Apparently, we do unnecessary calls to ResourceManager in the `fetchCrossMesh` method: https://github.com/kumahq/kuma/blob/master/pkg/xds/context/mesh_context_builder.go#L152-L161 

Map `resources.MeshLocalResources` already should have resources for the local mesh.

**Comment by michaelbeaumont** [comment]
Given that the results are cached, can this cause any performance issues?

**Comment by lobkovilya** [comment]
I don't know, to be honest. This came from the review, reported just in case, so we could revisit this

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's check if this is still the case

**Comment by jakubdyszkiewicz** [comment]
seems not to be the case anymore
