### ISSUE TITLE
`MeshHTTPRoute` basic api implementation

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#5470]
### Description

Implement https://github.com/kumahq/kuma/issues/4743

- Implement plugin ordering
- "Feature flag" for new routes -> if new route policies exist, only use new route policies
- Implement MeshHTTPRoute `targetRef`-based & `matches`-based merging
  - this requires significant refactoring because it's assumed everywhere that the `to` struct has a `Default` field
- Generate outbound listeners from `Dataplane` spec
  - handles default route/TcpProxy
- Generate clusters from new routes
  - 1st iteration - same cluster generation
- Generate routes on outbound listeners from new routes
  - Including ExternalServices
  - `kuma.io/service` for `Dataplanes` has priority over `ExternalServices`
    - document and warn about this
  - `targetRef.kind: ExternalService` as `backendRef`?
- Generate endpoints
- ZoneIngress support for new routes
  - needs only backendRefs for destinations
- No MeshGateway support

**Comment by michaelbeaumont** [comment]
I think this can be parallelized:

1. refactor the policy code to support a plugin with a policy that doesn't have the expected `To` structure
2. implement the plugin given a merged "rules" view of all routes

**Comment by lahabana** [comment]
FYI this issue doesn't cover Mirror which is covered by: https://github.com/kumahq/kuma/issues/724

**Comment by michaelbeaumont** [comment]
After https://github.com/kumahq/kuma/pull/5530:

- [ ] builder
- [ ] unify gateway & DP cluster naming
- [ ] handle the match based merging inside existing merge machinery
- [ ] inspect API

**Comment by lahabana** [comment]
As other issues are tracked somewhere else going to close this
