### ISSUE TITLE
Recurring log info messages "Another mesh has been added or removed or we must retry"

### ISSUE THREAD

**Issue by christianwolfcodesorcerer** [kumahq/kuma#5511]
### What happened?

After an update of kuma from 1.7.0 to 2.0.1  (multizone deployment, multiple meshes, global control plane and zone control plane versions 2.0.1, all dataplanes updated) we see a lot of recurring log messages.  The log messages have the form

```
2022-12-13T02:52:43.536ZINFOxds.secretsgenerating certificate{"Dataplane": {"Mesh":"xxx","Name":"xxx"}, "reason": "Another mesh has been
 added or removed or we must retry"}
```
and appear around every three seconds for every dataplane in the mesh.

For the updates we followed the upgrade instructions and first updated the global control plane, then the zone control plane and afterwards the dataplanes. We wirst updated to version 1.8.2 and then to 2.0.1. 

These are our mesh resources:

default:
```
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  creationTimestamp: "2022-06-29T09:07:12Z"
  generation: 1
  name: default
  resourceVersion: "54691551"
  uid: 31de5d29-8270-4225-b3b9-2fbe65e413d8
spec: {}
``` 

public: 
```
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  creationTimestamp: "2022-05-18T07:36:18Z"
  generation: 2
  name: public
  resourceVersion: "162191027"
  uid: bbba0f48-2eba-444f-b3f9-9c1854bf9708
spec:
  logging:
    backends:
    - conf:
        path: /dev/stdout
      name: loki
      type: file
    defaultBackend: loki
  metrics:
    backends:
    - conf:
        path: /metrics
        port: 5670
        skipMTLS: true
        tags:
          kuma.io/service: dataplane-metrics
      name: prometheus
      type: prometheus
    enabledBackend: prometheus
  mtls:
    backends:
    - name: ca-3
      type: builtin
    enabledBackend: ca-3
  networking:
    outbound:
      passthrough: true
  routing:
    localityAwareLoadBalancing: true
  tracing:
    backends:
    - conf:
        url: http://open-telemetry-collector-opentelemetry-collector.open-telemetry.svc:6831/api/v2/spans
      name: zipkin-collector
      sampling: 100
      type: zipkin
    defaultBackend: zipkin-collector
```

intern: 
```
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  creationTimestamp: "2022-05-18T07:36:43Z"
  generation: 2
  name: intern
  resourceVersion: "162191052"
  uid: 4d438eaf-f070-4f19-b17f-fc2eee87154e
spec:
  logging:
    backends:
    - conf:
        path: /dev/stdout
      name: loki
      type: file
    defaultBackend: loki
  metrics:
    backends:
    - conf:
        path: /metrics
        port: 5670
        skipMTLS: true
        tags:
          kuma.io/service: dataplane-metrics
      name: prometheus
      type: prometheus
    enabledBackend: prometheus
  mtls:
    backends:
    - name: ca-2
      type: builtin
    enabledBackend: ca-2
  networking:
    outbound:
      passthrough: true
  routing:
    localityAwareLoadBalancing: true
  tracing:
    backends:
    - conf:
        url: http://open-telemetry-collector-opentelemetry-collector.open-telemetry.svc:6831/api/v2/spans
      name: zipkin-collector
      sampling: 100
      type: zipkin
    defaultBackend: zipkin-collector
```

**Comment by michaelbeaumont** [comment]
Do you see any ERROR messages at any point? Specifically with `could not get other mesh CA cert`?

**Comment by lukidzi** [comment]
@christianwolfcodesorcerer Hi, I've tried to reproduce it by creating multi-zone deployment on k8s with Kuma 2.0.1. I had some demo applications and 3 meshes added but no errors in the logs. I'll try to make it 1.7-> 1.8.2-> 2.0.1 but if you could add more details about how big the cluster is, and some policies that you are using it might help. Also, could you check if there are any others logs after restarts at the beginning?

**Comment by lukidzi** [comment]
Ok, I think I've managed to reproduce the same log I am going to dig into what is going on.

**Comment by lobkovilya** [comment]
From @lukidzi:
> We found out that after the change with ordering, data in the cache is not correct. It's caused by not using provided functions as a key and sometimes filtered data is returned as a result for the resource. Depending on the last call it might return a filtered list or a whole list of results and it's changing all the time. From our analysis, it might affect cross-mesh communication.
