### ISSUE TITLE
Cannot filter by tags and name on Kubernetes

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#5512]
### Description

If you filter by tags + namePrefix, only tags filter is applied.

The bug is only visible with Kubernetes store.

**Comment by kleinfreund** [comment]
The issue is unrelated to the tag parameter. `namePrefix` doesn’t work without it either.

In a Kubernetes environment with 3 DPPs (of which only one has a name starting with `redis-`), the following requests return respectively 2 (2 matching the tag) and 3 responses.

Example requests:

```sh
curl 'http://localhost:5681/meshes/default/dataplanes+insights?tag=kuma.io%2Fprotocol%3Atcp&namePrefix=redis-'
```

```sh
curl 'http://localhost:5681/meshes/default/dataplanes+insights?namePrefix=redis-'
```
