### ISSUE TITLE
policy-gen: targetRef should not be "omitempty"

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#5548]
### Description

The initial assumption was to have a syntactic sugar for TargetRef. That's why the field was marked as `omitempty`. Since it's not the case anymore, we should remove `omitempty` for all TargetRefs and update the bootstrap policy generator.

**Comment by AyushSenapati** [comment]
Hi @lobkovilya and @jakubdyszkiewicz, can I work on this issue?
I asked here to make sure no one else has already picked this.
