### ISSUE TITLE
Terraform provider for Kuma

### ISSUE THREAD

**Issue by p0pr0ck5** [kumahq/kuma#555]
### Summary

Given that Kuma exposes an HTTP interface, it would be straightforward to develop a Terraform provider to manage the lifecycle of policies, mesh configure, etc. And continuing the thought train from https://github.com/Kong/kuma/issues/554, it would simplify managing service definitions for dataplane instances (this would work very well with Nomad, where application definitions themselves can also be managed via Terraform). 

Is there currently a Go SDK for the HTTP API? Not protobuf bindings or RPC, but a lib for the HTTP API used to configure the control plane. Such a library would further simplify developing a Terraform provider; I couldn’t find such code in the Kuma codebase, but admittedly I didn’t look very deep :)

I imagine such resource definitions might look like:

```
resource "kuma_mesh" "my_mesh" {
  name = "mesh-1"

  mtls {
    enabled = true
  }

  logging {
    backend {
      name = "file-tmp"
      tcp {
        address = "logstash.internal:9000"
      }
    }
  }
}

resource "kuma_dataplane" "my_backend" {
  name = "backend-1"

  mesh = kuma_mesh.my_mesh.name

  networking {
    inbound {
      interface = "127.0.0.1:11011:11012"
      tags {
        service = "backend"
        version = "2.0"
        env     = "production"
      }
    }

    outbound {
      interface = ":33033"
      service   = "database"
    }

    outbound {
      interface = ":44044"
      service   = "user"
    }
  }
}
```

Of course in keeping in line with #554 defining a `dataplane` resource in terraform doesn’t make a whole ton of sense :) 

I would be happy to do the development of the terraform provider itself if this is desirable, I just will need some guidance about a Go lib for the HTTP API

**Comment by jakubdyszkiewicz** [comment]
> Is there currently a Go SDK for the HTTP API? Not protobuf bindings or RPC, but a lib for the HTTP API used to configure the control plane. Such a library would further simplify developing a Terraform provider; I couldn’t find such code in the Kuma codebase, but admittedly I didn’t look very deep :)

You can find the client used in kumactl here https://github.com/Kong/kuma/tree/master/pkg/plugins/resources/remote

Although Terraform provider looks interesting, we always assumed that if someone wants to do infra as a code with Kuma on Universal, they can store YAML definitions in GIT (just like terraform files) and use kumactl apply in their deploy pipeline. Can you bring up benefits of using Terraform here? Thanks!

**Comment by p0pr0ck5** [comment]
> Although Terraform provider looks interesting, we always assumed that if someone wants to do infra as a code with Kuma on Universal, they can store YAML definitions in GIT (just like terraform files) and use kumactl apply in their deploy pipeline. Can you bring up benefits of using Terraform here?

That means I have to manage another separate step in my pipeline- more tools, more complexity. The more I can manage in Terraform, the less duct-taping I have to do. Our pipeline currently consists solely of Terraform, as we're managing infrastructure and logical software deployments via the Nomad provider for Terraform. CLI tools are antithetical to automated deploys- if there's any API, I want to consume the API programmatically, not via CLI :)

**Comment by subnetmarco** [comment]
@p0pr0ck5 do you want to start working on this task? I know that we have an OpenAPI spec in the works at https://github.com/Kong/kuma/pull/519

**Comment by p0pr0ck5** [comment]
@subnetmarco yes I will start development for this soon, likely within the next week

**Comment by nickolaev** [comment]
@p0pr0ck5 are you still considering this one? Is there anything we can help with?

**Comment by p0pr0ck5** [comment]
@nickolaev this would be useful but of limited value for us until https://github.com/Kong/kuma/issues/554 is more fleshed out. Let me know if you'd like to sync for some deeper discussion on that issue

**Comment by ludov04** [comment]
Hey team!
Now that #554 is closed, would this be a good time to bump this up?

We are implementing kuma on ECS, and our squads heavily use gitops with terraform to create resources in aws and in other places. This would greatly simplify the management of kuma resources by the squads for us, as this can integrate into the existing worflow.

**Comment by nickolaev** [comment]
@ludov04 since your team already has the expertise with Terraform, maybe you can start some work around this, which we can review together and support you with what is needed on the Kuma side.
We already provide ECS CloudFormation examples which I guess might be some form of a guideline of what might be needed here: https://github.com/kumahq/kuma/tree/master/examples/ecs

**Comment by ludov04** [comment]
Hey @nickolaev, we do have experience with Terraform, but we have no experience with Go at all.

We did create all the resources needed for kuma using terraform, which in indeed analogous to what your team has provided with the Cloudformation example.

This story however is about having a terraform provider for kuma, to be able to define kuma resources like a "Mesh", or policies, using terraform. This requires quite some experience with go itself, which might be too big of a challenge for us.

I understand it's not a priority for the kuma team tho, and am wondering if there is any recommended way at the moment to manage the different resources like the policies using a GitOps workflow

**Comment by nickvdyck** [comment]
Hey, we had another look at creating a Terraform provided for Kuma and agree that it shouldn't be too hard for us to get something up and running. We leverage Terraform quite heavily at Datacamp and would benefit a lot from having it available in our toolbelt. And thus I think it would make sense for us to take a stab at this. We would appreciate some reviews or general support given golang knowledge in our team is pretty basic. 

I personally experimented a bit here: https://github.com/nickvdyck/terraform-provider-kuma , very limited at the moment and just done to get an idea of feasibility. I'll update the thread when I have been able to discuss this internally and we have something more concrete to share.

**Comment by subnetmarco** [comment]
We would love to publish this as one of the official installation methods once it's ready.

**Comment by lahabana** [comment]
Stay put: https://github.com/Kong/terraform-provider-kuma

**Comment by lahabana** [comment]
The very first version of the provider was released: https://registry.terraform.io/providers/Kong/kuma/latest
