### ISSUE TITLE
Status code dashboard doesn't show internal_upstream_rq_xx

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5553]
### What happened?

When setting up a timeout the stat that's changed is: envoy_cluster_internal_upstream_rq_xx

The status code dashboards use: envoy_cluster_external_upstream_rq_xx

So we have a weird view like:

<img width="1120" alt="image" src="https://user-images.githubusercontent.com/702355/209351910-b66b6672-3178-4843-ba11-0cde4ef25f0d.png">

We should do something better here (either sum them together or just show them differently)

**Comment by jakubdyszkiewicz** [comment]
I'm putting this in needs reproducing. Sounds like an easy fix that can get us a lot of value
