### ISSUE TITLE
mesh-insights HTTP API endpoint reports non-policies in the policy insights

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5570]
### What happened?

On a fresh install we're showing 7 policies when it should be closer to 3

I think we're likely counting things like Mesh and Zones.

**Comment by johncowen** [comment]
Transferred this over from GUI:

<img width="720" alt="Screenshot 2023-01-04 at 11 51 41" src="https://user-images.githubusercontent.com/554604/210553108-7d6b60fa-667e-4855-a788-9073441f908e.png">

`Secret` and `ServiceInsight` shouldn't be there and results in the policy count in the GUI sidebar being 2 more than it should be.
