### ISSUE TITLE
Kuma not cleaning the deleted Dataplane resources 

### ISSUE THREAD

**Issue by parjun8840** [kumahq/kuma#5575]
### What happened?

I have a Mesh setup with 3 EKS clusters.
1 cluster- GlobalPlane
2 clusters- ZonePlane

I have removed both the zones EKS clusters on 30th December.
`Connect time: December 28, 2022 at 9:34:17 AM `

`Disconnect time: December 30, 2022 at 6:47:00 AM`

Today is: $ date
`Thu Jan  5 12:58:22 JST 2023`

I still see them on the main GUI-
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/54829402/210699420-38309b7a-1680-4a82-9061-21585d32bee8.png">

In the Mesh config I can see the following settings:
`"universal": {
      "dataplaneCleanupAge": "72h0m0s"
}`

**Expected behavior:** Shouldn't see the "offline" EKS clusters (Zone Plane)after 72h.

Kuma version: Kuma 2.0.1
K8s version: 1.24
Any help highly appreciated.

**Comment by jakubdyszkiewicz** [comment]
Hey, Kuma does not remove offline zone automatically because it might be a temporary connectivity problem between Global and Zone CP. If you want to permanently remove Zone, execute `kubectl delete zone mesh1-apne1` on global CP

see https://kuma.io/docs/2.0.x/deployments/multi-zone/#delete-a-zone
