### ISSUE TITLE
MeshHealthCheck (and likely other policies) don't work when VIPs enabled

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#5643]
### What happened?

On k8s `MeshHealthCheck doesn't work because of an error: 
```
config was previously rejected by Envoy. Applying backoff before resending it	{"backoff": "5s", "nodeID": "default.srv-000-1.kuma-test", "reason": "Error adding/updating cluster(s) srv-002_kuma-test_svc_80: Multiple health checks not supported"}
```

Because we are creating 2 ways of communication with service by VIP and standard way plugin tries to configure the cluster's healthcheck twice and that is causing an error. We disabled the VIP and everything worked.

- [x] `MeshHealthCheck` #5654  
- [x] `MeshCircuitBreaker` #5662
- [x] `MeshTimeout` - more complicated, see below discussion https://github.com/kumahq/kuma/pull/6916

**Comment by slonka** [comment]
should we somehow extract "applyToOutbounds" and other functions like that so we don't have to think about this and shotgun patch this across many policies?

**Comment by michaelbeaumont** [comment]
> should we somehow extract "applyToOutbounds" and other functions like that so we don't have to think about this and shotgun patch this across many policies?

Unfortunately it's not that simple I don't think. Looking at `MeshTimeout`, it seems vulnerable to the same problem except in this case I think it might be a real bug in that different rules might be overwriting each other. When the `MeshTimeout` plugin configures the cluster, it uses rules that actually (seem to from the code) depend on the listener, unlike `MeshHealthCheck`/`MeshCircuitBreaker`...

**Comment by slonka** [comment]
Any updates on this?
