### ISSUE TITLE
propagate tracing information on api-server request/response

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5696]
### Description

That's not something we currently do but it's useful for any service talking to us.

**Comment by jakubdyszkiewicz** [comment]
> Triage: tracing on KDS may not work because of bi-directional gRPC streaming.
> When it comes to API Server we are talking about propagating trace-id into logs.
>
> Go over all servers in Kuma CP and see if we can add tracing.

**Comment by michaelbeaumont** [comment]
We now handle tracing in the API Server with opentelemetry. KDS is indeed difficult on account of tracing being unavailable at the Msg level
