### ISSUE TITLE
Add 5xx to default retry

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#5703]
### What happened?

Should we add "[5xx](https://github.com/kumahq/kuma/blob/d77344c9c0c92af8ed70fce4c3f6773c4d32eea7/pkg/plugins/policies/meshretry/api/v1alpha1/meshretry.go#L53)" to [default retry](https://github.com/kumahq/kuma/blob/54879271f48177144dd50452a73df480c6afda9c/pkg/plugins/policies/meshretry/plugin/xds/configurer.go#L22)?

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's keep it as is. We can update docs example to explicitly use 5xx
