### ISSUE TITLE
MeshMetric policy

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5708]
### Description

We should have a policy for this like MeshTrace and MeshAccessLog.

**Comment by jakubdyszkiewicz** [comment]
> Triage: requires MADS changes.
> DP overrides may not be needed anymore with TargetRef MeshService

**Comment by lobkovilya** [comment]
Use cases to keep in mind when writing MADR:
* How to specify a list of services that can access the Prometheus listener?
* What if we want to configure timeout (or rate limit?) for the Prometheus listener?
