### ISSUE TITLE
Use fixed point percentage in StandardDeviationFactor for MeshCircuitBreaker

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5717]
### What happened?

This allow decimal and is a format users are used to.

**Comment by lahabana** [comment]
We should add a type like *k8s.Quantity that can read strings, int, float and then always persists and serialize as fixed point arithmetic. That way users can set things however they want but we always keep them without losing any precision.

What would be the max precision? 0.001? 0.00001?

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's go over the usages of floats to pick a proper precision

**Comment by jakubdyszkiewicz** [comment]
fixed by https://github.com/kumahq/kuma/pull/5768
