### ISSUE TITLE
Current kuma helm chart is out of date

### ISSUE THREAD

**Issue by rmgpinto** [kumahq/kuma#5771]
### What happened?

Current kuma helm chart is out of date. Can you please deploy the latest changes? Thanks

**Comment by michaelbeaumont** [comment]
Hi, in what sense is the helm chart out of date?

**Comment by rmgpinto** [comment]
I've pulled helm chart version 2.0.2, but I don't see the new changes like the `tolerations` variable on `values.yaml`

**Comment by michaelbeaumont** [comment]
[That change](https://github.com/kumahq/kuma/pull/5549) wasn't backported to version 2.0.2, it will be released with 2.1.x

**Comment by rmgpinto** [comment]
I see, thanks for the quick reply.
