### ISSUE TITLE
VirtualOutbound does not work with MeshGateway

### ISSUE THREAD

**Issue by brentos** [kumahq/kuma#5801]
### What happened?

I was trying to configure a VirtualOutbound like so:

```apiVersion: kuma.io/v1alpha1
kind: MeshGateway
mesh: default
metadata:
  name: edge-gateway
spec:
  conf:
    listeners:
    - hostname: foo.example.com
      port: 8080
      protocol: HTTP
      tags:
        port: http/8080
  selectors:
  - match:
      kuma.io/service: edge-gateway
---
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayInstance
metadata:
  name: edge-gateway
spec:
  replicas: 1
  serviceType: LoadBalancer
  tags:
    kuma.io/service: edge-gateway
---
apiVersion: kuma.io/v1alpha1
kind: MeshGatewayRoute
mesh: default
metadata:
  name: edge-gateway-route
spec:
  conf:
    http:
      rules:
      - backends:
        - destination:
            kuma.io/service: frontend_kuma-demo_svc_8080
        matches:
        - path:
            match: PREFIX
            value: /
  selectors:
  - match:
      kuma.io/service: edge-gateway
      port: http/8080
---
apiVersion: kuma.io/v1alpha1
kind: VirtualOutbound
mesh: default
metadata:
  name: default
spec:
  conf:
    host: hello.world
    parameters:
    - name: service
      tagKey: kuma.io/service
    port: "8080"
  selectors:
  - match:
      kuma.io/service: edge-gateway
```

If I point my VirtualOutbound directly to a service in my mesh, everything works fine; but when I point my VOB at my MeshGateway service, the "hello.world" does not get added to the Envoy sidecar config and traffic does not get routed properly.

I expected the above to work and be able to point a VirtualOutbound at my MeshGateway service.

**Comment by jakubdyszkiewicz** [comment]
> Triage: We can solve it with https://github.com/kumahq/kuma/issues/4741 
> Would be great to get the use case that the user was trying to implement with it.

**Comment by brentos** [comment]
Use case is this: the user wants to refer to the services in the mesh the same way whether the caller is in the mesh or outside of the mesh. For example:

(client outside mesh) -> http://myservice.mycompany.biz/mypath -> (MeshGateway) -> (service)
(client inside mesh) -> http://myservice.mycompany.biz/mypath -> (MeshGateway) -> (service)

**Comment by brentos** [comment]
Another option I thought of that would give similar functionality is to create an ExternalService pointed to http://myservice.mycompany.biz and then a TrafficRoute with each path configured to point to the corresponding service in the mesh. Essentially doing the same sort of routing that the MeshGateway + MeshGatewayRoute would do. This works fine but maybe there is a better / simpler way to do the same thing?
