### ISSUE TITLE
Filter high-cardinality labels from envoy metrics

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#5803]
### Description

An internal user of Kuma uses datadog envoy integration which scrapes [cluster.version](https://github.com/DataDog/integrations-core/blob/master/envoy/datadog_checks/envoy/metrics.py#L256) which contains cluster id that can cause a lot of active time series that can cause performance issues and is more expensive in datadog. We should filter out this metric.

**Comment by jakubdyszkiewicz** [comment]
> Triage: we need to check if this is solved by some param in Envoy itself. If not we need to use metrics filter by default.

**Comment by lahabana** [comment]
Worth adding support for this in: https://github.com/kumahq/kuma/issues/5708

**Comment by lahabana** [comment]
@slonka to check if that's still the case in Envoy

**Comment by slonka** [comment]
Envoy still exposes `envoy_cluster_version_text` which contains the label with UUID but I can only see `envoy_cluster_version` scraped in datadog. Seems like it's by default in datadog.

```
# TYPE envoy_cluster_version_text gauge
envoy_cluster_version_text{envoy_cluster_name="REDACTED_svc_9000",text_value="86f00f2f-b99e-4e2a-9073-8fdeb1a079cc",kuma_io_mesh_traffic="true"} 0
envoy_cluster_version_text{envoy_cluster_name="REDACTED_svc_8080",text_value="86f00f2f-b99e-4e2a-9073-8fdeb1a079cc",kuma_io_mesh_traffic="true"} 0
# TYPE envoy_cluster_version gauge
envoy_cluster_version{envoy_cluster_name="REDACTED_kauth_svc_9000",kuma_io_mesh_traffic="true"} 1.841802949314e+19
envoy_cluster_version{envoy_cluster_name="REDACTED_kauth_svc_8080",kuma_io_mesh_traffic="true"} 1.841802949314e+19
```

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's filter `envoy_cluster_version_text` out by default

@slonka to find the original thread about the client that reported this problem

**Comment by lahabana** [comment]
Default profile doesn't have this and it's easy to ignore this metric. So closing this
