### ISSUE TITLE
Make sure all policy plugins add HTTP filters correctly

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5806]
### What happened?

It's important for HTTP Filters to be added in a common way so that order in which they are set is predictable.

The discussed recommended way it: "always add filter just before routes (which are always the last one)".

We should also document whatever is done to make easy for users to understand

**Comment by jakubdyszkiewicz** [comment]
Fixed by https://github.com/kumahq/kuma/pull/6997
