### ISSUE TITLE
Go over pluggable policies and check if some defaults could be better

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#5807]
### What happened?

Some APIs might be a little complex because we're just 1:1 mapping to Envoy. Could we add defaults/rename fields etc to make them straightforward.

This issue is to track the full review which should be done by a single person for coherency. We will then open follow up issues to correct apis.

This needs to be done before we take new policies out of Beta

- [ ] `MeshAccessLog`: https://github.com/kumahq/kuma/issues/8223
- [ ] `MeshCircuitBreaker`: https://github.com/kumahq/kuma/issues/8224
- [x] `MeshFaultInjection`: no suggested changes
- [ ] `MeshHealthCheck`: https://github.com/kumahq/kuma/issues/8242
- [ ] `MeshHTTPRoute`: https://github.com/kumahq/kuma/issues/8286
- [x] `MeshLoadBalancingStrategy`: no suggested changes
  - I was investigating if our [behavior for applying default weights in affinity tags](https://github.com/kumahq/kuma/blob/e6899302e837c0506e7a420c62c5070de7cf1070/pkg/plugins/policies/meshloadbalancingstrategy/plugin/v1alpha1/priority.go#L37-L41) is similar to what other service meshes do, but I couldn't find that any other service mesh uses similar algorithm
- [ ] `MeshProxyPatch`: https://github.com/kumahq/kuma/issues/8287
- [ ] `MeshRateLimit`: https://github.com/kumahq/kuma/issues/8258
- [ ] `MeshRetry`: https://github.com/kumahq/kuma/issues/8259
- [x] `MeshTCPRoute`: no suggested changes
- [ ] `MeshTimeout`: https://github.com/kumahq/kuma/issues/8260
- [ ] `MeshTrace`: https://github.com/kumahq/kuma/issues/8289
- [ ] `MeshTrafficPermission`: https://github.com/kumahq/kuma/issues/8288

**Comment by slonka** [comment]
We need to review backend (especially MeshTrace, MeshAccessLog) fields structure consistency. E.g. datadog and zipkin have `url` even though datadog uses `host` and `port` only. Also, for OTel we have `endpoint`.

**Comment by bartsmykla** [comment]
https://kongstrong.slack.com/archives/C7J8S9N6Q/p1697488385751389


![Image](https://github.com/kumahq/kuma/assets/11655498/d4301d32-f76f-4ee4-874d-00bc225f63bb)

**Comment by bartsmykla** [comment]
- [ ] `MeshAccessLog`: https://github.com/kumahq/kuma/issues/8223

**Comment by lahabana** [comment]
@bartsmykla if all issues are tracked individually should we close this or is there other things we should look into?
