### ISSUE TITLE
Targeting MeshGatewayRoute doesn't work for MeshRateLimit

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#5864]
### What happened?

When you create the `MeshRateLimit` policy with `targetRef` `MeshGatewayRoute` no configuration change is applied.

**Comment by jakubdyszkiewicz** [comment]
> Triage: as a workaround it works with `MeshService: gateway_app_svc`

**Comment by bartsmykla** [comment]
I'm closing this issue as:
- No policy currently support targeting particular `MeshGatewayRoute`s and we don't want to change it, as `MeshGatewayRoute` is planned to be deprecated in favor of allowing `MeshHTTPRoute` and `MeshTCPRoute` to work with `MeshGateway` in the near future
- When you target `MeshGateway` (`{ kind: MeshService, name: gateway-name }`) rate limit configuration is being applied to all routes (ref. https://github.com/kumahq/kuma/issues/6591#issuecomment-1523273818)
