### ISSUE TITLE
Combating flakes in our codebase

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#5873]
### Description

While being on-duty and trying to reproduce flakes I thought of a couple of things that we could do to improve fighting flakes in our codebase (CI / tests etc.):
- write e2e tests that can be run with ginkgo `--until-it-fails` or `--repeat=N` (e.g. [HC tests](https://github.com/kumahq/kuma/blob/master/test/e2e_env/multizone/healthcheck/healthcheck.go#L16) use the same namespace and we delete the namespace without waiting for completion [because deletion is slow] and that causes subsequent repeats to fail)
- make a target/variable that would apply a CPU limit on docker/k8s so that the tests would run slower (I was able to reproduce [this](https://github.com/kumahq/kuma/pull/5821/files) only on CircleCi and never on my machine, my best guess is that it's because of machine performance)
- make it possible to run two e2e test suites in parallel on one machine (this way, while checking for flakes in one PR we could start working on something else)
- add a PR checklist item along the lines of `I've run tests related to this PR with `GINKGO_E2E_TEST_FLAGS=--repeat=100` (or 30/50 whatever)

**Comment by slonka** [comment]
Added a draft PR for this - https://github.com/kumahq/kuma/pull/6418

**Comment by jakubdyszkiewicz** [comment]
xref https://github.com/kumahq/kuma/issues/9170

**Comment by slonka** [comment]
superseeded by Jakub's hammer https://github.com/kumahq/kuma/pull/11625
