### ISSUE TITLE
kuma-net with eBPF should works in kuma after migration

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#5961]
During migration, we noticed some issues with running `kuma-net` inside `kuma` repository.

- [x] - we are using a fork of `merbridge` and pointing to the main branch - we should change the branch to some release one to have an immutable build
- [x] - ebpf files don't need to be built everytime, we should create GH Action in merbridge and publish the artifact to the repository so we won't have to build ebpf everytime and the current build script is going to work on all environments because we just need to download the artifact 
- [x] - One this is done we should be able to redo: https://github.com/kumahq/kuma-net/issues/113

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's build the eBPF binaries once for all OS distros and fetch them during build. time.
> 
> There is only one version of the bytecode, it's not kernel dependent.

**Comment by bartsmykla** [comment]
Done in https://github.com/kumahq/kuma/pull/6046
