### ISSUE TITLE
reintroduce kube-linter checks

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6049]
### Description

kube-linter was introduced in: https://github.com/kumahq/kuma/pull/4294

It's good but we only have [1 linter](https://github.com/kumahq/kuma/blob/master/.kube-linter.yaml), we should reintroduce the missing linters (search for Enabled by default: Yes): https://docs.kubelinter.io/#/generated/checks

**Comment by jakubdyszkiewicz** [comment]
> Triage: run only for HELM files, not for all Kube files in the repo
