### ISSUE TITLE
Make init-container order relative to other init-containers.

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6082]
### Description

As pointed by: https://github.com/kumahq/kuma/issues/3121#issuecomment-1438925975 there are use cases where you want other init-containers to run before iptables are applied (I can imagine a vault init or something similar).

Until now this worked because we were always running it lasts but with https://github.com/kumahq/kuma/pull/5857 it runs first.
There are good reasons for both: (If you want the mesh to  be up before running something or not), should we do a multiple option annotation:

`kuma.io/init-container-constraints: first,after(<containerName>),before(<containerName>),last`

Note that running an init-container after the Kuma init-container doesn't guarantee there will be network availability (it's likely the sidecar will not be started) maybe  https://github.com/kumahq/kuma/pull/5498 should be extended to all init-containers running after the kuma-init-containers.

Also this is important to understand that the order of webhooks that might touch init-containers is important. It seems like they are alphabetically ordered: https://stackoverflow.com/questions/69300681/whats-the-order-of-different-mutating-webhook-and-how-can-i-add-a-new-mutating

Worth referencing: https://github.com/kubernetes/enhancements/issues/753 as this might be a better path forward.

**Comment by curtiscook** [comment]
> @curtiscook @michaelgoodrx would that cover your respective use cases?

Init container order doesn't affect me. My only issue is the app having dns when it starts. That being said, it seems reasonable

**Comment by curtiscook** [comment]
> Note that running an init-container after the Kuma init-container doesn't guarantee there will be network availability (it's likely the sidecar will not be started) maybe  https://github.com/kumahq/kuma/pull/5498 should be extended to all init-containers running after the kuma-init-containers.

Iirc, init containers all load before the app/sidecars start, so it's probably not feasible to extend my pr. (However, there are a lot of people here with deeper k8s knowledge so others would know best)

**Comment by lahabana** [comment]
Thx @curtiscook btw don't block your work on this (we can always add more later) :)

**Comment by michaelgoodrx** [comment]
> @curtiscook @michaelgoodrx would that cover your respective use cases?

Yeah, we just need to be able to make the the iptable changes to run last, or at least after the init container we have that needs internet access. Thanks for opening the issue.

**Comment by jakubdyszkiewicz** [comment]
> Triage: we should only allow the order to be the first or the last

**Comment by lahabana** [comment]
@johnharris85 this is done right?

**Comment by johnharris85** [comment]
Fixed by #7070
