### ISSUE TITLE
Add blackbox test for clusterIP based routing to itself

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6095]
### Description

In the case where an instance uses its clusterIP and routes to itself it should take the same route as if it were loopback?

We should have a test to ensure this.
This is this rule: https://github.com/kumahq/kuma-net/blob/master/iptables/builder/builder_nat.go#L70-L74

**Comment by lukidzi** [comment]
@bartsmykla we did a lot around TP, does the rework cover this?

**Comment by bartsmykla** [comment]
> triage: it's covered, but we are not using blackbox tests anymore
