### ISSUE TITLE
When --dry-run only one of ipv4/ipv6 rules are displayed

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#6098]
### What happened?

DryRun calls only https://github.com/kumahq/kuma-net/blob/e0ebc9a724f81e573ff6e2f1b47885efe826d384/iptables/builder/builder.go#L60
so we should move logic for generation of ipv6 rules from https://github.com/kumahq/kuma-net/blob/e0ebc9a724f81e573ff6e2f1b47885efe826d384/iptables/builder/builder.go#L146

**Comment by lahabana** [comment]
@bartsmykla what's the state of this now?

**Comment by lukidzi** [comment]
It's fixed
