### ISSUE TITLE
Keep `helm` go dependency in sync with `helm` CLI version

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#6165]
### Description

We use [Helm in `kumactl` to render files](https://github.com/kumahq/kuma/blob/9ed757d3e5955ea57d7940badf4468057ed46663/go.mod#L67) and we also use [`helm`](https://github.com/kumahq/kuma/blob/9ed757d3e5955ea57d7940badf4468057ed46663/mk/dependencies/helm.sh#L6) to lint files during CI. These versions should be in sync. There can sometimes be changes to what's supported in templates between versions so the latter version must be the minimum Helm version our charts support!

**Comment by lahabana** [comment]
Should we just do something like https://github.com/kumahq/kuma/blob/master/mk/dependencies/go-deps.sh#L11 ? 

Also I was thinking that potentially this version should be actually saved to the file as the lock file doesn't include `go.mod`

**Comment by michaelbeaumont** [comment]
Yes, we  definitely should. But then we need to downgrade Helm in `kumactl`, which should be fine.

**Comment by lahabana** [comment]
Ho how come?

**Comment by michaelbeaumont** [comment]
We use `helm` CLI to lint etc `v3.8.2` because it's the minimum supported version of our charts. If these versions should be the same we'd need to downgrade `go.mod`. Or increase the minimum chart version but that seems unnecessary. Or just bump the CLI to `v3.11` and hope we don't accidentally introduce a breaking change

**Comment by lahabana** [comment]
Ha ok. Where do we specify the minimum version of helm?

**Comment by michaelbeaumont** [comment]
We only do so implicitly by using `helm lint` with some version of Helm.

**Comment by jakubdyszkiewicz** [comment]
> Triage: It's not a bug. It's a feature. We want to check the chart against the oldest supported `helm` version
