### ISSUE TITLE
Support `%GRPC_STATUS%` command operator in Envoy access log (coming in Envoy v1.14.0)

### ISSUE THREAD

**Issue by yskopets** [kumahq/kuma#621]
### Summary

* Support `%GRPC_STATUS%` command operator in Envoy access log format (coming in Envoy v1.14.0)
* see https://github.com/envoyproxy/envoy/pull/10299/files

**Comment by tharun208** [comment]
@jakubdyszkiewicz do we need this on our default accesslog ?

**Comment by tharun208** [comment]
@nickolaev I like to work on this !
