### ISSUE TITLE
helm: make resources from egress configurable

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6252]
### Description

These are currently hardcoded:

https://github.com/kumahq/kuma/blob/efdc14935969dd56bac47c727474572c836a42f9/deployments/charts/kuma/templates/egress-deployment.yaml#L101-L111

They should be configurable like the ingress: https://github.com/kumahq/kuma/blob/efdc14935969dd56bac47c727474572c836a42f9/deployments/charts/kuma/templates/ingress-deployment.yaml#L102

And then have good defaults: https://github.com/kumahq/kuma/blob/efdc14935969dd56bac47c727474572c836a42f9/deployments/charts/kuma/values.yaml#L407-L413

Also the defaults for ingress don't seem to follow the policy exposed: https://github.com/kumahq/kuma/pull/6127#issue-1598288395

**Comment by dascole** [comment]
I'll take this one

**Comment by ravish-kumar-maersk** [comment]
@lahabana 
When we can expect this fix released?
