### ISSUE TITLE
Traffic Permission working incorrectly when Issue with CNI + eBPF on Docker Desktop K8

### ISSUE THREAD

**Issue by iamsourabh-in** [kumahq/kuma#6300]
### What happened?

Description:

I have two issues:

1) CNI Pods fails to start.
2) When working in the above stated scenario.
Even after deleting the **TrafficPermission** of allow all. The traffic is still being able to pass

![image](https://user-images.githubusercontent.com/22702292/226239393-0fb5f9cc-4789-4179-b57e-83d7c635abbf.png)

```sh

## STEP 1
kumactl install control-plane --set "cni.enabled=true" --set "experimental.ebpf.enabled=true" | kubectl apply -f -

## STEP 2: Install demo app from Kuma-counter-demo
kubectl apply -f demo.yaml

## STEP 3:
kubectl delete trafficpermission allow-all-default

```
I am trying to run Kuma 2.1.1 on Docker desktop on Windows 11.

The kuma CNI pod fails to start.

The pod for the Control plane starts up. The services are being meshed and shows in the CP dasboard.

After port forward :

I am still able to make a request and get reponse . Even after deleting the **TrafficPermission** of allow all. 

![image](https://user-images.githubusercontent.com/22702292/226194645-bbe8b3e2-1278-4136-862f-f71efa7245af.png)

Doc Reference : 
https://kuma.io/docs/2.1.x/quickstart/kubernetes/#:~:text=see%20the%20GUI.-,Enable%20Mutual%20TLS%20and%20Traffic%20Permissions,-By%20default%2C%20the

**Comment by jakubdyszkiewicz** [comment]
> Triage: We did not test it with Docker Desktop on Windows 11.
> Usually with CNI you need to specify additional config. Here is how it's done for different setup and cloud providers https://kuma.io/docs/2.1.x/networking/cni/#configure-the-kuma-cni
> You would need to figure out what Docker Desktop for Windows 11 is using under the hood and what should be set for `cni.netDir` and `cni.binDir`.
>
> Also most likely image used in Docker Desktop for Windows 11 does not have eBPF kernel module enabled. See https://github.com/Jun10ng/ebpf-docker-for-desktop

**Comment by iamsourabh-in** [comment]
@slonka  I did try running the same setup on Linux based env.. it did work..

**Comment by iamsourabh-in** [comment]
I will try and update what @jakubdyszkiewicz  suggested ... Will update .

**Comment by bartsmykla** [comment]
@iamsourabh-in any updates? :-)

**Comment by iamsourabh-in** [comment]
I am not able to get it working with docker desktop, but runs fine in EKS.

**Comment by bartsmykla** [comment]
We are unfortunately not able to provide help for Windows + eBPF as it's currently not supported configuration. If enabling eBPF kernel module suggested by @jakubdyszkiewicz (ref. https://github.com/Jun10ng/ebpf-docker-for-desktop) didn't help I'm afraid we won't be able to help.
