### ISSUE TITLE
Review which kubectl image to use in Helm hooks

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6326]
### Description

If we still need them can we use an already existing kubectl image instead of building one. If yes let's remove `tools/kubectl`

**Comment by michaelbeaumont** [comment]
We have two separate, custom images for `kubectl` and `kumactl`. Let's remove `kubectl`!

**Comment by lahabana** [comment]
@slonka mentionned [gr.dev/chainguard/kubectl:latest](http://cgr.dev/chainguard/kubectl:latest) as the best option but this is shown as experimental: https://github.com/chainguard-images/images/tree/main/images and there's no public version that is not the `latest` tag. So fell back to bitnami even if it's less nice.
