### ISSUE TITLE
ExternalService with `kuma.io/zone` tag behave differently w/ and w/o ZoneEgress

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#6352]
### Description

If we have an external service with `kuma.io/zone: zone-2` and a client in `zone-1`. 

* When zone egress is enabled:
    ```
    client(zone-1) -> egress(zone-1) -> ingress(zone-2) -> egress(zone-2) -> external service
    ```

* When zone egress is disabled:

    actual:
    ```
    client(zone-1) -> external service
    ```
    expected:
    ```
    client(zone-1) -> ingress(zone-2) -> external service
    ```

Initially, I was thinking this is a bug, but apparently, this behavior is intended, and that's why it's an improvement.

**Comment by jakubdyszkiewicz** [comment]
Closing. This will be considered as a part of https://github.com/kumahq/kuma/issues/6330
