### ISSUE TITLE
Lost log on HTTPS admin server

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#639]
### Summary

We lose the log when HTTPS admin server fails to start.

### Steps To Reproduce

1. Set all varaibles require to run public admin server described here https://kuma.io/docs/0.4.0/documentation/security/#accessing-admin-server-from-a-different-machine except for KUMA_ADMIN_SERVER_PUBLIC_CLIENT_CERTS_DIR
2. run Kuma
3. HTTPS server will not start, but Kuma will.

### Additional Details & Logs

- Version 0.4.0

**Comment by lahabana** [comment]
KUMA_ADMIN_SERVER_PUBLIC_CLIENT_CERTS_DIR don't exist anyway
