### ISSUE TITLE
Wire in pc.AppContext() in postgres_plugin.go

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#6398]
### Description

Improvement from PR: https://github.com/kumahq/kuma/pull/6359#discussion_r1152845657

**Comment by bartsmykla** [comment]
@slonka is it still an issue? How should we proceed with this?

**Comment by slonka** [comment]
At 5:21 I deployed a new version of mink and we can see no drastic increase in active connections. So based on these metrics I conclude that we do not have a problem with pgx not closing connections on app shutdown.

<img width="1014" alt="image" src="https://github.com/kumahq/kuma/assets/2753650/4caa9be8-2930-4483-b4b7-3817765460c9">

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's close it as it seems it does not cause any harm for now
