### ISSUE TITLE
Figure out why postgres pool closing (both pgx and pq) do not cause connections to be closed on the server side

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#6399]
### Description

Continuation from: https://github.com/kumahq/kuma/pull/6359#discussion_r1152992470. There are two things here:
- closing the pool closes the connection on the server on some machines and not on others
- whats the correct behaviour

Also:
- check metrics of how it behaves when doing a regular deployment

**Comment by lahabana** [comment]
@jakubdyszkiewicz and @slonka is this still an issue?

**Comment by slonka** [comment]
I think yes. This was an issue on macos only.

**Comment by lahabana** [comment]
This only affects macOS let's not fix this and reopen if needed
