### ISSUE TITLE
Figure out capabilities necessary for the CNI

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#6569]
### What happened?

We are currently setting CNI containers with `privileged: true`, it would be good to figure out if we can restrict this with explicit capabilities, which would involve figuring out what exact capabilities CNI needs.

- [x] without eBPF
- [ ] with eBPF

**Comment by lahabana** [comment]
https://github.com/kumahq/kuma/blob/38d4be1578047cc1ac984e62ea378480bc5d730d/deployments/charts/kuma/values.yaml#L336-L346

**Comment by lahabana** [comment]
We should also likely document our capabilities in the plugin config:

https://github.com/containernetworking/cni/blob/main/CONVENTIONS.md#dynamic-plugin-specific-fields-capabilities--runtime-configuration

**Comment by lahabana** [comment]
Let's investigate difference between priviledged and sysadmin cap

**Comment by bartsmykla** [comment]
Unfortunately the container has to run as `privileged`:
```sh
The DaemonSet "kuma-cni-node" is invalid: spec.template.spec.containers[0].volumeMounts.mountPropagation: Forbidden: Bidirectional mount propagation is available only to privileged containers
```

**Comment by lahabana** [comment]
xref: https://github.com/kumahq/kuma/issues/6714 closing this one as there's nothing more to do that isn't covered in this new issue
