### ISSUE TITLE
Default policies in targetRef style

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6588]
### Description

To migrate to new policies as default. We need to create the default policies when the mesh is created.

Question: what policies actually need default resources?

Update: We've decided to not create default policies when the mesh is created, instead providing a recommended set of resources and having users explicitly create them.

This issue covers creating said recommended set

**Comment by KirtiKamal** [comment]
hey @lahabana i am new to opensource can you suggest me some kind of stuff so that i can contribute too

**Comment by bartsmykla** [comment]
Covered by: https://github.com/kumahq/kuma/issues/6592
