### ISSUE TITLE
Design how MeshGateway interacts with targetRef policies

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6590]
### Description

It's never been properly defined how gateways and new policies work together.

Some open questions:

- How does a policy target all incoming traffic of a gateway?
- How does a policy target only the traffic for a specific listener?
- How does a policy target only the traffic for a specific ingress route?
- Does the gateway use the same MeshHTTPRoute or does it have its own?

xref : 
- #5867  (because the way you attach to gateways and to dataplanes should be similar)
- https://github.com/kumahq/kuma/issues/4690

This should be one or multiple MADRs.

**Comment by michaelbeaumont** [comment]
Some thoughts, will collect into document:

Remembering that `spec.targetRef` specifies _which `Dataplane` config is being altered_ and discounting cross-mesh...

* `spec.to.targetRef` with a `MeshGateway` (or `MeshService` of a builtin gateway dataplane) makes no sense currently, right? What should the `spec.targetRef` even be?
* `spec.from.targetRef` with a `MeshGateway` makes sense in general

**Comment by michaelbeaumont** [comment]
Closing this as the MADR covering targeting gateways/listeners has been closed and there are issues for route targeting
