### ISSUE TITLE
Make new `targetRef` default

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6592]
### Description

New mesh should be created with default policies using targetRef style.

There should still be a flag for having the previous behaviour on (so that folks with existing automation don't have to change anything).

xref:

- #6588

**Comment by johnharris85** [comment]
Should this be configurable at the mesh level or at the CP level?

**Comment by lahabana** [comment]
I think it's at the CP level. I don't think it's worth having this in the Mesh.

I think we'd just tell users to set this if they don't want to move on new policies yet and this flag is only read when a mesh is created
