### ISSUE TITLE
Span reporting to DataDog nested incorrectly

### ISSUE THREAD

**Issue by captainbeardo** [kumahq/kuma#6619]
### What happened?

Prior to version 2.2, the mesh sidecar correctly nested spans when reporting to DataDog:

![image](https://user-images.githubusercontent.com/834135/234363566-73f02291-ac13-4784-9b47-6e1d68ff22f3.png)

In version 2.2, the nesting of the calls is incorrectly reported and it shows as a sibling span instead:

![image](https://user-images.githubusercontent.com/834135/234363703-00c727db-9b9f-464e-b4de-ccfa47b3a614.png)

Both examples are just one API call.

**Comment by lahabana** [comment]
@captainbeardo can you show both envoy spans in either case please?

**Comment by jakubdyszkiewicz** [comment]
> Triage: it was apparently solved by updating the old node library. Closing. Feel free to reopen if this is still an issue
