### ISSUE TITLE
Try to remove defaults component

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6624]
### What happened?

Currently we start 1 component that will ensure there's a default mesh and that the cluster has Envoy CA, TokenSigningKey and ZoneSigningKey. 
This is a little unfortunate and it would likely be sufficient to do this reactively as part of the tenant creation (if there's a single tenant on startup).

This would help make things a little cleaner as well as pg/k8s connection will be established before we start other components

**Comment by lahabana** [comment]
One possible solution is to move the component tick and recreate the resources if they are missing. Instead of just doing it once on startup.

Other option is to do a tenant reconciler that gets triggered on tenant change or periodically.

We need to understand with these things were implemented as components in the first place (cc: @jakubdyszkiewicz )

**Comment by jakubdyszkiewicz** [comment]
Fixed by https://github.com/kumahq/kuma/pull/6705 to skip tenant resources.
It is a component because it requires leader election
