### ISSUE TITLE
Go over new policies and figure out if we ever configure outbound listener

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6637]
### What happened?

Configuring outbound listeners is problematic as these do not exist in the Gateway. Most of the time we should be able to configure the route instead.

Let's go over all policies and figure out if we do this anywhere. If we do let's list this here and we'll open follow up issues to track this.

**Comment by jakubdyszkiewicz** [comment]
> Triage: @lahabana to xref issues and close this issue.

**Comment by lahabana** [comment]
Outcome of this issue:

- https://github.com/kumahq/kuma/issues/6644
- https://github.com/kumahq/kuma/issues/6646
- https://github.com/kumahq/kuma/issues/6647
- https://github.com/kumahq/kuma/issues/6645

We'll track completion in the issues above
