### ISSUE TITLE
Some collection resource endpoints return items as null instead of an empty array

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma#6639]
### What happened?

There seem to be at least some collection resource endpoints for which an empty list of resources is returned as `items: null` instead of `items: []`.

I could only find meshes/default/service-insights, but for this endpoint at least, it’s true.

All collection resource endpoints in Kuma should behave the same and return an empty list as `[]`.

**Comment by lahabana** [comment]
I'm checking all and here are the problematic ones:

- service-insights
