### ISSUE TITLE
MeshTrace configure per-route

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#6647]
### Description

There is https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#envoy-v3-api-field-config-route-v3-route-tracing to configure tracing per-route.

**Comment by michaelbeaumont** [comment]
[The tracing provider can't be configured at this level](https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/route/v3/route_components.proto#config-route-v3-tracing).

**Comment by lahabana** [comment]
It won't be possible to configure Trace on a MeshHTTPRoute
