### ISSUE TITLE
Offline dataplanes in some cases are never deleted

### ISSUE THREAD

**Issue by albertpx** [kumahq/kuma#6654]
### What happened?

We're using universal multi-zone cluster.

We have autoscaling of instances configured on each control planes of each zone.
When a scale down happens of our service, at the same time a scale down of the control plane instances can occur.
In such cases, it appears that if a dataplane goes down at the same time as control plane, the dataplane will be set offline, but will never be deleted.
The "service" then will appear as partially degraded.
For example, two services with hundreds of instances were downscaled to 1. Now the services are stuck in partially degraded state, because some of the dataplanes appear as offline, and are never deleted.
![image](https://user-images.githubusercontent.com/43440432/235524679-672d44a8-1986-4979-971a-c44c24a4a38c.png)

We have observed (although in more rare cases) that zone ingresses can be stuck in offline mode due to same issue.

Additionally, we have also observed that such issue can occur during replacement of the control plane instances (such as during rolling upgrade of the kuma version) - because dataplanes can be scaled down/up or simply recreated during rolling replacement of the control plane instances.

**Comment by jakubdyszkiewicz** [comment]
> Triage: Are DP stuck even after 72h? This is expected behavior that when CP is down and DP goes down, we miss the disconnect event. If you don't like 72h default, you can change it https://github.com/kumahq/kuma/blob/master/pkg/config/app/kuma-cp/kuma-cp.defaults.yaml#L355

**Comment by albertpx** [comment]
@jakubdyszkiewicz it's been 20 hours so far, I can wait further if needed.

However, we are observing now an issue with ingress proxy - apparently the ingress proxies are connected somehow to the offline dataplanes.
See a partial result of `clusters` here from an ingress proxy:
https://gist.github.com/albertpx/202193c16dc07bb788b314e59d8a01e0

The outbound is and inbound are sitting in different control plane zones - so the traffic flows through the ingress proxy (we have 3 ingress proxy instances).

The proxy is seeing many `kuma-test-inbound` instances - but we have only a single `online` instance there.
![image](https://user-images.githubusercontent.com/43440432/235686939-1231aea6-80dd-45f1-b2e1-415b1a3b6ce3.png)
![image](https://user-images.githubusercontent.com/43440432/235687700-c2471fea-0357-484c-bdd2-f5860957d783.png)


This result in timeouts in our `outbound` service as you can see in the metrics here. There is a single outbound instance sending 3 requests per second, and as you can see about half of the requests are getting timeouts:
![image](https://user-images.githubusercontent.com/43440432/235686756-154ef462-a03a-4b45-8b7b-082f88699810.png)

**Comment by albertpx** [comment]
@jakubdyszkiewicz should I open a new issue about the issue with ingresses as I explained above?

**Comment by albertpx** [comment]
I confirm, setting KUMA_RUNTIME_UNIVERSAL_DATAPLANE_CLEANUP_AGE to 2m has immediately showed results.
All the offline dataplanes have disappeared, and the single outbound instance stopped having issues right away as you can see the metrics (around 19:15):
![image](https://user-images.githubusercontent.com/43440432/235727580-3200fa9d-c9c1-46f3-8c20-c2a735f266bc.png)

However, it means that at least for 2 minutes, due to the issue with ingress proxies, the traffic will still be directed to offline dataplanes.

Another, (third) issue I have found, is that offline ingress proxies are never cleaned up, as evidenced in this screenshots:
![image](https://user-images.githubusercontent.com/43440432/235728565-c2f5066b-22a2-499d-a2ae-1d698d4f64ee.png)

The disconnect time was more than 2 weeks ago:
![image](https://user-images.githubusercontent.com/43440432/235728644-f0760e5a-5276-436a-8320-67fccc4f467e.png)

**Comment by jakubdyszkiewicz** [comment]
> Triage: Created an issue for zone proxies https://github.com/kumahq/kuma/issues/6716
> Also let's double-check that we don't put offline instances of dpps in zone ingress.

**Comment by jakubdyszkiewicz** [comment]
We don't use offline instances of ddp in zone ingress so closing this one as #6716 is the way to solve this

**Comment by albertpx** [comment]
@jakubdyszkiewicz I'm not sure why this issue has been closed. I have provided clear evidence that offline dps are being used by ingress proxies.

Reducing the env var KUMA_RUNTIME_UNIVERSAL_DATAPLANE_CLEANUP_AGE to 2m, simply mitigates the issue after 2 minutes, and does not solve the original issue.
