### ISSUE TITLE
MeshHTTPRoute does not allow uppercase characters in header names

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#6682]
### What happened?

[#5757](https://github.com/kumahq/kuma/pull/5757/files#diff-23a5b7b1e404474dba0866ac390ea41b771e9b0d04cfd7681838700900b90506R5) made it so that upper case characters are not allowed in any header names in new policies. This is in conflict with Gateway API resources and it's not clear that this is necessary or correct for _all_ uses of header names.

**Comment by lahabana** [comment]
I guess map uniqueness was one of the motivator. but I agree that's something that should be fixed

**Comment by michaelbeaumont** [comment]
We decided not to change this and merged #6704. It seems like Envoy HTTP normalization/HTTP2 makes the need to set headers with uppercase letters in their names moot.

**Comment by lahabana** [comment]
A yes that makes sense
