### ISSUE TITLE
"make k3d/start" doesn't work

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#6713]
### What happened?

It tries to create a cluster named `kuma` but there is no metallb config for it:
```
error: the path "./mk/metallb-k3d-kuma.yaml" does not exist
```

**Comment by michaelbeaumont** [comment]
You can specify `KIND_CLUSTER_NAME=kuma-1`

**Comment by michaelbeaumont** [comment]
This is fixed
