### ISSUE TITLE
Use a single listener for a given service listening on both the VIPs and the regular outbound IP

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6717]
### Description

Currently we have a listener per vip from looking at envoy is looks like there's an `additional_addresses` https://www.envoyproxy.io/docs/envoy/latest/api-v3/config/listener/v3/listener.proto#envoy-v3-api-msg-config-listener-v3-listener that should replace these redundant listeners

**Comment by lahabana** [comment]
xref: https://github.com/kumahq/kuma/issues/5643

**Comment by jijiechen** [comment]
Does this mean that we try to merge the listeners as much as possible and only make new listeners when necessary?

Per our current implementation, I think we are applying many kinds of policies on the outbound listener (and it's children nodes), and these policies will rely on the particular outbound/service information. 
If we are merging the listeners for these many outbounds, do we use filter chain match to provide the capabilities for policies that meant to apply to particular outbound/service on that shared listner?

https://github.com/kumahq/kuma/blob/master/pkg/xds/generator/outbound_proxy_generator.go#L94

If my understanding is correct, it seems this will be a significant change and needs much effort and testing.

**Comment by michaelbeaumont** [comment]
I think the description might be a little incomplete. This issue is about, for a given service, only creating one listener instead of the 2 listeners we currently create. One that listens on the VIP and one on the regular outbound. The policies applied to these listeners and the resulting config should be equivalent.

**Comment by jijiechen** [comment]
That's so much clearer, thanks for that explaination.
