### ISSUE TITLE
Support for file rotation on TrafficLog policy

### ISSUE THREAD

**Issue by doctorwu** [kumahq/kuma#675]
### Summary

As a user of TrafficLog policies, I would like to be able to rotate file logs after they reach a certain size. The rotated file logs should keep a history of a configurable number of old files. For example, I would like to keep a maximum of 5 log files after the current file rotates.

**Comment by jakubdyszkiewicz** [comment]
Shouldn't this be the responsibility of the soft like Logrotate that is consistent for all the software across the organization?
There is no support for log rotation in Envoy itself https://www.envoyproxy.io/docs/envoy/latest/configuration/observability/access_log

**Comment by doctorwu** [comment]
If I am using a local file backend, how would you customize the Kuma control plane container to use logrotate?

**Comment by jakubdyszkiewicz** [comment]
Can I ask side question here? How do you handle log rotation from your applications?

**Comment by doctorwu** [comment]
It can vary. Java applications will generally use logging frameworks like log4j where you have the ability to configure rolling file logging appenders. The Python logging handlers have a similar concept.

**Comment by jpeach** [comment]
xref #2099

**Comment by jakubdyszkiewicz** [comment]
That's not the same problem @jpeach 

@doctorwu was asking here about TrafficLog (Envoy builtin access log to file).

It seems it won't be implemented in Envoy itself https://github.com/envoyproxy/envoy/issues/1109 so the only viable solution is to use logrotate. Besides, I think the majority of use cases are to send access logs to the centralized system.

We can reopen if this is really critical.
