### ISSUE TITLE
Participate in LFX Mentorship Q3?

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#6752]
### Description

https://github.com/cncf/mentoring/tree/main/programs/lfx-mentorship/2023/03-Sep-Nov

**Comment by jakubdyszkiewicz** [comment]
> Triage: we need ideas for projects to participate

**Comment by mohamedawnallah** [comment]
I'm interested in contributing to Kumahq under LFX Mentorship Q3. Is there any progress on this issue?
