### ISSUE TITLE
Enable NodePort customization / configuration for all services in Helm

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#6759]
### What happened?

We allow specifying a NodePort in zone ingress / egress and we should also extend that customization to the global sync service and control-plane service.

**Comment by jakubdyszkiewicz** [comment]
> Triage: you can change the type, but you cannot set a specific NodePort

**Comment by michaelbeaumont** [comment]
You can [set a specific nodePort](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport-custom-port)

**Comment by johnharris85** [comment]
> You can [set a specific nodePort](https://kubernetes.io/docs/concepts/services-networking/service/#nodeport-custom-port)

Ye you can in K8s, just not in our helm chart (yet) :p
