### ISSUE TITLE
Validate MeshRetry when new `targetRef.kind: MeshGateway` is implemented

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#6790]
### Description

https://github.com/kumahq/kuma/pull/6779 adds support for MeshRetry to target MeshGateway. But since there is no `targetRef.kind: MeshGateway` there is no validation preventing users to create MeshRetry with `spec.to[].targetRef.kind: MeshService` even though it won't be applied. 

Comment: https://github.com/kumahq/kuma/pull/6779#discussion_r1196568121

**Comment by bartsmykla** [comment]
I believe this issue is already solved: https://github.com/kumahq/kuma/blob/4e95c9050ddeb0be1e022139ef2f30af6a1ffba1/pkg/plugins/policies/meshretry/api/v1alpha1/validator.go#L44-L47

@michaelbeaumont could you confirm?

**Comment by michaelbeaumont** [comment]
Looks like it
