### ISSUE TITLE
Create VIPs ConfigMap even if some number of them error out

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#6819]
### Description

If a VIP can't be created for some reason (e.g. duplicate service IP entry) we will fail to create the ConfigMap, blocking all other services / pods that come after. Any downsides to logging an error but proceeding to create the ConfigMap with the VIPs we _can_ create?

**Comment by lahabana** [comment]
How come we do fail? I think the reason this was done this way is that it shouldn't fail in the first place

**Comment by johnharris85** [comment]
A user experienced an issue with a headless service and hit this.

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's try to reproduce it first. Multiple headless services pointing to the same pod.

**Comment by lobkovilya** [comment]
I was able to reproduce it. I created 2 headless services pointing to the same pod and got Kuma CP error:

> 2023-07-03T11:59:39.572Z    ERROR    kube-manager    Reconciler error    {"controller": "configmap", "controllerGroup": "", "controllerKind": "ConfigMap", "ConfigMap": {"name":"kuma-default-dns-vips","namespace":"kuma-system"}, "namespace": "kuma-system", "name": "kuma-default-dns-vips", "reconcileID": "f1bb252a-e6f2-4a3b-8e67-43348a9f8f4b", "error": "autogenerated DNS entry 10.42.0.27:3001 from kubernetes conflicts with existing entry kubernetes, this happens when there are two external services with the same 'networking.address', to disable automatic DNS generation in external services set 'networking.disableHostDNSEntry=true' in at least one of these externalService"}

After that new services don't get entry in the VIPs ConfigMap.

**Comment by johnharris85** [comment]
The error is also misleading, it says the DNS entry is `kubernetes`. That's where it's coming from, but that's also the name of a service but not the erroring service. It also talks about external services as the reason / resolution (which is not correct either).
