### ISSUE TITLE
MeshHTTPRoute multizone fails when using the same service name in 2 different zones

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#6905]
### What happened?

Info coming from a user:

We tested MeshHTTPRoute policy to do canary deployments. The 2.1 doc said that it was not supported in a multi zones mesh, but the mention has been removed in version 2.2 of the doc. So we are assuming that this policy should now fully work with 2.2 in a multi zones context.
But we found that it doesn’t always work: 
it works if backendRefs are 2 different services (2 deployments with a kube service each one)
it doesn’t work if backendRefs are using the same service name (2 deployments, one single service as in your demo repo)

We’re getting this error when it doesn’t work : 
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 33554536:system library:OPENSSL_internal:Connection reset by peerbash-5.1

**Comment by michaelbeaumont** [comment]
@slavogiez I can't reproduce this, in which zones exactly are the two versions of `canary_mynamespace_svc_8080` running? Exactly which `Services` do you have deployed?

**Comment by slavogiez** [comment]
Indeed I succeed to make it work, but after some time, it is not working anymore but now the error is :

```
upstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: Secret is not supplied by SDS
```

**Comment by slavogiez** [comment]
I succeed to make it work again after : 
- restart all zonal CPs, ingresses and egresses
- removing and recreating the MeshHttpRoute policy

**Comment by michaelbeaumont** [comment]
@slavogiez Can you please describe exactly how the services are distributed in which zones and which zone you're making the failing requests from?

**Comment by lobkovilya** [comment]
I was able to reproduce and find the root cause. When we implemented https://github.com/kumahq/kuma/issues/5871 we didn't take ZoneEgress into account, while ZoneEgress is a route-aware component:

https://github.com/kumahq/kuma/blob/8edc182aff9764346a457f06c5fca12f0d4c6ee8/pkg/xds/generator/egress/generator.go#L124-L144

**Comment by lahabana** [comment]
@jakubdyszkiewicz this is a dupe of #7527 in the end right?

**Comment by jakubdyszkiewicz** [comment]
Looks like it, yes.

**Comment by lahabana** [comment]
Duplicate of https://github.com/kumahq/kuma/issues/7527
