### ISSUE TITLE
Plural/singular should result in same behavior

### ISSUE THREAD

**Issue by johnharris85** [kumahq/kuma#6908]
### Description

When getting resources with kumactl, we have different behavior between `get traffic-permission` and `get traffic-permissions`. Not sure if there's a technical reason for this? IMHO we should strive to emulate the kubectl behavior here for ease of user experience switching between the environments.

**Comment by lahabana** [comment]
Mind if I just dupe this to: https://github.com/kumahq/kuma/issues/4297 ?

I think kumactl could be made a lot simpler especially now that we have a `/policies` endpoint.
