### ISSUE TITLE
Kuma resource_count metric for Services and ExternalServices resource

### ISSUE THREAD

**Issue by brunda-bs** [kumahq/kuma#6935]
### Description

Hi,

I am looking for a metric to display the count of services and external services created in the mesh. I see resource_count metric is not supporting this 2 resource_type currently.

<img width="972" alt="Screenshot 2023-06-06 at 3 14 10 PM" src="https://github.com/kumahq/kuma/assets/97163498/c71fbcbe-c4fe-4104-9bfe-82d37b71d08f">

Kuma version - v2.1.1.

Is there any other metric which can be used for the same or is it possible to support services and external services resource type in the resource_count metric?

**Comment by jakubdyszkiewicz** [comment]
> Triage: I don't think there is any other metric that can indicate this. I don't think there is a strong reason for not including ExternalServices and Services. The info is available in MeshInsight on which this metric is based on.

**Comment by lahabana** [comment]
Not going to be done. But let's check it's reported correctly with MeshExternalService (#10238)
