### ISSUE TITLE
in KDS v2 don't send all metadata with each DiscoveryRequest

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#7034]
### Description

IIUC we're sending all the metadata on each DiscoveryRequest. 

https://github.com/kumahq/kuma/blob/49fc487db86d4549034975a176fb229e6f3c2ead/pkg/kds/v2/client/stream.go#L70-L76

Sending things like the entire config might not be the best idea as it's fairly big. Should we switch to something proactive like Stats/Clusters... ?

**Comment by lobkovilya** [comment]
Only the first N DiscoveryRequests contain metadata (N is equal to the number of resource types):

https://github.com/kumahq/kuma/blob/7a52a1b23ae841fcc97fd17b2fed64262f7c198e/pkg/kds/v2/client/kds_client.go#L54-L59

All the following requests are done through the ACK method without metadata:

https://github.com/kumahq/kuma/blob/7a52a1b23ae841fcc97fd17b2fed64262f7c198e/pkg/kds/v2/client/stream.go#L118-L124

So there is a small room for improvement, we can send N times fewer metadata on start, but this doesn't reduce the amount of data when KDS is already up and running.

**Comment by jakubdyszkiewicz** [comment]
> Triage: it's good enough for now ^
