### ISSUE TITLE
kong-mesh-control-plane service https-api-server does not respond when appProtocol is set

### ISSUE THREAD

**Issue by mynamewastaken** [kumahq/kuma#7086]
### What happened?

We are running the mesh in universal mode.

We enabled https on the `kong-mesh-control-plane` service via the `kuma.controlPlane.tls.apiServer.secretName: xxx` helm values.
With that set the service manifest looks like this:

```
...
  - appProtocol: http
    name: https-api-server                                                                                                                                                   
    nodePort: 31188                                                                                                                                                          
    port: 5682                                                                                                                                                               
    protocol: TCP                                                                                                                                                            
    targetPort: 5682
...
```
When this is set however, that port doesn't respond. Changing the `appProtocol` to https lets the port respond.

It looks like this was introduced in https://github.com/kumahq/kuma/commit/c332dbf0e35ba5202ce13736181fe076a2d3439e#diff-a1fc636e7462be9d5c02ed61215e52d04bf589dab244a16f6281b47fab683e31R25

**Comment by michaelbeaumont** [comment]
Closed, merged into release-2.3
