### ISSUE TITLE
Install link broken after version 2.1.X

### ISSUE THREAD

**Issue by walterjgsp** [kumahq/kuma#7132]
### What happened?

From version 2.2.X forward all links to install documentation are forwarded to https://kuma.io/docs/2.3.x/production/install-kumactl/ instead of the https://kuma.io/docs/2.3.x/installation/docker/ regardless the installation button that I click.. For version 2.1.X I still found out how to deploy `kuma-cp`.

From this version that I was able to figure it out how to use `kuma-cp` 2.3.0 with docker since the image is there.

Sorry if this was not the correct place to raise this issue.

**Comment by walterjgsp** [comment]
After reading documentation and seeing videos I figure how to update correctly to 2.3.0.

**Comment by bartsmykla** [comment]
@walterjgsp just as a curiosity - what videos are you talking about? :-)
