### ISSUE TITLE
Refresh interval should be a configuration on the zone object in global not a CP config

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#7143]
### Description

It makes more sense for global to control the frequency of refreshes as an admin might want to increase this for everyone quickly.

My guess is this could be a config in the zone resource (like enabled) and we'd have a good default in the global CP config.
Does this also apply to backoff?

The backward compat seems straight forward. KDS sends this in metadata, if we receive it we ignore the local config.

**Comment by lahabana** [comment]
I think if both are set the global control takes over (which makes an easy backward compat path too). In the long term I think the zone cp param should be removed

**Comment by michaelbeaumont** [comment]
> Triage: global needs control over zone CP refresh interval
> Migration: both CPs can set it, global takes priority -> remove option from zone CP
> Can we rate limit DiscoveryRequests from global?

**Comment by jakubdyszkiewicz** [comment]
> Triage: we now have a backoff mechanism
>       # This is a way to slow down Zone CP from sending resources too often.
>       responseBackoff: 0s # ENV: KUMA_MULTIZONE_GLOBAL_KDS_RESPONSE_BACKOFF
