### ISSUE TITLE
kuma-init fails to meet baseline PSS level

### ISSUE THREAD

**Issue by jbruce-nex** [kumahq/kuma#7196]
### Summary
PSS Baseline policy does not allow NET_ADMIN or NET_RAW as a security context capability (https://kubernetes.io/docs/concepts/security/pod-security-standards/#:~:text=Capabilities,SYS_CHROOT) 

### Details
Injecting kuma sidecar means deployment namespace has to be reduced to 'privileged' mode
PSA warning:
```pods "mypod" is forbidden: violates PodSecurity "baseline:v1.25": non-default capabilities (container "kuma-init" must not include "NET_ADMIN", "NET_RAW" in securityContext.capabilities.add)```

**Comment by lahabana** [comment]
We need to check as we may be able to get rid of `NET_ADMIN`.
However, `NET_RAW` is required for being able to bind to different IPs or interfaces which is what we do with transparent proxy

**Comment by michaelbeaumont** [comment]
AFAIU `NET_ADMIN` is also necessary for binding to arbitrary addresses and for modifying routing, which we do for transpareny proxying. I think the best option in this case would be to use CNI instead of `kuma-init`.

**Comment by jbruce-nex** [comment]
thanks both, am I to understand that these are the correct docs for using the CNI? https://kuma.io/docs/2.3.x/production/dp-config/cni/#configure-the-kuma-cni

**Comment by michaelbeaumont** [comment]
Yeah those are the ones

**Comment by jbruce-nex** [comment]
much appreciated
