### ISSUE TITLE
unable to migrate the postgres DB

### ISSUE THREAD

**Issue by adarsh-padhi** [kumahq/kuma#7212]
### What happened?

 I am getting this new error when I try to connect zone CP & postgres in the same VM
 
`{"error": "database is not migrated. Run \"kuma-cp migrate up\" to update database to the newest schema"} `

when I ran `kuma-cp migrate up`  its giving me

`Error: migrations are not supported for Memory resource store`

quick support is appreciated 
thanks

**Comment by michaelbeaumont** [comment]
You have to pass the same options to `kuma-cp migrate up` that you do for `kuma-cp`.

**Comment by adarsh-padhi** [comment]
I am not getting it ... can you brief it please
