### ISSUE TITLE
Remove access and metrics socket path backward compatibility

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#7220]
### What happened?

https://github.com/kumahq/kuma/pull/7218 ensured that socket files are created in one place and then passed in metadata.
Things were kept for backward compatibility that we should be able to clean in the future.

Probably can be done from 2.6 (2 versions after 2.4).

**Comment by slonka** [comment]
Not stale but needs to wait for 2.6

**Comment by Icarus9913** [comment]
I'll take it
