### ISSUE TITLE
Pods frequent restart issue until kuma-sidecar is ready

### ISSUE THREAD

**Issue by brunda-bs** [kumahq/kuma#7223]
### What happened?

Hi,

We are currently using Kuma version 2.1.1 with CNI enabled. Our kuma injected application pod utilizes a vault init container to retrieve secrets, and this container relies on an external service to establish a connection with the vault. However, we have encountered a persistent problem where these pods experience frequent restarts (typically around 10-15 times) until the kuma-sidecar is fully up and running.

application container log - 
```
\"[https://<VAULT -DNS>/v1/auth/abc/login\":](https://<VAULT -DNS>/v1/auth/abc/login/%22:) dial tcp xx.xx.xx.xx:443: connect: connection refused"
time="2023-07-12T08:01:41Z" level=fatal msg="failed to create vault clienttimeout [30s] during waiting for Vault token" app=vault-env
```
Kuma-sidecar error log during this process-

```
[2023-07-12 08:26:23.454][29][info][config] [source/server/listener_manager_impl.cc:789] all dependencies initialized. starting workers
[2023-07-12 08:27:13.895][29][warning][config] [./source/common/config/grpc_stream.h:196] StreamAggregatedResources gRPC config stream closed since 80s ago: 14, upstream connect error or disconnect/reset before headers. reset reason: connection termination
2023-07-12T08:27:48.758Z	INFO	Received signal, stopping instance gracefully	{"signal": "terminated"}
2023-07-12T08:27:48.758Z	INFO	kuma-dp.run	Kuma DP caught an exit signal. Draining Envoy connections
2023-07-12T08:27:48.760Z	INFO	kuma-dp.run	waiting for connections to be drained	{"waitTime": "30s"}
2023-07-12T08:28:18.760Z	INFO	kuma-dp.run	stopping all Kuma DP components
2023-07-12T08:28:18.760Z	INFO	metrics-hijacker	stopping Metrics Hijacker Server
2023-07-12T08:28:18.760Z	INFO	kuma-dp.run.envoy	stopping Envoy
2023-07-12T08:28:18.761Z	INFO	kuma-dp.run.access-log-streamer	done
2023-07-12T08:28:18.761Z	INFO	kuma-dp.run.dns-server	stopping DNS Server
2023-07-12T08:28:18.763Z	INFO	kuma-dp.run	stopping Kuma DP


```
Once the sidecar successfully initializes after a few restart attempts, the connectivity with the vault is established successfully.

**Comment by ravish-kumar-maersk** [comment]
Hi @lahabana , 
[6082](https://github.com/kumahq/kuma/issues/6082) and [annotation](https://kuma.io/docs/2.3.x/reference/kubernetes-annotations/#kumaioinit-first) won't help in this use-case as we are using Kuma CNI. 
They will help only if we are using "kuma init + vault init" containers.

**Comment by lahabana** [comment]
HAve you considered using: https://kuma.io/docs/2.3.x/reference/kubernetes-annotations/#traffickumaioexclude-outbound-ports to exclude the vault port?

**Comment by brunda-bs** [comment]
Adding 443 as exclude outbound port is not a good option here as there are other services which use the same port.

**Comment by lahabana** [comment]
If so I think we could add to our CNI the same thing we've done for the init-container: https://github.com/kumahq/kuma/issues/4967

**Comment by lahabana** [comment]
Please let me know if uid outbound port exclusion would work for you.

**Comment by ravish-kumar-maersk** [comment]
Sure @lahabana 
Will check for the `uid outbound port exclusion` option and revert.

**Comment by brunda-bs** [comment]
Hi @lahabana ,

We tried the below annotation and its not working as expected -
```
      annotations:
        traffic.kuma.io/exclude-outbound-tcp-ports-for-uids: '443:65534'
```

Vault init container uid reference - https://github.com/banzaicloud/bank-vaults/blob/1.4.1/Dockerfile#L24

**Comment by jakubdyszkiewicz** [comment]
Please also add `traffic.kuma.io/exclude-outbound-udp-ports-for-uids: "53:1234"`.
Take a look at this doc draft https://github.com/kumahq/kuma-website/pull/1423

**Comment by ravish-kumar-maersk** [comment]
It didn't help @jakubdyszkiewicz. 

Annotations used:

```
traffic.kuma.io/exclude-outbound-tcp-ports-for-uids: 443:65534
traffic.kuma.io/exclude-outbound-udp-ports-for-uids: 53:65534
```

Do we need to add External Service for this network call (which is outside the mesh)?

**Comment by lahabana** [comment]
> If so I think we could add to our CNI the same thing we've done for the init-container: https://github.com/kumahq/kuma/issues/4967

I think these are not implemented on the CNI right @jakubdyszkiewicz ?

**Comment by ravish-kumar-maersk** [comment]
Sure @jakubdyszkiewicz and @lahabana 

Will try by enabling experimental CNI.

**Comment by ravish-kumar-maersk** [comment]
The new CNI didn't help here @jakubdyszkiewicz and @lahabana.

CNI Image used - `kumahq/kuma-cni:2.1.1`

Annotations used - 
```
traffic.kuma.io/exclude-outbound-tcp-ports-for-uids: "443:65534"
traffic.kuma.io/exclude-outbound-udp-ports-for-uids: "53:65534"
```

Vault-init container used - `ghcr.io/banzaicloud/vault-env:1.14.1`

Application error - 
```
time="2023-07-28T07:48:52Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"VAULT-DNS/v1/auth/CLUSTER-NAME/login\": EOF"
time="2023-07-28T07:48:57Z" level=error msg="failed to request new Vault token" app=vault-env err="Put \"VAULT-DNS/v1/auth/CLUSTER-NAME/login\": EOF"
time="2023-07-28T07:48:59Z" level=fatal msg="failed to create vault clienttimeout [30s] during waiting for Vault token" app=vault-env
```

**Comment by jakubdyszkiewicz** [comment]
Are you sure that the Vault container runs with UID of 65534?
https://developer.hashicorp.com/vault/docs/platform/k8s/injector/annotations here it says that the default is 100
```
[vault.hashicorp.com/agent-run-as-user](https://developer.hashicorp.com/vault/docs/platform/k8s/injector/annotations#vault-hashicorp-com-agent-run-as-user) - sets the user (uid) to run Vault agent as. Also available as a command-line option (-run-as-user) or environment variable (AGENT_INJECT_RUN_AS_USER) for the injector. Defaults to 100.
```

**Comment by ravish-kumar-maersk** [comment]
@jakubdyszkiewicz 

We are using Banzai Cloud Vault Secret [Webhook](https://bank-vaults.dev/docs/mutating-webhook/) to perform secret mutation within Kubernetes, with Hashicorp [Vault](https://www.hashicorp.com/products/vault) KV as a source.

Detailed info - https://banzaicloud.com/blog/inject-secrets-into-pods-vault-revisited/

Deployment annotations for vault init injection - 
vault.security.banzaicloud.io/vault-role: "<ns_name>"
vault.security.banzaicloud.io/vault-skip-verify: "true"  

This mutates the Pod with vault init container `ghcr.io/banzaicloud/vault-env:1.14.1`.

**Comment by ravish-kumar-maersk** [comment]
> However, I see that we made it default in 2.2.0 and @ravish-kumar-maersk is on 2.1.1. We recommend upgrading, but you can also use experimental CNI https://github.com/kumahq/kuma/blob/release-2.1/deployments/charts/kuma/values.yaml#L684

Will try the solution by upgrading Kuma as the current annotations are not working as expected for Kuma 2.1.1.

In the meanwhile, K8s released an "alpha" version about [Sidecar container](https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#api-for-sidecar-containers) in 1.28.

Would appreciate it if there are plans to embrace it.
@lahabana

**Comment by lahabana** [comment]
We will of course embrace sidecar container (Just opened https://github.com/kumahq/kuma/issues/7541)

**Comment by lukidzi** [comment]
In release 2.4 we added the option to wait for a sidecar to be ready https://github.com/kumahq/kuma/pull/7583

**Comment by slonka** [comment]
@brunda-bs did you have time to check out 2.4?

**Comment by slonka** [comment]
pinging @brunda-bs again and moving to triage since we had this functionality since the last release, probably close if no response

**Comment by jakubdyszkiewicz** [comment]
> Triage: closing. Feel free to reopen this if you still have a problem in 2.4
