### ISSUE TITLE
New style resources restricted to kuma-system namespace

### ISSUE THREAD

**Issue by rdavyd** [kumahq/kuma#7257]
### What happened?

Resources like `meshhttproutes`, `meshretries` and others announced here - [LINK](https://konghq.com/blog/product-releases/kong-mesh-kuma-2-1) cannot be created outside of `kuma-system` namespace in 2.3.0.
```bash
Error from server (Forbidden): error when creating "STDIN": admission webhook "validator.kuma-admission.kuma.io" denied the request: policy can only be created in the system namespace:kuma-system
```
This is strange because resources are namespaced and I could create them in arbitrary namespaces in 2.1.1.
Is it intended behavior?

**Comment by jakubdyszkiewicz** [comment]
> Triage: It is intended behavior. The new resources for now should only be applied in the system namespace. In the future, we want to take into account the namespace of the resource. For example: MeshRetry applied in namespace `team-a` should only affect data plane proxies in namespace `team-a`. We had this validation from 2.0 https://github.com/kumahq/kuma/blob/release-2.0/pkg/plugins/runtime/k8s/webhooks/policy_namespace_validator.go

**Comment by jakubdyszkiewicz** [comment]
https://github.com/kumahq/kuma/issues/7269
