### ISSUE TITLE
Duplicate Host Entries in External Services Prevent new DNS entries being registered in the Envoy Sidecar config

### ISSUE THREAD

**Issue by james-bjss** [kumahq/kuma#7318]
### What happened?

**Issue:**
- Team discovered that it was not possible to connect to some services in the mesh and that .mesh addresses were not resolving.
- A `curl http://localhost:9901/config_dump` showed that the addresses for some pods/services were missing from the `listener_filters` in the envoy-sidecar config.
- On further inspection we noticed that there were 2x `ExternalService` defined with the same hostname.

**Resolution:**
Removal of the duplicate `ExternalServices` hostname resolved the issue and the missing hostnames of other services then correctly appeared in the list.

**Expected Behaviour:**
We should either prevent the creation of a duplicate entry (something we may enforce with OPA gatekeeper as a workaround). Or else would expect an error to be logged within Kuma and the system resume normal operation (skipping the duplicate).

**Further Info:**
Kuma version: `2.3.0`
Running on: K8s 1.20 (EKS)
mTls and transparent proxying enabled / passthrough disabled.
Kuma reported the missing services as Healthy and the External services simply report as Unknown (no indication of issues)

Also would like to understand how I could observe this issue in the logs. I Spotted the problem by combing the config in the cluster, but wondered if there would be an associated failure in the logs I could have observed as I wasn't able to track one down.

**Comment by james-bjss** [comment]
Wondering if this is a dupe of: https://github.com/kumahq/kuma/pull/7282

**Comment by jakubdyszkiewicz** [comment]
Thanks for reporting. It is indeed a duplicate. We already released a patch version with the fix
