### ISSUE TITLE
SimpleWatchdog.Start should take a ctx

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#7349]
### Description

After working on:
 - https://github.com/kumahq/kuma/pull/7348

We realised that SimpleWatchdog takes in a channel it would probably just use a context as it would avoid needing a goroutine and complex logic to handle closed channel.
If we actually go up the levels we can see that go-control-plane passes the ctx of the stream already. Should we just use this one or would that cause issues?
We have the stream ctx stored already in dataplane_callbacks.

**Comment by slonka** [comment]
Still the case https://github.com/kumahq/kuma/blob/ae945b01999633d1e7bd68ad74ae3979ad99b511/pkg/util/watchdog/watchdog.go#L21
