### ISSUE TITLE
Optimize K8s store resource counting

### ISSUE THREAD

**Issue by nickolaev** [kumahq/kuma#737]
### Summary

#723 introduces a `total` count field when listing resources, to note the overall count of the particular resource listed, regardless of the current pagination/offset requested. This has a number of uses in the GUI (https://github.com/Kong/kuma-gui/pull/25) and extends the HTTP API for its users.

When Kuma is run in K8s mode, where the resources are stored as K8s/etcd resources, the counting of the Totals is done by retrieving all the resource's items. This is suboptimal and incurs scalability issues. A better approach is to use informers and subscribe for resource change, so once kuma-cp is run it will always keep count of the actual number of the particular resource. This was put as out of scope of #723, but needs to be improved in a follow-up PR.

### Additional Details & Logs

A link to the discussion in the PR: https://github.com/Kong/kuma/pull/723#discussion_r422259547

**Comment by jakubdyszkiewicz** [comment]
We now have MeshInsights as well as Kubernetes cache
