### ISSUE TITLE
Add `isNewStylePolicy` field to `/policies`

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma#7485]
### Description

Add a `isNewStylePolicy` field to `/policies` indicating whether a policy type is of a new style. We specifically want this for https://github.com/kumahq/kuma-gui/issues/1290 meaning what we want to be able to do is know whether a policy of a certain policy type will have a top-level target ref object.

**Comment by lahabana** [comment]
Will be `isTargetRefBased`

**Comment by lahabana** [comment]
Will also add `isInbound` and `isOutbound` as its useful.
