### ISSUE TITLE
kuma-cp fails to create the dataplane if one of the deployment tag is empty

### ISSUE THREAD

**Issue by lucaghersi** [kumahq/kuma#753]
### Summary

kuma-cp fails to create the dataplane if one of the deployment tag is invalid in the deployment in Kubernetes

### Steps To Reproduce

1. Create a kuma enabled namespace in Kubernetes
2. Create a deployment with a empty label, for example like this:

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-api
spec:
  selector:
    matchLabels:
      app: delivery-api
  replicas: 3
  template:
    metadata:
      labels:
        name: delivery-api
        app: delivery-api
        Octopus.RunbookRun.Id: ""
    spec:
     .....
```

### Additional Details & Logs

- Version: 0.5.0
- Error logs

020-05-20T11:04:39.583Z	ERROR	controllers.Pod	unable to create/update Dataplane	{"pod": "delivery-api/delivery-api-55bc579cc8-z8pd8", "operationResult": "unchanged", "error": "admission webhook \"validator.kuma-admission.kuma.io\" denied the request: spec.networking.inbound[0].tags[\"Octopus.RunbookRun.Id\"]: tag value cannot be empty"}

2020-05-20T11:04:39.583Z	ERROR	controller-runtime.controller	Reconciler error	{"controller": "pod", "request": "delivery-api/delivery-api-55bc579cc8-z8pd8", "error": "admission webhook \"validator.kuma-admission.kuma.io\" denied the request: spec.networking.inbound[0].tags[\"Octopus.RunbookRun.Id\"]: tag value cannot be empty"}
E0520 11:04:39.585191       1 event.go:260] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"delivery-api-55bc579cc8-z8pd8.1610b7a69d35fe88", GenerateName:"", Namespace:"delivery-api", SelfLink:"", UID:"", ResourceVersion:"", Generation:0, CreationTimestamp:v1.Time{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, DeletionTimestamp:(*v1.Time)(nil), DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ClusterName:"", ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:"Pod", Namespace:"delivery-api", Name:"delivery-api-55bc579cc8-z8pd8", UID:"6eb9dbc2-225e-49c6-be10-22ae09e6c8ad", APIVersion:"v1", ResourceVersion:"60157248", FieldPath:""}, Reason:"FailedToGenerateKumaDataplane", Message:"Failed to generate Kuma Dataplane: admission webhook \"validator.kuma-admission.kuma.io\" denied the request: spec.networking.inbound[0].tags[\"Octopus.RunbookRun.Id\"]: tag value cannot be empty", Source:v1.EventSource{Component:"k8s.kuma.io/dataplane-generator", Host:""}, FirstTimestamp:v1.Time{Time:time.Time{wall:0xbfa9617ca93c0a88, ext:13091147576246, loc:(*time.Location)(0x3062e40)}}, LastTimestamp:v1.Time{Time:time.Time{wall:0xbfa96191e2cbb0a6, ext:13176039549808, loc:(*time.Location)(0x3062e40)}}, Count:20, Type:"Warning", EventTime:v1.MicroTime{Time:time.Time{wall:0x0, ext:0, loc:(*time.Location)(nil)}}, Series:(*v1.EventSeries)(nil), Action:"", Related:(*v1.ObjectReference)(nil), ReportingController:"", ReportingInstance:""}': 'events "delivery-api-55bc579cc8-z8pd8.1610b7a69d35fe88" is forbidden: User "system:serviceaccount:kuma-system:kuma-control-plane" cannot patch resource "events" in API group "" in the namespace "delivery-api"' (will not retry!)

### Expected

I would expect for the empty label to be ignored

**Comment by jakubdyszkiewicz** [comment]
Hey @lucaghersi 

thanks for reporting it!

I'm hesitant between loosing up validators letting empty tag value or ignoring such labels. I think we can go with ignoring for now.

This should be a fairly easy fix in `pod_converter.go`. It should land in the next version of Kuma.

**Comment by tharun208** [comment]
> Hey @lucaghersi
> 
> thanks for reporting it!
> 
> I'm hesitant between loosing up validators letting empty tag value or ignoring such labels. I think we can go with ignoring for now.
> 
> This should be a fairly easy fix in `pod_converter.go`. It should land in the next version of Kuma.

@jakubdyszkiewicz , can we ignore empty tags in `dataplane_validator`?

**Comment by jakubdyszkiewicz** [comment]
No we cannot, we should ignore such pairs when we convert Pod to Dataplane
https://github.com/kumahq/kuma/blob/master/pkg/plugins/discovery/k8s/controllers/inbound_converter.go#L50
