### ISSUE TITLE
Review provided gateway support in new policies

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#7544]
### Description

We should ensure new policies work with delegated gateways in all cases

**Comment by jakubdyszkiewicz** [comment]
> Triage: we need to first reproduce it. The problem is 99% with the new policies.

**Comment by jakubdyszkiewicz** [comment]
It is, at least with MeshCircuitBreaker

**Comment by michaelbeaumont** [comment]
[The above PR](https://github.com/kumahq/kuma/pull/8740) should solve this
