### ISSUE TITLE
New policies should have more efficient unmarshalling

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#7559]
### What happened?

When we unmarshal resources we do a lot of redudant unmarshalling.

https://github.com/kumahq/kuma/blob/2a4c31c93b64717b7250ad19c37c85b9a433eb6b/pkg/api-server/resource_endpoints.go#L147-L178

Could we generate a mapper from map[string]interface to the actual type to avoid the double JSON parsing.

**Comment by jakubdyszkiewicz** [comment]
> Triage: it's a create/update. It's probably not a bottleneck
