### ISSUE TITLE
Why the intermediate CA certificates are not allowed in "provided" CA?

### ISSUE THREAD

**Issue by ryysud** [kumahq/kuma#759]
### Summary

Why the intermediate CA certificates are not allowed in "provided" CA?
https://kuma.io/docs/0.5.0/policies/mutual-tls/#usage-of-provided-ca

I found a comment like `Envoy constraint` in the code and I want to know more about it.
https://github.com/Kong/kuma/blob/0.5.0/pkg/plugins/ca/provided/ca_cert_validator.go#L33-L35

**Comment by nickolaev** [comment]
Envoy has this pretty old issue, which apparently is still relevant: https://github.com/envoyproxy/envoy/issues/1220. I think it gives a good explanation, especially the last couple of comments.

Then there was this user sharing their experience: https://github.com/envoyproxy/envoy/issues/2675 I am sure there is more info around the internet.

Does that help you with your question?

**Comment by ryysud** [comment]
That is very helpful for me. Thank you.

**Comment by jakubdyszkiewicz** [comment]
Revisit intermediate CA support

**Comment by nikita15p** [comment]
+1
