### ISSUE TITLE
reduce the number of metrics sent by envoy by default

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#7596]
### Description

Envoy sends a LOT of metrics by default. It's overwhelming to new users.
Can we try to get a good set of metrics and only expose these ones on fresh installs?

**Comment by jakubdyszkiewicz** [comment]
Consider solving this as a part of https://github.com/kumahq/kuma/issues/5708

**Comment by lahabana** [comment]
Duplicate of https://github.com/kumahq/kuma/issues/8845
