### ISSUE TITLE
Use CLA cache efficiently for all types of proxies

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#7599]
### Description

We have at least 3 generators that are capable of using CLA cache:
1. DPP (already use CLA cache)
2. Builtin Gateway (already use CLA cache)
3. Zone Ingress (doesn't use CLA cache)

The problem is these generators name the clusters differently:
1. DPP – https://github.com/kumahq/kuma/blob/master/pkg/xds/generator/outbound_proxy_generator.go#L374
2. Builtin Gateway – https://github.com/kumahq/kuma/blob/master/pkg/xds/envoy/tags/match.go#L20
3. Zone Ingress – https://github.com/kumahq/kuma/blob/master/pkg/xds/generator/zoneproxy/generator.go#L24

Different cluster names lead to different keys in the CLA cache, and because of that, the cache is not as efficient as it could be.

**Comment by lahabana** [comment]
@lukidzi you may be interested in this too

**Comment by michaelbeaumont** [comment]
Update: we now name dataplane and gateway clusters the same way.

**Comment by lahabana** [comment]
Duplicate of #8124 a generic cache across DPPs should cover different proxy types
