### ISSUE TITLE
`TLS error: SSL:routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED`

### ISSUE THREAD

**Issue by Hunter-Thompson** [kumahq/kuma#7726]
### What happened?

```
upstream connect error or discconect/reset before headers.  TLS error: SSL:routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
```

Every once in a while Kuma fails to update the certificate for the upstream sidecar and I get the above error. I see no error logs in the control plane. This happens randomly and for different services in the mesh.

Kuma version: `v1.8.0`

**Comment by lahabana** [comment]
> Triage: 1.8 is technically out of support. Have you tried with a more recent version of Kuma?

**Comment by jakubdyszkiewicz** [comment]
> Kuma fails to update the certificate for the upstream sidecar

Do you see an error in CP?

**Comment by slonka** [comment]
@Hunter-Thompson can you share the logs of the CP?

**Comment by Hunter-Thompson** [comment]
> @Hunter-Thompson can you share the logs of the CP?

I've increased the time for certificate expiry since we can't afford the downtime in prod. I'll share the logs when it happens again in the dev environment.

**Comment by Hunter-Thompson** [comment]
> @Hunter-Thompson can you share the logs of the CP?

This happened again. On Kuma version 2.1.1 even after increasing the cert expiry date.

Error:

```
pstream connect error or disconnect/reset before headers. reset reason: connection failure, transport failure reason: TLS error: 268435612:SSL routines:OPENSSL_internal:HTTP_REQUEST
```

Side car logs: 

```
[2023-10-12 12:07:56.503][27][warning][config] [./source/common/config/grpc_stream.h:160] StreamAggregatedResources gRPC config stream closed: 2, authentication failed: authentication failed: token doesn't belong to a valid user
```

Control plane logs:
```
2023/10/12 12:09:07 http: TLS handshake error from 10.128.4.8:56662: EOF
```

Both of these errors are 2 min apart.

**Comment by jakubdyszkiewicz** [comment]
> Triage: looks like Kubernetes service account token is not valid anymore. Do you use short-lived projected service account tokens? What Kube distro do you use?

> Also we should add/log `tokenReview.Status.Error` in `kubeAuthenticator`

**Comment by Hunter-Thompson** [comment]
> > Triage: looks like Kubernetes service account token is not valid anymore. Do you use short-lived projected service account tokens? What Kube distro do you use?
> 
> > Also we should add/log `tokenReview.Status.Error` in `kubeAuthenticator`

We use EKS, and we use the projected SA tokens.

**Comment by jakubdyszkiewicz** [comment]
just for the peace of mind.
Do you use `dpServer.auth.useTokenPath ` described here? https://kuma.io/docs/2.4.x/production/secure-deployment/dp-auth/#token-rotation

**Comment by slonka** [comment]
pinging @Hunter-Thompson ☝️

**Comment by Hunter-Thompson** [comment]
We didn't add that option, I will retry with it.

**Comment by lahabana** [comment]
Hey @Hunter-Thompson any update?

**Comment by jakubdyszkiewicz** [comment]
> Triage: closing for now due to no answer. Feel free to reopen if this is still the issue. Thanks!
