### ISSUE TITLE
Value `not: true` in tags ignored during reference matching 

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#7728]
### What happened?

when generating header matching configs for envoy's fault filters, we are ignoring tag's value: not: true (i.e. { "key": "kuma.io/service", "value": "edge-gateway", "not": true }) which basically means for some of the fault filter configs we are generating inverted regexes.

This is the reason behind problem described here: https://github.com/kumahq/kuma/issues/6630

**Comment by lahabana** [comment]
> Triage: The problem is when doing service matching to figure if a policy applies to a service subset.
