### ISSUE TITLE
/global-insight has content-type plain/text

### ISSUE THREAD

**Issue by kleinfreund** [kumahq/kuma#7814]
### What happened?

The new `/global-insight` responds with content-type `plain/text` when it should be `application/json`.

**Comment by bartsmykla** [comment]
There is already PR with the fix: https://github.com/kumahq/kuma/pull/7813

**Comment by kleinfreund** [comment]
@bartsmykla Thanks! Can you please triage this issue? I don’t have the permissions to change labels, etc.

**Comment by bartsmykla** [comment]
Done
