### ISSUE TITLE
CNI mode triggers the node taint controller and blocks app rollout

### ISSUE THREAD

**Issue by bcollard** [kumahq/kuma#7835]
### What happened?

When using the CNI (v1), the node taint controller added `NodeReadiness:NoSchedule` taints.

The doc mentions a way to disable this controller (btw. only under the CNI v2 part): https://docs.konghq.com/mesh/latest/production/dp-config/cni/#kong-mesh-v2-cni-taint-controller

Tried to disable the controller with the following Helm values, didn't work:
```bash
helm template kong-mesh kong-mesh/kong-mesh --version 2.4.1 -s charts/kuma/templates/cp-deployment.yaml -f - <<EOF
kuma:
  cni:
    enabled: true
    chained: true
    netDir: /etc/cni/net.d
    binDir: /home/kubernetes/bin
    confName: 10-calico.conflist
  controlPlane:
    envVars:
      KUMA_RUNTIME_KUBERNETES_NODE_TAINT_CONTROLLER_ENABLED: false
EOF
```
Had to use the following instead:
`KUMA_RUNTIME_KUBERNETES_NODE_TAINT_CONTROLLER_ENABLED: "false"`

The user environment is GKE with data-plane v1 (Calico). They have security policies preventing the use of container NET_ADMIN capability

Kong Mesh v2.4.1 + MinK

**Comment by jakubdyszkiewicz** [comment]
There are two issues here
* We need to fix `"false"` instead of `false` in docs.
* We need logs of CNI to see why CNI failed to install.

**Comment by lahabana** [comment]
doc fix: https://github.com/kumahq/kuma-website/pull/1472

**Comment by slonka** [comment]
> We need logs of CNI to see why CNI failed to install.

@bcollard can you send over the logs?

**Comment by slonka** [comment]
pinging @bcollard again for an answer, also we releases 2.5.0 in the meanwhile so might try on 2.5.0
