### ISSUE TITLE
Flake on GatewayAPI TestConformance/HTTPRouteRequestMirror

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#7865]
### What happened?

The same test is flaky:

    --- FAIL: TestConformance/HTTPRouteRequestMirror (1.03s)
        --- FAIL: TestConformance/HTTPRouteRequestMirror/0_request_to_'/mirror'_should_go_to_infra-backend-v1 (60.00s)
        --- FAIL: TestConformance/HTTPRouteRequestMirror/1_request_to_'/mirror-and-modify-headers'_with_headers_should_go_to_infra-backend-v1 (60.00s)

Some runs:
https://app.circleci.com/pipelines/github/kumahq/kuma/25068/workflows/09360207-3157-4f85-a7e2-2883e540e2e7/jobs/504480
https://app.circleci.com/pipelines/github/kumahq/kuma/25015/workflows/fc117b51-c5f1-4b36-99fb-4a216fce4a33/jobs/502871
https://app.circleci.com/pipelines/github/kumahq/kuma/24964/workflows/ce6ecacd-13f9-415b-85c2-2168fcbd7c44/jobs/501594

**Comment by lahabana** [comment]
Have we seen this flake recently?

**Comment by lahabana** [comment]
Doesn't seem like it's failing anymore

**Comment by michaelbeaumont** [comment]
[Flaky run](https://github.com/kumahq/kuma/actions/runs/7960326410/job/21729082008#step:13:4111)

**Comment by lukidzi** [comment]
I haven’t noticed any Gateway API test flakes recently. Let’s close this for now and reopen it if the issue occurs again.
