### ISSUE TITLE
[Helm][Argo] Argo CD does helm templating which causes `tls-checksum` annotation change

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#7908]
### What happened?

Argo CD uses templating for managing deployments. Helm template doesn't connect to the cluster and cannot check if secrets exist. That causes the annotation `tls-checksum` to change the value. That can cause the creation of new `ReplicaSets` because the pod template has changed. Certificates are not changed just can cause additional `ReplicaSets`

**Comment by jakubdyszkiewicz** [comment]
We have docs for this problem https://kuma.io/docs/2.0.x/installation/helm/#argo-cd
We need to set certs explicitly to avoid this issue.
