### ISSUE TITLE
Improve validation of resources before sending them to DP

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#797]
#### Listeners

Since we are generating listeners in couple of places (InboundProxyGenerator, OutboundProxyGenerator, DirectAccessProxyGeneration, PrometheusEndpointGenerator etc.)
we should double-check if listeners are actually unique (PORT:IP) before sending them to Envoy

#### Proto validation

All envoy resources expose `Validate()` method. We should execute before sending them to DP, just in case.

**Comment by tharun208** [comment]
@jakubdyszkiewicz I'll work on this

**Comment by jpeach** [comment]
> All envoy resources expose `Validate()` method. We should execute before sending them to DP, just in case.

This part was done in #2537.

**Comment by jakubdyszkiewicz** [comment]
The most important part was implemented. We now have an XDS backoff and logs about rejected config in CP.
