### ISSUE TITLE
ValidateMeta function doesn't follow Kubernetes naming convention

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#7971]
### What happened?

ValidateMeta function checks that resource name is matching the regex `^[0-9a-z-_.]*$` (while Kubernetes is using `^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$`). There are at least 2 significant differences for us:
1. Kuma allows names with `_` (problem when syncing policy from Universal Global to K8s Zone)
2. Kuma doesn't allow names with `.` (problem when try to create secrets through API server)

**Comment by lahabana** [comment]
We have to be careful at backward compatibility here

**Comment by lobkovilya** [comment]
Yes, allowing dots is simple because we're allowing more names. But disallowing `_` requires backward compatibility

**Comment by jakubdyszkiewicz** [comment]
@kleinfreund to check regex on frontend

**Comment by kleinfreund** [comment]
We use `/^(?![-0-9])[a-z0-9-]{1,63}$/` and reference https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#rfc-1035-label-names in the comment here: https://github.com/kumahq/kuma-gui/blob/4f48278e39907e43a68874c9c99dddb3387ecdc7/src/app/zones/views/ZoneCreateView.vue#L394-L397

**Comment by lobkovilya** [comment]
I was using `subdomain` from [here](https://github.com/kubernetes/design-proposals-archive/blob/main/architecture/identifiers.md):

> [rfc1035](http://www.ietf.org/rfc/rfc1035.txt)/[rfc1123](http://www.ietf.org/rfc/rfc1123.txt) subdomain (DNS_SUBDOMAIN): One or more lowercase rfc1035/rfc1123 labels separated by '.' with a maximum length of 253 characters.

The regex looks like `^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$`. Seems like the only major difference is we're allowing '.'
