### ISSUE TITLE
Exclude some namespaces from the kuma sidecar injector mutating webhook

### ISSUE THREAD

**Issue by slavogiez** [kumahq/kuma#7974]
### Description

I'd like to exclude some sensitive namespace (ie: kube-system) from the kuma sidecar injector mutating webhook since we had some alert in GKE mentioning that requests to kube-system were intercepted by this webhook.

I figured out that in the Helm chart, there are 3 sections related to kuma-injector.kuma.io :
- [namespace-kuma-injector.kuma.io](https://github.com/kumahq/kuma/blob/71f9c31b4866d5765642130de8da5484740809cf/deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml#L119C21-L119C42): uses a namespaceSelector
- [pods-kuma-injector.kuma.io](https://github.com/kumahq/kuma/blob/71f9c31b4866d5765642130de8da5484740809cf/deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml#L141): uses an objectSelector
- [kuma-injector.kuma.io](https://github.com/kumahq/kuma/blob/71f9c31b4866d5765642130de8da5484740809cf/deployments/charts/kuma/templates/cp-webhooks-and-secrets.yaml#L163): no selector

What's the purpose of the last one? I feel that it is this one that is triggering alerts on GKE console.
Is there already a way to prevent this webhook from intercepting requests on specific namespaces? Or does it require a change on the chart?

**Comment by jakubdyszkiewicz** [comment]
> Triage:`kuma-injector.kuma.io` is a webhook for backwards compatability with `kuma.io/sidecar-injection` annotation before we switched to label. We removed support for annotations in Kuma 2.2, we can now remove this webhook.

**Comment by bhavyastar** [comment]
Hey @slavogiez, I would like to work on this issue.

**Comment by michaelbeaumont** [comment]
@bhavyastar Feel free! In particular we should remove `kuma-injector.kuma.io` as mentioned by jakub above.
