### ISSUE TITLE
GOMAXPROCS should be set according to the container CPU quota 

### ISSUE THREAD

**Issue by lobkovilya** [kumahq/kuma#7982]
### Description

By default, GOMAXPROCS is set according to the node's CPU capacity. Seems like it can cause throttling when a node has way more CPU than is available to the pod. 

One of the solutions is to use a library like https://github.com/uber-go/automaxprocs when running in container environments.

**Comment by lahabana** [comment]
When do we use GOMAXPROCS ?

**Comment by lobkovilya** [comment]
We don't set it explicitly, that's why the value for GOMAXPROCS is set by default to:
> the number of logical CPUs usable by the current process

And that value is a characteristic of the node (not the container).

**Comment by lahabana** [comment]
I guess in Helm we can easily fix by using the downwardAPI: https://kubernetes.io/docs/concepts/workloads/pods/downward-api/#downwardapi-resourceFieldRef

**Comment by lobkovilya** [comment]
There is a bit of logic that translates cgroups quota to GOMAXPROCS https://github.com/uber-go/automaxprocs/blob/master/internal/runtime/cpu_quota_linux.go#L35. I'm not sure if we want to implement the same in helm

**Comment by jakubdyszkiewicz** [comment]
Can this impact a performance in significant way? If so, should we run mesh-perf experiment?

**Comment by lahabana** [comment]
We're adding this to CP in: https://github.com/kumahq/kuma/pull/10879

I guess the question is for the DP go process. Should we restrict to 1 as the DP is not supposed to do much?

**Comment by michaelbeaumont** [comment]
Closing this since we've implemented this for CP but have decided for now not to set this for the DP
