### ISSUE TITLE
Prometheus node exporter as part of the mesh

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#799]
### Summary

We disabled Kuma DP injection next to node exporter for now, because it was crashing K8S Cluster (both on KIND and Minikube).

Double-check if Kuma DP works with DaemonSet.

Reference: https://github.com/Kong/kuma/pull/793#discussion_r433960065

**Comment by lahabana** [comment]
Not accurate anymore with have Kuma-sd
