### ISSUE TITLE
Support all tags in sources and destinations

### ISSUE THREAD

**Issue by nickolaev** [kumahq/kuma#801]
### Summary

TBD

**Comment by nickolaev** [comment]
Done for ingress.

**Comment by jakubdyszkiewicz** [comment]
Closing for now since it was not required for multizone after all

**Comment by Cephei** [comment]
Will this be re-opened and addressed for TrafficPermission sources? According to the latest docs: `For the time being the sources field only allows the service tag. This limitation will be removed in the future.`

It would be nice to use tags in the `sources`.
