### ISSUE TITLE
routes is not iterable error in GatewayDataplanePolicyList

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma#8107]
### What happened?

`src/app/gateways/components/GatewayDataplanePolicyList.vue at line 118:32`

```
for (const route of host.routes) {
```

Looks to to be around here ^

From what I understand this originates from an issue in the backend, where this property should be at least an empty array.

**Comment by jakubdyszkiewicz** [comment]
> Triage: it's inspect API
