### ISSUE TITLE
Supporting meshhttproute in meshretry

### ISSUE THREAD

**Issue by eshih** [kumahq/kuma#8110]
### Description

As a Kuma user I'd like to be able to apply MeshRetry (or Retry) policies at a HTTP path level. For example, I'd like to apply a Retry policy specifically on `myservice.mesh/pathA` and a different Retry Policy on `myservice.mesh/pathB`

**Comment by jakubdyszkiewicz** [comment]
> Triage: is it configure MeshGatewayRoute with MeshRetry?

**Comment by eshih** [comment]
For our specific use-case, we'd like to be able to set a MeshRetry policy at a specific path of the service.
Though adding retry abilities to MeshGatewayRoute would also be useful.

**Comment by lahabana** [comment]
Duplicate of https://github.com/kumahq/kuma/issues/6923
