### ISSUE TITLE
Put coredns configuration in a configmap

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#8119]
### Description

This would give users
1. visibility
1. configurability

into how we configure coredns to handle DNS requests in the mesh

**Comment by lahabana** [comment]
Only question is universal. Having it embedded is nice for universal

**Comment by jakubdyszkiewicz** [comment]
> Triage: it's still useful to have this embedded in kuma-dp run

**Comment by lahabana** [comment]
xref: https://github.com/kumahq/kuma/issues/8269

**Comment by jijiechen** [comment]
Replacing https://github.com/kumahq/kuma/issues/8633

More background:

## Description
People want to customize the DNS template used by the kuma data plane to address following issues:

* Integrate with their existing DNS servers
* Resolve certain network issues introduced by the DNS proxying model of kuma dp, e.g. it's found by some Kuma clients that the DNS in kuma data plane is not compatible with certain alpine images (https://github.com/alpinelinux/docker-alpine/issues/155#issuecomment-833676652)

It's good to make our builtin Corefile template customizable.

It's best to support for both k8s and universal data planes.

## Not in scope: 

configuring command line of CoreDNS at data planes parameters from the control plane

**Comment by jijiechen** [comment]
The PR has now been merged and we'll see if we need to backport to older versions.
