### ISSUE TITLE
Rethink CLA Cache

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#8121]
### Description

We use CLACache to hold `ClusterLoadAssignmanet` and do not rebuild them when many clients use the same endpoints. That is really useful and improves the performance of Control-plane because we don't need to do the same work for each dataplane. The problem is when each dataplane has different endpoints to communicate with. In this case, the cache might be initialized and endpoints might not be used. 

Example:
MeshLoadBalancingStrategy might create a different set of endpoints for each dataplane and entries in the cache might not make much sense.

Some ideas to validate:
* maybe we can store in the cache Endpoints instead of CLA
* better Cache key containing tags/policies?
* move cache to MeshContext?

**Comment by lahabana** [comment]
Closing in favour of #8124 that is a lot more specific
