### ISSUE TITLE
add all version.Build to cp_info metrics

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#8143]
### Description

Here:

https://github.com/kumahq/kuma/blob/152408bf7a8b02d712b25b4b32558b96d7b6f401/pkg/metrics/components/cp_info.go#L22-L25

we should make it so that we don't have to do this manually in the future

**Comment by jijiechen** [comment]
So are you actively working on this issue?  @lahabana

**Comment by lahabana** [comment]
Yes there's a PR for it I believe
