### ISSUE TITLE
Add log aggregation  to kumactl install

### ISSUE THREAD

**Issue by xbauquet** [kumahq/kuma#819]
### Summary

The goal for `kumactl install` to provide a way to aggregate and visualize app logs easily.  
I propose to use [grafana/Loki](https://github.com/grafana/loki) to aggregate app logs and visualize then directly into the Grafana installed with the metrics. 

This screen shot shows how log visualization with Loki can be used with the traces from Jaeger, if your logs contain the traceId. Some libraries add the traceId into the logs automatically (e.g. [Sleuth](https://github.com/spring-cloud/spring-cloud-sleuth), for Spring java apps).

<img width="1792" alt="Capture d’écran 2020-06-10 à 10 12 05" src="https://user-images.githubusercontent.com/8179943/84268653-4a312e00-ab28-11ea-97d6-e1191fe03611.png">

**Comment by nickolaev** [comment]
Fixed in #820
