### ISSUE TITLE
Rollout of deprecation of Standalone mode and Zone mode as default

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#8191]
### Description

Goal is to get rid of standalone. So we should stop new users from starting on Standalone by having the default be zone without global.

**Comment by lahabana** [comment]
> Triage: needs applying policy from zone first to do this. Also would we always need a zone name in this case?

**Comment by lobkovilya** [comment]
Today the default is Standalone both in `helm` and `kumactl`, we should change it to Zone.
