### ISSUE TITLE
Simplify and make MeshAccessLog API consistent before GA

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#8223]
### Description

Let's make sure that `MeshAccessLog` API is as simple and consistent before making it GA.

- [x] ~~Make `backends` consistent~~
  - [x] ~~Otel~~
    - [x] ~~Should we change the [`Body` field](https://github.com/kumahq/kuma/blob/a41b0631b1ded03b83b52eff039deba7bcd6f6b4/pkg/plugins/policies/meshaccesslog/api/v1alpha1/meshaccesslog.go#L79) to `Format` to make it consistent with other backends~~
    - [x] ~~Should we change the [`Endpoint` field](https://github.com/kumahq/kuma/blob/a41b0631b1ded03b83b52eff039deba7bcd6f6b4/pkg/plugins/policies/meshaccesslog/api/v1alpha1/meshaccesslog.go#L83) to `Address` to make it consistent with `TcpBackend`~~
  - [x] ~~File~~
    - [x] ~~Should we change the [`Path` field](https://github.com/kumahq/kuma/blob/a41b0631b1ded03b83b52eff039deba7bcd6f6b4/pkg/plugins/policies/meshaccesslog/api/v1alpha1/meshaccesslog.go#L92) to `Address` to be consistent with other backends? I'm not sure about it, as it might be slightly confusing as `Address` might suggest there is an option to put the file with logs somewhere external, not only to the local file.~~
- [ ] https://github.com/kumahq/kuma/pull/8533

Questions:
- ~~Currently we are not validating if list of `backend`s has at least one element. Should we allow policy without any backend?~~
  - empty list is a valid value as in some cases if there MeshAccessLog is set by default for all services you may want to disable it for particular services
- ~~Why `Format` field in `TCP` and `File` backends are pointers as [we are always checking if it's defined and if it's not empty](https://github.com/kumahq/kuma/blob/95ab5c494973eb62d74184c75f4ee21c8f2ff569/pkg/plugins/policies/meshaccesslog/api/v1alpha1/validator.go#L127-L167). Couldn't we just switch from pointer to regular type instead?~~

---

xref: https://github.com/kumahq/kuma/issues/5807

**Comment by michaelbeaumont** [comment]
Disagree on otel changes, this is the otel terminology. IMO it's much more likely for someone to know the otel language and be confused by renaming than someone know Kuma terms and be confused by the renaming

**Comment by bartsmykla** [comment]
Hmm. It makes sense 🤔
