### ISSUE TITLE
Return inbound tags in the order of their appearance, not alphabetically

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#8225]
### Description

Currently, `Values()` returns values in alphabetical order. However, if two inbounds have different locality tags, we might end up using the one based on this alphabetical order, even if it's not the first inbound. In practice, these tags shouldn't have different values, but it's possible to define them differently. We have the option to either validate if the tags have the same values or simply change the order to be based on the inbound order and use the tag from the first inbound.
https://github.com/kumahq/kuma/blob/master/api/mesh/v1alpha1/dataplane_helpers.go#L378

**Comment by lahabana** [comment]
> Triage: what's the risk of breaking backward compatibility here?

**Comment by lahabana** [comment]
Another thing to consider in: https://github.com/kumahq/kuma/issues/3339

**Comment by lahabana** [comment]
Will covered in https://github.com/kumahq/kuma/issues/3339
