### ISSUE TITLE
add gatewayAPI equivalent to ingress to our helm charts

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#8261]
### Description

Gateway API is GA and much better than ingress.
We should provide a way to create the equivalent of our `cp-ingress` in GatewayAPI style.

**Comment by michaelbeaumont** [comment]
@lahabana @lobkovilya  should we do this really? I feel like we'd have to parameterize almost everything about the Gateway. Some users will want to use their own certs and do plaintext Gateway -> HTTP Kuma API, some may want to use Kuma's autogenerated certs. Then there's customizing the `HTTPRoute`...

Do users really badly not want to create their own Gateways/HTTPRoutes?
If we just want an option to expose the API in a really basic way, is a LoadBalancer Service not enough?

**Comment by lukidzi** [comment]
> triage: let's wait for now, there is ongoing work on a gatewayApi side to simplify it.
