### ISSUE TITLE
kuma-system Namespace Remains in Terminating State Indefinitely

### ISSUE THREAD

**Issue by doctorwu** [kumahq/kuma#827]
### Summary

Having a weird issue when I am running Kuma in Kubernetes. When I try deleting the namespace kuma-system in order to start over, the kuma-system namespace hangs in a Terminating state indefinitely. When I run the following command:

`kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get -n kuma-system`

The only way to get around this is to restart Kubernetes.

```
NAME                             TYPE                                  DATA   AGE
default-token-smmkr              kubernetes.io/service-account-token   3      6m35s
kuma-admission-server-tls-cert   kubernetes.io/tls                     2      6m35s
kuma-control-plane-token-bsbsz   kubernetes.io/service-account-token   3      6m35s
kuma-sds-tls-cert                kubernetes.io/tls                     2      6m35s 
```

### Steps To Reproduce

1. Install Kuma in Kubernetes
2. Delete kuma-system namespace

### Additional Details & Logs

- Version: 0.5.1
- Kubernetes version 1.16
- I was running this on MacOS in docker desktop

**Comment by nickolaev** [comment]
I would recommend deleting kuma using the "reverse' of what you did to deploy it:
```
kumactl install control-plane | kubectl delete -f -
```
That should always work.

**Comment by jakubdyszkiewicz** [comment]
If this is only the matter of secret validation webhook, let's try to change `failurePolicy: Fail` to something less restrictive. This validator is really not that mandatory.
