### ISSUE TITLE
On k8s after GKE auto-upgrade cp seems to be stuck

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#8284]
### Description

Caused by leader election failing because of the k8s api not being available

### Details

We noticed that a leader couldn't be acquired in logs, and pod was in a `crashloopbackoff`. After the pod was killed control planes it started without a problem. We should investigate what caused that control-plane not to get a leader 

### Step to reproduce
1. create GKE cluster with autoupgrade
2. deploy kuma
3. when there is auto-upgrade wait for control-plane pod to go down

**Comment by jakubdyszkiewicz** [comment]
> Triage: you can try to trigger autoupgrade by starting cluster with 1-3 node and then add 10-20 more nodes

**Comment by Automaat** [comment]
I was unable to reproduce this with `2.5.1` version of Kuma, but I reproduced it with `2.4.0`. I assume that this now works properly, we can reopen anyone stumbles upon it again
