### ISSUE TITLE
Improve UX when routing.zoneEgress set to true and zone has no ZoneEgress

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#8323]
### Description

In certain scenarios in multi-zone deployments, when mesh has enabled `routing.zoneEgress`, but one or more zones lack `ZoneEgress`es, users attempting to send HTTP requests from these zones may encounter inconsistent responses, including empty responses and occasional `Connection reset by peer` errors. This issue arises due to the lack of egress connectivity in these zones, which disrupts the normal request forwarding process.

### Proposed Solution

To address this issue and provide a more consistent and informative user experience, I propose implementing a mechanism to return a 500 error code along with a clear message indicating that the zone lacks `ZoneEgress` and that request forwarding is not possible due to the enabled `routing.zoneEgress` setting. This approach will provide users with a more accurate understanding of the issue and prevent them from encountering unexpected errors.

### Technical Implementation

The proposed solution can be implemented by configuring Envoy with the `direct_response` for data planes in zones without `ZoneEgress`es. This feature will enable Envoy to directly respond to requests originating from these zones with 500 error codes and the appropriate message.

### Benefits

* Improved user experience with clear error messages and consistent behavior.
* Prevention of unnecessary request forwarding and potential errors.
* Enhanced troubleshooting and debugging capabilities for developers.

**Comment by jakubdyszkiewicz** [comment]
> Triage: we want to implement this with https://github.com/kumahq/kuma/issues/5870
