### ISSUE TITLE
Is it possible to delivery configuration to part of the cluster first?

### ISSUE THREAD

**Issue by spacewander** [kumahq/kuma#8359]
### Description

So that we can verify the configuration at a small scale, and the bad configuration won't affect the whole cluster.

**Comment by jakubdyszkiewicz** [comment]
Depends on the configuration. Do you have a specific configuration in mind?
With new policies (with Mesh prefix) you can target MeshSubet or MeshServiceSubset to only affect a subset of DPPs and try something on a small scale.

**Comment by spacewander** [comment]
@jakubdyszkiewicz 
Thanks for your quick reply! MeshSubset / MeshServiceSubset seems to be what I need.
I can't find them in https://kuma.io/docs. Are they real resources? Do I need to pre-create the subset or the subset is automatically created according to the tags of the dataplane?

**Comment by jakubdyszkiewicz** [comment]
No, they are not real resources. You don't need to create them. It's automatically inferred based on the tags from Dataplane.
btw. here are docs about matching https://kuma.io/docs/2.4.x/policies/targetref/

**Comment by spacewander** [comment]
Thanks!
