### ISSUE TITLE
version test fails on specific branch name

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#8374]
### What happened?

```
[It] Verify build flags are set Should have build info has semver version [build_check]
```

failed on `release-2.5_merge-master`

https://app.circleci.com/pipelines/github/kumahq/kuma/26383/workflows/395667a9-3fd8-490c-bdfd-1dad8de11481/jobs/549834/tests#failed-test-0

**Comment by jakubdyszkiewicz** [comment]
> Triage: this is the result of the release. The instructions were fixed
