### ISSUE TITLE
[Transparent Proxy] Add comments to `iptables` rules

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#8411]
### Description

When I was floating around other service meshes I learned something new about iptables.
More specifically that you can add comments to rules using `comment` extension

I think it could be a good improvements so users could better understand the purpose of each rule. It might be beneficial even for us, when we are be debugging issues related to transparent proxy.

---

```sh
comment
    Allows you to add comments (up to 256 characters) to any rule.

    --comment comment

    Example:
          iptables -A INPUT -i eth1 -m comment --comment "my local LAN"
```
ref. [man iptables-extensions(8)](https://man7.org/linux/man-pages/man8/iptables-extensions.8.html)

---

[Example from Linkerd](https://github.com/linkerd/linkerd2-proxy-init/blob/f934c857ca25181e7e95d90212f133b5442a3a8d/internal/iptables/iptables_test.go#L27-L41)

```sh
# Generated by iptables-save v1.6.1 on Fri Jan  6 23:00:00 2023
*nat
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:PROXY_INIT_OUTPUT - [0:0]
:PROXY_INIT_REDIRECT - [0:0]
-A PREROUTING -m comment --comment "proxy-init/install-proxy-init-prerouting/testExecutionTraceID" -j PROXY_INIT_REDIRECT
-A OUTPUT -m comment --comment "proxy-init/install-proxy-init-output/testExecutionTraceID" -j PROXY_INIT_OUTPUT
-A PROXY_INIT_OUTPUT -o lo -m comment --comment "proxy-init/ignore-loopback/testExecutionTraceID" -j RETURN
-A PROXY_INIT_OUTPUT -p tcp -m comment --comment "proxy-init/redirect-all-outgoing-to-proxy-port/testExecutionTraceID" -j REDIRECT --to-ports 1234
-A PROXY_INIT_REDIRECT -p tcp -m multiport --dports 1234 -m comment --comment "proxy-init/ignore-port-1234/testExecutionTraceID" -j RETURN
COMMIT
# Completed on Fri Jan  6 23:00:00 2023
```

**Comment by jakubdyszkiewicz** [comment]
> Triage: if we cannot squeeze full explanation we should link to docs done by https://github.com/kumahq/kuma-website/issues/1287


xref https://github.com/kumahq/kuma-website/issues/1287
