### ISSUE TITLE
Direct Access takes precedence over Headless support (suuport for stateful sets)

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#844]
### Summary

When having Headless Service, we would like to communicate directly to the instance of specified service. To support direct access, we introduced "direct access" https://kuma.io/docs/0.5.1/documentation/dps-and-data-model/#direct-access-to-services

The problem is that headless listeners are generated before direct access listeners. Therefore all requests will be load-balanced, which we want to avoid.

This can be tested with RabbitMQ for example https://github.com/rabbitmq/rabbitmq-peer-discovery-k8s/tree/master/examples/minikube

**Comment by pauliusuza** [comment]
Tracking. This is a blocker for us to take Kuma to production with mTLS enabled.

**Comment by jakubdyszkiewicz** [comment]
Every `inbound` of every Dataplanes of Headless service should be tagged with unique `tag: value`. This could be `app.kubernetes.io/instance`, `pod-hash` or our custom value like `kuma.io/instance`.

Then, when you generate outbound listener for such dataplanes, use this tag in `outbound.tags` section. Request then won't be load balanced across all instances.

Direct access does not have to be enabled for this use case.
