### ISSUE TITLE
InboundProxyGenerator: UpstreamBindConfig is always setup when using transparent proxying

### ISSUE THREAD

**Issue by nicoche** [kumahq/kuma#8483]
### What happened?

Hi!

It looks like this condition https://github.com/kumahq/kuma/blob/ee9cfca281a27322f425005679256d7b067eb6e1/pkg/xds/generator/inbound_proxy_generator.go#L45 is always evaluated to true whenever TransparentProxy is enabled. Is it expected? Should it be the following instead?

```
if proxy.Dataplane.IsUsingTransparentProxy() && (endpoint.WorkloadIP == core_mesh.IPv4Loopback.String() || endpoint.WorkloadIP == core_mesh.IPv6Loopback.String()) {
```

(see https://kuma-mesh.slack.com/archives/CN2GN4HE1/p1701184894860479 for more details)

**Comment by lukidzi** [comment]
Hi. I think the condition should be 
```
if proxy.Dataplane.IsUsingTransparentProxy() && (endpoint.WorkloadIP != core_mesh.IPv4Loopback.String() && endpoint.WorkloadIP != core_mesh.IPv6Loopback.String())
```

We should set upstream bind when:
1. Transparent proxy is enabled
2. Workload IP is different than Loopback IPv4 and IPv6
