### ISSUE TITLE
support customizing corefile template from kuma-cp

### ISSUE THREAD

**Issue by jijiechen** [kumahq/kuma#8633]
### Description

People want to customize the DNS template used by the kuma data plane to address following issues:
* Integrate with their existing DNS servers
* Resolve certain network issues introduced by the DNS proxying model of kuma dp, e.g. it's found by some Kuma clients that the DNS in kuma data plane is not compatible with certain alpine images ([refer to the link](https://github.com/alpinelinux/docker-alpine/issues/155#issuecomment-833676652))

It's good to make our builtin Corefile template customizable. 

It's best to support for both k8s and universal data planes.

**Comment by jakubdyszkiewicz** [comment]
Isn't it duplicate of https://github.com/kumahq/kuma/issues/8119 ?
Does it solve #8119 as well?

**Comment by jijiechen** [comment]
@jakubdyszkiewicz Un yes, I think, it's the same thing.

**Comment by jijiechen** [comment]
I'll close this one as it's replaced by #8119
