### ISSUE TITLE
Figure what happens with top level kind: Mesh and MeshGateway

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#8702]
### Description

Should top kind Mesh also cover gateway DPPs or should it do only regular dpps? 
Should there be a `kind: everything but gateways` then?

**Comment by jakubdyszkiewicz** [comment]
> Triage: let's try to answer this question by taking each policy into consideration

**Comment by lahabana** [comment]
@lukidzi is this covered by: https://github.com/kumahq/kuma/pull/8868 ?
