### ISSUE TITLE
Consistent logging

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#879]
### Summary

We should revisit our logging statements across codebase
* Logging about starting/stopping components should be consistent
* Uppercase/Lowercase it should be the same for every log
* No need for `...`
* There no need in "Starting API Server" if the logger is "api-server", don't repeat info
* Revisit levels of logs. For example DNS Server - should we see `Query for` on `Info` for every request? If so we need the same for API Server etc.
* Fix K8S logging about rejected events

**Comment by jakubdyszkiewicz** [comment]
The team decided for uppercase log messages

**Comment by jpeach** [comment]
FWIW, it's possible to enforce this with a custom linter, for example https://github.com/projectcontour/lint/blob/main/pkg/analysis/messagefmt/analyzer.go

**Comment by lahabana** [comment]
We should make sure we follow the approved MADR: https://github.com/kumahq/kuma/blob/master/docs/madr/decisions/003-logging.md

**Comment by lahabana** [comment]
Question for triage: Is this something we can realistically do in an issue or just something we should incrementally improve through future PRs?

**Comment by kleinfreund** [comment]
**Triage**: We’ve wrote the MADR on explaining how logging should be done. We probably still have things to make consistent, and we’ll get to it.

**Comment by lahabana** [comment]
The triage conclusion was that this was just going to happen organically and doesn't require its own issue
