### ISSUE TITLE
don't silently succeed if using ci/run-full-matrix on a fork

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#8807]
### What happened?

We must run this (and `ci/force-publish` too) with branches on the origin (not with forks).

Currently we silently succeed (the tests just don't run). It provides a false sense of confidence and we should stop this.

Likely just doing exit 1 on:
https://github.com/kumahq/kuma/blob/5fba9cfe5e813dc940509b4dc3b75ed4d7f9e349/.github/workflows/e2e.yaml#L189-L192

**Comment by jakubdyszkiewicz** [comment]
> Triage: we want to fail on empty circleci token
