### ISSUE TITLE
Webhooks / Defaulter for default Mesh

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#882]
### Summary

When Kuma starts it creates a default Mesh
```
apiVersion: kuma.io/v1alpha1
kind: Mesh
metadata:
  name: default
```

The problem is that on Kubernetes we've got webhooks for defaulter and validator that are based on K8S Service.
If the Control Plane is not ready yet but it created a Mesh, webhook fails. After a few reconciliation processes, everything is fine, but one of our users experienced a problem that Mesh was not created.

A couple of Ideas:
* Postpone Mesh creation after we make sure that service is ready
* Create a default mesh with `kumactl install control-plane` (tricky because we have to be careful to not override Mesh that exist)
* Omit hooks when creating default Mesh from the control-plane

**Comment by austince** [comment]
Related to https://github.com/Kong/kuma/issues/887. Just throwing this out there, but how difficult would it be to deploy the webhook service separately from the rest of the kuma CP?

**Comment by nickolaev** [comment]
@austince the webhook code is part of the `kuma-cp` binary now. I kind of like option one here - Postpone Mesh creation after we make sure that service is ready

**Comment by austince** [comment]
And breaking that out into a separate binary wouldn't be an easy task? I, selfishly :), hope we can support Helm users with whatever solution is chosen.
