### ISSUE TITLE
Question: L7 routing?

### ISSUE THREAD

**Issue by benpettman** [kumahq/kuma#885]
### Summary

I have been reading the docs and evaluating if Kuma & Kong will satisfy my companies requirements. Everything looks good apart from the L7 routing.

On the main Kuma site it seems to offer L4+7 policies, but the docs with regard traffic routing only offer L4.

So is it possible to do header/cookie based routing using Kuma? If so how is this achieved?

**Comment by YourTechBud** [comment]
I would love to help contribute this feature. We really need traffic splitting based on request headers and url.

**Comment by subnetmarco** [comment]
This is in progress as we speak by @jakubdyszkiewicz will ship next week.
