### ISSUE TITLE
Helm Installation Cannot Manage Default Mesh

### ISSUE THREAD

**Issue by austince** [kumahq/kuma#887]
### Summary

When installing k8s resource with Helm, the resource cannot exist prior to the first deployment. This creates a chicken-egg problem with the default Mesh, as the Kuma CP will create the default Mesh object if it doesn't exist, so we either have to a)  manage the Mesh outside of Helm, or b) deploy Kuma with the default Mesh object in the chart so the CP won't create one.

The first option works, but is not ideal, as we have to manage (update, delete, etc.) Kuma resources with multiple tools and doesn't fit nicely into DevOps systems built around Helm.

The second option would work well but the reliance on webhooks causes the Helm release to fail, as the webhook is not ready to accept requests until the entire CP is available. Unfortunately, Helm does not allow you to upgrade a release that has only one failed release in its history, which all first releases will in this approach.

### Steps To Reproduce

0. Ensure kuma CRDs are installed
0.5. Either run tiller locally or install in cluster 
1. Download attached chart (which was built from `kumactl install control-plane`)
2. Install via the included `deploy.sh` script
3. See webhook fail
4. See `helm list` show a failed deployment and subsequently fails to upgrade

### Additional Details & Logs

- kuma 0.6.0
- Helm 2 (though Helm 3 would likely have the same issues)

[kuma-chart.zip](https://github.com/Kong/kuma/files/4880238/kuma-chart.zip)

**Comment by nickolaev** [comment]
Adding charts to Helm Hub:
https://github.com/helm/hub/blob/master/Repositories.md
