### ISSUE TITLE
Deprecated `apiextensions.k8s.io/v1beta1` `CustomResourceDefinition`

### ISSUE THREAD

**Issue by nickolaev** [kumahq/kuma#888]
### Summary

Migrate `CustomResourceDefinition` to `apiextensions.k8s.io/v1` as `apiextensions.k8s.io/v1beta1` is deprecated

```
`CustomResourceDefinition` represents a resource that should be exposed on the API server. Its name MUST
be in the format .spec.name>..spec.group>.
Deprecated in v1.16, planned for removal in v1.19. Use apiextensions.k8s.io/v1 CustomResourceDefinition instead.
```

### Steps To Reproduce

1. Check https://github.com/Kong/kuma/tree/master/pkg/plugins/resources/k8s/native/config/crd/bases

### Additional Details & Logs

- Version
- Error logs
- Configuration
- Platform and Operating System

**Comment by austince** [comment]
Hey, I'm happy to take this on @nickolaev, if nobody else is working on it.

**Comment by nickolaev** [comment]
Thanks! I guess there's some testing to be fixed, which would be the major change.

**Comment by austince** [comment]
Do these tests already exist or do new tests need to be created? I'm happy to tackle tests as well, but might need some pointers on where they should go!

**Comment by nickolaev** [comment]
The existing tests will probably fail.

**Comment by austince** [comment]
Migration notes:
* https://github.com/kubernetes/kubernetes/pull/79604
