### ISSUE TITLE
OverrideDpVersion() doesn't work

### ISSUE THREAD

**Issue by curiositycasualty** [kumahq/kuma#8902]
### What happened?

Looking at https://github.com/kumahq/kuma/blob/d230b2aec28b8237ff528c6c1047a350b09dae88/test/framework/universal_app.go#L379-L381

I don't think package filenames have conformed to the string since ~2.1.8. Unsure where/how this is used.

Modern package names on Pulp look like:
[kuma-2.5.1-darwin-amd64.tar.gz](https://download.konghq.com/kuma-binaries-release/kuma-2.5.1-darwin-amd64.tar.gz)
[kuma-2.5.1-darwin-arm64.tar.gz](https://download.konghq.com/kuma-binaries-release/kuma-2.5.1-darwin-arm64.tar.gz)
[kuma-2.5.1-linux-amd64.tar.gz](https://download.konghq.com/kuma-binaries-release/kuma-2.5.1-linux-amd64.tar.gz)
[kuma-2.5.1-linux-arm64.tar.gz](https://download.konghq.com/kuma-binaries-release/kuma-2.5.1-linux-arm64.tar.gz)

And on Cloudsmith:
[kuma-2.5.1-darwin-amd64.tar.gz](https://packages.konghq.com/public/kuma-binaries-release/raw/names/kuma-darwin-amd64/versions/2.5.1/kuma-2.5.1-darwin-amd64.tar.gz)
[kuma-2.5.1-darwin-arm64.tar.gz](https://packages.konghq.com/public/kuma-binaries-release/raw/names/kuma-darwin-arm64/versions/2.5.1/kuma-2.5.1-darwin-arm64.tar.gz)
[kuma-2.5.1-linux-amd64.tar.gz](https://packages.konghq.com/public/kuma-binaries-release/raw/names/kuma-linux-amd64/versions/2.5.1/kuma-2.5.1-linux-amd64.tar.gz)
[kuma-2.5.1-linux-arm64.tar.gz](https://packages.konghq.com/public/kuma-binaries-release/raw/names/kuma-linux-arm64/versions/2.5.1/kuma-2.5.1-linux-arm64.tar.gz)

**Comment by curiositycasualty** [comment]
I am not blocked by this or anything, just noticed it while poking around.

**Comment by lahabana** [comment]
Thanks for reporting. Indeed this is very odd and I think this test:

https://github.com/kumahq/kuma/blob/d230b2aec28b8237ff528c6c1047a350b09dae88/test/e2e_env/universal/compatibility/dp_compatibility.go#L18-L28

Clearly doesn't do what it's supposed to...

**Comment by michaelbeaumont** [comment]
I actually started to fix this in https://github.com/kumahq/kuma/pull/8410/commits/c392b7957e44eb4e59b69c55cb23972fc2ae0a25, just waiting to be able to merge the PR

**Comment by lobkovilya** [comment]
@michaelbeaumont the PR you mentioned is merged. Should we close this issue?
