### ISSUE TITLE
Set total weight for Route Action

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#898]
### Summary

When using Weighted Cluster in TCP Proxy there is no limit for sum of weights, but for Route Action there is 100 by default
https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/route/route_components.proto#route-weightedcluster

We should set `totalWeight` to sum of all clusters weights (`default_route_configurer.go`)

**Comment by nickolaev** [comment]
@tharun208 will take this one.
