### ISSUE TITLE
Upgrade envoy to v1.29.0

### ISSUE THREAD

**Issue by bartsmykla** [kumahq/kuma#9016]
### Description

[Envoy v1.29.0](https://github.com/envoyproxy/envoy/releases/tag/v1.29.0) was released last week, and ~~I believe we should upgrade it before releasing 2.6.0~~

**blocked by** https://github.com/envoyproxy/envoy/issues/31932

**Comment by lukidzi** [comment]
https://github.com/kumahq/kuma/pull/9134
