### ISSUE TITLE
Replacing CircleCI insights with another flake analysis tool

### ISSUE THREAD

**Issue by slonka** [kumahq/kuma#9170]
### Description

After migration to GH actions we lost [CircleCI insights](https://app.circleci.com/insights/github/kumahq?reporting-window=last-30-days) so to catch flakes we need to manually review which tests failed on recent commits and "roughly" assess what's the priority to fix them. I think we could consider an alternative (e.g. https://github.com/operator-framework/flake-analyzer) to help us with that.

**Comment by jakubdyszkiewicz** [comment]
> Triage: we have it now
