### ISSUE TITLE
Stop using start_child_span in Router

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9182]
### What happened?

The field is deprecated: https://www.envoyproxy.io/docs/envoy/latest/api-v3/extensions/filters/http/router/v3/router.proto#extensions-filters-http-router-v3-router

This leads to logs on the sidecar: [2024-02-09 08:48:21.513][27][warning][misc] [source/common/protobuf/message_validator_impl.cc:21] Deprecated field: type envoy.extensions.filters.http.router.v3.Router Using deprecated option 'envoy.extensions.filters.http.router.v3.Router.start_child_span' from file router.proto. This configuration will be removed from Envoy soon. Please see https://www.envoyproxy.io/docs/envoy/latest/version_history/version_history for details. If continued use of this field is absolutely necessary, see https://www.envoyproxy.io/docs/envoy/latest/configuration/operations/runtime#using-runtime-overrides-for-deprecated-features for how to apply a temporary and highly discouraged override.

**Comment by michaelbeaumont** [comment]
I think https://github.com/kumahq/kuma/pull/9045 solved this?

**Comment by lahabana** [comment]
Ok this didn't make it to 2.6.0 so that's why.

**Comment by michaelbeaumont** [comment]
I _think_ because it isn't available in the Envoy that's in use in 2.4 so this would break the 2 versions rule.
