### ISSUE TITLE
Deprecate `from.kind: MeshService`

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9258]
### What happened?

This doesn't really make a lot of sense and everything can be achieved with `kind: MeshSubset tags: kuma.io/service`.

This will make things less confusing when we separate service and workload identity.

This issue covers updating the docs and starting to warn about the deprecation. We'll need a follow up issue to remove support.

**Comment by bartsmykla** [comment]
This is breaking change, and is modifying some of the previous MADRs, so there should be an MADR created before implementing this.

**Comment by lahabana** [comment]
This should start with a deprecation so that people are just warned that this is being removed
