### ISSUE TITLE
inspect the Dataplane by the name of the dataplane in zone

### ISSUE THREAD

**Issue by lukidzi** [kumahq/kuma#9286]
### Description

Zones sync the dataplane object to the Global and add a hash to the name to avoid conflicts. The issue arises when the user checks the zone for the Dataplane's name and later makes a request with kumactl to the global using the Dataplane's name from the zone. In this case, there is no dataplane with the provided name, and the user cannot, for example, inspect policies. It works when the user configures kumactl to request the zone but not the global. Is there anything we can do here to improve the user experience? Like return 
``` 
do you mean?
- dataplane_name | zone 
``` 

Other?

**Comment by jakubdyszkiewicz** [comment]
> Triage: there is no good way to solve it now.
