### ISSUE TITLE
Migrate config to aconfig

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#929]
### Summary

In the early days of Kuma, we were exploring configuration options. Our requirement was to load the config from file and override it with env variables (you can skip the file).
Viper had some problems with loading config just from env vars. Eventually, we went with the implementation that on the first step parses YAML and on the second step override fields using envconfig.

As the project evolved, it turned out that for example in Kuma DP users prefer to use cli args since config is small. Also sometimes overriding values in CP are easier using CLI args than env vars, which we don't support right now.

We should make loading config consistent across all binaries which means:
1) create default config
2) load from file
3) override with env vars
4) override with cli args

Recently introduced [aconfig](https://github.com/cristalhq/aconfig) nails all the requirements, while being lightweight.

Additionally, if we switch defining default config to `default` tags on fields and add descriptions in `usage` tag instead of comment we can autogenerate configuration using `aconfig#WalkFields`

As an extra step when doing this, we should migrate pointers to structs in our config. Right now you can modify a configuration during CP runtime, this should not be the case. Once the Runtime object is built and CP is started, the config should not change.

CC: @cristaloleg

**Comment by cristaloleg** [comment]
Thank you Jakub for the acknowledge. As an `aconfig` author I will kindly ask not to hurry with this transition, despite API is stable, I would like to make few additional fresh looks at the code to check what is still missing (I feel like something near `reflect` can be fixed, maybe error message clarification).

Any way stable `v1.0.0` will be next week. Thank you 🙌

**Comment by cristaloleg** [comment]
Looks like the API is stable enough, probably I'll cut v1 unless @jakubdyszkiewicz has other suggestions.

**Comment by slonka** [comment]
Removing stale since I don't think we tried it in kuma-dp.

**Comment by lobkovilya** [comment]
Should we give up on this? :)

**Comment by jakubdyszkiewicz** [comment]
> Triage: Yes :( It would be too complicated to do it now. We are however testing this in the new project :)
