### ISSUE TITLE
Avoid kuma.io/service matching in the api

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9301]
### What happened?

In policy matching kuma.io/service should just be a label like any other.

this implies we should:

1. use MeshGateway for gateway and MeshService for services. MeshSubset is only usable in from or top level
2. Introduce MeshExternalService to match an external service

What does this mean that Mesh or MeshSubset ? Do they select externalServices? Do we need another proxy type for them?

why do this?

it solves multiple issues and confusions: TODO add them

**Comment by jakubdyszkiewicz** [comment]
xref https://github.com/kumahq/kuma/issues/6330
xref https://github.com/kumahq/kuma/issues/6331
xref https://github.com/kumahq/kuma/issues/9258

**Comment by jakubdyszkiewicz** [comment]
> Triage: is there anything left to do?

**Comment by michaelbeaumont** [comment]
Closing this, opened an issue to document everything: https://github.com/kumahq/kuma-website/issues/1892
