### ISSUE TITLE
Question: kuma-gui support only localhost?

### ISSUE THREAD

**Issue by ktkfree** [kumahq/kuma#943]
Summary

kuma-cp( 0.7.0 ) was deployed on my remote server.
but, I can not connect to a gui-server.

kuma-gui support only localhost?

<img width="672" alt="스크린샷 2020-08-03 오후 5 57 14" src="https://user-images.githubusercontent.com/2183253/89165171-208a0580-d5b3-11ea-8617-cd2ca01c2c44.png">

**Comment by nickolaev** [comment]
This is a bug, result of moving the GUI from its dedicated port to the API (`:5681`). We're working to fix this. Thanks for reporting!

**Comment by subnetmarco** [comment]
I found out that the GUI is loading the value of the `guiServer.apiServerUrl` when requesting the Kuma configuration at startup via `:5681/config`.

In my tests, the value returned is always `http://localhost:5681`, which in turn makes the API server behave incorrectly.

This may be a problem in our API server and not in the GUI itself.

**Comment by subnetmarco** [comment]
Also [shouldn't this also be deprecated](https://github.com/kumahq/kuma/blob/master/pkg/config/gui-server/config.go#L11-L12) by now?

**Comment by nickolaev** [comment]
The value of `guiServer.apiServerUrl` is needed for development and testing purposes only. The GUI should default to `:5681/`.

**Comment by lijiapengsa** [comment]
@nickolaev  Come on ！

**Comment by lijiapengsa** [comment]
When to fix this bug

**Comment by nickolaev** [comment]
> When to fix this bug

There is a PR already open.

**Comment by bloqhead** [comment]
@nickolaev I've approved the PR with some comments.
