### ISSUE TITLE
outbound proxy defaults to tcp with http2 protocol (dataplane)

### ISSUE THREAD

**Issue by caribru** [kumahq/kuma#949]
### Summary

First off, thanks for landing the http2 and patching for proxy templates!

After upgrade to 0.7 and configuring services with http2 annotation, traffic was still not being loadbalanced across backends. 
Heh, I wish I just looked at the dynamic envoy config from the start :)

Confirmed that the outbound proxy was still set to tcp, though the clusters do now get the http2_protocol_options field set. 

I also just now saw #912 and #924 get merged which got me to look, and outbound proxy generator doesn't have support for http2 (nor grpc yet), so this may be a feature request rather than a bug. 

### Steps To Reproduce

1. Annotate a service with http2, dump envoy config, find the outbound listener for your service, filter will be TcpProxy
2. Update annotation setting protocol to http, confirm it changes to HttpConnectionManager

### Additional Details & Logs
- Version: 0.7
- Kubernetes backend

Notes:
Annotation in the service: 
    9080.service.kuma.io/protocol: http2

Get proxy configs via port forwarding to the pod on 9901
curl http://localhost:9901/config_dump

Confirmed just http and tcp protocols are currently supported for the outbound proxy:
https://github.com/kumahq/kuma/blob/master/pkg/xds/generator/outbound_proxy_generator.go#L96

**Comment by jakubdyszkiewicz** [comment]
Hey, thanks for the report - you are right.

HTTP/2 is now supported for the inbounds but it is indeed "downgraded" to TCP on outbound. Also good point about gRPC. We are planning to release Kuma 0.7.1 next week, so I'll make sure this is fixed in the next release since it seems like an easy fix.
