### ISSUE TITLE
Build socket paths in policies based on work dir sent from DP

### ISSUE THREAD

**Issue by lahabana** [kumahq/kuma#9496]
### Description

Atm we pass in AccessLogSocketPath and MetricsSocketPath. Anytime we add something new we need to add a new request. It's a little unfortunate and we should just pass in the tmpDir.

**Comment by Automaat** [comment]
`AccessLogSocketPath` and `MetricsSocketPath` should be based on workDir like we do in `MeshMetric`, [example](https://github.com/kumahq/kuma/blob/30d7cdadd29406db131311c1880fec0cdb2dbd7c/pkg/core/xds/sockets.go#L20-L27)

**Comment by jakubdyszkiewicz** [comment]
> Triage: It should be fixed for metrics with MeshMetrics, but we need to also do this for AccessLogs

**Comment by Automaat** [comment]
This was already implemented in: https://github.com/kumahq/kuma/pull/10364
