### ISSUE TITLE
MADS long polling not working after restarting prometheus

### ISSUE THREAD

**Issue by Automaat** [kumahq/kuma#9508]
### What happened?

We have changed how MADS recomputes state in Kuma version 2.6.0. We don't have single state but state per prometheus client. When you don't configure `client_id` in Prometheus explicitly, it will be autogenerated. When Prometheus restarts, it will get new `client_id` that will break long polling. The issue is that we periodically recompute monitoring assignment only for the first client. This is caused by our very basic implementation of [callback for http requests](https://github.com/kumahq/kuma/blob/a9cd4216ef06540a7b3b06eb4474066f392d0b47/pkg/util/xds/v3/watchdog_callbacks.go#L48).

We have two solutions here: 
- we can remove long polling altogether, and simply send requests periodically
- we can improve watchdog callback by creating watchdog for every client, we would need to add some mechanism of removing watchdogs for clients that stopped sending requests
- we can have a single watchdog that recomputes state for every `client_id` 

In my opinion, we can remove long polling. Long polling was already faulty in Prometheus. Prometheus does not start a new request after finishing the previous but waits for configured refresh interval. [Code here](https://github.com/prometheus/prometheus/blob/0a426215b52e461e3fa4c162c79279bcd5e3b795/discovery/xds/xds.go#L123). Which can cause the same delays as in a scenario without long polling.

**Comment by jakubdyszkiewicz** [comment]
> Triage: we want to go with 3rd option
