### ISSUE TITLE
A stable kumactl binary

### ISSUE THREAD

**Issue by sudeeptoroy** [kumahq/kuma#952]
### Summary

A new CP version with additional APIs or breaking changes need a new kumactl (or kuma-dp) binary too. A deployment with large user base force binary updates to all its users. The request is to decouple control plane and kumactl(and kuma-dp) with kuma-cp so that upgrading kuma-cp is easier. With this users are not forced to upgrade kumactl (or kuma-dp) frequently.
An example can be kubectl which does this well.

### Additional Details & Logs

- Version: all

**Comment by michaelbeaumont** [comment]
@sudeeptoroy At the moment we only emit a warning if the versions between `kumactl` and the control plane don't match. If the API hasn't changed, there shouldn't be an issue using an older version of `kumactl`.
