### ISSUE TITLE
Universal on kuberenetes mode - DNS error

### ISSUE THREAD

**Issue by brunda-bs** [kumahq/kuma#9604]
### What happened?

Hi,

We are using the kuma 2.5.2 version and trying to deploy Kuma Global CP "universal on Kubernetes" mode. We see that the init container - “migration” is not able to resolve the Postgres DNS. 

However, 
1. The control-plane container in the same pod can resolve the Postgres DNS. 
2. With the same credentials, I can access the Postgres DB from local as well as other Kubernetes pods in the same cluster.

**From Migration init container:**
~ % kubectl logs po/kuma-control-plane-85859bcf66-4krzp  -n kuma-system **-c migration**

Error: cannot connect to DB: failed to connect to `host=[xxxx.postgres.database.azure.com]
 user=kuma
 database=kuma
`: hostname resolving error (lookup [xxxx.postgres.database.azure.com](http://xxxx.postgres.database.azure.com/) : no such host)

**From control-plane container:**
kubectl exec po/kuma-control-plane-7fc4d64d68-pzgsc -n kuma-system -it -- sh

~ $ wget http://xxxx.postgres.database.azure.com:5432/ 
Connecting to xxxx.postgres.database.azure.com:5432 (xx.xx.xx.xx:5432)

**Comment by jakubdyszkiewicz** [comment]
> Triage: do you have any other init containers in the Pod? Can you hit any other DNS host from this init container? Does it happen in any other init container?

**Comment by brunda-bs** [comment]
Hi @jakubdyszkiewicz,
The encrypted secret for postgres db host was misconfigured. The connectivity is working fine now. Thanks
