### ISSUE TITLE
Provide even more native integration with Prometheus

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#961]
### Summary

For now, to integrate Prometheus + Kuma we have `kuma-prometheus-sd` binary that we deploy next to Prometheus deployment. `kuma-prometheus-sd` connects to CP and creates a file that is then consumed by file sd in Prometheus.

It works well but it is a pain to integrate current Prometheus deployments, because you need to add an extra container, mount the volumes to prometheus server and modify config. We had instruction how to do it in `kuma.io` but at some point we removed it because we felt it is too convoluted.

Prometheus federation is the simplest way to integrate with current Prometheus deployments but it's not always an option.

We can make this smoother by providing native builtin integration in Prometheus. This way, a user needs to only modify config of Prometheus.

Bonus point: we promote Kuma in Prometheus site ;)

**Comment by austince** [comment]
Slack thread where this was discussed: https://kuma-mesh.slack.com/archives/C013ALVE1GU/p1598284231004100

Currently looking into the steps to add a new `discovery` to Prometheus: https://github.com/prometheus/prometheus/tree/master/discovery

**Comment by austince** [comment]
Looks like we'll need a 'sponsor' from the Prometheus team (I think?) with push access: https://github.com/prometheus/prometheus/pull/6671#issuecomment-576579587
I'll reach out to that list

**Comment by nickolaev** [comment]
The discussion was held in this issue:
https://github.com/prometheus/prometheus/issues/7919

But in the end is closed in favor of https://github.com/prometheus/prometheus/issues/6484. Shall we continue there?

**Comment by austince** [comment]
I think we should continue on the dev mailing list [here](https://groups.google.com/forum/#!topic/prometheus-developers/w2F6gxYW8U8). I haven't had time to try to revive it, but have left my ideas for what we'll need to do in  https://github.com/prometheus/prometheus/issues/7919#issuecomment-694254880

**Comment by austince** [comment]
Close in https://github.com/prometheus/prometheus/pull/8844/
