### ISSUE TITLE
Support `initContainers` mesh access

### ISSUE THREAD

**Issue by michaelbeaumont** [kumahq/kuma#9630]
### Description

Up until #7541, it wasn't possible for `initContainers` to access the mesh. Now if we order `[kuma-init, kuma-sidecar]` before other `initContainers`, they'll be able to access the mesh.

How should this functionality be exposed to users? I propose:

```
metadata:
  annotations:
    kuma.io/init-container-mesh-access: [enabled, disabled]
``` 
* `enabled`: `[kuma-init, kuma-sidecar, otherInitContainers...]`
* `disabled`: `[otherInitContainers..., kuma-init, kuma-sidecar]`

With CNI this could behave the same except we'd of course leave out `kuma-init`.

Before this feature, this would be simply always `disabled`. Should we change the default to be `enabled` when using sidecar containers?

Additionally, how should this interact with [`kuma.io/init-first`](https://kuma.io/docs/2.6.x/reference/kubernetes-annotations/#kumaioinit-first) which could theoretically be used to intentionally disable all traffic and could still be used to do so (`[kuma-init, otherInitContainers, kuma-sidecar]`)

**Comment by johnharris85** [comment]
Defaulting to true would be a difference in current behavior (potentially one that folks were relying on for some security?) so I don't think we should change that. I think how you've laid out the interaction with `init-first` makes sense to me? We should also still mention somewhere that this is _best effort_, as in, we don't have a _validating_ webhook to make sure what the user specified actually happened. Another mutating hook could have altered this behavior after ours.

**Comment by jakubdyszkiewicz** [comment]
> Triage: I'd go with the annotation that we have `kuma.io/init-first` and if true `[kuma-init, kuma-sidecar, otherInitContainers...]` if false `[kuma-init, otherInitContainers, kuma-sidecar]`

**Comment by michaelbeaumont** [comment]
> Triage: I'd go with the annotation that we have kuma.io/init-first and if true [kuma-init, kuma-sidecar, otherInitContainers...] if false [kuma-init, otherInitContainers, kuma-sidecar]

But at the moment `init-first` causes init containers _not_ to have access.
The problem is that there are now 3 states. There's "disable mesh usage" (the default previously), "enable mesh usage" (new option) and "disable traffic entirely" (`kuma-init` before).

**Comment by jakubdyszkiewicz** [comment]
> Triage: We could just go with `[kuma-init, kuma-sidecar, otherInitContainers...]` by default and not have the configuration at all

**Comment by michaelbeaumont** [comment]
This is supported now
