### ISSUE TITLE
Kubernetes service is picked up when you inject dataplanes into default namespace

### ISSUE THREAD

**Issue by jakubdyszkiewicz** [kumahq/kuma#977]
### Steps To Reproduce

1. Deploy Kuma
2. Annotate default namespace with kuma injection
3. Deploy apps into `default` namespace
4. Deploy Kong (it can be in a separate namespace)
5. Enable mTLS

So what is happening is that some apps are picking an extra inbound with Kubernetes default namespace

```
- apiVersion: kuma.io/v1alpha1
  kind: Dataplane
  mesh: online-boutique
  metadata:
    creationTimestamp: "2020-08-13T16:45:04Z"
    generation: 2
    name: shippingservice-7b7758b5d4-556g9
    namespace: default
    ownerReferences:
    - apiVersion: v1
      blockOwnerDeletion: true
      controller: true
      kind: Pod
      name: shippingservice-7b7758b5d4-556g9
      uid: b049e9c9-d509-4cb2-8a0a-9591b408d4ce
    resourceVersion: "71048"
    selfLink: /apis/kuma.io/v1alpha1/namespaces/default/dataplanes/shippingservice-7b7758b5d4-556g9
    uid: e89767c4-2621-4eae-bc97-b03b2a4bcb24
  spec:
    networking:
      address: 10.8.2.15
      inbound:
      - port: 443
        tags:
          app: shippingservice
          kuma.io/protocol: tcp
          kuma.io/service: kubernetes_default_svc_443
          pod-template-hash: 7b7758b5d4
```

Given `kubernetes` service
```
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2020-08-13T17:46:50Z"
  labels:
    component: apiserver
    provider: kubernetes
  name: kubernetes
  namespace: default
  resourceVersion: "87833"
  selfLink: /api/v1/namespaces/default/services/kubernetes
  uid: 9dab757a-4dc5-4f53-8959-5b247bb51860
spec:
  clusterIP: 10.11.240.1
  ports:
  - name: https
    port: 443
    protocol: TCP
    targetPort: 443
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
```

there are no selectors so every pod will match this service, but somehow we also match the port. The result is that we create an inbound.

Here is tricky part. Kong Ingress Controller is using `kubernetes.default.svc` to connect it. Kuma then load balances this request over all dataplanes which includes `shippingservice-7b7758b5d4-556g9`, so request is going to this service instead of Kubernetes API Server. KIC cannot connect to Kubernetes, therefore it cannot start.

### Additional Details & Logs

- Version 0.7.0

If you are experiencing this problem now, please don't use injection in the default namespace

**Comment by subnetmarco** [comment]
@jakubdyszkiewicz what do you suggest is the solution here?

**Comment by jakubdyszkiewicz** [comment]
@subnetmarco see #978
