### ISSUE TITLE
consider adding display-name/namespace labels to 'nested' policies in the HTTP API

### ISSUE THREAD

**Issue by johncowen** [kumahq/kuma#9851]
### Description

We have display/name/namespace labels in the HTTP API for the policy listing and policy detail response, but for places where policies aren't the "top-level" resource such as affected policies, we don't have this information.

Therefore in the GUI we sometimes display the `display-name` as the "name of the thing" and sometimes we show the full `display-name.namespace` as the "name of the thing", which would be confusing.

**Comment by jakubdyszkiewicz** [comment]
> Triage: update this structure https://github.com/kumahq/kuma/blob/4752f7b828e80c80ade6a7da89a7c083c1c99cad/api/openapi/specs/common/resource.yaml#L42-L57

**Comment by lahabana** [comment]
Should the schema of labels be strict (each label key defined) or should it just be a `array` `object: key->value` or just an `object` ?

```
labels:
 - key: namespace
    value: my-ns
```

**Comment by Icarus9913** [comment]
1

**Comment by lahabana** [comment]
Example paths that should include labels:

- https://us.api.konghq.com/v0/mesh/control-planes/777e2d6a-d53b-4780-af2f-9ac3b3beece3/api/meshes/default/meshcircuitbreakers/mesh-circuit-breaker-all-default
- https://us.api.konghq.com/v0/mesh/control-planes/777e2d6a-d53b-4780-af2f-9ac3b3beece3/api/meshes/default/dataplanes/demo-app-c7cd6588b-5jrhg-zdz9458zf88466z4/_rules

Need to add an entry like:

```
"labels": {
    "k8s.kuma.io/namespace": "kuma-demo",
    "kuma.io/display-name": "demo-app-c7cd6588b-5jrhg",
    "kuma.io/origin": "zone",
    "kuma.io/zone": "local"
   },
```

Where labels are taken from the resource referenced

**Comment by lahabana** [comment]
<img width="1655" alt="image" src="https://github.com/kumahq/kuma/assets/702355/38db35ef-8698-45e5-98d6-7588692fa3ee">

https://cloud.konghq.com/us/mesh-manager/777e2d6a-d53b-4780-af2f-9ac3b3beece3/meshes/default/policies/meshcircuitbreakers/mesh-circuit-breaker-all-default/overview
