### ISSUE TITLE
grpc dataplane causes xds-server.reconcile errors 

### ISSUE THREAD

**Issue by caribru** [kumahq/kuma#991]
### Summary
Declaring service protocol in kubernetes service annotation to grpc causes error: 

ERROR    xds-server.reconcile    inconsistent snapshot { ... "proxyError": "json: unsupported type: xds.TrafficPermissionMap", "error": "mismatched route reference and resource lengths: map[outbound:echo_ctest1_svc_80:true] != 0" ... }

I confirmed this with any basic service/deployment on both kind (local) and eks v1.16

### Steps To Reproduce

1. Create any service + deployment (which creates a dataplane automatically)
2. Add a service annotation declaring protocol as grpc
2. Tail kuma-control-plane pod's logs

### Additional Details & Logs

- Kuma Version: 0.7.1
- service annotation: 80.service.kuma.io/protocol: grpc

**Comment by subnetmarco** [comment]
@nickolaev has this been fixed with the latest patch on http2?

**Comment by nickolaev** [comment]
Yes, it is fixed by #998 which is already merged to master. Interestingly enough, that did not close this issue although mentioned in its description. Closing manually here.
