### ISSUE TITLE
Kuma with mtls on - no Kong traffic incoming

### ISSUE THREAD

**Issue by digibank-rons** [kumahq/kuma#995]
### Summary

When using Kuma on K8s with Kong as an API gateway with mtls enabled - "An invalid response was received from the upstream server"

### Steps To Reproduce

1. Install Kong + Kuma on K8s cluster (1.17)
2. Create Mesh - add all services into mesh plus Kong Gateway
3. Create trafficPermission to allow all traffic
4. Enable Mtls
5. Attempt to access services

### Additional Details & Logs

- Version - 0.7.1
- Error logs - Kong ingress output - "upstream prematurely closed connection while reading response header from upstream - 502", no error in sidecars on neither pod 
- Platform and Operating System - EKS - K8s 1.17

**Comment by jakubdyszkiewicz** [comment]
Hey,

from docs https://kuma.io/docs/0.7.1/documentation/dps-and-data-model/#universal

```
When integrating Kong for Kubernetes with Kuma you have to annotate every Service that you want to pass traffic to with ingress.kubernetes.io/service-upstream=true annotation. Otherwise Kong will do the load balancing which unables Kuma to do the load balancing and apply policies.
```

have you annotated your services?

**Comment by digibank-rons** [comment]
@jakubdyszkiewicz Thanks for responding, unfortunately adding the annotations did not fix the issue,
I noticed my Kong ingress pod is not tagged as part of the mesh my actual services run in, is this an issue?
I hope not, setting up an ingress per mesh doesn't seem reasonable, notice the issue only occurs when I enable MTLS,
I appreciate your help.

**Comment by jakubdyszkiewicz** [comment]
Hey, applications in the Mesh expects traffic to be encrypted with mTLS, therefore Kong needs to be a part of the mesh.

Unfortunately, right now there is a limitation that you need to have gateway per Mesh, but cross-mesh communication and multi-mesh support in dataplane is fairly high on our roadmap, so you can expect this limitation to be lifted in the near future.

**Comment by digibank-rons** [comment]
@jakubdyszkiewicz Thank you
