### ISSUE TITLE
networking.outbound[0].kuma.io/service: cannot be empty

### ISSUE THREAD

**Issue by LukeCz** [kumahq/kuma#996]
### Summary

Hi, could you clarify what is the correct format in 0.7 for outbound service definition? From the basic example in documentation (https://kuma.io/docs/0.7.1/documentation/dps-and-data-model/#gateway) kuma.io/service: backend does not parse while service: backend (without kuma.io prefix) do. Should the documentation be corrected?

### Steps To Reproduce
```

@instance-5:~/kuma-0.7.1/bin$ echo "type: Dataplane
> mesh: default
> name: kong-01
> networking:
>   address: 10.0.0.1
>   gateway:
>     tags:
>       kuma.io/service: kong
>   outbound:
>   - port: 33033
>     kuma.io/service: backend" | ./kumactl apply -f -
Error: Could not update a resource (Resource is not valid)
* networking.outbound[0].kuma.io/service: cannot be empty
@instance-5:~/kuma-0.7.1/bin$     
@instance-5:~/kuma-0.7.1/bin$     echo "type: Dataplane
> mesh: default
> name: kong-01
> networking:
>   address: 10.0.0.1
>   gateway:
>     tags:
>       kuma.io/service: kong
>   outbound:
>   - port: 33033
>     service: backend" | ./kumactl apply -f -
@instance-5:~/kuma-0.7.1/bin$ 
```

### Additional Details & Logs

- Version 0.7.1
- Error logs
- Configuration
- Platform and Operating System Debian 10.5

**Comment by jakubdyszkiewicz** [comment]
Hey, it should be
```
outbound:
  tags:
    kuma.io/service: backend
```

Sorry about that, let us fix the docs.

**Comment by subnetmarco** [comment]
@jakubdyszkiewicz have the docs been fixed?

**Comment by jakubdyszkiewicz** [comment]
Fixed in https://github.com/kumahq/kuma-website/pull/264
